### ISSUE TITLE
FR: RegEx to ignore files

### ISSUE THREAD

**Issue by jvdevlab** [platers/obsidian-linter#1000]
## Is Your Feature Request Related to a Problem? Please Describe.

I use [another](https://github.com/akosbalasko/zoottelkeeper-obsidian-plugin) plugin to generate Folder Notes with "_" prefix. 
I would like linter not to touch these files. 

## Describe the Solution You'd Like

Add regex pattern next to Folders to Ignore where we can specify a pattern for MD files to be ignored.

## Describe Alternatives You've Considered

I need both plugins so not sure what could be the alternative. 

## Additional Context

Linter and zoottelkeeper conflict in multiple ways.

1. zoottelkeeper adds special comment block inside which it will generate links. 
 `%% Zoottelkeeper: Beginning of the autogenerated index file list  %%` 
Note how there are 2 whitespaces before %%. 
When remove extra spaces rule is applied this block is modified.

2. When Linter adds frontmatter (insert properties via whatever YAML rule), zoottelkeeper is confused and doesn't put extra space after --- resulting into broken MD file. 

3. When you do bulk linting with Linter and bulk reindexing with zoottelkeeper lots of files modified unnecessarily causing mess in git history and Sync versioning.

**Comment by themensch** [comment]
I would find it useful to ignore certain files spread throughout my fault, for example `*.excalidraw`. This fits with the title of the feature request, but not the intent of ifnoring certain folders.

**Comment by pjkaufman** [comment]
Hey @themensch , could you provide an example for markdown files? I ask because non-markdown files should already be ignored. If not, that is a bug that should be addressed as a bug.

**Comment by themensch** [comment]
@pjkaufman Sure thing!  I worked with the Excalidraw author in this case: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1808, which has a couple example files.

**Comment by pjkaufman** [comment]
Hey @themensch, I don't use excalidraw, but can you explain how you were getting the Linter to run and what the full file name is (i.e. is it a `.md` file or does it have another file extension)?

**Comment by pjkaufman** [comment]
If I read excalidraw's readme correctly, they are advertising their files as markdown files, so the Linter is not incorrect on trying to run on them. So ignoring them would be a valid use case here.

**Comment by themensch** [comment]
@pjkaufman That was my take as well.  I have the excalidraw files scattered throughout my vault and while I've ignored the default excalidraw folder, I haven't yet hit other subfolders, but I could.  A regex ignore option. would be super handy though.

**Comment by pjkaufman** [comment]
I have a theoretical solution for this. I think it will work, but I am not certain. I will probably create a beta release for this since I want to make sure any bugs get caught before it goes out to everyone. But the changes I am planning on merging should handle it.

**Comment by pjkaufman** [comment]
I am going to go ahead and merge this change. It will be on master and go out with the next release.

**Comment by pjkaufman** [comment]
This change should now be in the latest beta release (1.25.0-rc-1). Feel free to test it out.

**Comment by themensch** [comment]
@pjkaufman Thank you!
