### ISSUE TITLE
Bug: Heading spacing being violated by paragraph spacing

### ISSUE THREAD

**Issue by theukedge** [platers/obsidian-linter#1011]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

I noticed Linter was doing something peculiar regarding spacing between headings and paragraphs. I have both [Heading blank lines; `Bottom=false`](https://platers.github.io/obsidian-linter/settings/spacing-rules/#heading-blank-lines) and [Paragraph Blank Lines](https://platers.github.io/obsidian-linter/settings/spacing-rules/#paragraph-blank-lines) turned. I always want no spacing below a heading, but in all other circumstances, I want the Paragraph Blank Lines rule to make sure that there's one (and only one) blank line between paragraphs. However, when both rules are enabled, the Heading rule runs first, followed by the Paragraph rule, so the paragraph rule inserts a space between the heading and the subsequent paragraph.

## How to Reproduce

1. Enable both the Paragraph Blank Lines and Heading Blank Lines rules.

Example to reproduce issue with

``` markdown
## Heading 2

## Heading 2a
This paragraph is right up against the heading.

This paragraph is next.
This one doesn't have a space between the preceding one.
```

[Linter log.md](https://github.com/platers/obsidian-linter/files/14185988/Linter.log.md)

## Expected Behavior

``` markdown
## Heading 2

## Heading 2a
This paragraph is right up against the heading.

This paragraph is next.

This one doesn't have a space between the preceding one.
```

## Actual Behavior

``` markdown
## Heading 2

## Heading 2a

This paragraph is right up against the heading.

This paragraph is next.

This one doesn't have a space between the preceding one.
```

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Hey @theukedge . That is actually the expected behavior. The rules generally do not communicate with one another. On top of this, `Bottom=false` only means that it will not add a blank below a heading and will try to remove a blank line between headings.

**Comment by theukedge** [comment]
Thanks for the reply @pjkaufman. I don't disagree that it's "expected" behaviour, but only because you can't alter the order in which rules are applied. Am I right in thinking that if Paragraph Blank Lines was applied first, and Heading Blank Lines second, then it'd format as I would like it? Because it'll space everything out like they're separate paragraphs, but then remove the blank lines after headings? If so, there must be other situations where the execution order of rules causes conflicts? Might it be worthwhile to introduce a priority system, so that every rule starts with an initial priority of, say, 500, but you can manually adjust the priority to any integer between 1 and 1000?

Also, I think that my understanding of `Bottom=false` was as you described it, so I'm curious if there's some nuance that I'm missing? I would expect it to add a blank line above headings, but not below.

**Comment by pjkaufman** [comment]
If the order in which those two ran were different, it would result in the exact same result since `Bottom=false` leaves spacing below a heading alone unless it is followed by another heading.

**Comment by pjkaufman** [comment]
You likely need to use a custom regex in order to handle that spacing.

**Comment by pjkaufman** [comment]
Hey @theukedge , did you opt to use a custom replacement under the custom tab to get the desired output?

**Comment by pjkaufman** [comment]
Hey @theukedge . Could you try the following custom regex to see about removing the blanks after a heading?
regex find: `(^#+\s.*)\n+`
regex replace: `$1\n`
regex flags: `gm`

Does that take care of the scenario in question?

**Comment by pjkaufman** [comment]
Hey @theukedge . I wanted to check in see if you had had time to see if the custom replacement from my previous comment formatted the headers the way you wanted?

**Comment by mahtaran** [comment]
> Hey @theukedge . Could you try the following custom regex to see about removing the blanks after a heading? regex find: `(^#+\s.*)\n+` regex replace: `$1\n` regex flags: `gm`
> 
> Does that take care of the scenario in question?

@pjkaufman, though I am not the original author of this issue, I was facing the same issue and this regex fixed it. Perhaps this could be added to the documentation?

**Comment by pjkaufman** [comment]
> > Hey @theukedge . Could you try the following custom regex to see about removing the blanks after a heading? regex find: `(^#+\s.*)\n+` regex replace: `$1\n` regex flags: `gm`
> > Does that take care of the scenario in question?
> 
> @pjkaufman, though I am not the original author of this issue, I was facing the same issue and this regex fixed it. Perhaps this could be added to the documentation?

What would it look like to add this to the documentation? I am not sure whether you are saying to add an info bubble to the website or something else.

**Comment by mahtaran** [comment]
Yes, that's precisely what I meant! I made a quick PR with how I envision such a warning to look like.

**Comment by theukedge** [comment]
Sorry for the delayed follow-up here. It *almost* fixes my problem.

It *does* space paragraphs correctly, while still leaving no space between a heading and the paragraph below it, *but*, it also bunches up headings that do not have paragraphs below them.

For instance, when I have this text:
````
## Daily notes
Text

Text

Text

## Journal

Text
Text

Text

## Another H2

## Communication log
### 0000
````

and I lint it, I would like it to look like this:

````
## Daily notes
Text

Text

Text

## Journal
Text

Text

Text

## Another H2

## Communication log
### 0000
````

but instead it does this:

````
## Daily notes
Text

Text

Text

## Journal
Text

Text

Text

## Another H2
## Communication log
### 0000
````

That is to say, it handles the Daily Notes section and the Journal section correctly, but my desired behavior would be that it leaves the spacing between `Another H2` and `Communication Log`, *while* leaving the `0000` up against the `Communication Log`.

Here's my desired ruleset:

1. If a heading has no paragraph text beneath it, and is followed by another heading tag of the same or higher level (e.g. H2 that is followed by H2 or H1), there should be one blank line between the two heading tags.
2. If a heading has no paragraph text beneath it, and is followed by another heading tag of a lower level, there should be no spacing between the two heading tags (I forget if there's a linting option that correctly adjusts for missing levels, e.g. H2 followed by H4 becomes H2 followed by H3 - if so, this could be simplified to "followed by another heading of the next level down")
3. If a heading has paragraph text beneath it (or I suppose, anything that is not a heading tag), there should be no space between the heading and the paragraph text

So, this:

````
## Heading 1.1
### Heading 1.1.1
### Heading 1.1.2
## Heading 2.1

### Heading 2.1.1
Text

### Heading 2.1.2

Text
### Heading 2.1.3
1. Bullet 2.1.3.1

### Heading 2.1.4

1. Bullet 2.1.4.1
````

should become this:

````
## Heading 1.1
### Heading 1.1.1

### Heading 1.1.2

## Heading 2.1
### Heading 2.1.1
Text

### Heading 2.1.2
Text

### Heading 2.1.3
1. Bullet 2.1.3.1

### Heading 2.1.4
1. Bullet 2.1.4.1
````

**Comment by Drakemoor** [comment]
I wish there was a way to achieve this.
