### ISSUE TITLE
Bug: Sort YAML Array Values rule sorts uppercase values before lowercase ones

### ISSUE THREAD

**Issue by redactedscribe** [platers/obsidian-linter#1024]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Sort YAML Array Values claims to sort arrays alphabetically but it actually sorts uppercase values alphabetically first, and then lowercase ones alphabetically.

## How to Reproduce

1. Enable Sort YAML Array Values rule and lint a file which has the content below:

Example to reproduce issue with

``` markdown
tags:
  - tag/a
  - tag/B
  - tag/c
  - tag/D
```

Gets linted as

``` markdown
tags:
  - tag/B
  - tag/D
  - tag/a
  - tag/c
```

## Expected Behavior

Sort alphabetically regardless of case.

Expected output if applicable:

(Same as first codeblock above)

``` markdown
tags:
  - tag/a
  - tag/B
  - tag/c
  - tag/D
```

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

Linter v1.23.1

**Comment by pjkaufman** [comment]
Hey @redactedscribe . Can you verify that sorting algorithms do not distinguish between case when they sort alphabetically? It is my understanding that sorting has always been affected by the case of the text unless it is specified to be case insensitive.

**Comment by pjkaufman** [comment]
What I am seeing on the matter is that end users seem to care about case where as the sorting algorithms care about case: https://ux.stackexchange.com/questions/79259/does-case-matter-when-reading-and-sorting-a-list-of-items.

I am not 100% sure I consider this a bug. I understand that end users may, but since I am a programmer I wrote the logic with the assumption that whatever the default sorting algorithm handled would be the way it got sorted alphabetically. It looks like JS does care about case.

If this is something that gets changed, we would need to swap to something like what is described [here](https://stackoverflow.com/a/9645447/8353749).

**Comment by redactedscribe** [comment]
After a quick search, how an algorithm chooses to sort (sensitively vs insensitively) really depends on what's trying to be achieved. I think because the sorting serves no purpose other than for the users to easily locate items in a array/list, I'd argue it would make better sense to sort case-*in*sensitively. Then there would be no need to check two locations for values beginning with 'a' for example: the top and the middle (A and a).

I'm not sure how sorting case sensitively would help a program ingesting this data more than if it were case *in*sensitively. To me, the main purpose of sorting is usability, but I'm biased since I tend to focus on UX/UI stuff.

**Comment by pjkaufman** [comment]
This will probably get updated to be a case insensitive sort since that will likely be the most useful for users. But I am a little hesitant on that.

**Comment by redactedscribe** [comment]
Feel free to present further arguments against doing so, but so far I can't think of a compelling reason to keep it as it is.

**Comment by pjkaufman** [comment]
I believe I have a fix for this, but it likely will not go out until the next release which could be a couple weeks or so barring a lot of bugs that need addressing.

**Comment by pjkaufman** [comment]
I added the change to master. It should be on master and go out in the next release. Please let us know if there are any issues with this.

**Comment by redactedscribe** [comment]
Works as expected. Thanks @pjkaufman!

**Comment by pjkaufman** [comment]
No problem. Thanks for pointing it out!
