### ISSUE TITLE
Bug: There is a space between the underline and the Chinese text

### ISSUE THREAD

**Issue by XiaoTonghuan** [platers/obsidian-linter#1036]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

such as

English: Hello-World, that is no bug
Chinese: 你好 - 世界，I think this is a bug, not feature or regular.

## Expected Behavior

Expected output if applicable:

``` markdown
你好-世界
```

**Comment by pjkaufman** [comment]
Hey @XiaoTonghuan , thanks for opening an issue. I am not sure that this is a bug since it looks to me like you are using a non-fullwidth dash with Chinese characters. Do you have the rule for Spaces Between CJK and English or Numbers enabled? If so, I believe this is expected behavior.

**Comment by XiaoTonghuan** [comment]
Yeah, you're right, Maybe I should use fullwidth dash. thank you.

**Comment by XiaoTonghuan** [comment]
Emmm, I think it's strange to use full width dash, because I'm used to adding non-fullwidth dash between numbers and Chinese characters or Chinese and English in Heading, so, Are you interested in adding a rule to exclude characters that do not require spaces?

**Comment by XiaoTonghuan** [comment]
@pjkaufman I think this feature is necessary.

**Comment by pjkaufman** [comment]
I believe I have a change that should make this no longer an issue. But it is coming as a feature addition where you will need to remove `-` from the list of punctuation and symbols.

**Comment by pjkaufman** [comment]
I have merged the change into master. It should be on master and go out in the next release. It looks to be working, but there may be some issues with it. Feel free to let us know if there are any issues.
