### ISSUE TITLE
FR: Do not auto format if only the modifed field changes

### ISSUE THREAD

**Issue by rebornsick** [platers/obsidian-linter#1040]
## Is Your Feature Request Related to a Problem? Please Describe.

I'd love to enable `Lint on File Change` option but I have a problem with it.

I'm using Linter to add `created` and `modified` in YAML to track my notes changes.

When I simply open a note and close it (no modif), the modified time in the YAML header changes, which adds a modified file in Git and messes up my Dataview querywith the `modified` field.

## Describe the Solution You'd Like

I don't know about the code things, can we add a check if there are nothing formated except `modified` filed then don't format the notes?

## Describe Alternatives You've Considered

For now I'm using `Lint on Save` which is a little inconvenient and sometimes forgot to save manually.

## Additional Context

here is what diffview looks like

<img width="314" alt="Snipaste_2024-03-13_19-09-29" src="https://github.com/platers/obsidian-linter/assets/28842872/1bd06ba7-1a43-464c-a9bd-9112bd17d419">

**Comment by rebornsick** [comment]
@pjkaufman Thanks for your hardwork, I just tested with a new vault and find out that might be syncing issue which caused by remote-save.🤣

But it would be nice to have a option to auto lint depending on actual file changes instead of file modification time in obsidian, like what we did for the creation time. File metadata is not "true" sometimes and that's why we add extra YAML frontmatter for creation or modification time.

**Comment by pjkaufman** [comment]
Yeah. That definitely sounds like a syncing issue since many syncing services do not set the file metadata to the same thing across systems.

But as for adding this, it definitely sounds like #183 would handle the problem for modification date. But it will likely be some time before all the tickets that prevent its implementation get added.

**Comment by pjkaufman** [comment]
You may be able to use [https://obsidian.md/plugins?search=update%20modified](https://obsidian.md/plugins?search=update%20modified) for the time being to automatically update date modified when a file changes.

**Comment by rebornsick** [comment]
OK thanks, this workaround works perfect.
