### ISSUE TITLE
Bug: couldn't load plugin on android mobile obsidian

### ISSUE THREAD

**Issue by Ariestar** [platers/obsidian-linter#1052]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug
![Screenshot_20240320_105754_md obsidian_edit_10498572498397](https://github.com/platers/obsidian-linter/assets/47706741/60336179-6ca2-4516-9ce3-2a4701d75710)

I download the plugin of my mobile obsidian from the community, but it could be installed but failed to be enabled. It said "failed to load the plugin obsidian-linter"

## Device

- [ ] Desktop
- [x] Mobile

## Additional Context

I tried to transfer the plugin folder from my pc which is worked well on my PC obsidian. But the same problem. I guess the problem is from the code not my device.

**Comment by pjkaufman** [comment]
Hey @Ariestar . Is this an issue still?

**Comment by Ariestar** [comment]
> Hey @Ariestar . Is this an issue still?
Yeah, it's still an issue, but I found that there's actually many plugins that cannot be loaded on mobile Obsidian. So I think the the problem is caused by Obsidian not Linter.
