### ISSUE TITLE
Bug: Blockquote Style removes code block indentation

### ISSUE THREAD

**Issue by mahtaran** [platers/obsidian-linter#1055]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

When [blockquote style](https://platers.github.io/obsidian-linter/settings/content-rules/#blockquote-style) is turned on, it will remove indentation inside code blocks.

## How to Reproduce

Given the following example:

```markdown
> Example blockquote
>Wrongly indented line
> 
> ```javascript
> function greet() {
>     console.log("Hello mom!")
> }
> ```
```

### Expected Behaviour

```markdown
> Example blockquote
> Wrongly indented line
> 
> ```javascript
> function greet() {
>     console.log("Hello mom!")
> }
> ```
```

### Actual Behaviour

```markdown
> Example blockquote
> Wrongly indented line
> 
> ```javascript
> function greet() {
> console.log("Hello mom!")
> }
> ```
```

## Additional Context

I believe this issue could be resolved by defining an `insideCodeBlock` flag in [updateBlockquoteLines](https://github.com/platers/obsidian-linter/blob/5e96e0ec59eba39acc352fd787adf400190aedff/src/rules/blockquote-style.ts#L58) which will skip any lines inside the code block.

**Comment by pjkaufman** [comment]
Hey @mahtaran . If we are saying saying that we are ignoring code blocks in blockquotes altogether, then we would add them to an ignore list. But if we are saying we still need to apply the blockqoute style to those lines then a flag would be needed.

**Comment by mahtaran** [comment]
Yeah, I feel like ignoring any content within code blocks might be the best solution.

**Comment by pjkaufman** [comment]
It will ignore the blockquote indicators as well. So that means it would end up being something like the following to the rule:

``` markdown
```

**Comment by pjkaufman** [comment]
Does that sound like the intended result? It will replace `{CODE_BLOCK}` with its original content.

**Comment by mahtaran** [comment]
Yes! Perhaps it could still check the indentation before the opening backticks, but apart from that I'd leave it up to the user how they want to indent their code.

**Comment by pjkaufman** [comment]
I think it would still allow for the opening backticks, but the rest would be unaffected.

**Comment by pjkaufman** [comment]
I believe I have a fix. It just needs to finish running the CI and if that passes, I will go ahead and merge it.

**Comment by pjkaufman** [comment]
I have merged the change. So this issue should be fixed on master and in the next release. Please let us know if it is not working in either case.
