### ISSUE TITLE
Question: Possible to Save Current Time When Using Template to Create Note

### ISSUE THREAD

**Issue by kennygokh** [platers/obsidian-linter#1066]
Hi, any advise on how to set the current date & time when I create the note using template? Currently, the template has "created" field in frontmatter which store the created date & time of the template file. Hence, when I create note using template, the note created with the template's created date & time instead of current date & time. Example as below.

Template Note A - "created" field save as 01-Mar-2024 09:00
New Note Name B (created based on Template Note A) - "created" field save as 01-Mar-2024 09:00 (the same as Template Note A). How to make it that New Note Name B store current date & time in "created" field?

**Comment by pjkaufman** [comment]
Hey @kennygokh , this sounds like an odd scenario. Have you ignored the folders that include your templates?

**Comment by kennygokh** [comment]
Hi Peter,

Thanks for you advice. I have tried ignore Templates folder and it looks like working now.

Regards.

Kenny Go

**Comment by pjkaufman** [comment]
I am going to close this as it seems to already have been addressed by ignoring folders.
