### ISSUE TITLE
FR: Add option to skip Liquid tags and content wrapped by them

### ISSUE THREAD

**Issue by xplosionmind** [platers/obsidian-linter#1067]
## Is Your Feature Request Related to a Problem? Please Describe.

I use [Eleventy](https://11ty.dev) to publish what I write/edit in Obsidian. Sometimes, Markdown linting breaks [Liquid](https://liquidjs.com) tags and/or the content inside them.

## Describe the Solution You'd Like

Give two opt-in choices to users:

- Skip what is between `{%` `%}` and `{{` `}}` tags
- Allow users to choose closing and ending tags to pinpoint what blocks to exclude. In the example below, the opening tag would be `{% renderTemplate "md" %}`, and the closing tag would be `{% endrenderTemplate "md" %}`.

**Please include an example where applicable:**

```liquid
{% renderTemplate "md" %}
  <h1>{{ something }}</h1>
{% endrenderTemplate "md" %}
```

(Original text = expected outcome, because it should be skipped)

**Comment by pjkaufman** [comment]
Hey @xplosionmind . Out of curiosity, have you already tried using the [range ignore syntax](https://platers.github.io/obsidian-linter/usage/disabling-rules/) for this?

**Comment by xplosionmind** [comment]
Hi @pjkaufman, thanks for your reply!

> have you already tried using the [range ignore syntax](https://platers.github.io/obsidian-linter/usage/disabling-rules/) for this?

I did not know about this! For sure it can be a nice workaround, but providing an option specific for custom tags to be ignored would be much more convenient, without having to type `<!-- linter-disable -->` many times in many files.

**Comment by pjkaufman** [comment]
Hey @xplosionmind , I have not seen users requesting this feature at this time. Since it is something that can be fixed with the ranged ignores, I am going to close this for now. If users do indeed want this feature, it can be reconsidered at a later date.

**Comment by xplosionmind** [comment]
I understand. Thank you, @pjkaufman!
