### ISSUE TITLE
Several Minor Suggestions as the number of rules grows

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#107]
Now that the number of rules is slowly growing (🥳), I think some small changes might be appropriate to keep it overseeable:
1. the rules on the [front page readme](https://github.com/platers/obsidian-linter#rules) should be sorted by rule-category
2. rules could get numbers as aliases, as many linters have, e.g. [Markdownlint](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md)
3. break up the "Spacing" Rule-Category into "Spaces" and "Line Breaks", as the category is otherwise quite big in comparison to the others
4. condense the display settings, since you have to scroll quite a bit by now. Here a suggestion how I would condense it:
<img width="1096" alt="Screenshot 2021-10-15 22 16 35" src="https://user-images.githubusercontent.com/73286100/137548822-904218a5-9045-4390-bfad-94b43ec7a59a.png">

5. edit: also, you might consider move the [rules section of the readme](https://github.com/platers/obsidian-linter#rules) up to be the first heading – right now, they come after contributing and explanations how to disable rules. However, as the rules are the core of the linter, I think the order of sections in the readme should be rules → usage → contribution

**Comment by platers** [comment]
Great suggestions! Will probably implement most of them. 
I'm not sure what the benefit of having numbers as aliases is.

**Comment by JeppeKlitgaard** [comment]
One benefit of using the same numbers as Markdownlint and custom ones for other features would be that it would be easy to get an impression of which rules from Markdownlint are already implemented.

The number/ID could be displayed after the title of each rule (where the upper arrow of the @chrisgrieser's lovely diagram is pointing)

**Comment by chrisgrieser** [comment]
Thanks for implementing the improved settings menu so quickly already, looks much better! Now with the more condensed design, I noticed a new small issue: the `hr` is visually a bit confusing. You are using `hr` as underline of the headers, while I however, instinctively see things between two `hr` as one unit. So in this case, for example, visually, the close succession of `hr`s tells me that the sentence "header levels should only increment by one level at a time" belongs together with "file name heading".

<img width=50% alt="Screenshot 2021-10-20 01 44 14" src="https://user-images.githubusercontent.com/73286100/138005413-bbe36859-1e9f-464b-b118-2f7bcc0094b4.png">

I would suggest to simply remove the `hr`, which would remove the visual confusion that at least some people like me get. This has the bonus benefit of saving *yet another* line of space, making the settings menu even more condensed. :)

**Comment by chrisgrieser** [comment]
@platers 
I think not? Like I just checked a bunch of plugins and most of them have `hr`s, where heading and description are between `hr`s, instead of having a `hr` between them.

<img width=30% alt="Screenshot 2021-10-20 02 19 10" src="https://user-images.githubusercontent.com/73286100/138007661-2f30c78c-91a7-47f2-8547-30da2c264a60.png">

I think the issue arises as the rule names get `h3` as class and the descriptions get `setting-item-name`. What you could do is to give rule names the class `setting-item-name` and assign `setting-item-description` to the rule descriptions. This will most likely place the `hr`s correctly. And as a side benefit, the litner settings would be more consistent with how the other plugin settings are styled.

**Comment by pjkaufman** [comment]
@chrisgrieser , looks like it was added by `setting-item`. I was able to add some logic to remove the border at the top of the element which was displaying like an hr. I am adding a PR for this and should have it merged today.
