### ISSUE TITLE
FR: Keep Title if It Already Exists

### ISSUE THREAD

**Issue by danielo515** [platers/obsidian-linter#1071]
- [ ] I have verified that I am on the latest version of the Linter

## Describe the Bug

I have the title feature activeated, but sometimes I already have a title, and I want to keep it different from the main H1, but when I run the linter the title is overwritten with the contents of the main h1

## How to Reproduce

1. Set a title
2. Ensure the title rule is active
3. Set an H1
4. Run the linter

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Hey @danielo515 . Thanks for the feedback. I believe that this is not currently a use case or functionality that the Lintee handles. So this would be a feature request. I will update the issue name accordingly.

**Comment by pjkaufman** [comment]
Please do let me know if the Linter does say it will only add/replace the title in the frontmatter if it is not currently present.

**Comment by danielo515** [comment]
Thank you for your answer @pjkaufman 
As everything in life, it is subject to interpretation: 
<img width="809" alt="Screenshot 2024-04-11 at 13 58 09" src="https://github.com/platers/obsidian-linter/assets/2270425/7e7530f1-9fac-431a-8a43-580681bc2d14">
It says "inserts", it us up to the reader to interpret if that means that it will add only if not present or not.
I'm ok with keeping this as a feature request, because it is true that the current behavior can be understood as correct.
Maybe, now that you are adding features... it can be a mode called sync? if the title exists in the frontmatter, it can be added as h1?

**Comment by pjkaufman** [comment]
> It says "inserts", it us up to the reader to interpret if that means that it will add only if not present or not. I'm ok with keeping this as a feature request, because it is true that the current behavior can be understood as correct.

This term can probably be updated to be "Inserts or replaces" to help reduce confusion here. I think the examples on the website help clarify it, but I could be wrong. But is definitely something that would be good to have updated in the plugin settings so it leads to less confusion.

> Maybe, now that you are adding features... it can be a mode called sync? if the title exists in the frontmatter, it can be added as h1?

I think there have been requests for something like that in the past, but so far that has not really gone anywhere. I would be open to PRs around this, but a lot of my time right now is taken up with some other features I am working on.

**Comment by pjkaufman** [comment]
This issue will only be for the UI update. For the feature mentioned, you will want to go over to #192  or a new issue if that does not cover what you are looking for.

**Comment by pjkaufman** [comment]
I have made the wording changes for `YAML Title Alias`. It should be present in the next release.
