### ISSUE TITLE
FR: Don't auto-complete acronyms

### ISSUE THREAD

**Issue by Kainkun** [platers/obsidian-linter#1075]
## Is Your Feature Request Related to a Problem? Please Describe.

For example, ['aadd', 'add'], converts aadd to add regardless of capitals. If AaDD is an acronym, it gets converted to Add.

## Describe the Solution You'd Like

Add an option to not auto-complete if characters after the first character is capital.

**Please include an example where applicable:**

I would still like aadd and Aadd to be converted to add and Add.
Just not things like AADD, aADD, aaDD, aadD, AADd, AAdD, etc.

## Describe Alternatives You've Considered

Cant think of any alternatives

## Additional Context

n/a

**Comment by pjkaufman** [comment]
This is in progress and I believe a fix for this is being added in the form of an option to say only auto-correct words with up to 1 capital letter present.

**Comment by pjkaufman** [comment]
I have merged the PR to add ignoring acronyms/words with multiple capital letters in them. It should be on master and in the next release. Please let us know if either has an issue.
