### ISSUE TITLE
Bug: Created date gets updated to a different timezone

### ISSUE THREAD

**Issue by chmac** [platers/obsidian-linter#1077]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

This is the diff I see in git after linting a file:

```patch
-created: 2024-04-03T15:23:19+01:00
-updated: 2024-04-03T15:26:57+01:00
+created: 2024-04-03T16:23:19+02:00
+updated: 2024-04-24T07:43:39+02:00
```

## How to Reproduce

1. Enable the option "Date Created" and "Force Date Created Key Value Retention"
2. Create a file, save it
3. Wait for DST to roll around (or change your system timezone)
4. Lint file again

## Expected Behavior

I expect the value in `created` to remain the same when I have the value retention option set.

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Hey @chmac , thanks for reportting this. This does seem odd, but I am guessing the problem is that moment does not consider values from a different timezone valid when parsed. I will need to look into this once I get some time.

**Comment by pjkaufman** [comment]
Just in case I did not document this in the docs, the created date retain value will be updated if you change your locale, you have a date that moment does not consider valid for the provided locale and format, or your format changes.

I will need to see if any of these 3 get triggered here. Hopefully this is just an oversight and not one of those three scenarios.

**Comment by pjkaufman** [comment]
Also, @chmac , could you provide your date format? I would prefer to nor have to recreate it from trail and error if possible to make sure things can be tested faster.

**Comment by chmac** [comment]
@pjkaufman I haven't changed the format since I set it up. I think the thing that's changed is DST, but I could be wrong. I've played with when to enable / disable auto linting because I'm using git. So once I pull changes on another machine, I think the file's creation time and modification time are set to the time of the pull, and not the same time as on the other machine. Auto linting all the time lead to all of these spurious changes. But I just noticed that it's actually the same date but only changing the timezone. That's for the created date anyway.

Here's my format:

    YYYY-MM-DDTHH:mm:ssZ

Thanks for responding so quickly to this, and in general, thanks for linter, it's really awesome and has improved my obsidian experience no end. 🧡

**Comment by pjkaufman** [comment]
I am glad to hear that. I will have to see about reproducing this at some point.

**Comment by chmac** [comment]
I know my way round TypeScript fairly well, although mostly web, mobile, node and deno rather than Obsidian plugins. But if you have any ideas about where the issue might lie, I could spend some time digging into it and see if I can figure out what's going on. I'm seeing this every day with the "lint on change" setting enabled, so that provides me some motivation to see if I can fix it! :-)

**Comment by chmac** [comment]
Well, turns out your code is much easier to navigate than I expected. So, 10 minutes later, I guess I found the issue:

https://github.com/platers/obsidian-linter/blob/d8aefcba8e465f6d4c5175efe4db8cafce00876c/src/rules/yaml-timestamp.ts#L111-L116

Here's my understanding of what's happening:

- The current date is read from yaml
- That date is parsed into a moment object
- The date is formatted with the current format string
- This value is compared against what is in the file

Here's where the issue arises. If the DST change has happened, `moment.format()` will return a different string output (at least for my format). Moment is always outputting dates in local time, not in UTC, etc. That means when you change timezones, then the text representation of the date changes. Which in turn triggers an update to the YAML field value.

## Intended behaviour?

I guess one could take the view that this is the intended behaviour. I believe this means that every time the user's timezone changes, their created_at dates will be updated. The string representation of the dates will be different.

The idea of keeping the same date but parsing it into the new format (if the format has changed) is a nice idea. But it seems like it clashes with the timezone issue. I'm not sure what to suggest as an approach here, I don't know the plugin well enough to offer anything more than uniformed opinion.

What do you think?

**Comment by pjkaufman** [comment]
Hey @chmac , that sounds like it is pretty much the problem there. I am not sure of many good ways of determining if a time format has changed. Because if the time format is changed programmatically or outside of the plugin settings page in Obsidian, it may not get caught. That being said, there is an issue open to convert data to UTC and its associated PR: #1070

Would using UTC instead of the local timezone fix things for you?

If not, there is the possibility of trying to handle things more delicately when the timezone specifier has been added to the actual timezone string. The problem will be that changes to the format may be ignored. Though I think we could do a timzone agnostic comparison where the timezone is stripped out of the text, but that may be error prone (it would need to check that both values have a timezone value before it stripped the timezone from it).

How does that sound to you? Do you see any glaring issues in either using UTC or stripping out the timezone info when we do a text comparison when the timezone info is present in the format?

**Comment by chmac** [comment]
I have just figured out why it only becomes an issue when the timezone is included in the output. If it's just `2024-04-28:12:00` then when it gets parsed back, it is actually a different time, but it's parsed in the current timezone and so it doesn't produce a change. 🤔 

Using UTC would be an option for me. In my case I'm usually 1/2 hours from UTC. But it does lose a little of the readability. I like the human readable date format because I can see that something was last edited at 23:00 and think, hmm, late night!

Thinking about this from a totally different angle, would it be an option to add a setting that says "never change the created value"? In my case, I'd be happy with that. Whatever was written, in whatever format, can stay. If I want to change the format I would handle that separately.

If I understood the code correctly, the current value is parsed based on the current format. So a dramatic change of format might not actually work? Like if I went from `2024-04-28:12:00` to `Sunday 28th April 2024 at 12:00` then I guess the parsing of my old data would fail anyway.

Is there a use case where the format update succeeds? I'm not sure how moment's parsing works and how "smart" it is at figuring out the old values.

**Comment by pjkaufman** [comment]
There is a section of logic that is meant to parse the value if parsing using the current timestamp fails: https://github.com/platers/obsidian-linter/blob/d8aefcba8e465f6d4c5175efe4db8cafce00876c/src/rules/yaml-timestamp.ts#L182

But maybe there is a better way to tell if there was an issue getting the current date. I do think we still need to handle the format changing where possible. So I would rather handle that rather than add another setting option if possible.

**Comment by chmac** [comment]
Ah, right, I missed that part. Makes sense. Okay, so parse the format, try to parse the old date. Hmm, yeah, I can see your point that handling timezones specially seems like a reasonable approach.

It seems like moment has 4 different tokens that output the timezone, `z`, `zz`, `Z`, `ZZ`. The lowercase variants are deprecated from 1.6.0. I'm not sure how robust the logic needs to be. If the format field contains one of those tokens, then we use a different comparison method? I suppose that would mean if the current format has a timezone included, then it wouldn't overwrite an old format.

Here's a different idea. What about comparing the `actualFormat` with the current format, and if they're the same, and the preserve flag is set, then we skip any further checks?

In theory, this would mean that we catch format changes, and then use the standard logic, but ignore cases where the format hasn't changed but the output it would render has.

**Comment by pjkaufman** [comment]
> Ah, right, I missed that part. Makes sense. Okay, so parse the format, try to parse the old date. Hmm, yeah, I can see your point that handling timezones specially seems like a reasonable approach.
> 
> It seems like moment has 4 different tokens that output the timezone, `z`, `zz`, `Z`, `ZZ`. The lowercase variants are deprecated from 1.6.0. I'm not sure how robust the logic needs to be. If the format field contains one of those tokens, then we use a different comparison method? I suppose that would mean if the current format has a timezone included, then it wouldn't overwrite an old format.
This probably could be done, byt your next point is the approach I like best.

> Here's a different idea. What about comparing the `actualFormat` with the current format, and if they're the same, and the preserve flag is set, then we skip any further checks?
> 
> In theory, this would mean that we catch format changes, and then use the standard logic, but ignore cases where the format hasn't changed but the output it would render has.

I think this would be the approach to take. I would need to double check a few things in the code, but this seems more reasonable and lines up more with what I was thinking when I saw this logic here.

**Comment by chmac** [comment]
I'm happy to try my hand at a PR if you like. I would probably do it freehand on GitHub, I wouldn't have the whole codebase running and so on, so I won't have linting, etc. But if it's helpful, let me know and I'll have a go.

**Comment by pjkaufman** [comment]
Feel free to take a stab at it if you would like right now. I plan to take a look on Wednesday if I do not have time tonight. I am creating a release tonight which should take a little bit of time, but I do have other things to tackle, so I am not sure if I will be able to get to this today.

**Comment by pjkaufman** [comment]
Looks like I may have a little bit of time. I will try to recreate this situation and then resolve it from there.

**Comment by pjkaufman** [comment]
I believe I have a fix. I will put a zipped `main.js` here for you to test if you so choose and I will create a PR to fix this issue.
[main.zip](https://github.com/platers/obsidian-linter/files/15156079/main.zip)

**Comment by pjkaufman** [comment]
I have merged what I believe fixes this issue. You can build from master, wait for the next release (not v1.24.0 as I released that earlier today), or use the `main.zip` attached above. If any of these do not work for this issues, please let us know and we can reopen this issue and look at this again.

**Comment by chmac** [comment]
@pjkaufman That's awesome! Thanks a lot. Really appreciate how quickly this got solved also.

Just tested the main.zip you shared, and it works like a charm. No timezone changes!

🚀 🧡 🚀

**Comment by pjkaufman** [comment]
I am glad to hear that. Thanks for working with me on possible solutions.
