### ISSUE TITLE
Question: How do I increase the number of new lines to two before a heading?

### ISSUE THREAD

**Issue by AndreiSager** [platers/obsidian-linter#1079]
What you would like to know more about... I would like to know how I can use the linter to maintain two spaces before a heading like the sample image.

My goal is to have one space on the bottom of a heading and two spaces on the top (except where the heading is at the beginning or at the ending of the document).

# Images

![326461117-b5f4c8c4-643b-4ec5-81ae-c755713c6939](https://github.com/platers/obsidian-linter/assets/107153674/32d13a6a-6434-4239-a68f-6aaf9a0c82c1)

![Screenshot 2024-04-29 215159](https://github.com/platers/obsidian-linter/assets/107153674/53f2b8ac-e1ea-4645-a44d-20bbb67fe58e)

**Comment by pjkaufman** [comment]
Hey @AndreiSager . The Linter does not directly support this use case. However it does allow you to use custom regex for this situation. How familiar are you with regex?

**Comment by AndreiSager** [comment]
Thanks for responding! I am not familiar with regex, but I have heard of it.

**Comment by LV** [comment]
For those reading this, these are the steps necessary to make this happen:

1. Open Settings > Linter > Custom
2.  _Add new regex replacement_, do the following:
- regex to find: `([^ \t\r\n\v\f])\n(#)`
- `gm`
- regex to replace: `$1\n\n$2`

**Comment by AndreiSager** [comment]
> For those reading this, these are the steps necessary to make this happen:
> 
> 1. Open Settings > Linter > Custom
> 2. _Add new regex replacement_, do the following:
> 
> * regex to find: `([^ \t\r\n\v\f])\n(#)`
> * `gm`
> * regex to replace: `$1\n\n$2`

Thank you for your solution! I have tried it and it is not working. Am I supposed to disable or enable a setting to make it work?

![image](https://github.com/platers/obsidian-linter/assets/107153674/fd4d82ef-c615-4fc7-88a8-ed0e440c8d21)

**Comment by pjkaufman** [comment]
The regex you need will be based on the following logic in the code:
``` Typescript
      text = text.replace(/^(#+\s.*)/gm, '\n\n$1\n\n'); // add blank line before and after headings
      text = text.replace(/\n+(#+\s.*)/g, '\n\n$1'); // trim blank lines before headings
      text = text.replace(/(^#+\s.*)\n+/gm, '$1\n\n'); // trim blank lines after headings
    }

    text = text.replace(/^\n+(#+\s.*)/, '$1'); // remove blank lines before first heading
    text = text.replace(/(#+\s.*)\n+$/, '$1'); // remove blank lines after last heading
```

So if you want to make it so that all headings have something like `/^(#+\s.*)/gm` and the `\n\n\n$1` for the replace.
Then you need to trim blank lines before headings if they are too long: `/\n{2,}(#+\s.*)/g` for find and `\n\n\n$1` for replace.
Lastly, you nedd to remove the blank lines before the first heading:
`^\n+(#+\s.*)` and the replace `$1` and make sure it has no flags.

Thus it looks something like this:
| Search | Flags | Replace |
| ----------- | --------- | ------------- |
| `^(#+\s.*)` | `gm` | `\n\n\n$1` |
| `\n{2,}(#+\s.*)` | `g` | `\n\n\n$1` |
| `^\n+(#+\s.*)` | `` | `$1` |

Note: I have not tested this and cannot really do so at this time. But hopefully this gets you roughly to wherw you need to be.

**Comment by AndreiSager** [comment]
@pjkaufman Thank you very much for helping solve my problem! The solution you gave works wonders!

![image](https://github.com/platers/obsidian-linter/assets/107153674/d3141d17-2f35-4ccc-8322-259aebac0d12)
![image](https://github.com/platers/obsidian-linter/assets/107153674/7f3c1ba5-a7ea-4ff6-81cb-97fd86970b18)

**Comment by pjkaufman** [comment]
I am glad that it works!

**Comment by andraxiusabyss** [comment]
For Obsidian-Linter version 1.28.0 this method breaks similar to below, but I have found the solution.

![Image](https://github.com/user-attachments/assets/7e98e8d5-2478-4042-8ce7-7d8f61f5e51f)

You should disable "Consecutive Blank Lines". It is the only setting that breaks the custom regex.

![Image](https://github.com/user-attachments/assets/734b1aad-6db0-4c98-8ab6-37bce0fe5fd0)

![Image](https://github.com/user-attachments/assets/bb44180e-d4ab-442d-86e3-e437dbbdbf00)
