### ISSUE TITLE
Settings Description needs to be updated

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#108]
With release 1.2.4, this was added:
> Ignored folders are no longer linted on manual lint

However, the settings still state this:
<img width="361" alt="Screenshot 2021-10-15 22 28 18" src="https://user-images.githubusercontent.com/73286100/137549643-8fd02b8d-47af-4548-9e84-a4cabc2de689.png">

**Comment by JeppeKlitgaard** [comment]
As far as I recall it does still lint on explicit manual lints, just not on 'lint-on-save' lints. I will update the settings description to match this.
