### ISSUE TITLE
Bug: tildes in URLs cause the URL to be broken

### ISSUE THREAD

**Issue by dawbarton** [platers/obsidian-linter#1084]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Whenever the linter encounters a URL with a tilde in, it breaks the URL. It doesn't seem to recognise that `~` is a valid character in a URL.

## How to Reproduce

1. Put `<https://some.website/~username/>` into a file
2. Run the linter
3. The result is `<<https://some.website/>~username/>` when the URL should have been left untouched.

**Comment by dawbarton** [comment]
Looks like a regex is incorrect <https://github.com/platers/obsidian-linter/blob/a67df98fdd7abebc971e2b7598a78a533c860a96/src/utils/regex.ts#L29>

**Comment by pjkaufman** [comment]
The change for this should now be on master and go out in the next release. Please let us know if it is not working in either place.
