### ISSUE TITLE
Bug: auto “created” and “modified” date time in custom format.

### ISSUE THREAD

**Issue by Diane-Best** [platers/obsidian-linter#1090]
- [ ] I have verified that I am on the latest version of the Linter

## Describe the Bug
It always does not work with auto “created” and “modified” date time in custom format. 

## How to Reproduce

1. Go to '.Linter Settings'
2. Click on 'YAML'
3. Scroll down to 'YAML Timestamp' > 'Format'
4. Enable "Date Created"
5. Enable "Format"
6. Add "YYYY-MM-DD HH:mm:ss" Format
7.  Execute Linter for the first time and front matter will be filled with the "null" date created

## Screenshots

![Clip_2024-05-08_18-10-52](https://github.com/platers/obsidian-linter/assets/12445472/4820b58a-fe1e-4458-8564-4a5a8d2a95c9)
![Clip_2024-05-08_18-11-21](https://github.com/platers/obsidian-linter/assets/12445472/77d265ce-ba1f-4d0f-abc3-af8339255f80)

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Hey @Diane-Best , it looks like you have not enabled the rule itself (the first toggle button below the rule name). If that is not toggled on, any values enabled under it are not going to run.

**Comment by Diane-Best** [comment]
Oh yes!  Sorry for your time. Thank you so much!

**Comment by pjkaufman** [comment]
No problem. I will go ahead and close this issue then.
