### ISSUE TITLE
Question: File Specific Rule Disabling in YAML Frontmatter - Hiding/Editing/Commenting Out rules

### ISSUE THREAD

**Issue by MemeAddict314** [platers/obsidian-linter#1092]
Hi, I am trying to disable some Linter rules in specific files relating to inserting YAML attributes. I have some documents that I want to have the automatic adding and updating of YAML properties on and some I don't. Based on what I've tried already, I wanted to know if there was a way to have the `disabled rules: [insert-yaml-attributes, yaml-key-sort, yaml-timestamp]` command hidden/commented out. In my setup, properties are displayed in YAML format (I would be ok switching to visible). The problem is, when I add the disabled rules to the documents I want to, it adds a whole section that if possible I would prefer to have removed. I tried using the `<!-- linter-disable --> <!-- linter-enable -->` range ignore for the YAML, but it messed with the formatting. If there are any rules I can change or code to add to make that happen I'd appreciate more information about it.

The ideal for me would be something that when Linter runs it goes:
```
If (in specific folder/files starting with @/files tagged a certain way [Not sure how this would work]):
> Lint file with disabled rules: [insert-yaml-attributes, yaml-key-sort, yaml-timestamp]
> Else Lint file normally
```
While not having `disabled rules: [insert-yaml-attributes, yaml-key-sort, yaml-timestamp]` in the YAML frontmatter visible. Thank you!

**Comment by pjkaufman** [comment]
Hey @MemeAddict314 , thanks for reaching out.

> Hi, I am trying to disable some Linter rules in specific files relating to inserting YAML attributes. I have some documents that I want to have the automatic adding and updating of YAML properties on and some I don't. Based on what I've tried already, I wanted to know if there was a way to have the `disabled rules: [insert-yaml-attributes, yaml-key-sort, yaml-timestamp]` command hidden/commented out. In my setup, properties are displayed in YAML format (I would be ok switching to visible). The problem is, when I add the disabled rules to the documents I want to, it adds a whole section that if possible I would prefer to have removed.

I see that you are using `disabled rules` in the frontmatter. I am not entirely sure what you mean when you say a section shows up that you do not want visible. My best guess is that you are saying that you would prefer the properties plugin to not display the disabled rules key and values in the widget. If that is the case, you would need to use custom CSS to hide that if possible. I would suggest looking at the Obsidian Discord if you plan to go this route. If you are referring to something else, could you elaborate on what the section is that you would not like to show?

> I tried using the `<!-- linter-disable --> <!-- linter-enable -->` range ignore for the YAML, but it messed with the formatting. If there are any rules I can change or code to add to make that happen I'd appreciate more information about it.

As of right now, the linter disable and enable comments turn off all formatting. There is a feature request that I added around making it work on a rule by rule basis (#878 ). But so far it has not been needed by most users. So right now, if you want formatting and to only disable specific rules in a file `disabled rules`  in the frontmatter is your best bet.

Hopefully this helps better understand the situation.

**Comment by MemeAddict314** [comment]
> My best guess is that you are saying that you would prefer the properties plugin to not display the disabled rules key and values in the widget. If that is the case, you would need to use custom CSS to hide that if possible. I would suggest looking at the Obsidian Discord if you plan to go this route. 

Yes, this was the thing I was wondering about. Thank you for the suggestion, I'll look for custom CSS that would work and if I find it I'll post it here.

**Comment by MemeAddict314** [comment]
Ok, I found a solution thanks to your suggestion about finding custom CSS. Based on [this](https://forum.obsidian.md/t/properties-view-css-the-fall-collection/66512) forum post you can use their snippet that hides a specific property type ([guide for snippets](https://help.obsidian.md/Extending+Obsidian/CSS+snippets)).
```
[data-property-key="propertyname"] {
    display:none;
}
```
I used this on "disabled rules" and it worked! Thank you for the help!

**Comment by pjkaufman** [comment]
I am glad that that worked for you.
