### ISSUE TITLE
FR: Add Ability to Enable/Disable Custom Replacement

### ISSUE THREAD

**Issue by XMB-7** [platers/obsidian-linter#1098]
![image](https://github.com/platers/obsidian-linter/assets/65625632/4887bb6c-6ac4-4dde-aa1a-4fd60fc9c0fc)

So a custom regex replacement can be inactive without getting removed.

**Comment by pjkaufman** [comment]
I have gone ahead and merged the changes for this. Please let us know if master or the next release is not working correctly with these changes.
