### ISSUE TITLE
Bug: Lint on save doesn't lint on file write on mobile

### ISSUE THREAD

**Issue by chmac** [platers/obsidian-linter#1099]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Lint on save doesn't work on app exit on mobile, yet the file is saved.

## How to Reproduce

1. Enable lint-on-save
2. Create a new note on mobile
3. Leave the app
4. Check the file contents on disk, note it has not been linted

## Expected Behavior

I assume that "lint on save" means that when my file gets written to disk, it gets linted. I don't know the details of the semantics of what obsidian calls a "save", so maybe I'm misunderstanding something.

## Device

- [ ] Desktop
- [x] Mobile

## Additional Context

I started out writing a feature request asking for a "lint on change" option that only applies to mobile. But as I was writing it, I realised that it seems like something isn't working correctly on mobile. In that my files are saved, I use the Working Copy app to track them via git, so I regularly see the contents of my files, and I know they were updated. But I guess the "save" workflow of obsidian wasn't triggered. Maybe this is really a feature request to make mobile work more like desktop by interpreting "lint on save" as "lint on change" when on Mobile, or something like that.

**Comment by pjkaufman** [comment]
Hey @chmac , lint on active filr change only applies when you change which file is the currently active file. There is currently no way to lint on the change to a file as that would cause an infinite loop with some of the Linter rules. However there is working being made towards this.

**Comment by chmac** [comment]
@pjkaufman Ah, I see. I just tested, and you are right, there is no linting when I leave the app even with "lint on change" enabled. I mistakenly thought that was the case.

I see your point about infinite loops! I thought there would maybe be a way to lint when the file is written to disk, but of course that also creates the infinite loop issue.

If this is something that's being worked on elsewhere, should I close this issue? No need to clutter the repo if this is not relevant.

Also, I forgot to add to the issue, thanks a lot to all the folks who make linter possible. It's really game changing in my obsidian experience. 🧡

**Comment by pjkaufman** [comment]
The issue that you originally thought that this feature was is https://github.com/platers/obsidian-linter/issues/183. So if you want to add a reaction to that FR, that would be great. I will close out this issue.

I am glad that you find the Linter userful!
