### ISSUE TITLE
Bug: preview mode lint of daily note funnnnnky results

### ISSUE THREAD

**Issue by ksdavidc** [platers/obsidian-linter#1101]
- [ x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Linting in source mode works. Linting in preview mode does weird things like cut off text, add dashes to end of frontmatter, 

Also, this only happens ON FIRST LINT, not subsequent lints....which is why I am always creating new entries, not reusing entries.

## How to Reproduce

see these videos
1. walkthrough in detail

https://github.com/platers/obsidian-linter/assets/62230004/ee6fdacd-b66e-4d42-a9b9-1aebb0bae03f

(note that in video I say I am not in preview, I mean I am now in preview)
(also, while removing the toc and frontmatter seemed to work, in fact it does not always do so....)

2. debug

https://github.com/platers/obsidian-linter/assets/62230004/d5270715-c134-4911-a8d4-01cf667d78a1

3. shows extra dashes

https://github.com/platers/obsidian-linter/assets/62230004/46b69463-4386-4d9b-85c8-8e1e601efa06

4. attached vault
[LintTest.zip](https://github.com/user-attachments/files/15744041/LintTest.zip)

I tried to create a sandbox, but wasn't quite able to create the right configuration, so I took my original vault and deleted data and most plugins to get this result.

## Expected Behavior

a properly linted file

## Screenshots

above

## Device

- [ x] Desktop
- [ ] Mobile

## Additional Context

debug info

SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.8
	Operating system: Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 23.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: AnuPpuccin v1.4.5
	Snippets enabled: 13
	Restricted mode: off
	Plugins installed: 18
	Plugins enabled: 18
		1: Dataview v0.5.66
		2: Automatic Table Of Contents v1.4.0
		3: BRAT v1.0.1
		4: Calendar v1.5.10
		5: Doubleshift v2.2.1
		6: File Explorer Note Count v1.2.2
		7: Garble Text v1.2.0
		8: floating toc v2.4.7
		9: File Tree Alternative v2.5.9
		10: Theme Toggler v1.0.1
		11: Table of Contents v0.2.0
		12: Thino v2.4.47
		13: Templater v2.3.3
		14: MySnippets v1.2.3
		15: Plugin Manager v0.1.5
		16: Plugin Update Tracker v1.5.2
		17: Settings Search v1.3.10
		18: Linter v1.24.0

**Comment by pjkaufman** [comment]
Hey @ksdavidc , have you tried this in the BRAT/beta release (v1.25.0-rc-1)?

**Comment by ksdavidc** [comment]
Brilliant! Works like a charm.

**Comment by pjkaufman** [comment]
I am glad to hear that. I will go ahead and close this then.

**Comment by pjkaufman** [comment]
This was already fixed by #1094
