### ISSUE TITLE
Question: Copy `复生吸芽 mAP\@.5` but the pasted text is `复生吸芽 mAP\@`. how to fix it?

### ISSUE THREAD

**Issue by Guan9Wu** [platers/obsidian-linter#1107]
Copy `复生吸芽 mAP\@.5` but the pasted text is `复生吸芽 mAP\@`, missing `.5`. I have tested it when disabled Linter plugin, there is 
no problem. So I am sure this problem is with Linter plugin. Which option can be modified to solve this problem? Thanks for your attention.

**Comment by pjkaufman** [comment]
Hey @Guan9Wu . What paste rules do you have enabled? I am assuming the issue with [Remove Leftover Footnotes from Quote on Paste](https://platers.github.io/obsidian-linter/settings/paste-rules/#remove-leftover-footnotes-from-quote-on-paste). The examples on that rule seem to be closest to what you have displayed above.

**Comment by Guan9Wu** [comment]
> Hey @Guan9Wu . What paste rules do you have enabled? I am assuming the issue with [Remove Leftover Footnotes from Quote on Paste](https://platers.github.io/obsidian-linter/settings/paste-rules/#remove-leftover-footnotes-from-quote-on-paste). The examples on that rule seem to be closest to what you have displayed above.

This advice solved my problem. Thanks for your answer.

**Comment by pjkaufman** [comment]
I am glad it worked for you.
