### ISSUE TITLE
Question: Custom Command: converting multiple single lines to bullet points

### ISSUE THREAD

**Issue by pinetreemoonlight** [platers/obsidian-linter#1114]
Is it possible to have a custom command that converts for example:

hello

test

blabla

to 

- hello
- test
- blalbla

? Would appreciate some help as I don't really know how to set that up.

**Comment by pjkaufman** [comment]
Hey @pinetreemoonlight . This would require that you have a functioning understanding of JavaScript. Is that the case?
If so, then it is just a matter of looking at how QuickAdd allows you to add custom JS logic as shown in [the macros section of the documentation](https://quickadd.obsidian.guide/docs/Choices/MacroChoice). I am not 100% sure of the requirements you have for the JS or how familiar you are with Obsidian's APIs so at this time that is about all I can tell you.

Hopefully this gives you enough information to at least move forward a little.

**Comment by pjkaufman** [comment]
I am going to close this issue as I have not heard back. I am more than happy to help where possible if this is still something that you are having trouble with, though I will not be able to write it for you. About all I have time for is to help nudge you in the right direction if you get stuck.
