### ISSUE TITLE
Bug: Tag Regex Matches Punctuation Like `:` Which Causes Other Problems

### ISSUE THREAD

**Issue by eteffy** [platers/obsidian-linter#1116]
## Is Your Feature Request Related to a Problem? Please Describe.

I have move tags to YAML turned on and when I lint the current file it moves on of the tags into the YAML but it's showing as an error (in the Obsidian Properties in Live Preview) because it is also copying the colon after the tag in my text.
![image](https://github.com/platers/obsidian-linter/assets/114887599/cfed7810-1bef-4d21-ae17-104727c7450c)

![image](https://github.com/platers/obsidian-linter/assets/114887599/58e11b19-d2cf-4b3f-b3bc-bd382d4a2958)

## Describe the Solution You'd Like

Ideally, I would like an option similar to the remove trailing punctuation in heading, but for tags.

**Example:**
Before:
``` markdown
---
tags: #tag1:
---
```
After:
``` markdown
---
tags: #tag1
---
```

## Describe Alternatives You've Considered

The only alternative I've really considered is trying to remember to add a space after tags when using punctuation after them.

**Comment by pjkaufman** [comment]
Hey @eteffy , this sounds more like a bug in the tag regex if it is allowing a colon in the tag, but when you type it out, it does not alloe the colon to be a part of the tag.

**Comment by pjkaufman** [comment]
I believe I have a fix for this. I am creating a PR now.

**Comment by pjkaufman** [comment]
This has been merged into master and should go out with the next release. Please let us know if either has an issue.

Thanks for reporting this!
