### ISSUE TITLE
Bug: Remove space header when option `RemoveSpaceAroundCharacters` is enabled and Katakata is beginning of the line

### ISSUE THREAD

**Issue by NatsukiFukazawa** [platers/obsidian-linter#1127]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Title.

## How to Reproduce

1. Enable `RemoveSpaceAroundCharacters` and `includeCJKSymbolsAndPunctuation` in the settings
2. Create a note with the following content:

```
## テスト
```

3. Lint the note, then the space between `##` and `テスト` will be removed.

## Expected Behavior

Don't remove the space between `##` and `テスト`.

## Device

- [ ] Desktop
- [x] Mobile

**Comment by pjkaufman** [comment]
The fix for this has been merged and should go out in the next release. If this problem persists on master or in the next release, please let us know,
