### ISSUE TITLE
Bug: Some strings are only processed on alternate pastes

### ISSUE THREAD

**Issue by plufz** [platers/obsidian-linter#1145]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

I noticed that some URL:s that I pasted wasn't processed by the paste handler in the linter (e.g. remove double list indicator). I haven't quite figured out the pattern, but I would guess it has something to do with the plugin not escaping regex characters properly.

## How to Reproduce

1. Disable all plugins but Linter
2. Make sure "Prevent Double List Item Indicator on Paste" is active
3. Create a list item "- " (without the quotes)
4. Directly after the list item paste "- //a.aa/" (without the quotes)
5. Create a new line with another list item "- " (without the quotes)
6. Directly after the list item paste "- //a.aa/" (without the quotes)
7. One of the lines should now be stripped from the extra list item and the other not.

## Expected Behavior

The pastes should be processed every time, not every other time.

## Screenshots
<img width="163" alt="Screenshot 2024-08-22 at 14 41 03" src="https://github.com/user-attachments/assets/906e58ea-4b74-406d-929c-b6550a64d01a">

## Device

- [x] Desktop

**Comment by pjkaufman** [comment]
Thanks for reporting this @plufz . It is a little bit time specific from what I am seeing. But I will see if this is something that I can add a fix for. I think what is happening is the current line is not being properly transmitted to the plugin because of how fast things are happening, but I will know more once I did more into the scenario.

**Comment by pjkaufman** [comment]
As a dev note: here is the log I am getting when the paste attempt fails:  `logger.ts:79 [Obsidian Linter] aborted paste lint as the clipboard content is a link and doing so will avoid conflicts with other plugins that modify pasting.`. This implies that sometimes the pasted text is being considered to be a link and other times it is not. I need to figure out why.

**Comment by pjkaufman** [comment]
I believe I have a fix for the issue mentioned here. It seems that the Linter would ignore a paste if a link was found anywhere in the text. In this case, it was partially matching. I did not get down to the exact reason why it was only matching some of the time. But I did find that I only need to skip the URL if it is the only text present after trimming the text to paste. As such, I have updated the paste regex which should fix this issue.

**Comment by pjkaufman** [comment]
I have a potential fix for this, but I am leaving it as a draft until I get feedback from other devs in the discord for Obsidian. I  have not been able to determine why pasting the same value a second time is causing different results for the regex. I am hoping that a dev in the Obsidian discord will have an idea why this might be happening.

**Comment by pjkaufman** [comment]
I have not really gotten an explanation around what is going on so, I am going to see about merging the change and creating a release. I am hoping that it will all go nicely and I can get feedback around this soon.

**Comment by pjkaufman** [comment]
I have merged the change. Please let us know if this is not fixed on master or in the next release.
