### ISSUE TITLE
Bug: Heading blank lines not only adds a blank line before/after headings, it also removes consecutive blank lines

### ISSUE THREAD

**Issue by bluebirch** [platers/obsidian-linter#1146]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Heading blank lines not only adds a blank line before/after headings, it also removes consecutive blank lines, effectively ensuring there is one and only one blank line before and after headings.

## How to Reproduce

Before:

```markdown
text


# heading 1


text


## heading 2


text
```

After linting:

```markdown
text

# heading 1

text

## heading 2

text
```

## Expected Behavior

Expected output is same as input.

## Screenshots

![image](https://github.com/user-attachments/assets/35b49b35-4407-419d-978d-0d0e2506c556)

![image](https://github.com/user-attachments/assets/9373a75f-0c9e-4472-a8e9-c637149c1f61)

## Device

- [x] Desktop
- [ ] Mobile (not tested)

**Comment by bluebirch** [comment]
There is no example there showcasing consecutive blank lines. And the description only mentions inserting blank lines. And that  "all headings have a blank line both before and after", which perhaps chould be clarified that "all headings have **exactly one** blank line both before and after" (or, as I expected, "all headings have **at least one** blank line both before and after".

**Comment by bluebirch** [comment]
> The example here does show consecutive blank lines getting cut down to exactly one:

You're right. Sorry. Missed that. Yes, please clarify, if nothing else to avoid bug reports from people like me. 😉

**Comment by pjkaufman** [comment]
Sounds good. I will do that and then close this issue out when I make that doc change.

**Comment by pjkaufman** [comment]
The wording update should be ready to go live in the next release and on master.
