### ISSUE TITLE
Bug: First letter in Title Case not Uppercase when preceded with numbers or special characters

### ISSUE THREAD

**Issue by ekarious** [platers/obsidian-linter#1148]
- [x] I have verified that I am on the latest version of the Linter
Linter version 1.25.0

## Describe the Bug

When having a title like this 
```
135_  A letter arrived
```
It gets formatted as 
```
135 - a Letter Arrived
```

If the letter is in the lowercase words, It will be lowercased even if first letter in the header.

## How to Reproduce

1. Make a title similar to mine as the first word is not a letter 
2. Set Capitalize Headings to Title Case
3. Ignore Cased Words to false
4. Lowercase Words should have `a` inside for this example.
5. Format the file
6. See error in the first heading

## Resources
[data.json](https://mega.nz/file/EmoEgTaa#VXhUw8w18oBLbm6AQX9ejvzVvzr8pdm9JpKBcKtHxFY)
[logs.txt](https://mega.nz/file/R3RSmJiA#iR95JHnqZ6sf9b_XEUzTP7dqAqaaRcXGoBZ85y3YXA4)

## Expected Behavior

As the linter run, the header
```
135_  A letter arrived
```
should have been
```
135 - A letter arrived
```

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

As additional context, take note that I am currently using a regex to modify the header to change `_ ` -> ` - ` as:
`^# (\d+)_ (.+)\n` `gm` `# $1 - $2\n`
As I am not an expert in regexes, maybe this can contribute to the bug.

**Comment by ekarious** [comment]
I know another issue was filed and fixed for this in 2022.
https://github.com/platers/obsidian-linter/issues/171

**Comment by pjkaufman** [comment]
Hey @ekarious , thanks for reporting this. This seems like the regex for finding valid words is likely hitting an issue where it is matching all digits. I do need to verify this though.

**Comment by pjkaufman** [comment]
Ok. I took a look and it looks like the issue is because it is not properly filtering out some single letter situations. It looks like if `-` or `'` are by themselves with whitespace around them in the header before any letter, it gets considered to be the first "letter". This should not be too hard to fix (fingers crossed).

Thanks for bring this to our attention.

**Comment by pjkaufman** [comment]
I believe I have a fixed that is now merged into master and should go out with the next release. Please let us know if there is an issue with either.

**Comment by ekarious** [comment]
Thank you a lot ! :)
