### ISSUE TITLE
FR: Start Header Increment at Heading Level 2 - Add option to ignore very first heading.

### ISSUE THREAD

**Issue by pipe-organ** [platers/obsidian-linter#1153]
**Start Header Increment at Heading Level 2** option works perfectly but it would be awesome if there is an option to ignore the very first heading for those who use **[File name Heading Sync](https://github.com/dvcrn/obsidian-filename-heading-sync)** plugin.

My document always starts with 

```
# title (which matches the file name 😅 one less thing to think about...)
```

But currently **Start Header Increment at Heading Level 2** changes this very first heading to H2. So it would be great if there was an option to ignore this very first one. 

Thanks again for the wonderful plugin!!

**Comment by pipe-organ** [comment]
wow thank you so much for not only looking at my request but also providing the perfect solution. Thanks again for taking the time to write the detailed answer @pjkaufman !!

**Comment by pjkaufman** [comment]
I am glad that that satisfies your use case. Have a blessed day!
