### ISSUE TITLE
FR: Zipped release for manual install

### ISSUE THREAD

**Issue by 1ku1** [platers/obsidian-linter#1163]
## Is Your Feature Request Related to a Problem? Please Describe.

In order to install the plugin manually, you have to download the three files individually, then create a folder and rename it with the plugin id and put these files in it.

## Describe the Solution You'd Like

I know these files are needed for automatic installation to work, but it would be much easier for the user to be able to **download a zipped file also** from the releases tab in the following configuration:

```
plugin-id-{v}.zip
    plugin-id\
        main.js
        manifest.json
        styles.css
```

This way we can just extract the zip file in the plugin folder. Thank you.

**Comment by pjkaufman** [comment]
Hey @1ku1 , could you explain the reason for why you would install the plugin manually this way as opposed to automatic installation or BRAT installation?

Also, could you point to a plugin that currently does this? I want to make sure this will not cause problems with Obsidian.

**Comment by 1ku1** [comment]
>Hey @1ku1 , could you explain the reason for why you would install the plugin manually this way as opposed to automatic installation or BRAT installation?

Firewall policy.

>Also, could you point to a plugin that currently does this? I want to make sure this will not cause problems with Obsidian.

https://github.com/javalent/settings-search
https://github.com/AlexBieg/obsidian-better-command-palette

Thanks

**Comment by pjkaufman** [comment]
Thanks for those examples @1ku1 . I am looking at adding that workflow for the next release. I will see how well it works with a test run and hopefully then it can be in place for the next release.

**Comment by pjkaufman** [comment]
Test looks to have passed for me. The changes are now on master and should start running with the next release. Please let us know if this has some kind of issue.

**Comment by 1ku1** [comment]
Thanks
