### ISSUE TITLE
FR: Add button to refresh "Extra Auto-Correct Source Files"

### ISSUE THREAD

**Issue by jjspace** [platers/obsidian-linter#1167]
The documentation says:

> - The list of custom replacements is only loaded when the plugin first lints a file or when the file is added to the list of files that include custom misspellings
>     - This means that making a change to a file that is already in the list of custom misspelling files will not work unless the Linter is reloaded or the file is removed and re-added to the list of custom misspelling files

It would be really nice if there was a button in the settings that just refreshed this list on demand. It'd be even nicer if it automatically refreshed when you modify the input files but a refresh button would be fine so you don't have to fully reload the application

**Comment by pjkaufman** [comment]
This sounds fine to handle. I am not so sure about refreshing on change as that requires listening to change events. But something more akin to what Templater does where you have the refresh button to reload all the custom autocorrect files does make sense.

**Comment by pjkaufman** [comment]
I am working on getting this added. I believe I have something working, but I will need to test it out and verify that it works. Once that is done, I can go ahead and get this merged. Hopefully it will be in the next release.

**Comment by pjkaufman** [comment]
The change has been merged to master and should go out in the next release.
