### ISSUE TITLE
Question: How to configure rule exceptions?

### ISSUE THREAD

**Issue by jonas-schulze** [platers/obsidian-linter#1180]
I would like to disable `line-break-at-document-end` and `file-name-heading` for the templates directory. Currently, I fix my templates using a different text editor. It would be nice, if I could use Obsidian instead. How would you approach this issue?

**Comment by pjkaufman** [comment]
Hey @jonas-schulze , right now there is no way to disable a rule for a specific file unless you use the [frontmatter](https://platers.github.io/obsidian-linter/usage/disabling-rules/#yaml-frontmatter) logic to disable those specific rules.

However if you copy/use those templates for creating other files that will propagate those rules being disabled to all files that are instantiated off of them. I am not sure if this is what you want. If it is, then you can proceed with that.

You can disable linting specific files as well. Or you can do what I do which is [ignore the templates folder](https://platers.github.io/obsidian-linter/usage/disabling-rules/#ignoring-a-folder) for linting.

Does this answer your question?

**Comment by jonas-schulze** [comment]
Thanks for the swift response!

I would like to use sub-file templates. Therefore, using the frontmatter does not work, as that would be spliced mid-file into the new location.

Ignoring the templates folder works just fine for me. Should I mess up a template, that will be fixed once the linter runs on the file I spliced the template into. I will close this issue then.
