### ISSUE TITLE
Bug: When opening command palette: `Command failed to execute:  obsidian-linter:lint-all-files-in-folder`

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#1182]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

An error occurs when opening the command palette for the first time after opening the vault. As far as I can tell, other than the error msg, there is nothing happening – but I do hope that the linter does not try to run commands simply when I open the command palette?

## How to Reproduce

1. Open vault
2. Open Command palette
3. The error appears in the console:

```
Command failed to execute:  obsidian-linter:lint-all-files-in-folder
app.js:1 TypeError: Cannot read properties of null (reading 'parent')
    at Object.editorCheckCallback (plugin:obsidian-linter:307:3438)
    at e.mobileOnly.Il.isMobile.e.checkCallback (app.js:1:2068235)
    at app.js:1:2068860
    at Array.filter (<anonymous>)
    at e.listCommands (app.js:1:2068798)
    at e.getCommands (app.js:1:2660005)
    at t.getItems (app.js:1:2661047)
    at t.getSuggestions (app.js:1:1709952)
    at t.updateSuggestions (app.js:1:1709135)
    at t.onOpen (app.js:1:1708977)
```

## Expected Behavior

No error happening. 

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

I am on Obsidian 1.7.3 (Insider release)

**Comment by pjkaufman** [comment]
Hey @chrisgrieser , are you using the latest BRAT release? I updated the minimum node version to 18, but recently saw that maybe some versions of Obsidian still expect 16.x.

**Comment by pjkaufman** [comment]
If it is having issues, I can see about fixing that, but the Linter is not running commands onload.

**Comment by pjkaufman** [comment]
I just double checked some code. I probably need to not assume that the editor callback will be called for a file object. I need to check if that exists and if it does not return false.

The error seems to be happening on the validation check that tries to check if a command should show in the editor.

**Comment by chrisgrieser** [comment]
> Hey @chrisgrieser , are you using the latest BRAT release?

Nope, I am on the latest regular release of the linter

**Comment by pjkaufman** [comment]
Gotcha. So that rules out the node change. I am pretty sure it is the check on this line that needs extra guards: https://github.com/platers/obsidian-linter/blob/b29f66cb6737af5be59d3d1f585f9f9a6814672f/src/main.ts#L235

Is the file you are looking at a custom view or is there no file open? Those are my two best guesses as to what would cause this unless it is a new bug where the `ctx` is not getting file info populated.

**Comment by pjkaufman** [comment]
Interesting. I will have to double check that then. Thanks for the reproduction information!

**Comment by pjkaufman** [comment]
I am not able to reproduce this issue, but I will add some logic to be more defensive when checking that logic to avoid an error.

**Comment by pjkaufman** [comment]
Here is a potential fix for this issue, but it does include the BRAT/beta features: 
[main.zip](https://github.com/user-attachments/files/17270983/main.zip)

**Comment by pjkaufman** [comment]
Hey @chrisgrieser , is this issue still happening in the latest release? I believe that this should be fixed and plan to close this unless I am told that there is still an issue around this.

**Comment by chrisgrieser** [comment]
yup, can confirm, the bug is fixed with the latest release!

**Comment by pjkaufman** [comment]
I am glad to hear that!
