### ISSUE TITLE
Bug: Setting Panel is missing in the lastest v1.27.0

### ISSUE THREAD

**Issue by PlayerMiller109** [platers/obsidian-linter#1194]
- [x] I have verified that I am on the latest version of the Linter

## How to Reproduce

See the GIF took in Win11 Obsidian v1.6.7 Sandbox Vault. I have tested downloading from Community Plugin Market and from the release.

<img width="500" src="https://github.com/user-attachments/assets/21a11ab2-55be-4779-9732-eb23dbeb917e">

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Hey @PlayerMiller109 . I currently do not see this issue on my devices. Could you check you console `ctrl+shift+I` and see if any errors are logged there? I am not seeing this issue on mobile or on my Linux computer.

**Comment by PlayerMiller109** [comment]
@pjkaufman here the screenshot:

<img width="800" src="https://github.com/user-attachments/assets/51ff8a46-4a02-41a5-84ac-d7eefc3d0d38">

and the System Info:

```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 11 Home China 10.0.22631
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Linter v1.27.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

```

**Comment by PlayerMiller109** [comment]
<img width="400" src="https://github.com/user-attachments/assets/db41a4fe-bb35-44fd-980d-2054bc3d1dbb">

Ah, I clicked the error message. It seems that if you have `data.json` when you enable it, it works fine. If not, the creation process for `data.json` can't be initiated, which causes an error. Can you take a look at it?

**Comment by pjkaufman** [comment]
Ah. So this sounds like a clean install issue. Let me see about issuing a change for this in a patch. It looks like I need to create the default settings before checking this. I will check when I get a chance.

**Comment by pjkaufman** [comment]
Hey @PlayerMiller109 , the change to fix this should be on master and released now. Please let us know if the issue continues.
