### ISSUE TITLE
Bug: Remove Multiple Spaces removes indentation from nested bullet points INSIDE a nested callout

### ISSUE THREAD

**Issue by rachelkd** [platers/obsidian-linter#1203]
- [X] I have verified that I am on the latest version of the Linter

## How to Reproduce

``` markdown
> [!goal]+ Two goals of object-oriented design
>
> > [!def]- Cohesion
> > - How strongly related the parts are inside a class
> > - About a class
> > - A class is *cohesive* if the data and behaviour of these objects makes sense
> > - **High cohesion**:
> >     - A class does one job, and does it well
> > - **Low cohesion**:
> >     - Class has parts that do not relate to each other
> > - e.g., `Customer` class might have `getName`, `getAddress`, but also `sendEmail` that sends an email to the customer → Weird; not a major responsibility of the customer → ==not cohesive
```

## Expected Behavior

`> >     - A class does one job, and does it well` and `> >     - Class has parts that do not relate to each other` are expected to keep their spaces since it is a nested list inside a nested callout, but the remove multiple spaces setting removes the spaces between `>` and `-`.

## Device

- [X] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
This is reproducible. It is some kind of issue with the regex used, but I am not sure what the problem is exactly since it seems to not match if the list item is not in a nested callout/blockquote.

**Comment by pjkaufman** [comment]
It may be better to just swap from regex to manually iterating over the file's content's to find the necessary locations to replace. Or I can just ignore lists and run a replacement on list item text separate from the linting of the other content. But I guess I could do this with regex as well. Let me take a stab at this and see how it goes.

**Comment by pjkaufman** [comment]
I believe I have a fix. I will create a PR and see if it passes the unit tests.

**Comment by pjkaufman** [comment]
The fix for this should be on master and go out with the next release. Please let us know if either is not the case.

Thanks for reporting the issue!
