### ISSUE TITLE
Bug: the Linter incorrectly ignores all paths that begin with ignored folder name

### ISSUE THREAD

**Issue by greetclammy** [platers/obsidian-linter#1208]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug
When adding a folder to "folders to ignore" (e.g. "test"), the Linter incorrectly ignores files and folders that begin with that name, rather than matching the exact folder.

## How to Reproduce

1. Add "test" to "folders to ignore" in general settings.
2. Create files with following structure:
```
/test/file1.md         // Should be ignored
/testing/file2.md      // Currently ignored, but should NOT be
/test-dir/file3.md     // Currently ignored, but should NOT be
/src/test/file4.md     // Currently ignored, but should NOT be
```

[data.json](https://github.com/user-attachments/files/17533204/data.json)

## Expected Behavior
The Linter should only ignore files and folders inside the exact "test" folder name.

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context
It appears the Linter is doing a prefix string match instead of exact folder name matching.

**Comment by pjkaufman** [comment]
Hey @greetclammy , that is a correct understanding of how the Linter currently works. I think I can add `/` to the end of the folder prefix check to try to make it handle the exact folder check. I am not 100% sure that it will work on all OS's, but I can check and see how `normalizePath` works and if it always adds `/` or `\` I can just use that at the end of the folder path to ignore. It should prevent all subfolders from getting included and fix the scenario described here.

**Comment by pjkaufman** [comment]
Looks like I have a fix for the issue in question. It should limit it to files that are in a folder that is ignored or one of the ignored folders' subfolders. I will see about pushing up a fix. Though I do want to see if I can first add an integration test for this exact scenario to make sure it is handled in release checks that I do manually. Granted it is run on the same OS, so it is possible that it would use a different value, but I think that is unlikely.

**Comment by pjkaufman** [comment]
The changes for this should be merged and go out in the next release. Please let us know if this fix does not work on master or in the next release.
