### ISSUE TITLE
Bug: dedupe tags not working

### ISSUE THREAD

**Issue by bloominburges** [platers/obsidian-linter#1218]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

I have "Dedupe YAML tags section" enabled -- yet it does not remove dupes. Linter is actually CREATING dupes whenever i move notes (i have setting enabled to linter on both file saver, and "focused file change". I have tags in the body, and so it's adding those to the YAML frontmatter EVERY Time i switch out of the note.

In case it matters, i have "YAML tags section style for "single-line space delimited". 

## How to Reproduce

1. few tags in note body: #test1 #test2
2. Click on anolther note (w/ setting enabled for linter on file focus chg)
3. click back to the other note you had in focus -- observe body tags now in the frontmatter (as intended
4. change focus to another note
5. back to original note: notice you now have 2x the amount of tags in the frontmatter, 2 sets of duplicates

## Expected Behavior
Only "test1" and "test2" should be in the frontmatter

## Device

desktop
![LINTERerror](https://github.com/user-attachments/assets/6dd0db12-3c96-4018-9fc4-5a1586b247de)

**Comment by pjkaufman** [comment]
This definitely sounds like a bug @bloominburges . Could you provide a sample file as well as your `data.json` so I can see about reproducing this issue?

**Comment by bloominburges** [comment]
I figured a workaround. I’m not sure why it happened but if i cleared ALL tags from the front matter, and let it repopulate them from stage zero, it won’t keep duplicating forever.

**Comment by pjkaufman** [comment]
I am glad that you found a work around. In order to fix this at a programatic level, I will need your `data.json` as well as a sample file which has the issue.

**Comment by pjkaufman** [comment]
Hey @bloominburges . I have not been able to reproduce this and I do not see a `data.json` that has been provided. I will close this to cleanup the open issues on the Linter if I have not heard back by January 5th.

**Comment by bloominburges** [comment]
understood. 

I haven't run into this issue again since a few weeks ago when i posted this. 

Not sure what caused it. If it happens again i'll reopen this or create a new bug note.

**Comment by bloominburges** [comment]
missclick reopen
