### ISSUE TITLE
Bug: log spam when locale not found

### ISSUE THREAD

**Issue by baodrate** [platers/obsidian-linter#1220]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

When obsidian is set to a language for which obsidian-linter does not have a translation, the console log is overwhelmed with warning-level log messages.

## How to Reproduce

- enable obsidian-linter plugin
- go to Obsidian Settings > General > Language, set to "Tiếng Việt" (Vietnamese)
- restart obsidian
- console logs are filled with:

```stacktrace
helpers.ts:99 [Obsidian Linter] locale not found for 'vi'
```

## Expected Behavior

A single log message is sufficient. See behavior of [`obsidian-front-matter-title-plugin`](https://github.com/snezhig/obsidian-front-matter-title):

<img width="901" alt="image" src="https://github.com/user-attachments/assets/4e9ee6d2-f207-4b65-851f-ab4629833abc">

## Screenshots

<img width="727" alt="image" src="https://github.com/user-attachments/assets/d6efce4c-630d-404f-8871-789b80571ed5">

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

Suggestion: rather than having the log message in every call to `getTextInLanguage`:

https://github.com/platers/obsidian-linter/blob/7c408f01bb9db25efc0c8f4aa3e3e1118e5cb1a8/src/lang/helpers.ts#L88-L100

move it to the top level of the file (where `locale` is initialized)

```diff
diff --git a/src/lang/helpers.ts b/src/lang/helpers.ts
index 28fa4fb..fe73dd7 100644
--- a/src/lang/helpers.ts
+++ b/src/lang/helpers.ts
@@ -88,6 +88,9 @@ export type LanguageStringKey = NestedKeyOf<LanguageStrings>
 
 let lang = 'en';
 let locale = localeMap[lang];
+if (!locale) {
+  logWarn(`locale not found for '${lang}'`);
+}
 
 export function setLanguage(newLang: string) {
   lang = newLang;
@@ -95,10 +98,6 @@ export function setLanguage(newLang: string) {
 }
 
 export function getTextInLanguage(str: LanguageStringKey): string {
-  if (!locale) {
-    logWarn(`locale not found for '${lang}'`);
-  }
-
   const text: unknown = (locale && getString<LanguageStrings>(locale, str)) || getString<LanguageStrings>(en, str);
 
   return text as string;
```

**Comment by pjkaufman** [comment]
I think setting it in set language would be better just in case the user updates the language. But you are right, it should not be in get language text.

**Comment by pjkaufman** [comment]
I believe I have a fix. It should get merged shortly.

**Comment by pjkaufman** [comment]
Thanks for letting us know about this issue.

It should now be fixed on master and go out with the next release. Please let us know if this continues to persist on master or in the next release.
