### ISSUE TITLE
Bug: Obsidian failed to load plugin obsidian-linter

### ISSUE THREAD

**Issue by macrospecter** [platers/obsidian-linter#1241]
For the past couple of weeks, Obsidian has not been loading the plugin properly upon startup. I get an error flag as I open with the content of the post subject line: Obsidian failed to load plugin obsidian-linter. Linter still shows as enabled among my plugins in Settings, but the Options panel is gone. I can get the Options panel to appear by disabling and then re-enabling Linter. Still, my hotkeys don't work even after that re-enabling. Any ideas how to fix this?

I have uninstalled and reinstalled Linter, restarted Obsidian, and restarted my computer—with no luck. I'm on MacOs Sequoia.

**Comment by pjkaufman** [comment]
Hey @macrospecter , I am sorry to hear that you are having this problem. What version of Obsidian and the Linter are you using?

Also can you open the developer console when it loads and copy the relevant error so I can see what it is complaining about? I think the hotkey for opening the developer tools is cmd+shift+I on Mac.

**Comment by macrospecter** [comment]
Thanks for the reply, Peter. Oddly, the problem cleared up soon after I posted! Go figure. (In case someone else has this problem and it becomes relevant, I'm on Obsidian 1.7.7 and 1.27.1 Linter.)

**Comment by pjkaufman** [comment]
Gotcha. I will go ahead and close this. If the issue pops back up again, we can reopen this.
