### ISSUE TITLE
Bug: If any 'Paste' rules are enabled, pasting in page preview edit mode pastes to active note instead

### ISSUE THREAD

**Issue by greetclammy** [platers/obsidian-linter#1242]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

If any 'Paste' Linter rules are enabled, pasting in page preview edit mode pastes in active note instead.

## How to Reproduce

1. Enable any 'Paste' rule
2. Open a note
3. Bring up a [page preview](https://help.obsidian.md/Plugins/Page+preview) for another note from anywhere (link to another note in current note, in file explorer, etc.)
4. Click within page preview to enter edit mode
5. Attempt to paste into the page preview  

**Linter logs**
```
Running linter
rules before regular rules: 0.10000000894069672 ms
Running Custom Regex
custom regex rules: 0.20000000298023224 ms
rules after regular rules: 0.7999999970197678 ms
rules running: 1.2999999970197678 ms
```

[data.json](https://github.com/user-attachments/files/18196236/data.json)

## Expected Behavior

Pasting in page preview pastes in note that is open in that preview (in edit mode), not in current note.

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Hey @greetclammy , I want to say this has been fixed, but has not yet been released.

Is this the same issue as #1219 ?

**Comment by greetclammy** [comment]
Correct. Glad that's already taken care of! 🙌
