### ISSUE TITLE
Bug: Excluded folders are still linted

### ISSUE THREAD

**Issue by MMoMM-org** [platers/obsidian-linter#1251]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

- I have enabled linting on focus switch
- I have excluded \X\ from linting
- notes which are in \X\someplace are still linted

## Expected Behavior

I would expect that all notes below X are not linted, not only notes in X

## Additional Context

If this is working as designed please add the option to incl. subfolders from exclusion, either per folder or in generell.

**Comment by pjkaufman** [comment]
Hey @MMoMM-org . Subfokders should be excluded from my understanding. Could you provide your `data.json`?

**Comment by MMoMM-org** [comment]
I guess it was a quirck. It works now.
