### ISSUE TITLE
Some blank lines in examples not showing up in docs

### ISSUE THREAD

**Issue by platers** [platers/obsidian-linter#126]
See https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#line-break-at-document-end

**Comment by pjkaufman** [comment]
@platers , I am pretty sure this is not actually an issue. If you look at those codeblocks, the last new line is not as pronounced. However if you were to use the copy option next to the code block you get the new line at the end and you can see the scrollbar which indicates there is more than 1 line present. The last line will not get highlighted when you try to manually copy it.

Is there something I am missing or is what I said above not actually accurate?

**Comment by platers** [comment]
Ah I was confused by the visuals. Thanks for clearing this up.
