### ISSUE TITLE
FR: Exclude Heading Level from `header-increment`

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#138]
Some themes use specific header levels to do some trickery (e.g. h6 for right aligned headings, h6 for admonitions) and some plugins interact with h1 headings.

In all those cases, the `header-increment` usually causes some problems, meaning you would have to turn off the rule, even tough you would like to use `header-increment` otherwise.

A solution to this could be to add some option to `header-increment` to ignore h1 and/or h6.

**Comment by chrisgrieser** [comment]
Hmm, so I personally don't need this anymore, yes. So guess we can close this 👍

**Comment by pjkaufman** [comment]
Thanks for letting me know. I appreciate all of your feedback on the linter, @chrisgrieser !
