### ISSUE TITLE
Header Increment Issue

### ISSUE THREAD

**Issue by liangzh-404** [platers/obsidian-linter#142]
version: v0.13.4
![image](https://user-images.githubusercontent.com/31941670/142771422-2faef288-8288-4a55-88d4-65bd6870f939.png)

**Comment by platers** [comment]
Is this on mobile?

**Comment by liangzh-404** [comment]
> Is this on mobile?

no~it's on destop

**Comment by platers** [comment]
I see, the logic in the header increment rule has issues.

**Comment by pjkaufman** [comment]
Is this still an issue @liangzh-404 ? If so, could you include an example that causes the issue and your data.json to help debug the issue?

Thanks!

**Comment by platers** [comment]
> Is this still an issue @liangzh-404 ? If so, could you include an example that causes the issue and your data.json to help debug the issue?
> 
> Thanks!

I believe the issue is in the header increment rule. I didn't clearly define its behavior, and the logic isn't clear, leading to some bad behavior on some cases. It needs better documentation or a full rewrite.

**Comment by pjkaufman** [comment]
This is likely due to not checking that the value of the header repeat is greater than 0: https://github.com/platers/obsidian-linter/blob/master/src/rules.ts#L1524-L1533

**Comment by pjkaufman** [comment]
When you go from a larger heading to a smaller heading where the decrement value is larger than the current header, the new header level becomes negative. For example:
``` text
#### Heading 4
# Heading 1
```

**Comment by pjkaufman** [comment]
I will see about fixing this tomorrow.

**Comment by pjkaufman** [comment]
I believe the issue should be fixed now, but I am not sure it catches all scenarios. I am hopeful that the fix will catch most scenarios and we can iron out anymore edge cases as they arise.
