### ISSUE TITLE
FR: Have Date Modified and Date Created Check for Differences in Format

### ISSUE THREAD

**Issue by IllyaMoskvin** [platers/obsidian-linter#143]
Here are some example steps to recreate the issue:

1. Toggle "Date Created" and "Date Modified" to true
2. Set date format to `dddd, MMMM Do YYYY, h:mm:ss a` (lowercase am/pm)
3. Open a file and save it.
4. Note how the YAML frontmatter updates with e.g. the following:
    ```yaml
    created: Monday, November 22nd 2021, 9:31:22 pm
    updated: Monday, November 22nd 2021, 11:30:18 pm
    ```
5. Set date format to `dddd, MMMM Do YYYY, h:mm:ss A` (uppercase AM/PM)
6. Save your file again.
7. Note how the modified date has the new format, but the created date does not:
    ```yaml
    created: Monday, November 22nd 2021, 9:31:22 pm
    updated: Monday, November 22nd 2021, 11:41:43 PM
    ```

I'm guessing this is happening here:

https://github.com/platers/obsidian-linter/blob/4af6bdde42f7ec8d4e49e333f93b6964df0ec143/src/rules.ts#L645-L672

**Comment by platers** [comment]
I suppose there could be a option like `Force update created dates` that always replaces the created date with the files created time. The time may change if you run it on a different computer.

**Comment by pjkaufman** [comment]
There can be a check added for this to see if the lines differ in values when a date created or modified rule is enabled. This would allow for these changes to be caught. I am working on something similar, so I will incorporate this and probably update the information in the rule to warn about the possibility of bad data if used across multiple devices.

**Comment by pjkaufman** [comment]
I took some extra time to think about this and realized I need to make sure that I create something more robust than just updating the date created value and date modified values if they change. I would need to read in the current value if present and compare it to what the current expected value is based on format.

I will need to take some more time to look into what this would look like without automatically updating the updated at info no matter what.

**Comment by pjkaufman** [comment]
This should be taken care of on master. Please let me know if master or the next release does not fix this issue.
