### ISSUE TITLE
[format-tags-in-yaml] Accented letters in a tag's name seem to prevent the recognition of the tags that follows

### ISSUE THREAD

**Issue by Klemet** [platers/obsidian-linter#144]
For example,

`tags: #test1 #test2 #test3`

returns after linting with `format-tags-in-yaml` activated:

`tags: test1, test2, test3`

while the following:

`tags: #tést1 #test2 #test3`

returns:

`tags: tést1 #test2 #test3`

The same behaviour seems consistent: every time a tag contains an accented letter (like `tést1` above), it is properly treated; but all of the over tags on the same line are not considered.

Sadly, I have no idea as to where the problem might come from.

**Comment by platers** [comment]
fixed in #148

**Comment by Klemet** [comment]
Just downloaded v1.2.8, and I can confirm that everything is working perfectly. Thank you so much !
