### ISSUE TITLE
Tags in YAML are not formatted if the tag has emoji in it.

### ISSUE THREAD

**Issue by nihitkhandelwal-eng** [platers/obsidian-linter#152]
As of now, linter is the only way to autofill the tags without having to type the whole thing, but it is not working if the tag has emoji in it. 
It would be very helpful if it works with emojis as well.
Thank you!

**Comment by dariuszkowalski-com** [comment]
+1

**Comment by pjkaufman** [comment]
Do you mind elaborating on this idea? Is this something that would be in the list of tags to add to the yaml or is there some kind of issue if the frontmatter has an emoji in it?

**Comment by nihitkhandelwal-eng** [comment]
I tried doing it again & it works now. 
I have been using the plugin "Frontmatter Tag Suggest", so didn't notice earlier.
Thanks!

**Comment by pjkaufman** [comment]
Thanks for the update. I will close this issue then.
