### ISSUE TITLE
FR: Allow for Automatically Numbering Ordered Lists

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#153]
<img width="111" alt="Screenshot 2021-12-28 00 33 20" src="https://user-images.githubusercontent.com/73286100/147513648-99633cf8-c088-4969-8883-8b6ac9326a25.png">

When editing numbered lists, the numbering is often off. It would be great to autofix this. Afair, markdown linters have this, so probably this isn't something we would have to implement ourselves?

**Comment by harmtemolder** [comment]
Or maybe just use `1.` for all items (like so: https://github.com/google/styleguide/blob/gh-pages/docguide/style.md#use-lazy-numbering-for-long-lists=)?

**Comment by pjkaufman** [comment]
It has been a while since I took a look at this. Since it has been requested several times, I will go ahead and see about adding this functionality. I know I definitely would find ti useful, I just have to test for a couple of edge cases. Hopefully do this and a couple other changes will buy me some time to finish the UI changes.

**Comment by chrisgrieser** [comment]
Note that you might simply sherlock[ the feature from the Markdown prettifier plugin](https://github.com/cristianvasquez/obsidian-prettify#ordered-lists). Since the dev literally said they are no longer using it themselves, since they use the linter plugin, I doubt they won't object 😆 

<img width="835" alt="Pasted image 2022-09-16 23 24 03" src="https://user-images.githubusercontent.com/73286100/190773268-8d3e5e04-884b-400f-a884-f3db44c8c78e.png">

see also https://github.com/cristianvasquez/obsidian-prettify/issues/96

**Comment by pjkaufman** [comment]
The problem is I don't see where they were doing that. It may be a dependency they used which I would not easily be able to use if it were a prettifier.

**Comment by pjkaufman** [comment]
I think I have something. It is not necessarily going to be link emphasis and bold were as they are a little different of a cookie to crack. They act differently in how you would determine the consistent option, so I will leave that off unless it is expressly asked. However it will format it as either a lazy or ascending numeric number. It will also allow you to end the list item indicator with a period or parenthesis.

**Comment by pjkaufman** [comment]
This change should be included in the next release. If there is a desire to have the option consistent added to either of the options please open another issue indicating that that is the case. Please let us know if the changes on master or in the next release do not satisfy this feature request.
