### ISSUE TITLE
Move Footnotes to the Bottom and Re-Index Footnote are not working with 500+ footnotes

### ISSUE THREAD

**Issue by Liong1976** [platers/obsidian-linter#154]
I tried these two functions of the Linter plugin with 500+ footnotes and it didn't work.

**Comment by chrisgrieser** [comment]
Most likely related, I also noticed that the linter seems to break Obsidian when I use it in a bigger document. (In my case, it was only a dozen or so of footnotes). I am not entirely certain what causes the issue, though.

**Comment by Liong1976** [comment]
Thanks for your information, Christ. In my case, the Obsidian froze, and I needed to restart the Obsidian, so I didn't know which one was the cause (move footnotes to bottom or re-index footnote).

**Comment by Liong1976** [comment]
Now, I remember that I also tried Chris's templater code to move the footnotes to the bottom (with the same doc), and it worked. When I tried the Linter's re-indexing footnotes, the Obsidian froze again.

**Comment by platers** [comment]
Im having trouble reproducing, can you share a file that crashes?

**Comment by Liong1976** [comment]
I had deleted the file, but I just made a new one with 108 footnotes, and didn't work either. 
Here is the file. Thanks!
[Linter-Footnote Testing.md](https://github.com/platers/obsidian-linter/files/7858727/Linter-Footnote.Testing.md)
