### ISSUE TITLE
Remove # from YAML tags does not work

### ISSUE THREAD

**Issue by dariuszkowalski-com** [platers/obsidian-linter#156]
Remove # from YAML tags does not work.
I have checked:
![image](https://user-images.githubusercontent.com/37656900/148739015-94d192d0-4c63-4049-b055-73307042628f.png)

and for example, file with this:
![image](https://user-images.githubusercontent.com/37656900/148739239-55ab1c3c-a862-47e9-a149-b2a817edcc93.png)

and Ctrl+S do not remove \#  tags and do not format YAML at all

**Comment by platers** [comment]
Whoops, forgot to push the new release. Can you update the plugin and try again?
