### ISSUE TITLE
Replace tabs by spaces at frontmatter

### ISSUE THREAD

**Issue by dariuszkowalski-com** [platers/obsidian-linter#157]
LINTER do not work at the frontmatter section, when I use tabs instead of spaces for 
aliases:  and tabs: elements

The tabs should be replaced by spaces to make the frontmatter correct

**Comment by pjkaufman** [comment]
I seem to be able to reproduce this using the following file contents:
```yaml
---
tags:
	- test
	- test 2
---
```

**Comment by pjkaufman** [comment]
@dariuszkowalski-com I believe I have a fix that will allow the tabs to remain in the frontmatter without removing them, but it may cause tabs values to be removed if they are present in the frontmatter. I am working on getting this fix pushed up.

**Comment by pjkaufman** [comment]
I think I have it so it will not remove the tabs in the contents of the yaml frontmatter if it does not start at the beginning of the line. The PR should be up and merged shortly.
