### ISSUE TITLE
`insert-yaml-attributes` does not respect order of attributes when only some are missing

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#160]
Probably best explained with this example. I have the three keys `tags`, `aliases` and `similar` in my config of `insert-yaml-attributes`. The current note only has `tags` and `aliases`. Even though `similar` is at the bottom of the list in the config, it is inserted at the top.

https://user-images.githubusercontent.com/73286100/150324965-56319874-8e33-4e3d-97cc-23c31031747e.mov

**Comment by pjkaufman** [comment]
This should be able to be managed by the new sort rule. I am going to close this issue. You should be able to specify the order you want using that. Please let us know if the sort rule on master which should be in the next release is not a solution to this problem.
