### ISSUE TITLE
Convert leading spaces to tabs adds too many tabs

### ISSUE THREAD

**Issue by mtalexan** [platers/obsidian-linter#161]
With the tab count set to 4, the following text (`.` represents a space):
```
1..Some text
....- Some indented text
....- More indented text
```
Is converted to (`-   ` represents a tab):
```
1..Some text
-   -   - Some indented text
-   -   - More indented text
```
With tab stops set to 4, it's converting 4 leading spaces into 2 tabs.  All conversions seem to add one too many extra tabs.

**Comment by mtalexan** [comment]
Version 1.2.9.

**Comment by platers** [comment]
cant reproduce this with all rules on and tab size=4

**Comment by mtalexan** [comment]
Oops, forgot to close this when I realized I had duplicate linters turned on that were causing it. Aorry
