### ISSUE TITLE
Bulleted lists broken by incorrect bullet conversion

### ISSUE THREAD

**Issue by mtalexan** [platers/obsidian-linter#163]
In version 1.2.9.  
While there is no option to enable or disable converting bullets, there are a number of settings related to indenting of bullets and preventing accidentally jumping multiple levels in the bullets.  With both of these enabled in the settings, a nested bulleted list is being improperly converted.

A starting list like:
```markdown
- Item 1
- Item 2
    - Item A
    - Item B
- Item 3
    - Item C
    - Item D
```
Is converted to:
```markdown

* Item 1
* Item 2
    * Item A
    * Item B
* Item 3
    * Item C
    * Item D
```
Which is not valid Markdown syntax.  

The Markdown syntax allows for `* ` to be used instead of `- ` for bulleted lists, but only at the top level.  All nested levels of bullets must only use `- `.  
Additionally, the Obsidian markdown viewer does not seem to support the alternate syntax of `* ` at even the top level.

The result is that bulleted lists are always made unusable by the Linter.

**Comment by platers** [comment]
Im unable to reproduce this, I have all rules enabled. I don't think any rules will convert - to *

**Comment by mtalexan** [comment]
Oops, sorry this one was supposed to be filed on a different markdown linter plugin
