### ISSUE TITLE
Feature Request : Option to Insert YAML Front Matter Sections to the Top or the Bottom

### ISSUE THREAD

**Issue by StefanoRausch** [platers/obsidian-linter#167]
This request is somehow related to issue #160: [insert-yaml-attributes does not respect the order of attributes when only some are missing](https://github.com/platers/obsidian-linter/issues/160).

I have stored a YAML Front End [ YFE ] section on the settings page of the plugin. If an old file is missing this section I would like Linter to insert it at the bottom of the existing list -- currently, it is always put at the top, as the first item.

It would be great if Linter could have the following optional settings:

1. Store the YFE section at the top.
2. Store the YFE section at the bottom.
3. Store the YFE section according to the predefined order by adding only the missing ones.

To improve the last option, Linter should ( 1 ) check only the existence YFE section name and not the content as well to skip the addition ( 2 ) have an additional "force overwrite" option to add the section nevertheless.

Thank you for considering the enhancements I am suggesting.

**Comment by pjkaufman** [comment]
@StefanoRausch , I believe that this issue can be addressed using the [YAML Sort Keys](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#yaml-key-sort) rule. As such, I am going to close this issue. If for some reason this rule does not address this issue, please let us know.
