### ISSUE TITLE
FR: Format Tables (Prettify Tables?)

### ISSUE THREAD

**Issue by Sh4rK** [platers/obsidian-linter#168]
Hi!

I just found this plugin, and I like it so far!

However, I found an omission: MD tables are not prettified. What do you think, could this be added at some point?

(I haven't looked at the code yet, so I don't know how hard it would be, maybe I'll take a look later.)

**Comment by platers** [comment]
Rules for tables are welcome! I don't use tables myself but look forward to PRs. It should be straightforward to implement, follow the instructions in the readme.

**Comment by 0xlevel** [comment]
Advanced tables is doing a great job in my use cases. Perhaps it would be possible to hook it in?

**Comment by pjkaufman** [comment]
When we say tables are "prettified" what exactly is meant by this, @Sh4rK ? Does this mean that the table would be made to have the same width character-wise for each row or is there more to it?

As for integrating with another plugin, I am not entirely sure how that works in Obsidian, but if there were an example of how that is done, I would definitely consider it. Do you know of any plugins that already do this @0xlevel ?

**Comment by 0xlevel** [comment]
> As for integrating with another plugin, I am not entirely sure how that works in Obsidian, but if there were an example of how that is done, I would definitely consider it. Do you know of any plugins that already do this @0xlevel ?

Sorry, @pjkaufman, I wouldn’t know and from a quick glimpse at the plugins I use, I came up empty.

**Comment by Sh4rK** [comment]
> When we say tables are "prettified" what exactly is meant by this, @Sh4rK ? Does this mean that the table would be made to have the same width character-wise for each row or is there more to it?

Sorry, I didn't really use this since, so I don't remember exactly. I imagine it would align all table columns, to line them all up visually, like what Prettier does, though this might not be needed in Obsidian with the automatic rendering feature.

**Comment by pjkaufman** [comment]
I would not be opposed to having rules added for tables, but I am not sure what would be requested for this here.

**Comment by pjkaufman** [comment]
Looks like we could go ahead and add a feature for it. Here is an NPM package we could use: https://github.com/darkriszty/MarkdownTablePrettify-VSCodeExt#npm

It would make the tables be prettified and allow for the specification of table column padding. I am not sure how customizable this would be.

**Comment by pjkaufman** [comment]
The only thing is that it looks like it will support latin characters, but Chinese, Japanese, and other similar languages may have issues with the table formatting.

**Comment by ben-yip** [comment]
[Advanced Tables](https://github.com/tgrosinger/advanced-tables-obsidian) is one of the most popular community plugin in Obsidian. It has a “Pad cell width using spaces” feature. And yes, it does NOT support CJK characters, but better than nothing, right? I can live with that.

I suggest Linter provide a switch to left tables untouched for **Advanced Tables** users, otherwise those padded spaces are trimmed in tables on **lint** right now.

**Comment by pjkaufman** [comment]
> [Advanced Tables](https://github.com/tgrosinger/advanced-tables-obsidian) is one of the most popular community plugin in Obsidian. It has a “Pad cell width using spaces” feature. And yes, it does NOT support CJK characters, but better than nothing, right? I can live with that.
> 
> I suggest Linter provide a switch to left tables untouched for **Advanced Tables** users, otherwise those padded spaces are trimmed in tables on **lint** right now.

Do you mimd providing an example? I remember updating the table rule to ignore multiple spaces in tables.

**Comment by ben-yip** [comment]
> > [Advanced Tables](https://github.com/tgrosinger/advanced-tables-obsidian) is one of the most popular community plugin in Obsidian. It has a “Pad cell width using spaces” feature. And yes, it does NOT support CJK characters, but better than nothing, right? I can live with that.
> > I suggest Linter provide a switch to left tables untouched for **Advanced Tables** users, otherwise those padded spaces are trimmed in tables on **lint** right now.
> 
> Do you mimd providing an example? I remember updating the table rule to ignore multiple spaces in tables.


I made some tests and found out it was my mistake. GFM tables requires a blank line before, but Obsidian's Live Preview mode just render it into a table anyway regardless of this rule. 😂

Multiple spaces in tables are indeed ignored as you say.

**Comment by Sh4rK** [comment]
To be honest, I've lost interest in this (I don't use Obsidian that much).

Given that there's another plugin specifically for tables, should we close this issue?

**Comment by pjkaufman** [comment]
> To be honest, I've lost interest in this (I don't use Obsidian that much).
> 
> Given that there's another plugin specifically for tables, should we close this issue?

I would think that this is fine unless someone else really wants Obsidian Linter to prettify tables.

**Comment by 0xlevel** [comment]
> > To be honest, I've lost interest in this (I don't use Obsidian that much).
> > Given that there's another plugin specifically for tables, should we close this issue?
> 
> I would think that this is fine unless someone else really wants Obsidian Linter to prettify tables.

I did not think, integrating table magic would be wise, anyway… unless the linter could pass the job to another plugin, which seems to be unheard of. Some kind of exception (e.g.) for tables (like @ben-yip proposed) might be sensible, though. That said, I am happy with the current state. Cheers.

**Comment by pjkaufman** [comment]
> > > To be honest, I've lost interest in this (I don't use Obsidian that much).
> > > Given that there's another plugin specifically for tables, should we close this issue?
> > 
> > 
> > I would think that this is fine unless someone else really wants Obsidian Linter to prettify tables.
> 
> I did not think, integrating table magic would be wise, anyway… unless the linter could pass the job to another plugin, which seems to be unheard of. Some kind of exception (e.g.) for tables (like @ben-yip proposed) might be sensible, though. That said, I am happy with the current state. Cheers.

Using another plugin to handle tables could be done, but its implementation would be hard to test and relies on continued maintenance of the other plugin. Because of this, I am hesitant to do such a thing.

**Comment by pjkaufman** [comment]
Based on what has been stated on this issue, I am going to close this issue and if there is a need for this feature in the future we can revisit this;.
