### ISSUE TITLE
FR: Format YAML 'tags' Key 

### ISSUE THREAD

**Issue by alanalvarado** [platers/obsidian-linter#172]
sometimes we have

tags: tag1 tag2 tag3
Tags: tag1, tag2, tag3
tags: 
       - tag1
       - tag2
       - tag3

but would be good if they can be linted to rules, or proper yaml

tags: [tag1, tag2, tag3]

**Comment by pjkaufman** [comment]
@alanalvarado , am I understanding correctly that you are saying that you would prefer to allow for yaml lists to be formatted in the format `key: [item1, item2, ..., itemx]`?
I want to make sure I am understanding since from my understanding of yaml, the following is valid as well:
``` yaml
key:
- item1
- item2
...
- itemx
```

**Comment by pjkaufman** [comment]
I believe this should now be possible on master. I plan to release it later today. I believe I have worked out several of the blatant issues with it when inspecting how it affected my local notes. Please let us know if master or the next release does not allow for the desired formatting.
