### ISSUE TITLE
Move Footnotes to the bottom: inserts extra 2 blank lines every time you run it

### ISSUE THREAD

**Issue by laurastephsmith** [platers/obsidian-linter#174]
Move Footnotes to the bottom keeps adding an extra two blank line above the footnotes each time you run Linter.

Before:
```
A sentence about stuff.[^1]

[^1]: A reference about stuff.
```
  
After first run of Linter:
```
A sentence about stuff.[^1]



[^1]: A reference about stuff.
```

After second run of Linter:
```
A sentence about stuff.[^1]





[^1]: A reference about stuff.
```

After third run of Linter:

```
A sentence about stuff.[^1]







[^1]: A reference about stuff.
```

And so on. Thanks for your help!
Laura

**Comment by pjkaufman** [comment]
It seems this is fixed by turning on the removal of multiple blank lines, but should not bee too hard to determine what is going on with moving the footnote to the bottom of the file.

**Comment by pjkaufman** [comment]
I have a fix for this coming up.

**Comment by laurastephsmith** [comment]
Thanks ever so much, I'll give it a try! I've used the remove duplicate blank lines setting for now, but there was a reason why I didn't really want it on. Which I'm sure will come back to me... :)
