### ISSUE TITLE
[FR] Rename file with first line in the case of `Untitled` file

### ISSUE THREAD

**Issue by gavinmn** [platers/obsidian-linter#175]
I started building a plugin for this myself last night as a way to be able to more quickly create notes and not be flooded with "Untitled" "Untitled 1" "Untitled 2" but I began realizing that a lot of the code that would be needed here overlaps with Linter and it might be better off as a rule that exists in the Linter plugin? 

Curious as to your thoughts on whether a feature to rename files based on the first line of the file (barring things like code blocks and YAML) belongs in a linter plugin.

The code I wrote is here https://github.com/gavinmn/obsidian-rename-untitled/blob/master/main.ts if you want to take a look.

**Comment by platers** [comment]
Hmm, thats a nice feature. I dont think it fits linter well though, linter only deals with the files contents.

**Comment by gavinmn** [comment]
That's fair and why I wanted to ask before opening a PR. I'll continue developing it in my own plugin. Mind if I reuse some of Linters code for things like ignoring YAML when grabbing the first line with proper credit in the code and README?

**Comment by platers** [comment]
Go ahead!
