### ISSUE TITLE
FR: Convert Aliases to Multiline Array

### ISSUE THREAD

**Issue by mrwhaler** [platers/obsidian-linter#182]
The option so that you can do from this:
```
---
aliases: h1
---
```
This:
```
---
aliases: 
- h1
---
```

**Comment by pjkaufman** [comment]
I believe this should now be possible on master. I plan to release it later today. I believe I have worked out several of the blatant issues with it when inspecting how it affected my local notes. Please let us know if master or the next release does not allow for the desired formatting.
