### ISSUE TITLE
FR: Add Option for Lint on File Close or Changed

### ISSUE THREAD

**Issue by QuantumRoseinAmethystVase** [platers/obsidian-linter#188]
I usually will forget to press CTRL + S to run the modification time, especially when I jump between multiple files. I can't press CTRL + S before each jump. When I modified the notes and jumped to other notes or when I closed the panel / obsidain, it was so wonderful if it was able to run a plugin!

**Comment by platers** [comment]
agree, would be a nice option to have in addition to lint on save

**Comment by pjkaufman** [comment]
This is definitely something I would like to add, but I am just having some trouble on how to properly lint a file before changing which file is displayed. Would it make sense to lint the previous file even if the next one is now being displayed?

**Comment by pjkaufman** [comment]
@DEabcdp , would it be acceptable to lint the previous file when a new one is selected? This would look slightly different than how it looks on linting the current file when it comes to the display information if active. This means when you go from say `file1.md` to `file2.md` it will then lint `file1.md`. I am not certain that it would lint on closing the vault or the current file. But I could probably add this separately.

**Comment by DEabcdp** [comment]
> @DEabcdp , would it be acceptable to lint the previous file when a new one is selected? This would look slightly different than how it looks on linting the current file when it comes to the display information if active. This means when you go from say `file1.md` to `file2.md` it will then lint `file1.md`. I am not certain that it would lint on closing the vault or the current file. But I could probably add this separately.

Of course you can! That's a huge improvement! It's just that if I close Obsidian after editing file2.md and open Obsidian again (by default the file2.md that was closed last time is opened). If I open file3.md directly without editing file2.md, will the information I edited on file2.md when I closed Obsidian last time be appended to file2.md?

**Comment by pjkaufman** [comment]
I am not sure what you mean by information appended to `file2.md` in your example.  The linter would still try to lint `file2.md` on active leaf change (this should be a file change). So whatever information is already present in `file2.md` would get linted. I need to about verifying that that works that way, but if it is fine linting the file on file change, I think that can be done. I just don't see how I would be able to do it before the file swaps which is being displayed.

**Comment by Gewerd-Strauss** [comment]
I think the question he is asking is whether or not the linter retains changes across program reboots. The steps he's asking about:

1. Edit `file2`
2. immediately afterwards close it, before linter executes
3. reopen obsidian, see `file2` by default as it was the last-active
4. do not edit `file2`
5. open `file3`
6. do stuff

Will file2's changes _from before the program closed_ now be linted?

**Comment by pjkaufman** [comment]
> @pjkaufman I think the question he is asking is whether or not the linter retains changes across program reboots. The steps he's asking about:
> 
> 1. Edit `file2`
> 2. immediately afterwards close it, before linter executes
> 3. reopen obsidian, see `file2` by default as it was the last-active
> 4. do not edit `file2`
> 5. open `file3`
> 6. do stuff
> 
> Will file2's changes _from before the program closed_ now be linted?

Well, this would depend on implementation. But most likely it would lint file2 so long as it was listed as the last opened when the user went to open file3 with file2 open.

**Comment by ryanmsnyder** [comment]
I would be interested in this as well. Something similar to how VS Code works - when you change focus from file1 to file2, file1 is automatically saved (and formatted if a formatter is configured such as prettier for JavaScript or Black for Python).

**Comment by Calorion** [comment]
> This is definitely something I would like to add, but I am just having some trouble on how to properly lint a file before changing which file is displayed. Would it make sense to lint the previous file even if the next one is now being displayed?

Definitely. Really just any way for it to auto-fire once in a while would be fine. Maybe on autosave but only if it hasn't fired in X time (30 seconds, 1 minute, 5 minutes, whatever)?

**Comment by pjkaufman** [comment]
I don't like the autosave option as that can cause an infinite loop if done incorrectly. I much prefer the idea of when the active file is changed. But it may be possible to just have it run on file change if the last modified time for the file were greater than the dropdown value selected by users to indicate how frequently they would like autosave to happen.

**Comment by pjkaufman** [comment]
I guess that while I am at it, I should go ahead and add an option for linting a file on close or file change. I am not sure if I can do anything about Obsidian closing though. That would be interesting to see if it would be feasible to run the Linter before closing, but if an infinite loop is hit in some of the logic I believe that would require Obsidian to be manually killed which could pose some problems.

**Comment by pjkaufman** [comment]
I was hoping to work on this, but I ran into an issue where the API is not providing the correct info, so I am blocked for now. I have reached out on the discord channel plugin_dev in order to see if any other devs have an idea on how to get an up to date value for the last active file.

**Comment by pjkaufman** [comment]
The change for linting on file close or the file changing should be present on master now and it will go out in the next release. Please let us know if this does not work as expected or has any issues.

The changes allow you to lint a file when you swap which file you are looking at (the previous file gets linted) or when you close a file (the file that was just closed gets linted).

There is also the ability to turn on a notification to let you know when the previous file being linted finishes. Its wording is like so: `Linted {INSERT_FILE_PATH_HERE}`.
