### ISSUE TITLE
there's no space-between-chinese-and-english-or-numbers rule in the latest release 1.2.10

### ISSUE THREAD

**Issue by goodwenxi** [platers/obsidian-linter#189]

**Comment by pjkaufman** [comment]
@goodwenxi , could you give some markdown we can test against where this is happening or some other piece of information to help determine the issue? As it stands all UTs are passing and I do not use Chinese and English together, so I am not sure what the issue would be. An example where it is not working would be very helpful. Thanks!

**Comment by goodwenxi** [comment]
@pjkaufman, after update to v0.14.6 this issue is gone. thanks.
