### ISSUE TITLE
FR: Remove empty lines between list items

### ISSUE THREAD

**Issue by harmtemolder** [platers/obsidian-linter#190]
Sometimes when I delete an item from a list I'm left with

```markdown
- item
- item

- item
- item
```

It would be great if that empty line could be removed

```markdown
- item
- item
- item
- item
```

(Same for numbered lists, which might then need #153 also)

**Comment by pjkaufman** [comment]
@harmtemolder , the change should now be in the master branch. It should be included in the next release. Please let me know if you are able to use the master branch to check out the fix prior to that.

I am guessing the next release will be within the next 2 weeks, but that will depend who all makes changes and how many changes are made.
