### ISSUE TITLE
FR: Remove empty lines in frontmatter

### ISSUE THREAD

**Issue by harmtemolder** [platers/obsidian-linter#191]
The "Removes leading and trailing blank lines in the YAML front matter." option already cleans

```markdown
---

modified: 2022-04-20T11:46:00+02:00

created: 2021-11-02T10:45:00+01:00

---
```

into

```markdown
---
modified: 2022-04-20T11:46:00+02:00

created: 2021-11-02T10:45:00+01:00
---
```

How do you feel about removing the empty line in the middle as well?

**Comment by pjkaufman** [comment]
I think that would be fine to add. It would just probably need to be its own rule since some people may be fine with spaces in the center, but not at the ends.

**Comment by pjkaufman** [comment]
This should now be available in the master branch and will be added in the next release. Please let me know if the changes made do not work for you @harmtemolder .
