### ISSUE TITLE
Feature request: Add two spaces before line breaks, if next line is not empty

### ISSUE THREAD

**Issue by benbohmer** [platers/obsidian-linter#195]
Some markdown renderers will ignore line breaks if they don't have two spaces at the end.

Some times there is use for having a line break without necessarily starting a new paragraph.

**Comment by pjkaufman** [comment]
@benbohmer , would it be correct to assume that lines of text that are side by side would be considered to be in the same "paragraph". For example
``` text
1. This is continued on the next line
This is a continuation of the previous line

This is a new paragraph

This is line 1 of the paragraph.
This is line 2 of the paragraph.

- This list item is continued with the next line
A continuation of the previous line

- This is not continued by the next text

New paragraph
```

So if a list item (ordered or unordered) is followed by a line of text, it will be considered to be in the same a paragraph.

**Comment by pjkaufman** [comment]
It seems this also applies to blockquotes.

**Comment by pjkaufman** [comment]
I merged in some logic to address this rule suggestion. You can either try it out now using the master branch directly, or you can wait until it gets released in a week or so. It should apply to blockquotes, paragraphs, and list items (ordered and unordered).
