### ISSUE TITLE
[Usability-breaking issue] Linter modifies links

### ISSUE THREAD

**Issue by firinael** [platers/obsidian-linter#196]
I have files with multiple spaces in their names, because reasons. Using Linter breaks the links to all those files by removing the double spaces. I'm sure this applies to other filters, and is something that completely breaks the usability of the plugin.

And yes, I can remove the double spaces from the file names, but Linter absolutely shouldn't be messing with anything that's inside a `link` environment anyways.

**Comment by platers** [comment]
Oops, text in links should be ignored. Should be a simple addition to the `ignoreYAML and other stuff` function.

**Comment by pjkaufman** [comment]
This looks like a simple change (I still need to take a look at the underlying logic). Is there any qualm with me taking a look and trying to fix it, @platers ?

**Comment by platers** [comment]
@pjkaufman please go ahead! Those look like the right targets
