### ISSUE TITLE
Feature Request: Custom Date Updated Field Name

### ISSUE THREAD

**Issue by zcysxy** [platers/obsidian-linter#2]
Thanks for the great plugin. I have a small FR, that we can customize the field name of `date updated`, for example, change it to `modified`.

By the way I have a small question: what is the syntax of `yaml-timestamp format=`? I wrote

```
yaml-timestamp format=YYYY-MM-DD HH:MM
```

and it told me `invalid argument format`. Seems like the space between `YYYY-MM-DD` and `HH:MM` is invalid.

**Comment by platers** [comment]
oh oops, parameter parsing doesn't allow spaces. Will fix

**Comment by platers** [comment]
fixed, now you can use `yaml-timestamp format="YYYY-MM-DD HH:MM"`
