### ISSUE TITLE
Linter Breaks the wikilinks on titles

### ISSUE THREAD

**Issue by lucasbonanni** [platers/obsidian-linter#201]
Hi! I found an issue using the linter plugin, in some titles where I have a wiki link and then use the linter, and it replaces the wiki link.
Ex.
`# Fundamentals of [[Docker]]`
after the linter runs
`# Fundamentals of Placeholder_link 57849`
I run the linter and replaces `[[Docker]]` by `Placeholder_link 57849`

(Edited) Linter version 1.3.0

**Comment by platers** [comment]
@pjkaufman any idea whats happening?

**Comment by lucasbonanni** [comment]
Looking at the code, it seems when I enable "YAML title" in the config, it runs this function on titles. [ignoreCodeBlocksYAMLAndLinks](https://github.com/platers/obsidian-linter/blob/master/src/utils.ts#L106) that replaces the wikilinks in lines [118,119,120](https://github.com/platers/obsidian-linter/blob/master/src/utils.ts#L118).

I tried disabling "YAML title" and is not happening.

**Comment by pjkaufman** [comment]
I can definitely take a look, but it looks like for some reason the value of the placeholder has been modified which causes it to not replace correctly. Are there any capitalization rules active?

**Comment by pjkaufman** [comment]
Here is the expected placeholder: https://github.com/platers/obsidian-linter/blob/master/src/utils.ts#L118.
I guess I need to do a case insensitive replacement.

**Comment by lucasbonanni** [comment]
I have this capitalization rules active
![image](https://user-images.githubusercontent.com/13741024/169388310-6d9eb1a7-41b8-492f-8673-66bba468eb4c.png)
I  also attached the data.json with the config.
[data.txt](https://github.com/platers/obsidian-linter/files/8733761/data.txt)
.

**Comment by pjkaufman** [comment]
Thanks, @lucasbonanni ! I should  be able to take a stab at this today or tomorrow.

**Comment by pjkaufman** [comment]
I can reproduce the issue with the provided configuration. I will see about fixing this. It should just be a matter of doing a case insensitive replace, but we will see.

**Comment by pjkaufman** [comment]
I should have a PR up to fix this today. It took a little while to reproduce in a UT.

**Comment by pjkaufman** [comment]
The PR is up and live. Now it is a matter of just getting an approval and maybe even a verification that the issue is gone. The issue was solely with the rule to capitalize first letter style. If all other rules were turned off, this one allowed me to trigger the the issue. It was my simplest case and that is what I based the solution on. Please let me know if the proposed solution does not work for some reason.
