### ISSUE TITLE
FR: Break down the yaml-title rule into two rules

### ISSUE THREAD

**Issue by yimingli** [platers/obsidian-linter#205]
Currently the `yaml-title` rule gets the title from the first H1 **or** filename. This is incompatible with the use case that uses H1 headers as section names rather than the file name. See [here](https://www.reddit.com/r/ObsidianMD/comments/rsr4mx/do_you_start_each_note_with_a_header_that_has_the/) for a discussion about different styles of H1 usage. For example:

```
# section 1
```

will be converted to

```
---
title: section 1
---

# section 1
```

Breaking the rule into 2 rules would solve this problem: `yaml-title-from-filename` and `yaml-title-from-h1`.

**Comment by pjkaufman** [comment]
I believe it makes the most sense to make the `yaml-title` header work with a dropdown as to how it should work. It would have 3 options:
- title from first H1 or file name
- title from file name
- title from first H1

We can add options down the road if we so choose this way. It also makes breaking this logic up better.

**Comment by pjkaufman** [comment]
I believe that I have the change as described in my previous comment ready. I need to add the text for each of the current languages and then go ahead and update the current `YAML Title` description to match the new functionality of the rule. It should work the same out of the box.

**Comment by pjkaufman** [comment]
The change to `YAML Title` adding 3 modes (one for how it currently works, one for just the filename, and one for just the first H1) should go out with the next release. Please let us know if this does not work on master or in the next release.
