### ISSUE TITLE
FR: Do not Remove Empty List Markers on Cursor Line 

### ISSUE THREAD

**Issue by pdelre** [platers/obsidian-linter#229]
As I often take notes with lists, while writing with [Remove Empty List Markers enabled](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#remove-empty-list-markers), I've often paused on a new list item when I hit `ctrl-s` with **Lint on save**. That removes the line the cursor is currently on, breaking the flow of the list. I would prefer the linting to not remove an empty list marker that has the cursor located on it.

Example (cursor position: `▒`)

_Original state_
```
- one
- two
- ▒

```

_Current linting behavior_
```
- one
- two▒

```

_Requested behavior, no change from original state_
```
- one
- two
- ▒

```

Negative case (no change requested)

_Original state_
```
- one
- two
- 
▒
```

_Current & expected linting behavior_
```
- one
- two
▒
```

**Comment by pjkaufman** [comment]
I am going to go ahead and close this. I do not believe there is currently enough interest in this feature to justify adding the maintenance overhead to account for this scenario. So for the time being, I am going to close this issue. We can revisit this if this is indeed something users would like.
