### ISSUE TITLE
When I checked the option "Space between Chinese and English or numbers", the tag is changed

### ISSUE THREAD

**Issue by agentptx** [platers/obsidian-linter#234]
before:
  #标签A      #标签2标签

after:
  #标签 A      #标签 2 标签

---

When the tag contains Chinese characters and letters or numbers, the formatted space changes the tag itself, hoping to repair it.

**Comment by pjkaufman** [comment]
This does not look like it will be too bad to fix. I will see about fixing it after I finish what I am currently working on.

**Comment by pjkaufman** [comment]
In the meantime, I would recommend disabling that rule in the YAML of the affected file(s) until the issue is resolved.
