### ISSUE TITLE
Bug: remove-link-spacing removes spacing inside checkbox when followed by markdown link

### ISSUE THREAD

**Issue by olearydj** [platers/obsidian-linter#236]
Hello again.
I noticed today that when `remove-link-spacing` is active, empty check boxes (`- [ ]`) get nuked on lint. I don't use them often but when I do, I they get linted into oblivion. A sub-option on this to exclude checkboxes would be great.

**Comment by pjkaufman** [comment]
@olearydj , what do you mean by get nuked? Could you provide an example as well as a copy of your `data.json` for this plugin to help me reproduce the issue?

**Comment by olearydj** [comment]
Sorry, I just mean that the linter removes the space between the square brackets, which breaks the checkbox.

**Comment by pjkaufman** [comment]
I can try a couple more rule combinations,but without the list of rukes you have active (the `data.json`) and/or a snippet of markdown with which to reproduce the situation with, I may not be able to recreate and fix the scenario you are describing.

I have not seen the behavior mentioned as of yet.

Here ias what I believe you are saying is happening:
``` markdown
- [ ] 

Other content here...
```
After lint:
``` markdown
- [] 

Other content here...
```

Is this the scenario you are describing, @olearydj ?

**Comment by pjkaufman** [comment]
Just in case you are not aware of where the `data.json` is, it should be located in `path-to-your-vault/.obsidian/plugins/obsidian-linter/`.

**Comment by pjkaufman** [comment]
I may have found a way to reproduce this issue, but I will have to do some more testing to see if I am actually able to do so. If I can, I will see about fixing this for this release.

**Comment by pjkaufman** [comment]
So it looks like if you have a link in a checkbox, it can cause an issue as follows.
Before:
``` markdown
- [ ] [Songs Tasks](Tasks/SongsTasks.md)
```
After:
``` markdown
- [] [Songs Tasks](Tasks/SongsTasks.md)
```

This seems like it will not be too hard to fix. It is likely due to not excluding a particular character from the regex. I will see about fixing this once I finish going through the changes made by the linting all my personal files to see if any issues popped up.

**Comment by olearydj** [comment]
Yes, that was exactly the situation. It was a list of obsidian plugins to look into, actually. Todo list of links.
Sorry I wasn't more specific / thorough in my reporting this time.

I've updated the plugin and can confirm this problem is fixed where I was able to repro it before.

Thank you!
