### ISSUE TITLE
Bug: File Metadata for Date Modified not Respected

### ISSUE THREAD

**Issue by dylan-ing** [platers/obsidian-linter#240]
对于时间戳自动更新，1.3.2版本能够实现ctrl+s自动更新，但1.3.3版本就不可以了【同样的配置】，希望大佬看一下

**Comment by pjkaufman** [comment]
According to Google Translate, I get the following  as the contents of the above message:
``` plaintext
For the automatic update of the timestamp, the 1.3.2 version can realize the automatic update of ctrl+s, but the 1.3.3 version cannot [the same configuration], I hope the big guy will take a look
```

@dylan-ing , do you mind explaining what you expected to happen versus what actually happened? I am planning to fix a couple things around the timestamp like changes to the actual timestamp in the file metadata also trigger the updating of date modified on the next lint, but that is yet to come. Before it always added a date modified no matter what which was not the intended functionality. I hope to have it setup in a more robust way for next release.

According to Google Translate, my above statement is roughly:
@dylan-ing, 你介意解释一下你期望发生的事情和实际发生的事情吗？ 我计划围绕时间戳修复几件事，例如更改文件元数据中的实际时间戳也会触发下一次 lint 上修改的日期的更新，但这还没有到来。 在它总是添加一个修改日期之前，无论哪个不是预期的功能。 我希望在下一个版本中以更强大的方式设置它。 这是谷歌翻译的，如果这看起来很奇怪或不正确，很抱歉。
