### ISSUE TITLE
FR: Ignore Tables when Removing Multiple Spaces

### ISSUE THREAD

**Issue by gavinmn** [platers/obsidian-linter#244]
In the latest update, using the `Remove multiple spaces` rule now completely mangles tables on lint. It would be great if a setting could control ignoring tables on lint.

**Comment by pjkaufman** [comment]
@gavinmn , thanks for reporting this.

Are you saying this just started happening with tge latest update, or is this new to the latest release? I am just asking for a little clarity in this case.

It may be a little tricky to ignore tables, but I should be able to.

**Comment by gavinmn** [comment]
It's tough for me to say. I had been using that rule for weeks and had no issues with tables. When I updated linter last night to the latest release I started running into problems. I'm fairly sure I was on the most recent version until I updated yesterday, but could have been one or two behind.

**Comment by pjkaufman** [comment]
Thanks for the info. I will see what I can do.

**Comment by pjkaufman** [comment]
It looks like I figure something out for the above scenario. Should be merged in shortly.
