### ISSUE TITLE
FR: A new YAML timestamp type called "Date Updated" which acts like the to-be-deprecated "Date Modified" timestamp

### ISSUE THREAD

**Issue by XDcedar** [platers/obsidian-linter#247]
@pjkaufman Hi, I saw the pull request #245 is going to change how metadata `Date Modified` would function:

> Date modified is updated if file changed time is more than 5 seconds away from the value in the yaml.

If my understanding is correct, it means `Date Modified` could update automatically. That's a nice feature which I would definitely use, but I still hope to keep the deprecated way to update `Date Modified` manually. The reason is that I use `Date Modified` to track version update date and I don't treat typo correction as an "update". For now this could be done by closing note without pressing Ctrl+S after correcting typo, but it would be hard to do so if `Date Modified` could update automatically.
Therefore it would be nice to add a new "Date Updated" YAML timestamp that allows users refresh its value manually.
Or maybe, just rename the old `Date Modified` option to `Date Updated` and add a new option called `Date Modified`. Not sure if this makes any difference, might affect the new feature "updated on format change"?

BTW I'm not sure if this is the best name, `Date Revised` or `Date Reviewed` may be better.

**Comment by pjkaufman** [comment]
Hey @XDcedar , the `Date Modified` rule will not be automatically updated without the user manually triggering the lint rule. So it will work the same with a coupke of changes. That 5 second difference is used during a manually triggered lint to see if the last time the file was listed as modified is greater than 5 seconds ago. It means that linting in quick sucession will not update date modified unless the date modified metadata for the file is more than a 5 second difference from the value at the top of the file in the YAML.

Does that make sense?

**Comment by XDcedar** [comment]
Oh, great, so it's a debounce feature, not a auto-update feature. That makes sense. I'm sorry I misunderstood your pull request. I'll close the issue. Thanks a lot!
