### ISSUE TITLE
Bug: paragraph-blank-lines only work on paragraphs started with English character

### ISSUE THREAD

**Issue by FrankinRUC** [platers/obsidian-linter#250]
When I enable paragraph-blank-lines, this rule only works on paragraphs started with English characters.
#### bad case 1: paragraphs started with Chinese characters
Before:
```
测试 foo
测试 bar
```

After:
```
测试 foo
测试 bar
```
#### bad case 2: paragraphs started with number
Before:
```
123 foo
123 bar
```

After:
```
123 foo
123 bar
```
#### bad case 3: paragraphs started with whitespace
Before:
```
 foo
 bar
```

After:
```
 foo
 bar
```
#### good case
Before:
```
foo
测试 bar
```

After:
```
foo

测试 bar
```

**Comment by pjkaufman** [comment]
Could you explain why those are two different paragraphs? In markdown, you often need a blank line between characters for them to be considered a new paragraph. I may be misunderstanding what that rule is meant to do, so I will check the examples, but clarification on why those are separate paragraphs would be very much appreciated.

**Comment by pjkaufman** [comment]
After looking at the rule, I can see how this would be considered a bug based on the example, but I would still like clarification on why they would be considered different paragraphs.

**Comment by pjkaufman** [comment]
@FrankinRUC , depending what you mean by "paragraphs started with whitespace", this case may not be able to be accommodated as a certain amount of whitespace is used to denote a code block. If the amount of whitespace used does not denote a code block, the parser may be able to identify the paragraph, but I make no promises.

**Comment by pjkaufman** [comment]
@FrankinRUC , I believe that I have fixed this on the master branch. It did not go out with the latest release as I did not know how long it would take to fix or if I would address this before the sorting of YAML keys. Please let me know if this issue persists on master or after the next release.

**Comment by zheng-weihao** [comment]
@pjkaufman sorry for the delay. I usually write notes in Chinese so I find that write paragraphs started with Chinese characters cannot add a blank line automatically. Bad case 1 drives me crazy when Chinese paragraphs in Obsidian merge into one in other Markdown preview tools like GitHub or vscode. Other bad cases are just limit tests for this rule and I don't know if they are designed or not. Thanks for the help and fast reply. I really appreciate it because I'm not a typescript developer.
