### ISSUE TITLE
Create Github Template Setup for Bug and Feature Requests to Help with Maintaining the Plugin

### ISSUE THREAD

**Issue by pjkaufman** [platers/obsidian-linter#253]
When bugs or feature requests come in, there is often something that is missing with regards to the content of the issue that has been created. This is because there is no guide to help those submitting tickets know exactly what is expected of them for the type of issue they are trying to report (a feature request or bug). It would be helpful to guide people through this process by adding templates for the people to fill out when submitting bugs or feature requests.

@platers , do you think this would be a good addition? I am now to this whole concept, but it looks doable: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by platers** [comment]
That looks useful! I dont think we should enforce any template strictly, but I think it will reduce the back and forth on tickets.

**Comment by pjkaufman** [comment]
I am not able to add any template via the methods described in the article for using the github UI. Is that something I should have access to or is that something you would have to add @platers ?

**Comment by platers** [comment]
I was able to follow the instructions. The output is in #255.

**Comment by pjkaufman** [comment]
Nice! I will see about adding some feedback to that PR. It looks pretty good, but there are 1 or 2 things that look like they would need tweaking.
