### ISSUE TITLE
Rule: YAML alias from title

### ISSUE THREAD

**Issue by mnaoumov** [platers/obsidian-linter#254]
The rule should transform

```
# My title
```

into

```
---
aliases:
  - My title
---

# My title
```

This would be helpful as `Quick Switcher` (`Ctrl + O`) supports aliases, so notes could be found not only by filenames but also with titles

***

However, I am not sure how to handle edits

```
---
aliases:
  - Old title
---

# Old title
```

edited to

```
---
aliases:
  - Old title
---

# New title
```

How can we possibly detect that `Old title` was the previous title on `modify` event?

**Comment by pjkaufman** [comment]
@mnaoumov , thank you for your request. Is my understanding correct that you would want the `alias` to keep one of its values the same as the name of the file?

For example `Test File.md` would have an alias value of 
``` yaml
alias:
  - Test File
```

Then when the name is changed via Obsidain to something else like `Test File 2.md`, the YAML would be updated to
``` yaml
alias:
  - Test File 2
```

**Comment by mnaoumov** [comment]
@pjkaufman No, I mean similar to https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#yaml-title but for `aliases`, that could be multiple values, not just single
