### ISSUE TITLE
Refactoring idea: Switch from strings to strongly-typed TypeScript constructs

### ISSUE THREAD

**Issue by mnaoumov** [platers/obsidian-linter#262]
While I was browsing the codebase I noticed a lot of places where options keys and its values are accessed by string, so typescript compiler can't detect typos if any.

I have some ideas how to improve it. But I know that authors rarely approve massive refactoring PRs. So I would like to get author's vision and approval before I start working on my PR.

**Comment by pjkaufman** [comment]
@mnaoumov , do you mind showing a small example of a change you are thinking of? I would be open to such a change if it is intuitive and does not break the old setup (i.e. not able to be made backwards compatible with current `data.json`).

Right now I am really the only active maintainer. My background is not so much in JS, but I can make things work in it. I am definitely open to suggestions.

**Comment by pjkaufman** [comment]
We could definitely do that for certain things that are common in the options object.
