### ISSUE TITLE
Bug: no-bare-urls adds brackets incorrectly to embedded images

### ISSUE THREAD

**Issue by Interpause** [platers/obsidian-linter#275]
## Describe the Bug

When linting, Obsidian Linter incorrectly adds brackets to embedded images in a way that breaks the image.

## How to Reproduce

``` markdown
<!--Correct: Does not add brackets-->
[text](https://www.example.com)

<!--Incorrect: Linter adds brackets-->
![image](https://www.example.com/foo.png)
<!--becomes...-->
![image](<https://www.example.com/foo.png)>
```

As shown above, the brackets are added as `(<link)>` instead of `(<link>)`, which would still work...

## Expected Behavior

``` markdown
<!--Either-->
![image](https://www.example.com/foo.png)
<!--Or-->
![image](<https://www.example.com/foo.png>)
```

## Device

- [x] Desktop
- [x] Mobile

**Comment by pjkaufman** [comment]
Thanks for reporting this @Interpause. I have an idea of what to do to fix this. I will see about fixing this for the next release.

**Comment by pjkaufman** [comment]
I am pretty sure it should just need me to use the markdown parser instead of regex.

**Comment by pjkaufman** [comment]
Looms like I need to ignore images as well for the method in question. I will see about refactoring it to make it easier to use and extend.

**Comment by pjkaufman** [comment]
This should be fixed on master now. Please let us know if it is not fixed on master or in the next release.
