### ISSUE TITLE
New rule to insert static lines into YAML

### ISSUE THREAD

**Issue by platers** [platers/obsidian-linter#28]
New rule, `Insert YAML line`, that inserts static lines into the yaml like `tags:`, `aliases:`.
Options: `line`: the line to insert.

Does nothing if line not specified.

**Comment by chrisgrieser** [comment]
I would also add the YAML seperator `---` as well, so that this rule is able to insert a complete YAML frontmatter when the document doe snot have one.

**Comment by platers** [comment]
Agreed, there is a function called initYAML which does that. Anyone can feel free to implement this, I might not get to it for a bit

**Comment by shauxesis** [comment]
While we are talking about YAML, in addition to the above, it would be great if we could also insert filename as `title:` into the YAML.
