### ISSUE TITLE
Bug: Indentation Removed from Lists Nested in Block Quote or Callout

### ISSUE THREAD

**Issue by ScottKillen** [platers/obsidian-linter#289]
## Describe the Bug

Linter destroys legitimately formatted multi-level unordered lists within quote blocks & callouts

## How to Reproduce

1. Create an unordered list with multiple indentation levels.
2. Add '>' to the beginning of the lines to create a quote block or callout
3. Run linter.
4. Observe that the whitespace between '>' and '-' used to create the multiple levels of the list has been collapsed, and the list is no longer multi-level.

## Expected Behavior

Linter should ignore spaces between a '>' at the beginning of the line and '-' regardless of the rules selected.

## Screenshots

![2022-07-15_13-36-56](https://user-images.githubusercontent.com/1509989/179279370-0077d80a-0efd-4b71-84e3-bf3c74b84654.gif)

## Device

- [x] Desktop
- [ ] Mobile

[data.json.txt](https://github.com/platers/obsidian-linter/files/9122892/data.json.txt)

**Comment by pjkaufman** [comment]
@ScottKillen , could you include the underlying markdown as well? It looks like you are using a callout, but I would like to make sure that is the case before I move forward with this if possible.

**Comment by ScottKillen** [comment]
@pjkaufman 

I am using a callout here:

```
> [!info] Unordered List
> - First Level
> - First Level
>   - Second Level
>     - Third Level
> - First Level
```

I want extra spaces that do not contribute to the format to be removed. For instance, two spaces between words.

However, the linter should not remove **semantic** whitespace.

For instance, further testing reveals that the linter also breaks code within a callout:

```
> [!info] Code
>     Line 1
>     Line 2
>     Line 3
```

I would expect the spaces between '>' and the next non-space character to be unmolested.

'>' + 5 spaces = code within a callout.
'>' + a space + two spaces for each level of indent = multi-level unordered list.

If this isn't automatic behavior, I would love to have it as an option.

**Comment by pjkaufman** [comment]
Gotcha. It currently does not respect nested format in these cases, but I can see if this is an easy fix and aim to get it in this release or try to get it in in a later release. I want to say that the rule in question does ignore whitespace at the start of a line, but block quotes were not added as a part of tge start of the line exception.

**Comment by ScottKillen** [comment]
Thank you!

**Comment by pjkaufman** [comment]
This should be present on master now. I plan to do a release later today so the change should be included in that. If you would like the changes for the new release, please make sure you are on the latest version of Obsidian `v0.15.6` since a change made needed that version of Obsidian and would not work on prior versions.
