### ISSUE TITLE
Bug: i can't update from 1.3.5 to 1.3.6

### ISSUE THREAD

**Issue by chumido98** [platers/obsidian-linter#296]
## Describe the Bug

i can't update from 1.3.5 to 1.3.6. I tried reinstall plugin, download plugin ver 1.3.6 and paste in plugin folder. I'm on mac Catalina and Obsidian v0.15.6

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
@chumido98 , are you on version `0.15.6` of Obsidian? The latest update requires it.

**Comment by pjkaufman** [comment]
Please disregard my question. I misread your message. I am seeing the same behavior myself.

**Comment by pjkaufman** [comment]
@chumido98 , I believe it is fixed now. I am not sure why, but it seems it did not like something I thought could be left alone in the `manifest.json`

**Comment by pjkaufman** [comment]
I am going to close this issue since I am now able to update it via the community tab. Please let us know if the issue does persist.

**Comment by chumido98** [comment]
It work now. Thank you very much.

**Comment by pjkaufman** [comment]
Thanks for reporting the issue. I have not had this happen before.
