### ISSUE TITLE
Bug: When I use emphasis, there will be spaces

### ISSUE THREAD

**Issue by ashtime99** [platers/obsidian-linter#301]
I checked the option "Space between Chinese and English or numbers"
When I use emphasis, there will be spaces
![image](https://user-images.githubusercontent.com/75244264/179440879-43dbaf94-4dd8-4966-b13d-d83093f91434.png)
after:
![image](https://user-images.githubusercontent.com/75244264/179440929-9db45081-2b6a-4571-8265-84bfcc46a011.png)

**Comment by pjkaufman** [comment]
@ashtime99 , I want to make sure that you would like to ignore bold and emphasis for the "Space between Chinese and English or numbers" rule. Is that correct?

**Comment by ashtime99** [comment]
yes，I want ignore bold and emphasis for the "Space between Chinese and English or numbers" rule

**Comment by pjkaufman** [comment]
I have a fix for that, ready to go, but it will not be on master until next release (hopefully not this week, but next). In the meantime, it may make sense to not use "Space between Chinese and English or numbers" if you need those spaces retained.

**Comment by pjkaufman** [comment]
I need to go ahead and make sure to make a more robust solution for this, so I will take a little extra time on this, but hopefully ti will still go out this release.

**Comment by pjkaufman** [comment]
Simple uses of italics and bold now only have their text modified and the italics and bold indicators should be left alone. If you are hoping to use nested bold and italics with Chinese characters, the rule does not support this at this time and a PR to add this functionality is welcome. If this issue still persists on master or in the next release, please let us know.
