### ISSUE TITLE
Bug: Image Links with Chinese characters can cause problems

### ISSUE THREAD

**Issue by zhl111** [platers/obsidian-linter#302]
If this feature is selected——`Space between Chinese and English or numbers`
![image](https://user-images.githubusercontent.com/29135984/179560012-2b402f0a-435f-4cf6-8c03-501bab7daa52.png)

**Comment by pjkaufman** [comment]
I will see about creating a fix for this. Did you just want to ignore the link reference and not the text?

**Comment by pjkaufman** [comment]
Image links should now be ignored by this rule. If this issue still persists on master or in the next release, please let us know.
