### ISSUE TITLE
Bug: can't insert space between Chinese and math equation correctly

### ISSUE THREAD

**Issue by 15040941306** [platers/obsidian-linter#303]
I turn on the function "Space between Chinese and English or numbers" and try to lint the file.

But I found it can only insert a space before a math equation but can't insert a space between the equation.

Sample:

- Before:

```markdown
这是一个数学公式$f(x)=x^2$这是一个数学公式
```

- After：

```markdown
这是一个数学公式 $f(x)=x^2$这是一个数学公式
```

**Comment by pjkaufman** [comment]
@15040941306 , this sounds like it is a feature request, but I will see what I can find out relating to this.

**Comment by 15040941306** [comment]
@pjkaufman I'm sure that is a bug instead of a feature, because it either both add space to the left and right of math equations, or leave this case alone in normal conditions. It won't add only one space in the left but no in the right.

**Comment by pjkaufman** [comment]
Found an easy fix to the issue:
swapping [tail](https://github.com/pjkaufman/obsidian-linter/blob/master/src/rules.ts#L3014) to be `(\[[^[]*\]\(.*\)|`[^`]*`|\w+|[-+;:'"°%)$\]}]|[^*]\*)( *)([\u4e00-\u9fa5])` seems to fix the issue.

**Comment by pjkaufman** [comment]
I will see about getting this merged after the refactor changes get merged.

**Comment by pjkaufman** [comment]
This issue should be resolved on master. Please let us know if this is not resolved on master or in the next release.
