### ISSUE TITLE
Bug: disabled rules: [all] does not disable YAML Timestamp.

### ISSUE THREAD

**Issue by zcysxy** [platers/obsidian-linter#306]
## Describe the Bug

`disabled rules: [all]` does not disable YAML Timestamp.

## How to Reproduce

1. Set up the YAML Timestamp like this ![](https://user-images.githubusercontent.com/48207708/180135592-00880f1d-a08f-4b2c-bd71-676d4d803c7a.png)
2. In a note, write `disabled rules: [all]` in the YAML
3. Excute the command `lint current file`
4. The YAML timestamp is still inserted

## Expected Behavior

The YAML timestamp should not be inserted when `disabled rules: [all]` is there.

## Device

- [x] Desktop (macOS)

**Comment by pjkaufman** [comment]
@zcysxy , thanks for reporting this. I will see about taking a look at this for this next release.

**Comment by pjkaufman** [comment]
Note to self, I need to check disabled rules for each special rule that is not run as if it were a regular rule to allow it to run in a particular order.

**Comment by pjkaufman** [comment]
This issue should be resolved on master. Please let us know if this is not resolved on master or in the next release.
