### ISSUE TITLE
Bug: Not support YAML multiline array

### ISSUE THREAD

**Issue by Tinc233** [platers/obsidian-linter#307]
## Describe the Bug
YAML Multiline array may cause errors.

## How to Reproduce
Issue1:
It will show an error messge and stop.
Example:
```
---
tags: 
- tag1
- tag2
stars: aaaa
---
content
```

Issue2:
If I turn on YAML key sort:
Example:
```
---
note: 
tags:  
- tag1
- tag2
aliases: 
- aliase1
- aliase2
---
```
It should behavior like this:
```
---
aliases:
- aliase1
- aliase2
note: 
tags: 
- tag1
- tag2
---
content
```

But it will convert to:
```
---
aliases:
note: 
tags: 
- aliase1
- aliase2
- tag1
- tag2
---
content
```

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
@Tinc233 , sounds like it does have an issue with the arrays, but I may be missing something since I am pretty sure that YAML list items are required to be indented in the YAML.

Could you try with the list items for the YAML multiline array indented?

**Comment by pjkaufman** [comment]
Well, I just looked for YAML arrays and found zero indentation on list items for multiline arrays, but I don't think the YAML parser we use allows for that. I will have to see what is going on.

If for issue 1, you get a YAML Excpetion, there is likely nothing I can do about it.

**Comment by pjkaufman** [comment]
I may need to add documentation around what YAML is valid for the plugin itself since YAML is tricky and not all parsers support all formats.

**Comment by Tinc233** [comment]
> @Tinc233 , sounds like it does have an issue with the arrays, but I may be missing something since I am pretty sure that YAML list items are required to be indented in the YAML.
> 
> Could you try with the list items for the YAML multiline array indented?

Thank you for your reply!
I tried with the list items indented，but issue1 and issue2 will appear again . If I write in single line, it would work very well. 
---
I just find both of **the issues will appear ONLY when the key is "aliases", ”aliase" or "tags"**.
For example:
If I change the keys into other words, such as:
```
---
tag: 
  - tag1
  - tag2
hhh:
  - tag1
  - tag2
stars: aaaa
alias:
  - aliase1
  - aliase2
---
content
```
Then it works as expected! (YAML-key-sort  works well too)
```
---
alias:
  - aliase1
  - aliase2
tag:
  - tag1
  - tag2
hhh:
  - tag1
  - tag2
stars: aaaa
---
```
I think the problem is probably related to Obsidian's native Yaml support

**Comment by pjkaufman** [comment]
I will take a closer look at this when I get a chance since I do not use the Obsidian API for parsing the YAML, it is likely something that was misses when parsing the yaml.

**Comment by pjkaufman** [comment]
Could you include a file that you can reproduce the issue with and your `data.json` file from `path_to_vault/.obsidian/plugins/obsidian-linter/`? I cannot seem to reproduce the exact issue you are referring to, but I am seeing issues with blank yaml values.

**Comment by Tinc233** [comment]
> Could you include a file that you can reproduce the issue with and your `data.json` file from `path_to_vault/.obsidian/plugins/obsidian-linter/`? I cannot seem to reproduce the exact issue you are referring to, but I am seeing issues with blank yaml values.

It's my fault. I should input 2 spaces beffor "-". 
Here's the files:
[test.zip](https://github.com/platers/obsidian-linter/files/9173866/test.zip)

This plugin works very well! Thank you.
