### ISSUE TITLE
Bug Capitalize Headings: bug with accented letters

### ISSUE THREAD

**Issue by Oskiator** [platers/obsidian-linter#321]
Hi ! Here is a but with  the "Capitalize Headings" fonction.

## Describe the Bug
When Capitalize Headings is enabled, and a title begins with an accented letter, the first two letters of the title will be capitalized instead of just the first letter.

## How to Reproduce

1. Just write a title starting with an accented letter
2. lint the file with Capitalize Headings a/ enabled ; b/ Style set to "First letter"

## Unexpected Behavior

E.g
```
## état  
```
will be replaced by 
```
## ÉTat
```
and
```
## équilibre
```
will be replaced by 
```
## ÉQuilibre
```

## Expected Behavior
```
## état  
```
should be replaced by 
```
## État
```
and
```
## équilibre
```
will be replaced by 
```
## Équilibre
```

Thanks for your work !
Michaël

**Comment by pjkaufman** [comment]
Thanks for reporting this issue. I am pretty sure that I know what is causing this issue, I just need to figure out how to ignore numbers, whitespace, and punctuation and then I should be able to make this happen.

**Comment by pjkaufman** [comment]
The fix is coming up for this. It was a simple change thanks to https://stackoverflow.com/a/62032796 which really helped out determining how to do this properly.

**Comment by pjkaufman** [comment]
This issue should be accounted for in the next release and on master. Please let us know if the issue continues to exist in either of those.

**Comment by Oskiator** [comment]
Great, many thanks for your work !
