### ISSUE TITLE
FR: Remove empty numbered markers

### ISSUE THREAD

**Issue by yimingli** [platers/obsidian-linter#331]
## Is Your Feature Request Related to a Problem? Please Describe.

Currently the rule "Remove Empty List Markers" removes the empty list markers, but doesn't remove empty numbered list markers.

## Describe the Solution You'd Like

Remove empty numbered list markers.

**Please include an example where applicable:**

Before:
``` markdown
1. first item
2. second item
3.
```

After:
``` markdown
1. first item
2. second item
```

**Comment by pjkaufman** [comment]
Thanks for pointing this out. It seems it does not check for several list indicators. I will see about adding something for all the cases.

**Comment by pjkaufman** [comment]
Though, I guess it would not affect nesting inside of bloquotes yet. I would need to handle that as well.

**Comment by yimingli** [comment]
Thanks for looking! A related issue with the "Remove Empty List Markers" rule is as follows (maybe it's the side effect of some other spacing rules):

Before:
```markdown
* item 1
    *
* item 2
```

After:
```markdown
* item 1

    *

* item 2
```

What I expected:
```markdown
* item 1
* item 2
```

**Comment by pjkaufman** [comment]
That is related. The only list marker accoubted for is `-`, so that would be added with the others.

**Comment by pjkaufman** [comment]
I had some spare time and saw that this should be a relatively quick fix, so the change for it should be present on master soon. I have a fix working. I plan to add another simple feature request and push those two up together.

**Comment by pjkaufman** [comment]
The fix for this should now be on master and is slated for the next release. Please let us know if for some reason it is not fixed on master or in the next release.
