### ISSUE TITLE
FR: Recognize special blocks or syntaxes to disable Linter on them

### ISSUE THREAD

**Issue by AMGMNPLK** [platers/obsidian-linter#334]
I'm starting using [Obsidian_to_Anki plugin](https://github.com/Pseudonium/Obsidian_to_Anki) and it works with an special use of the blank lines and probably other syntaxis. If I use Linter I break these rules and the [Obsidian_to_Anki plugin](https://github.com/Pseudonium/Obsidian_to_Anki) function.

I would like that Linter recognize these rules in the notes and avoid modifying these features of those texts.

Example

Original text
``` markdown
Question %% #flashcard %%
Answer
```
After the current Linter version 
``` markdown
Question %% #flashcard %%

Answer
```
The ideal solution should have a toggle in the configuration to select (or make it default) if we want to respect the rules of [Obsidian_to_Anki plugin](https://github.com/Pseudonium/Obsidian_to_Anki) on these lines (maybe with the toggle to force Linter to act). Another not so good option could accept some regex templates and which rules should not be executed on them.

**Comment by pjkaufman** [comment]
This sounds like it could be an interesting addition to the plugin. I am definitely open to PRs around this. As of right now, I am focusing on older FRs that have been requested multiple times or have been around for a while that I have the knowledge to work on at this time.

If you would like to, you could open a PR to add this feature.

Thanks again for the request!

**Comment by pjkaufman** [comment]
So far I have a basic form of the UI and I have started work on passing it into rules. This would not apply to paste rules or custom commands. I do plan to add this functionality to the custom ignores though.

**Comment by pjkaufman** [comment]
This should go out in the next release. Please let us know if the new syntax does not work for ignoring the Linter rules on master or in the next release.
