### ISSUE TITLE
Bug: bar links with hash get embraced repeatedly on lint.

### ISSUE THREAD

**Issue by ben-yip** [platers/obsidian-linter#339]
## Describe the Bug

a bare link with any trailing hash part like `https://foo.bar#hash` get embraced with `<` and `>` repeatedly on lint.

## How to Reproduce

Consider `https://foo.bar#hash`, when the file is linted three times, would result in `<<<https://foo.bar#hash>>>`.

**Comment by pjkaufman** [comment]
Thanls for reporting this issue. I may have fixed this earlier this week as I fixed a similar issue that I couldn't figure out for the longest time.

I will take a look and see if this ia still happening for me.

**Comment by pjkaufman** [comment]
Looks like it is still happening. I will have to take a closer look.

**Comment by ben-yip** [comment]
If possible, while fixing this, consider removing multiple `<>`s around bare links when lint is performed.

**Comment by pjkaufman** [comment]
I will see about adding this in the change to add formatting YAML arrays. I have been out sick for the past couple of days, so it is taking longer than expected to enact some of these changes, but hopefully I will have this wrapped up today.

**Comment by pjkaufman** [comment]
The problem seems to be that it thinks the ending of the URL is a tag. I am going to try to force the tag matching to require it to be a start of a lone or follow some kind of whitespace.

**Comment by pjkaufman** [comment]
I have a fix, but removing multiple angle brackets is being a bit tedious for some reason.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release which I plan to put out tonight. Please let us know if it is not fixed on master or in the next release.
