### ISSUE TITLE
Large linting errors when the file has an additional YAML frontmatter section

### ISSUE THREAD

**Issue by gavinmn** [platers/obsidian-linter#34]
I haven't been able to test this out further but just had to restore a few files from my version history because large duplications of content and messed up formatting occurred when there was a second instance of frontmatter.

Example: 
```
---
frontmatter: at the top of the file
---

Contents of the file
Contents of the file

---
code block: with frontmatter
---
code
code

```
Using rules:
```
heading-blank-lines bottom="false"
consecutive-blank-lines
space-after-list-markers
yaml-timestamp format="YYYY-MM-DD" dateCreated="false"
compact-yaml
capitalize-headings
file-name-heading
```

**Comment by platers** [comment]
Thanks for reporting, can you check if #35 fixes the issues?

**Comment by gavinmn** [comment]
Looks like it fixed the issue. I tested it on the same content that I hit the issue with before and it was all good.
