### ISSUE TITLE
FR: renumber lists...

### ISSUE THREAD

**Issue by olearydj** [platers/obsidian-linter#340]
## Is Your Feature Request Related to a Problem? Please Describe.

It would be nice to offer the option to reindex numbered lists, i.e. after I edit a numbered list to remove an item, lint to update the numbering.

## Describe the Solution You'd Like

See above. I believe this is self-explanatory.
If not, I'll come back and add details next week.

## Describe Alternatives You've Considered

Manual. Probably there are other plugins, but it seems a good linter feature.

## Additional Context

Thanks for this valuable plugin!

**Comment by pjkaufman** [comment]
@olearydj , unless I am mistaken this is a duplicate of #153 . If it is, I will close this in favor of that FR as it is older.

**Comment by olearydj** [comment]
Yep, sorry about that!

**Comment by pjkaufman** [comment]
No problem.
