### ISSUE TITLE
Bug: Single dollar sign in inline code replaced by wired content.

### ISSUE THREAD

**Issue by ben-yip** [platers/obsidian-linter#344]
## Describe the Bug

If there is a single dollar sign in inline code format, linting appears to introducing wired content. 
I ran into it when the `` `$` `` is replaced by a large amount of paragraphs of the original article.

I suppose it is a regex bug of internal linting rules.

## How to Reproduce

before:
``` markdown
# Title
- lorem `$` ipsum
```

after:
```markdown
# Title
- lorem `# Title
 ipsum
```

**Comment by pjkaufman** [comment]
That is likely becaise the content is not being regex escaped as there was not a use case for doing so at the time.

**Comment by pjkaufman** [comment]
Could you provide your `data.json` located in `path_to_obsidian/.obsidian/plugins/obsidian-linter/`? I am not sure exactly which rule is causing the problem.

**Comment by pjkaufman** [comment]
I finally found it. It was the fullwidth rule. I have a fix.

**Comment by pjkaufman** [comment]
This change should be merged into master. I plan to release bug fixes that are fixed today by the end of the day.
