### ISSUE TITLE
Bug: `invalid date` as value for `date created`

### ISSUE THREAD

**Issue by BonfireAtNight** [platers/obsidian-linter#346]
## Describe the Bug

When I lint a file, the `date created` key gets a `invalid date` value.

## How to Reproduce

The described behavior occurs every time I lint a file. This is true for newly created notes, too. It was not the case until yesterday, though I'm not 100% certain that it began with the newest plugin update. The only other thing I did is that I've installed the Regex Pipeline plugin.

**Comment by pjkaufman** [comment]
Can you confirm that this happens for when you are just using Obsidian Lint (i.e. other community plugins are disabled)?

**Comment by pjkaufman** [comment]
Also what version of Obsidian are you using? The plugin has not been tested for the insider releases.

**Comment by pjkaufman** [comment]
Seems I am seeing the same result. I will see about getting a bug fix together for it.

**Comment by pjkaufman** [comment]
I have a fix. I will release a patch version later today with a couple other minor bug fixes from the release. It seems the file metadata is not in a locale specific format.

**Comment by pjkaufman** [comment]
This change has been merged into master and should go out later today as a set of bug fixes for release.

**Comment by BonfireAtNight** [comment]
Great, thanks a lot for the fantastic work you are doing here!
