### ISSUE TITLE
FR: Option to add/update file creation date only if doesn't already exist in yaml (YAML Timestamp option).

### ISSUE THREAD

**Issue by sessionsdev** [platers/obsidian-linter#353]
I use obsidian and sync across several devices.  When linting the file on any device, it updates the file creation time to the local system file creation time.  For me, this limits the usefulness of recording the file creation date in the frontmatter.

## Describe the Solution You'd Like

A toggle option to only write the file creation date if the key does not exist yet.

**Comment by pjkaufman** [comment]
I don't recommend using date created across file systems. It is not designed for such use as it only knows about the current one and will try to make it work with that value.

**Comment by pjkaufman** [comment]
The option should be feasible to add. But I will caution that it may not fix all scenarios in question.

**Comment by anatexis** [comment]
It would be great if it would be added (again). In an earlier version of Linter it just updated the modified date. This was really useful for me because I imported a large number of notes from another software and I could manually modify the creation time and it didn't change afterwards.

**Comment by pjkaufman** [comment]
This is related to #621 which I believe I have a fix for.

**Comment by pjkaufman** [comment]
The change for this should now be on master and go out with the next release. Please let us know if that is not the case.
