### ISSUE TITLE
Bug: Removing empty list markers failed when there's no blank line at the end of the document

### ISSUE THREAD

**Issue by yimingli** [platers/obsidian-linter#356]
## Describe the Bug

Removing empty list markers failed when there's no blank line at the end of the file.

Related to https://github.com/platers/obsidian-linter/issues/331

## How to Reproduce

Before:

```markdown
* item
*
// [end of file without blank line here]
```

After: linter adds a blank line, keeps the empty marker, and adds 3 additional blank lines to the end of the file. Linting again would remove the empty marker as well as the blank lines.
```markdown
* item

*



```

If there's a white space after the empty list marker, linter adds 1 blank line instead of 3 blank lines to the end of the file.

Expected:
```markdown
* item
```

Related rules:
* https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#line-break-at-document-end
    * when I turn off the "line break at document end" rule, the 3 extra blank lines won't be added to the end of the document. But linting again won't remove the blank line and the empty marker.

[data.json.zip](https://github.com/platers/obsidian-linter/files/9339529/data.json.zip)

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
I actually merged what I belive to be the fix for the removal of the empty list marker at the end of a file.

**Comment by pjkaufman** [comment]
Thanks for putting in the bug. I will link it to the PR I merged in for this some time later today.

**Comment by pjkaufman** [comment]
It was fixed by https://github.com/platers/obsidian-linter/pull/355

**Comment by pjkaufman** [comment]
I plan to release the fix later today. Thanks again for putting in the bug!
