### ISSUE TITLE
FR: Support custom lint rules or scripts

### ISSUE THREAD

**Issue by windily-cloud** [platers/obsidian-linter#358]
## Problem

The current lint rules are becoming more robust as developers work on them, but they currently lack a certain amount of flexibility. For example, for the title rule in yaml, I need to read the name of the parent folder as a prefix and add it to the title. Such rules are too personal to be integrated directly into the lint plugin.

This may be more common, and it's hard for developers to add options one by one in the settings.

## Solution

This solution can be difficult or easy, depending on the developer, and I offer the following ideas for reference.

Probably the easiest：
Add a new lint rule and execute the script after the other rules have run. This part can even be further simplified with quickadd, which executes the quickadd command after the other lint rules are executed.

Probably the most difficult:
Similar to eslint, standardize, register and manage lint rules, load into existing lint rules via npm packages

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/30640638/184781858-64623a60-9f31-4d07-9493-9bee09e21eb0.png">

## Additional Context

How do you think this feature should be handled better? Looking forward to any response from you.

**Comment by SWIO** [comment]
I would like to develop this idea to support the kind of rule that would convert a 'smart' quote to a 'straight' quote

“This phrase is inside smart quotes” and "this phrase is inside straight quotes"

**Comment by pjkaufman** [comment]
This is definitely is something that I think could be added. It is something that would be hard to make sure it works and we do not get a lot of erroneous bug reports due to bad syntax and things of that nature. I do like the idea and think it definitely could be feasible.

I am guessing it would have to work kind of like custom scripts for Templater in that it lets you specify which folder to look in for the scripts it will use as custom rules. Defining when they run might be tricky as well, but it should be able to be handled. I am definitely not opposed to PRs around this while I work on bugs and adding warning mode. However this is a promising idea to help people out with adding some rules they want without having to add it for everyone if it is a more niche need.

How would this work for mobile?

Would we allow for an option to disable a script that is present in the directory?

How would we determine run order between the custom scripts? Would this be alphabetical, user defined, etc.?

**Comment by windily-cloud** [comment]
> How would this work for mobile?

Just like quickadd plugin, it can work for mobile.

> Would we allow for an option to disable a script that is present in the directory?

This can also be handled like quickadd, which writes the options to data.json and then loads them in the settings.

> How would we determine run order between the custom scripts? Would this be alphabetical, user defined, etc.?

Just put the custom script after the linter rule and run it, I guess it doesn't really need to be executed before the other rules, at least I do.

I think I can do it in a day if I use the existing quickadd function. There may be problems with debugging and testing, but it's enough for personal use.

**Comment by pjkaufman** [comment]
If you create the changes to add the basic functionality in a draft PR, I likely can add the UTs and get it into the format that follows how rules are linted in the Linter.

Otherwise, it might take me a little while to get to this. But I do see the benefit of this.

**Comment by windily-cloud** [comment]
I have submitted a draft PR：
<img width="798" alt="image" src="https://user-images.githubusercontent.com/30640638/188317405-26c8938f-5707-4947-a1fc-3e9f27d19fbe.png">

This way I just need to write custom lint code in quickadd, register it as a command, and it will work with linter.

**Comment by pjkaufman** [comment]
I am not sure on the part about adding it as an Obsidian command. But wriiting the logic to run it makes should be all that is needed yet. I am curious how the js scripts will be run (I am hoping they are functions that can run as using `eval` is not recommended). I am still taking a look at the PR, but it looks like there are several minor things that woukd need addressing.

**Comment by windily-cloud** [comment]
1. install quickadd plugin
2. write a custom js file in the vault
3. go to quickadd setting page, create a macro and choose your js file
4. register this macro as a obsidian command in the quickadd settting page
5. register obsidian command in the linter page，so that linter can excute the command sometime

**Comment by pjkaufman** [comment]
While that does seem like that makes running the custom lint rules easy, I don't think making the Linter use another plugin would be recommended here. I do like the concept of using a custom js file.

**Comment by windily-cloud** [comment]
You can even format md files with python, rust, go and other programming languages with the help of shell command plugins. quickadd, the shell command only serves to register the operation of running the code, as a command, and we linter only use to call the command.

**Comment by pjkaufman** [comment]
Using another plugin comes with a lot of extra considerations that needed to be taken into account like checking that the specified plugin is installed before enabling the Linter setting toggle for the custom lint rule. It also makes verifying that the custom lint rules are working a decent bit harder as UTs cannot verify that.

**Comment by pjkaufman** [comment]
I am not sure that QuickAdd being used is something that is not feasible, but there several things that needed to be addressed before we can do that including how to verify that the rule is working correctly.

**Comment by windily-cloud** [comment]
I probably can't help much then, quickadd does quite a bit of work. templater so far can't run scripts on the phone, but quickadd can, and it works well.

**Comment by windily-cloud** [comment]
The ease of use of quickadd is reflected in the ui, dragging, suggester, automation, etc. Our linter only has a main.js, I did not even dare to import the ui library. for fear of spoiling the simplicity of the linter plugin.

**Comment by windily-cloud** [comment]
> like checking that the specified plugin is installed

The read is an obsidian command, it doesn't matter if you have quickadd installed or not, and it doesn't matter if you have verified the installation of the plugin.

> It also makes verifying that the custom lint rules are working a decent bit harder as UTs cannot verify that.

Verification and testing can also be left entirely to the users themselves, after all, quickadd debugging is quite convenient.

**Comment by pjkaufman** [comment]
> I probably can't help much then, quickadd does quite a bit of work. templater so far can't run scripts on the phone, but quickadd can, and it works well.

It just removed that restriction, but it may not work for iOS.

**Comment by pjkaufman** [comment]
> > like checking that the specified plugin is installed
> 
> The read is an obsidian command, it doesn't matter if you have quickadd installed or not, and it doesn't matter if you have verified the installation of the plugin.
> 
> > It also makes verifying that the custom lint rules are working a decent bit harder as UTs cannot verify that.
> 
> Verification and testing can also be left entirely to the users themselves, after all, quickadd debugging is quite convenient.

Letting users be the QAs should be done with caution as this can easily create a poor quality result. In this case that may not be the case, but we need to be careful to make sure it works correctly and well.

**Comment by pjkaufman** [comment]
To make sure I am not misunderstanding what is being said here, the following will be true about this feature:

- It will use the specified Obsidian commands as custom rules
- It will not require a dependency on another plugin (i.e. it only adds references to Obsidian or Linter specific logic)

If the above two things are true (please correct me if I am misunderstanding something), then I think this addittion s

**Comment by pjkaufman** [comment]
Sorry I accidentally hit the wrong button.

**Comment by windily-cloud** [comment]
> It will not require a dependency on another plugin (i.e. it only adds references to Obsidian or Linter specific logic)

Well, I'm probably not much help, it's pretty hard for me to custom run the code and get it stable. But now I'm writing this should satisfy my needs, haha！

Thank you for your patience, you can choose to close this issue.

**Comment by pjkaufman** [comment]
> > It will not require a dependency on another plugin (i.e. it only adds references to Obsidian or Linter specific logic)
> 
> Well, I'm probably not much help, it's pretty hard for me to custom run the code and get it stable. But now I'm writing this should satisfy my needs, haha！
> 
> Thank you for your patience, you can choose to close this issue.

I am more than happy to take it from wherever you would like to stop as this does seem like it would fill a need that several people have where they would like a rule added, but we have not gotten to it or it is too niche to justify adding for everyone. Please let me know if you would like me to work off of your current implimentation or if you plan to add some more changes yet.

**Comment by windily-cloud** [comment]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/30640638/188323519-bd1d7a28-45e9-4b64-97b9-06c14ccd5932.png">

My last step is to run all the commands of `lintCommand` array in the `data.json` file at the end of this function. That's good enough for me, it currently doesn't rely on any other plugins and just runs obsidian's commands.  There are some places I may have missed without reading through the code, and I'll leave it up to you to decide where you should run custom commands

> To make sure I am not misunderstanding what is being said here, the following will be true about this feature:
> 
> It will use the specified Obsidian commands as custom rules
> It will not require a dependency on another plugin (i.e. it only adds references to Obsidian or Linter specific logic)

I just understood what you meant, lol.

**Comment by pjkaufman** [comment]
Gotcha. I would not add them at the end of that file. I would add it at the end of the try catch statement as that is where the linting logic resides. I may want to move that out to a testable function somewhere, but that would be down the road.

**Comment by windily-cloud** [comment]
Or you consider more thoughtful, after you add the code I will learn to how to increase the reliability of the plugin.👍👍👍

**Comment by pjkaufman** [comment]
Sounds good. I would like to refactor it and move it over today, but we will see how that goes.

**Comment by pjkaufman** [comment]
@windily-cloud , could you provide an example usage of a quick add macro that would update a file? I am curious since I do not see how it is getting the current file info to update the correct information. Thanks for helping me visualize what is going on here.

**Comment by windily-cloud** [comment]
It may be a little tricky, but it's easy once configured, and I'll elaborate on each step:

Step 1:
- Install quickadd plugin
- Create a folder in your vault and create a .js file like this:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/30640638/188553986-8196d8cb-fb83-4e92-845b-4197118be137.png">

Step 2:
- Write the logic for modifying the current md file in the js file
- I write a modify the yaml title key as example:

This file changes the title value in yaml to the file name
```js
module.exports = async (params) => {
  const currentFile = app.workspace.activeLeaf.view.file
  const newTitle = currentFile.basename
  if(!currentFile){
    return
  }
  const frontmatter = app.metadataCache.getFileCache(currentFile)?.frontmatter
  if(!frontmatter){
    return 
  }

  const {position: {start, end}} = frontmatter
  const fileContent = await app.vault.cachedRead(currentFile)
  const newFileContent = fileContent.split("\n").map((line, index)=>{
    if(index > end){
      return line
    }
    if(/^title: .*/.test(line)){
      return `title: ${newTitle}`
    }
    return line
  }).join("\n")
  //console.log(newFileContent)
  await this.app.vault.modify(currentFile, newFileContent);
}
```

Step 3:
- Create a quickadd macro and config it like this
- Regist this macro to obsidian command
- Restart obsidian（Important）

<img width="444" alt="image" src="https://user-images.githubusercontent.com/30640638/188559262-df020cfc-f0aa-41d3-adc0-021f59821ed4.png">

<img width="813" alt="image" src="https://user-images.githubusercontent.com/30640638/188576106-27dbadff-1da8-422e-a9ee-8f7f9eae1b1f.png">

Step 4:
- linter config

If something is not clear, please point out (this part of quickadd's documentation is an issue), it took me a lot of effort to figure out how to use macro and how to use quickadd api...😭

**Comment by pjkaufman** [comment]
That makes sense. It took me a minute to realize that this was essentially updating a file from outside the linter. I understand how this works now. I will do my best to add that to the documentation and the potential caveats that it creates with things like `yaml-timestamp`. I think I can point people in the rigbt direction on how to create custom scripts.
