### ISSUE TITLE
Rule Suggestion: Convert between Tabs and spaces

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#36]
First of all, thanks for the plugin! It's one of those little things saving a bit of time every day. 

A rule that I would find very useful is the conversion between tabs and spaces. For me personally, this would be incredibly useful because all the notes I imported from earlier apps use spaces, but the various relationship line css snippets need tabs to work.

**Comment by platers** [comment]
Would this logic work?

For every line, count the number of leading spaces, `spaces`. Replace them with `spaces/tabsize` tabs.

**Comment by chrisgrieser** [comment]
I think so. 

One consideration could be to also deal with cases where you have one more space than your tabsize, which would result in `tab+space`. But that would rather be another rule, I guess?

**Comment by chrisgrieser** [comment]
> You can pass it in as an option, the user can set `tabsize=2` in the settings. See the other rules for examples.

That would work, but it isn't ideal. Users might not consider that the tabsize set in the Linter plugin is independent from the tabsize set in the Obsidian main settings.

**Comment by platers** [comment]
I was thinking about your use case, when you are copying from external sources. It would be nice if the default tabsize was the obsidian tab size though.

**Comment by platers** [comment]
on the discord, found vault.getConfig("tabSize").

**Comment by chrisgrieser** [comment]
is this how you would do it in the `rules.ts`?
```typescript
(text: string) => {
        let tabsize = vault.getConfig("tabSize"); // <- is this I would have to do it?
        (...)
},
```

also, concerning the examples, how exactly do I have to write them, with the indention in the code code of the `rules.ts` itself?

**Comment by platers** [comment]
You should test the tabSize syntax in obsidian. If you put the repo in your plugins folder, after you run `npm run compile` you should be able to activate it in obsidian and test it.

Yep dedent deals with it, its pretty smart about the indentation.

**Comment by chrisgrieser** [comment]
okay, I have a working solution ready, but there are two problem.

---

**Problem 1:** `vault.getConfig("tabSize")` does not work, when compiling, I get the following error:
```bash
(!) Plugin typescript: @rollup/plugin-typescript TS2304: Cannot find name 'vault'.
src/rules.ts: (654:23)

654         let tabsize = vault.getConfig("tabSize");
                          ~~~~~
```
I also tried adding `import { App } from 'obsidian';` to the imports at the top of the document, but that did not solve it. 

---

**Problem 2:** So what I did for now, was to simply use `tabsize` as an option, as you suggested before. `npm run compile` works fine and all tests are passed, however, `npm run lint` has – surprise ;) – a problems with me having added tabs.
```bash
> obsidian-sample-plugin@0.12.0 lint
> eslint . --ext .ts --fix

/Users/chrisgrieser/Google Drive/File Hub/obsidian-linter/src/rules.ts
  674:13  error  Unexpected tab character  no-tabs
  676:13  error  Unexpected tab character  no-tabs

✖ 2 problems (2 errors, 0 warnings)
```

`674:13` and `674:13` are, of course, exactly the two positions where I have inserted the tabs for the example. Naturally, removing the tabs for the linter causes the test not to pass. 😝

So assume you would have to change some linter configuration before I can commit this rule?

**Comment by chrisgrieser** [comment]
Well, at least problem #2 I figured out on my own by [using inline comments to temporarily disable linting rules](https://eslint.org/docs/2.13.1/user-guide/configuring#disabling-rules-with-inline-comments). Will be adding a PR shortly.
