### ISSUE TITLE
Bug: Crash when email address added as an alias 

### ISSUE THREAD

**Issue by ScottKillen** [platers/obsidian-linter#360]
## Describe the Bug

Linter crashes if a file contains an email address as an alias

## How to Reproduce

Example to reproduce issue:

``` markdown
---
title: John & Jane Doe
aliases: [John & Jane Doe, email@example.xyz, (123) 456-7890]
cssclass: [table-lines-bright, col-lines, row-lines]
---

# John & Jane Doe

This stuff doesn't really matter.

```

Please make sure to include the rule(s) that cause the issue if applicable. If you are not sure which rule(s) may cause the issue, please attach the `data.json` file located at `<vault>/.obsidian/plugins/obsidian-linter/`.

## Expected Behavior

I expect lint4er not to crash.

## Screenshots

![image](https://user-images.githubusercontent.com/1509989/184920007-00359623-2c95-4370-a70e-bc4677598f65.png)

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

Attached data.json.txt

This may be a problem with compatibility with meta-edit. 

[data.json.txt](https://github.com/platers/obsidian-linter/files/9352373/data.json.txt)

**Comment by pjkaufman** [comment]
Thanks for reporting this. I will have to take a closer look and see what is causing this. It is likely trying to determine what to do with the email link.

**Comment by pjkaufman** [comment]
It looks like I have a fix for this. I am not sure why position would come back as undefined for the link, but with the fix in place it seems to ignore it. I guess I will wait on another bug or two before creating another release. I should have the fix on master soon.

**Comment by pjkaufman** [comment]
This issue should be fixed on master. Please feel free to let us know if it is not fixed on master or in the next release.

**Comment by ScottKillen** [comment]
Thank you!
