### ISSUE TITLE
Problem with date created time stamp

### ISSUE THREAD

**Issue by edu-zam** [platers/obsidian-linter#362]
Hello

First of all, thanks for this amazing plugin. It is very useful

I have a little problem with the Date created time stamp
In this example, the sidebar shows that my note was created at 2022-06-06. But, when I launch the linter, the plugin writes  "date created 2022-08-16".

How can I solve that?
Thanks

ps: The Date modified input is correct.

![ddays](https://user-images.githubusercontent.com/74326159/184948389-5a165336-f9e6-4934-9d75-5c215ef825b2.gif)

**Comment by pjkaufman** [comment]
I will take a look later today and see if the right datetime is coming through. It could be that the wires got crossed accidentally.

**Comment by pjkaufman** [comment]
I see the problem. The wires got crossed whwen I fixed the invalid date issue. I will issie a fix and release tonight.

**Comment by pjkaufman** [comment]
This should be fixed on master now and there should be a release with the bug fix shortly.

**Comment by edu-zam** [comment]
Thanks for your quick replay.
It works well on 1.4.3

Have a nice day.
