### ISSUE TITLE
FR: No line between quote and math block option for `Paragraph blank lines`

### ISSUE THREAD

**Issue by firinael** [platers/obsidian-linter#366]
## Is Your Feature Request Related to a Problem? Please Describe.

I use similarly styled blockquotes and mathblocks so I can join them to give the mathblock a title. The `Paragraph blank lines` option is one I always use, but it frustrates me to no end when it adds a line between my math and quote blocks.

## Describe the Solution You'd Like

Please add an option for this exception.

**Thank you for your work!**

**Comment by firinael** [comment]
## before linting with `Paragraph blank lines`
![image](https://user-images.githubusercontent.com/67032657/188023652-09959cea-2881-4d5d-abca-3afd39300b14.png)

## after linting with `Paragraph blank lines`
![image](https://user-images.githubusercontent.com/67032657/188023726-88359d0e-f22c-43ca-9b57-c1b2e34fa482.png)


I'd like the option for linting to not add the space shown in the second image. Also an option for not adding said blank line between a `quote-1` and `quote-2` would be nice.

**Comment by pjkaufman** [comment]
Coukd you provide the source values (i.e. Markdown) instead of screenshits of the live preview mode? Thanks!

**Comment by firinael** [comment]
![image](https://user-images.githubusercontent.com/67032657/188051220-a3b1b902-f0e0-4a1c-80a3-6a778fcb0cf5.png)

is this ok?

**Comment by pjkaufman** [comment]
That works as a way I can copy over the source for testing.

You mentioned something about `quote-1` and `quote-2`, but I don't see it in your example. If you don't mind explaining what a `quote-#` is, that would help as well.

**Comment by firinael** [comment]
A `quote-#` is a blockquote where the number of `>` is `#`. That is:

> this is a `quote-1`
>> this is a `quote-2`

In the Shimmering Focus theme (and probably others), `quote-2`s following `quote-1`s (like above) are used to name the source of the quote, so it'd be nice if that could be added as an option as well.

**Comment by pjkaufman** [comment]
Gotcha. I see what you mean now. I will see what can be done.

**Comment by pjkaufman** [comment]
Given how much time has passed, I do not believe that this feature will be implemented. I believe that it makes sense to focus on other issues that have been reported and other feature requests with more users indicating their desire for them. As such, I will be closing this issue.

We can reconsider this at a later time if users do indeed want this specific feature.

Do note that [ranged ignores](https://platers.github.io/obsidian-linter/usage/disabling-rules/#range-ignore) were added and can probably be used to handle this. Do note that it will turn off all Linter rules for the contents inside the ranged ignores. But it could allow for this effect. You could also use [custom regex replacements](https://platers.github.io/obsidian-linter/settings/custom-rules/#custom-regex-replacements) if you are so inclined.
