### ISSUE TITLE
FR: Non-autofixable lint rules

### ISSUE THREAD

**Issue by jqhoogland** [platers/obsidian-linter#368]
## Problem

I'd like to write a rule that lets me raises an error when I have a nested wikilink `[[Like/So]]` because I find duplicate note names is confusing and messy. Since this has the potential to be a destructive change, I'd like the linter to tell me where it occurred, rather than to make the change for me. 

Before implementing this rule, I'd need to be able to implement rules that are not autofixed.

## Solution

An obvious solution would be to introduce a panel that lists the errors encountered in the previous pass. 
For now, I'm just throwing an error in the dev tools console to warn me.

**Comment by pjkaufman** [comment]
I am working on a warning mode #272 which should allow for rules that are not fixable to be added. I just have not had a whole lot of time recently with being out sick and now trying to get back into the swing of things. I hope to have a warning mode in place in the next couple of weeks. That should satisfy adding support for rules like this.

**Comment by jqhoogland** [comment]
Yeah that totally answers it. Sorry for the duplication.
