### ISSUE TITLE
FR: Allow searching settings

### ISSUE THREAD

**Issue by Explosion-Scratch** [platers/obsidian-linter#371]
## Is Your Feature Request Related to a Problem? Please Describe.

It's so hard to find settings, please let us search

## Describe the Solution You'd Like

Search settings. This search should also include searching through the aliases given in rules.md

**Comment by pjkaufman** [comment]
I am not sure I would be able to implement a search as the UI is not my strong suite. But I would be open to PRs to add this.

**Comment by pjkaufman** [comment]
@Explosion-Scratch , you might be able to use [obsidan setting search](https://github.com/valentine195/obsidian-settings-search) to allow you to search settings until the linter is able to get something setup for either searching the rules or making it easier to find rules.

**Comment by pjkaufman** [comment]
I think I have thought up a way to add the search feature, but I will have to test it out after custom lint commands is added.

I am thinking you will be able to search all rules that are regular rules. This means that general settings and custom lint commands (a pending feature) would not be included in the search.

Programmatically I am thinking the following should work nicely:
- Add rule alias as an attribute for each rule's element
- Add a search box above the generated rule options, but below the heading. When a search is made, hide any that do not match the search.
- Rules would be displayed as all or nothing.

**Comment by pjkaufman** [comment]
I wanted to give an update on this. I am not the best when it comes to UI, but I have converted the  settings layout into a tab layout. From there, I am going to add a search settings tab. 

While I would love for this to be visually pretty, it may not be at first. But I will do my best. This looks like I may be able to add it by the end of the week. However it would not be available until the next release unless you pulled from master.

**Comment by pjkaufman** [comment]
I have not forgotten this. A search is in the works, but I decided to redesign the settings as well to help make things clearer on what rules exist and where to find them. Here is what I have so far:
![2022-09-09_20-29](https://user-images.githubusercontent.com/29898683/189885487-b8c0ac8f-86ca-4214-835f-10c85f5ce842.png)

I still need to iron out how search will work and get it and a new layout for mobile. But once that is done, I can go ahead and merge the changes.

**Comment by pjkaufman** [comment]
I just finished up search for desktop. I am working on the mobile design and searching. I will hopefully get to that today.

**Comment by pjkaufman** [comment]
This should now be added for both mobile and desktop. Mobile has a slightly different navigation, but it follows the same principles. It should be easy enough to pickup how it works with search as well. Please let us know if there are any issues with this in the next release or on master.
