### ISSUE TITLE
Add autogenerated files to the `.gitignore`

### ISSUE THREAD

**Issue by mnaoumov** [platers/obsidian-linter#376]
Files such as `docs/rules.md` are generated automatically on `npm run compile` so there is no need to keep them in the repository and track their changes.

I think all such files has to be removed from the repository and added to `.gitignore`

See related discussion in #373

**Comment by pjkaufman** [comment]
The generated files are documentation for the user or devs. Thus removing it from git would cause problems with viewing this info.

**Comment by mnaoumov** [comment]
@pjkaufman please elaborate. How does it create a problem for the devs if the file is automatically generated on `npm run compile`? For me it is similar as `npm install` that we need to call after we cloned the repo

**Comment by pjkaufman** [comment]
The issue is not for the devs, but rather for non-devs that look at the Readme or the rule documentation on github instead of in the Obsidian app.
