### ISSUE TITLE
Bug: If a label is in Chinese or English, a space will be inserted in the middle, causing the label to be broken

### ISSUE THREAD

**Issue by rRy96693** [platers/obsidian-linter#379]

**Comment by pjkaufman** [comment]
Could you add an example that reproduces this issue? I am not sure I can do anything about this unless I know what you mwan by label.

**Comment by pjkaufman** [comment]
I cannot find an exact meaning to a markdown label @rRy96693 . Without knowing what is getting modified, I will be forced to close this after a week or so. I just want to give you a heads up so it is no surprise if that happens. If I do close this, feel free to create another issue with the reproducible example in it.

**Comment by rRy96693** [comment]
like this
![image](https://user-images.githubusercontent.com/109261861/187821249-f9d903d3-d8ce-4702-835b-e006a3ff352e.png)
But I just tried without reappearing
