### ISSUE TITLE
Bug: Not sure a bug or not: plugin still works after disabled

### ISSUE THREAD

**Issue by cnyyk** [platers/obsidian-linter#383]
## Describe the Bug

Still display lint message when `Linter` plugin is disabled.

## How to Reproduce

1. Install a refresh obsidian(v0.15.9) on my macOS 12.5.
2. Install and enable community plugin: `Linter` v1.4.3 (author: Victor Tao).
3. Open options, switch on both `Lint on save` and `Display message on lint`.
4. Create a note, type something, save it, message displayed on the top right corner: `0 characters added, 0 characters removed`. `Linter` works.
5. Disabled `Linter`, edit that note then save, still displayed message on the top right corner: `0 characters added, 0 characters removed`. `Linter` still works.
6. Close that note, open any existed note and save it, the lint message still displayed.
7. Restart Obsidian app, edit and save, no lint message displayed again.

## Expected Behavior

When `Linter` disabled, there should no lint messages displayed.

## Screenshots

N/A

## Device

- [x] Desktop macOS 12.5
- [ ] Mobile

## Additional Context

Plugin Version: 1.4.3
Obsidian Version: 0.15.9

originally posted on https://forum.obsidian.md/t/not-sure-a-bug-or-not-plugin-still-works-after-disabled/42780

NOT SURE IS A BUG OR NOT.
MAYBE A BUG OF OBSIDIAN?

**Comment by pjkaufman** [comment]
This may be a bug with the linter. When it is disabled, I do not believe it is removing its on save hooks. I can see about taking a look tomorrow.

**Comment by cnyyk** [comment]
> This may be a bug with the linter. When it is disabled, I do not believe it is removing its on save hooks. I can see about taking a look tomorrow.

really appreciate.

**Comment by pjkaufman** [comment]
I went ahead and added a boolean to allow me to know when lint on save running is actually valid. There may be a better or more proper way to do this like unsetting the value of the save callback on unload, but for now a boolean should do the trick.

This should be fixed on master and in the next release. Please let us know if this is not the case. Thanks again for reporting the issue @cnyyk !

**Comment by cnyyk** [comment]
My honor to make the plugin better.
Thanks for you and the team.
