### ISSUE TITLE
Bug: move-footnotes-to-the-bottom 

### ISSUE THREAD

**Issue by mmmmmmmgo** [platers/obsidian-linter#389]
## How to Reproduce

``` markdown
xxx[^1]

[^1]:[b](http://b.com)

- [a](http://a.com)
```

after save

actual result:

```
xxx[^1]

- [b](http://b.com)

[^1]:[a](http://a.com)
```

## Expected Behavior

``` markdown
xxx[^1]

- [a](http://a.com)

[^1]:[b](http://b.com)
```

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
I see the problem. I may need to not ignore links for footnote logic as moving the values after the ignore has been set is causing the values to be replaced incorrectly. I will try removing the ignore logic and see if that fixes the issue.

**Comment by pjkaufman** [comment]
It seems to fix the problem. I have a fix coming up. It should go out with the release today.

**Comment by pjkaufman** [comment]
This should be fixed on master and the next release. Feel free to reopen the issue if it still exists on master or in the next release. Thanks for reporting the issue!
