### ISSUE TITLE
Possible rule suggestion: Reformat & Re-Index Footnotes

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#39]
Not sure whether this is something that fits with this plugin, but I think some reformatting of footnotes could also make sense. One example would to move all footnotes to the bottom after merging two or more notes, [see also here](https://github.com/SilentVoid13/Templater/discussions/365). Another case could be the re-indexing of footnotes, which unfortunately, [is not fully covered by the Tidy Footnotes Plugin](https://github.com/charliecm/obsidian-tidy-footnotes/issues/2). 

For both cases, you could argue that they belong to some footnote plugin, or maybe to the longform plugin, but I think you could also make the case for those issues belonging to the linter. When you think they fit with the Linter, I could do a PR for it?

**Comment by platers** [comment]
Sure, those seem reasonable
