### ISSUE TITLE
Timestamp format question

### ISSUE THREAD

**Issue by Calorion** [platers/obsidian-linter#391]
What format does the Timestamp function use? I'm trying to format it in ISO 8601 (which to my mind should be the default in frontmatter), like "2022-09-04T00:39:20-05:00," but I can't quite figure how.

**Comment by pjkaufman** [comment]
Based on what I am seeing here: https://momentjscom.readthedocs.io/en/latest/moment/04-displaying/01-format/
It looks like ISO 8601 is the default. However since the Linter always passes in a format that will need to be passed in as the proper format. I am looking to see if I can recreate it using the format string.

**Comment by pjkaufman** [comment]
Here is the format that moment seems to say is ISO 8601: `YYYY-MM-DDTHH:mm:ssZ`. If you use that it says that you should get the desired format.

**Comment by Calorion** [comment]
But I don't want Zulu time; I want relative to Zulu time with the offset (in my case -05:00). 

But the timestamp uses Moment? At least that gives a starting place to look. Perhaps that should be mentioned in the documentation.

**Comment by pjkaufman** [comment]
Do you mind explaining what you mean by Zulu time? If you want a specific timezone, I am not sure how you can specify that via the format. By default, it should be in your current timezone. But maybe I am misunderstanding something.

The timestamps do use moment as that is what Obsidian uses under the hood. It could be added to the documentation that that is where the format comes from.

**Comment by Calorion** [comment]
Zulu time is Greenwich Mean Time; that's what the Z on the end refers to. 

But nevermind; that works correctly. I thought that would output 2022-09-04T15:32:23Z, but it outputs 2022-09-04T11:36:07-05:00, which is what I want. Thanks. 

Oddly, however, when I paste `YYYY-MM-DDTHH:mm:ssZ` into the plugin, it pastes as `yyyy-mm-ddthh:mm:ssZ`, which gives very different results.

**Comment by pjkaufman** [comment]
Yeah. A  lowercase value is quite different for moment formats. I will see about adding it to the documentation that the format is for Moment adding a link to the format page. Hopefully that will reduce any confusion around date formatting int the furture.
