### ISSUE TITLE
Bug: YAML Key Sort does not remove blank lines

### ISSUE THREAD

**Issue by Calorion** [platers/obsidian-linter#397]
## Describe the Bug

When YAML Key Sort is active, and blank lines are present in the YAML, they are sorted to the end, not deleted as the documentation states. 

## How to Reproduce

1. Create some YAML frontmatter
2. Put blank lines in among the YAML lines
3. Lint
4. Sorting takes place according to your preferences, but the blank lines remain

## Expected Behavior

Blank lines removed

## Device

- [ ] Desktop
- [x] Mobile

**Comment by pjkaufman** [comment]
Thanks for letting me know. I need to update the documentation to say it may remove empty lines. I believe it did so consistently at one point, but with the change to get things working on iOS and the fact hat we have rules to handle empty lines in the frontmatter leads me to the decision to just update the wording.
