### ISSUE TITLE
FR: Auto-close YAML on lint

### ISSUE THREAD

**Issue by Calorion** [platers/obsidian-linter#398]
## Is Your Feature Request Related to a Problem? Please Describe.

I never want the frontmatter to be expanded unless I deliberately expand it. It gets in the way and is unattractive. I can hide it in Reading view, but not in Source or Live Preview.

## Describe the Solution You'd Like

A Rule that says when a file is Linted, the YAML is folded. 

## Describe Alternatives You've Considered

[Advanced URI](https://github.com/Vinzent03/obsidian-advanced-uri) can do this, but can only use the built-in command to fold every header, which may not be what I want.

**Comment by pjkaufman** [comment]
Thanks for thw suggestion. The linter cannot currently handle this as it is not a text change.

The linter is designed to update the text in a file. However the above is more of how Obsidian displays content which goes beyond the current scope of the linter. It may work with custom rules, but I do know that it will not work with the current setup.

**Comment by pjkaufman** [comment]
My best suggestion on this would be the following.

Grab the current master branch. Then go ahead and get the QuickAdd plugin. Once you do that, create a custom js script following the QuickAdd format that sets the current cursor location to the first line in the file. Create a maccro that runs the script and then runs the Obsidian command to fold the current line. Add thd macro as a command in QuickAdd. Then use it as a custom command in the linter. That should do what you are asking for.

Does that make sense?

**Comment by pjkaufman** [comment]
Do note that visual changes may not work well with `Lint All File` and `Lint All Files in Folder`. I am planning on making a hoisted namespace to hold information that can be used when running those two commands. Even so, it will likely only be feasible to lint the currently open file and make visual changes.

**Comment by pjkaufman** [comment]
Since this is a visual change and it out of scope for the Linter's functionality set of modifying text values, I am going to close this FR as this is likely better suited as a custom command, a script, or another plugin.

Please feel free to suggest more changes in the future.

**Comment by pjkaufman** [comment]
Maybe https://github.com/liamcain/obsidian-creases can handle the change you are looking for, @Calorion .
