### ISSUE TITLE
FR:  add a option that if YAML-title could be surrounded by " token or ' token

### ISSUE THREAD

**Issue by oldwinter** [platers/obsidian-linter#400]
## Is Your Feature Request Related to a Problem? Please Describe.

Hugo static website generater needs frontmatter YAML to be like `title: "xxxx"`, but now linter only support add title section like `title: xxxx` and can not choose if add " or ' token .

now: 
``` markdown
---
title: README
---
```

supposed:
``` markdown
---
title: "README"
---
```

**Comment by pjkaufman** [comment]
I wanted to check and make sure I understand before making any changes. Would adding an option to escape the title to `https://github.com/platers/obsidian-linter/blob/cd91ff0f03c0b752be47341ee8f198bba4a98e12/docs/rules.md#yaml-title` satisfy what you are looking for?

**Comment by oldwinter** [comment]
> I wanted to check and make sure I understand before making any changes. Would adding an option to escape the title to https://github.com/platers/obsidian-linter/blob/cd91ff0f03c0b752be47341ee8f198bba4a98e12/docs/rules.md#yaml-title satisfy what you are looking for?

thank you. it is  not the same thing. escape feature happens when yaml value contains : or " or '，but what I need is that yaml value for title key will always surrended by " or '.

**Comment by pjkaufman** [comment]
There should be an option to force the use of Yaml escape characters on certain keys if they are not an array in the rule `yaml-escape-characters`. It will go out this coming release. You can get the changes early by going ahead and manually installing this repo.
