### ISSUE TITLE
Bug: `Remove Empty List Markers` rule removes number if it's the only content in the line

### ISSUE THREAD

**Issue by mnaoumov** [platers/obsidian-linter#405]
## Describe the Bug

`Remove Empty List Markers` rule removes number if it's the only content in the line

## How to Reproduce

Consider note

``` markdown
# World War II

1939
```

And run  `Remove Empty List Markers` rule.

## Expected Behavior

The note is not changed

## Actual Behavior

`1939` is trimmed from the note as it was mistakenly considered to be a list marker, which is weird, because it is not followed by a dot `.`

**Comment by pjkaufman** [comment]
Thanks for reporting this. I will see if I can reproduce the issue and create a fix. Though if you want to create a fix in the meantime with a UT, that works as well.

**Comment by pjkaufman** [comment]
Looks like you already have a PR for it. The only issue I saw was that the check needs to be a number that ends in a period. So I put the desired regex change there.
