### ISSUE TITLE
Bug:  inline LaTeX ends with Chinese may fail for 1 inserted space 

### ISSUE THREAD

**Issue by pomopopo** [platers/obsidian-linter#407]
## Describe the Bug
version 1.4.4, when Sapce between Chinese and English option is ON, linter will insert a space between ending Chinese and $, this may cause LaTeX fails to render properly.

## How to Reproduce

before: `$M0 = 现金$`, 
after lint: `$M0 = 现金 $`, there is one redundant space added, and obsidian latex fails. (maybe this is the problem of obsidian, github can render it correctly.)

## Expected Behavior

expects that no space added before inline latex ending $ sign.

**Comment by pjkaufman** [comment]
Thanks for reporting this. This should be a simple fix for next release. Hopefully the release will go out this weekend, but that is dependent on the UI changes going smoothly.

**Comment by pjkaufman** [comment]
Should just need math inline and block added as types to ignore on this line: https://github.com/platers/obsidian-linter/blob/master/src/rules/space-between-chinese-and-english-or-numbers.ts#L31.

**Comment by pjkaufman** [comment]
This should be fixed on the master branch and will go out with the next release. If this is still an issue on the master branch or in the next release, please feel free to let us know. Thanks for reporting the bug!
