### ISSUE TITLE
FR: Fix the numbering of the numbered list

### ISSUE THREAD

**Issue by seyeeL** [platers/obsidian-linter#408]
## Is Your Feature Request Related to a Problem? Please Describe.
In live preview,if I have a list numbered 12345,I delete 3,the list will be 1245,only in preview mode,looks like 1234
I want the live preview mode to be like preview mode

## Describe the Solution You'd Like

**Please include an example where applicable:**

``` markdown
original text
```

``` markdown
expected outcome
```

**Comment by pjkaufman** [comment]
Thanks for the suggestion. I believe this ia a duplicate of #153 . Could you take a look and let me know if it would satisfy your needs? Thanks!
