### ISSUE TITLE
FR: Rule "convert-spaces-to-tabs" Support in Callouts

### ISSUE THREAD

**Issue by Beau-Yang** [platers/obsidian-linter#410]
## Is Your Feature Request Related to a Problem? Please Describe.

I'm always frustrated when trying to use the rule "convert-spaces-to-tabs" in [callouts](https://help.obsidian.md/How+to/Use+callouts). The rule doesn't work for the codes in the callouts.

## Describe the Solution You'd Like

Original code:

```markdown
> [!note]
> - A
>     - B
> - C
```

What I expect:

```markdown
> [!note]
> - A
> 	- B
> - C
```

## Other Context

According to the obsidian syntax, there should be one space after `>`. So the rule should work from the second space.

Ex. There are 9 spaces after `>`. (Line C). The rule should replace the 2-5th and 6th-9th spaces with two tabs instead of 1-4th and 5-8th spaces.

```markdown
> [!note]
> - A
>     - B
>         - C
```

**Comment by pjkaufman** [comment]
Thanks for the request. I will add a couple of things here to note about this. I generally treat callouts as quote blocks. So whatever is being done for this would also affect quote blocks.

Whether it would conform to Obsidian syntax may be in question and would require testing. Just a heads up about how this would work assuming it gets added.

**Comment by pjkaufman** [comment]
I don't see it say it has to have a space after the `>` in order to work. It will need to be tested and verified if it does work that way.

**Comment by Beau-Yang** [comment]
Yes, I think I made a mistake: it still works if there is no space after the `>`. However, I find that the rule "paragraph blank lines" will perform on it and lead to a strange result if so.

For example,

Original Text

```markdown
no space after `>`, 4 spaces
>[!note]
>- A
>    - B
>    - C

one space after `>`, 4 spaces
> [!note]
> - A
>     - B
>     - C

no space, 1 tab
> [!note]
>- A
>	- B
>	- C

one space, 1 tab
> [!note]
> - A
> 	- B
> 	- C
```

After,

```markdown
no space after `>`, 4 spaces
>[!note]

>- A

>    - B
>    - C

one space after `>`, 4 spaces
> [!note]
> - A
>     - B
>     - C

no space, 1 tab
> [!note]

>- A

>	- B
>	- C

one space, 1 tab
> [!note]
> - A
> 	- B
> 	- C
```

The rule seems to identify the single line starting with `>` without a space after it as a paragraph.

What's more, the rule "convert-spaces-to-tabs" indeed doesn't have an effect on the spaces in the callouts. The spaces in the callout blocks in the above examples are not changed to tab.

**Comment by pjkaufman** [comment]
The part about no spaces being converted to tabs in callouts makes sense since it is not technically a space at the start of a line.

As for paragraph blank lines considering something to be or not be a paragraph, that is based on whether or not the blockquote/callot has a blank line after a line without two spaces at the end or a line break if there is text. I would need to look more closely at your examples to be sure of what is happening.

**Comment by pjkaufman** [comment]
I am not seeing the scenario in question around things not being properly handled with paragraph blank lines when no space is before the callout indicator/label. However I am hitting a slight issue with getting the mentioned functionality to work.

**Comment by pjkaufman** [comment]
I believe I got this working. Ironically it starts making more sense in my head after I mention that I am having trouble getting it to work. Hopefully this will take care of this scenario.

**Comment by pjkaufman** [comment]
The change has been merged onto master. Please let us know if this has an issues on master or in the next release.
