### ISSUE TITLE
Plugin Roadmanp Github Project

### ISSUE THREAD

**Issue by pjkaufman** [platers/obsidian-linter#411]
@platers , I was thinking that maybe we should go ahead and create a github Project for this repo that would allow us to more easily track which issues are in progress, and which are done and ready for release. I was thinking it would be somewhat like the one that Obsidian Kanban has: https://github.com/mgmeyers/obsidian-kanban/projects/1. I was thinking the columns would be `Backlog`, `Queue`, `In Progress`, `Review`, `Releasing`, and `Done`.

The only problem I am seeing is that since you own the repo, you would have to create the github project for this repo since only the owner of a repo can go ahead and create a github project for any given repo for personal accounts.

Please let me know what you think about this.

**Comment by pjkaufman** [comment]
If this is not something we want to do, I can close this that is fine. I just thought it would be easier to determine priorities if we had a project roadmap for the plugin.

**Comment by platers** [comment]
@pjkaufman I created a project and invited you as admin. Thank you for your incredible contributions!

**Comment by pjkaufman** [comment]
Thanks! I will go ahead and move things around on it making sure to close out tickets and put them where they belong.
