### ISSUE TITLE
Bug: YAML Key Sort Removes Multiline Dictionaries

### ISSUE THREAD

**Issue by lyao6104** [platers/obsidian-linter#415]
## Describe the Bug

It looks like, when YAML Key Sort is on and set to sort keys alphabetically, any multiline dictionaries in the metadata will have all their keys deleted. This issue does not occur when key sorting is off, or when the "YAML Sort Order for Other Keys" option is set to "None".

## How to Reproduce

1. Make sure "YAML Key Sort" is on in Linter settings, with "YAML Sort Order for Other Keys" set to either Ascending Alphabetical or Descending Alphabetical.
2. Add a multiline dictionary to the YAML front matter (see below for example).
3. Lint file.

Or

Example to reproduce issue with

``` markdown
---
test_key: "Hello"
dictionary:
  abc: "abc"
  def: "def"
tags: 
  - Test
---
```

Upon linting, the front matter turns into this:

```markdown
---
dictionary: 
tags:
  - Test
test_key: "Hello"
---
```

## Expected Behavior

I expected the keys to be sorted in alphabetical order, without removing the dictionary's keys.

Expected output if applicable:

``` markdown
---
dictionary: 
  abc: "abc"
  def: "def"
tags:
  - Test
test_key: "Hello"
---
```

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

I tried uninstalling and reinstalling the plugin to see if that might fix things, but it didn't seem to have an effect.

It also looks like linting the file while the keys are already in alphabetical order will still delete any dictionary keys. Single-line dictionaries don't seem to be affected.

**Comment by pjkaufman** [comment]
Thanks for reporting this! This might be due to how the yaml is parsed. I will take a look this weekend and see what is going on.

**Comment by pjkaufman** [comment]
It looks to me that it does not recognize the inner properties which is likely because it was designed for limited to no nesting. I will see what can be done in this case.

**Comment by pjkaufman** [comment]
I am pretty sure I know where the issue is, but I need to make sure I can figure out the proper change and how to allow it to work properly.

**Comment by pjkaufman** [comment]
Looks like the fix is simple, so I will go ahead and move it on in. Do be careful with nesting though. The logic is not tested for multiple sets of nesting or even nesting in general.

**Comment by lyao6104** [comment]
Alright, thanks for the heads up. So I guess if there are issues in the future I should stick to single-line values?

**Comment by pjkaufman** [comment]
You can report any issues with nesting and I am happy to try to add a fix for them. I am just not actively going out of my way to test all of the nuances of the yaml key configurations.

Please feel free to go ahead and open a new issue if there is another issue with yaml key sort with yaml values. Also feel free to reopen this issue if for some reason this issue continues to exist on master or in the next release.
