### ISSUE TITLE
Order of Rule Execution

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#42]
Is there a specific order in which the rules are executed? Relevant for [this point](https://github.com/platers/obsidian-linter/pull/40#discussion_r707419523).

From your comment, I assume that it's the order in which they are listed by the user in the Linter settings, is that correct? Especially with increasing rule numbers, I think it might be worthy of consideration whether the order of rule execution is left to the user who might not factor in potential unintended effects or certain rule orders. 

My suggestion would be to stipulate to execute rules in a specific order. This avoids undesired effects like for example running  `move-footnotes-to-the-bottom` after the `consecutive-blank-lines` by an unsuspecting user.

**Comment by platers** [comment]
Yeah the user controls the order of the execution. I like giving the user control of the order, enforcing the order seems complicated. 

Maybe there could be a setting to run lint multiple times? Then the order wouldn't matter.
