### ISSUE TITLE
FR: Add a support for "spaced repetition multi-line"

### ISSUE THREAD

**Issue by mathisgauthey** [platers/obsidian-linter#421]
## Is Your Feature Request Related to a Problem? Please describe.

Hi everyone. I'm using the spaced-repetition plugin (https://github.com/st3v3nmw/obsidian-spaced-repetition#readme) and I would like to be able to add an exclusion to the linter for the multi-line cards. **Linter is breaking my multi-line cards.**

## Describe the Solution You'd Like

I'd like to add an exclusion to the line break feature of linter. The idea is that if between two paragraphs there is a **?** symbol, it doesn't do a line break. So that my flashcards aren't broken if I lint my note.

**Please include an example where applicable:**

Example:

``` markdown
paragraph 1 (question)
?
paragraph 2 (answer)
```

Results now:
``` markdown
paragraph 1 (question)

?

paragraph 2 (answer)
```

Expected result after feature added:
``` markdown
paragraph 1 (question)
?
paragraph 2 (answer)
```

## Describe Alternatives You've Considered

I don't see alternatives.

## Additional Context

I think this is clear enough. But I can explain more if asked.

**Comment by pjkaufman** [comment]
Thanks for the input! This seems like it would be covered by the custom ignore rules that are slated to be added (#334).

**Comment by mathisgauthey** [comment]
I'd like to add that the spaced-repetition adds a line after the flashcard entry like that : 
```
This is a ==random== tip.
<!--SR:!2022-11-26,4,270-->
```
My issue is that the `<!--SR:!2022-11-26,4,270-->` line is getting displaced, it ends up like that : 
```
This is a ==random== tip.

<!--SR:!2022-11-26,4,270-->
```

Hence the card countdown is broken. If something could fix both of these with custom plugin integrations it would be amazing !

**Comment by mathisgauthey** [comment]
On an added note, I found a way to make it work without breaking anything ! 
You just need to add the following setting in the spaced repetition plugin : 
![image](https://user-images.githubusercontent.com/46576952/204211548-cfeee3d4-14e7-447a-aa91-bd0fd479ab13.png)

**Comment by pjkaufman** [comment]
This should be feasible to implement using the new ranged custom ignores: #725 .
