### ISSUE TITLE
Bug: Date modified value gets duplicated

### ISSUE THREAD

**Issue by Skjolnir** [platers/obsidian-linter#426]
## Describe the Bug

`date modified` yaml value gets duplicated on saving, but appears as `date data modified`:

```markdown
---
type: 
status: 
tags: 
aliases: 
cssclass: 
publish: false
date date modified: 2022-09-27 14:30
date created: 2022-09-27 13:39
date modified: 2022-09-27 14:34
---
```

## How to Reproduce

1. Download and open the repro vault: [LinterRepro.zip](https://github.com/platers/obsidian-linter/files/9655794/LinterRepro.zip)
2. Open the TestFile
3. Save using Ctrl + S
5. Save using Ctrl + S again
6. See a second duplicated line
7. Save using Ctrl + S again
8. see an error message

## Expected Behavior

no duplication

Expected output if applicable:

``` markdown
---
type: 
status: 
tags: 
aliases: 
cssclass: 
publish: false
date created: 2022-09-27 13:39
date modified: 2022-09-27 14:30
---
```

## Screenshots

![image](https://user-images.githubusercontent.com/5647119/192527911-49dd3930-f559-4bb1-a29e-6bf15985581c.png)

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

See rules in repro vault. Does not happen with default rules.

**Comment by pjkaufman** [comment]
This seems to be an issue with removing a yaml key. I need to experiment with this to be certain, but it looks like it is accidentally removing a value from the yaml incorrectly.

**Comment by pjkaufman** [comment]
I need to work out some kinks on the solution I am working towards, but it should fix this issue if it does not break the other scenarios.

**Comment by pjkaufman** [comment]
I found the cause of the issue and it should be resolved on master. I plan to release the changes this weekend along with some other changes as well. Please let us know if the issue is not resolved on master or in the next release.
