### ISSUE TITLE
FR: Exceptions block in Move Tags to YAML rule

### ISSUE THREAD

**Issue by Calorion** [platers/obsidian-linter#429]
## Is Your Feature Request Related to a Problem? Please Describe.

Some tags perform specific functions, such as #tasks for the [Tasks](https://github.com/obsidian-tasks-group/obsidian-tasks) plugin, and need to not be moved to the frontmatter. And I use #quote on a paragraph level, not a document level, for instance. 

## Describe the Solution You'd Like

An exceptions block to list tags the user does not want moved.

## Additional Context

__Originally posted by @Calorion in https://github.com/platers/obsidian-linter/issues/246#issuecomment-1255462974__

**Comment by pjkaufman** [comment]
I have gone ahead and added this since it was not too big a change. It should go out with the next release and be on master now. Please let us know if there is some issue with the changes or if it does not satisfy the feature request.
