### ISSUE TITLE
FR: Add Escaping for the YAML Title Key

### ISSUE THREAD

**Issue by julianmueller** [platers/obsidian-linter#440]
As described in #341 my request for a rule regarding the [YAML Title](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#yaml-title) is the follwing:

- after inserting the H1 (or filename if nonexistent) into the yaml key (eg `title`) add an escaping sequenz around the text from the H1 (as done in rule: https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#escape-yaml-special-characters)
- maybe also split the option for the source into two parts:
    - take first H1 and put it into the yaml key
    - if no h1 is present, fall back and use the filename

Thanks to @pjkaufman for the suggestion of a new FR and the work already done in #341!

**Comment by pjkaufman** [comment]
Looks like `tag` and `aliases` styles and escape character would be the 3 values that would need pulling out to cut down on excess settings options and allow an easier update for character escaping. For the tags and alias rules, the following is how the condensed setting value should be decided:
If there is only one selected rule that is active with the format specified, then use that. If there are multiple or there aren't any selected, use the Obsidian specific formats first, then the regular markdown formats.

**Comment by pjkaufman** [comment]
Another value that would need refactoring is whether to escape using double quote or single quote.

**Comment by pjkaufman** [comment]
I think I got the refactor working. Now I need to move the force escape logic to its own rule and then go ahead and have it run at the end before the other special ending rules.

**Comment by pjkaufman** [comment]
I think the copy rule portions are properly setup and the rules has been created. Now to just test and verify that it is working. But that will have to wait until Friday or Saturday.

**Comment by pjkaufman** [comment]
I fixed an issue I found. I will go ahead and move this over to in progress and aim for a release either tomorrow or this weekend. This past week got me a little all over the place.

**Comment by pjkaufman** [comment]
This should go out with the coming release. Please let us know if it does not work or if there are any issues with it.
