### ISSUE TITLE
FR: smart quotes

### ISSUE THREAD

**Issue by berot3** [platers/obsidian-linter#442]
## Describe the Solution You'd Like

Using smart opening quotes for text.

**Please include an example where applicable:**

``` markdown
click on "Options"
```

``` markdown
click on “Options”
```

## Additional Context

This is maybe not wanted for everyone in every case, but I think its nice to have :)

**Comment by pjkaufman** [comment]
Thanks for putting in the request! This is either the same as #399 or the opposite of it from what I gather.

**Comment by Calorion** [comment]
Pretty sure it's the same.

**Comment by pjkaufman** [comment]
I am going to close this as a duplicate, but please reopen this if it is not a duplicate since the feature addition suggested would be to be able to select the style of quotes to have in non-code/math blocks or the yaml since those do not recognize specific quotes as valid.

**Comment by berot3** [comment]
Yes, thanks, that's the one. Did not find it on a quick search.
