### ISSUE TITLE
FR: Move tags to Yaml - option to delete tags completely

### ISSUE THREAD

**Issue by blackpeasy** [platers/obsidian-linter#444]
As of now there is only an option to `Remove the hashtag from tags in content body`

I would like to request an option to `Remove the tags in content body completely`.
- So all the text is deleted in the body and after the link, the tags only exist in the yaml front matter.

**Comment by pjkaufman** [comment]
Thanks for this request! This looks simple enough. I will see about adding it for the next release. What do you mean by "after the link"? I am not entirely sure what that means and would need to know in order to be certain that the situation would be handled fully.

**Comment by blackpeasy** [comment]
Nice!
Ahh it was a typo - should be "after the lint"

**Comment by pjkaufman** [comment]
I am taking a look today. I got a little side tracked with my break from the front-end work. I will hopefully have it and the release ready today.

**Comment by pjkaufman** [comment]
The changes should be ready for this now. I am hoping to be able to get this out soon. I am just running the precursor tests for release to verify that none of the rules that are active for my vault cause any weird looking results. It is not perfect, but it should do the trick for verifying that several of the rules are just fine. Though I do wish there was a better IT that I could run.

**Comment by pjkaufman** [comment]
I think I fixed the issue I noticed and all things seem to be working as expected, so I will push up the changes for this and then go ahead and create a release.

**Comment by pjkaufman** [comment]
The changes for this should now be on master with a release coming either today or early tomorrow since I need to create the release notes first. Feel free to pull this in from master in the meantime.

Feel free to let us know if there is an issue with the feature.

**Comment by blackpeasy** [comment]
Thanks a lot! I will test it on release and return if I experience any bugs.
