### ISSUE TITLE
Bug: Lint a file takes the create date and uses that as filename.

### ISSUE THREAD

**Issue by dredhorse** [platers/obsidian-linter#449]
When I lint a file the create date is taken and used as filename.

This happens for:
title
alias
linter-yaml-title-alias

see before:

![2022-10-11 18-24-58 - Privat - Obsidian v0 15 6 ](https://user-images.githubusercontent.com/1054143/195147344-695379f7-a97b-4e0f-9b16-43666c213c79.png)

and after:
![2022-10-11 18-25-51 - test - Privat - Obsidian v0 15 6 ](https://user-images.githubusercontent.com/1054143/195147507-d660e1d6-6ea5-4f1c-ac78-0485af6f33c2.png)

**Comment by pjkaufman** [comment]
Thanks for reporting this!
This looks like it is a bug with the links present in the heading since the text is often ignored. Could you provide a minimum reproducible example? I see the images, but that is not enough to know how this is happening without some text to pull in that causes the issue.

**Comment by dredhorse** [comment]
the problem is the # [[test]] changing that to # test fixes it.

`---
UUID: 20221010205858
DateStamp: 2022-10-10
Updated: 
publish: false
language: de
Vault: Privat
title: "test"
tags: 
aliases: []

---
> [!METADATA]-
> - Created:: [[2022-10-10]]
> - Related::
> - Summary::
> - Content:: 
> - up:: 
> - Topics:: 
> - Type:: #type/note/normal
> - Status:: #status/seed 
> - **Related**:: 
> - **Reference**::
---
# [[test]]


## Daily Log

Dies ist ein Test
- mal schauen
- wie das aussieht
CSS Styling ist doof.

## Und der Rest

das ist der Rest


#test

`

**Comment by pjkaufman** [comment]
Ok. I am pretty sure I see the problem. If I no longer ignore linka for thia rule it should start working again.

**Comment by dredhorse** [comment]
cool, looking forward to it.

**Comment by pjkaufman** [comment]
This change should now be on master. Please let us know if the issue is not fixed on master or in the next release.

**Comment by dredhorse** [comment]
thanks will take a look.
The metadata block is an idea I grabbed from somewhere.. I want to put data in there which I need, but don't want to see (looking forward to a way to hide the yaml in edit / preview mode).
Some people put the data at the end, but I like it at the top so that I can easily access it in larger notes and my notes have the correct data. (you don't want to see my templater files 😀 ).
Having H1 as a link is also coming from a lot of templates.
