### ISSUE TITLE
Bug:  No setting about "empty-line-around-math-blocks"

### ISSUE THREAD

**Issue by wenbopeng** [platers/obsidian-linter#452]
## How to Reproduce
![image](https://user-images.githubusercontent.com/74350447/195835663-dc598423-a3d3-460c-be31-e4e9d2536d46.png)
![image](https://user-images.githubusercontent.com/74350447/195836153-0ad5bb21-858b-483e-a500-e005245f2c11.png)

**Comment by pjkaufman** [comment]
@wenbopeng, are you using the version from the master branch of this repo or are you using the latest release?

**Comment by pjkaufman** [comment]
It looks like you are not on master based on the image as thetab for pasting rules. As a result, I am going to close this issue. The setting you are looking for should be released this next release. If for some reason you are using the latest from master, please reopen the issue.

**Comment by wenbopeng** [comment]
> 

I installed the latest version from the plugin store 

![image](https://user-images.githubusercontent.com/74350447/195978302-00264a10-e0d0-42b0-96ac-389515321b34.png)

**Comment by pjkaufman** [comment]
Gotcha. Using the latest release doesn't ensure you have all rules on master. Changes are released at times and the associated docs are updated without those changes.
