### ISSUE TITLE
How not to generate spaces to the left and right of the "-"

### ISSUE THREAD

**Issue by zhl111** [platers/obsidian-linter#453]
## Is Your Feature Request Related to a Problem? Please Describe.

the plugin `linter`  add spaces automatically：`多内拉 -h- 梅多斯 (Donella H. Meadows)`。
I wish it was a person's name without spaces：`多内拉-h-梅多斯`。

The names of people in English, such as `Donella H. Meadows`, are customarily represented in Chinese as `多内拉•h•梅多斯`. Here `•` needs to be switched to full-angle mode, which is very inconvenient, so I used to use `-` instead. But the plugin `linter` will add spaces automatically, I want to just ignore the spaces around `-` in the middle of the person's name while keeping the other added spaces, how do I do that?

The function of this request is similar to the following link：
- [文件路径会自动增加空格，这能否像网址一样排除在外？ · Issue #78 · Yaozhuwa/easy-typing-obsidian](https://github.com/Yaozhuwa/easy-typing-obsidian/issues/78 )  2022/10/15

**Comment by pjkaufman** [comment]
Hey @zhl111 . Thanks for the question. Do you use the rule https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#space-between-chinese-and-english-or-numbers?

If so, you will need to wait until #334 is added.

**Comment by pjkaufman** [comment]
The only other way to do what you are looking for is to turn off the rule https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#space-between-chinese-and-english-or-numbers or to disable it for the files in question until custom ignore rules are available.

**Comment by pjkaufman** [comment]
It looks like this may also be related to #493 .

**Comment by pjkaufman** [comment]
I believe this change was just added to master with the most recent change to how the removal of spaces around characters was made. You should be able to disable the dashes and em dashes from having space removed around them or in your case, you should be able to enable it. It may work at removing the spaces entirely https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#remove-space-around-characters.

If you do enable it, be careful as it will affect it in all files that the Linter affects.

Please let us know if this allows for the closing of this question.

**Comment by pjkaufman** [comment]
@zhl111 , have you been able to remove the spaces around `-` in your files using the rule for removing space around characters?

**Comment by pjkaufman** [comment]
I see that no comment has been made on this ticket in a while, so I am going to close it.
