### ISSUE TITLE
Setting for Documents never to lint

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#46]
Especially when using the "lint on save" setting, it is easily to accidentally lint a document that is not meant to be linted (e.g. templates or templater scripts, which annoyingly are still saved as `.md` ...).

May be setting to never lint certain files might make sense? This would prevent accidental linting. [The Filename Header Sync Plugin](https://github.com/dvcrn/obsidian-filename-heading-sync) has pretty much implemented this for files where headings should not be synced with the filename, I assume a bigger part of that code can be re-used.

**Comment by platers** [comment]
Yeah, I was thinking about implementing a system like [eslint](https://eslint.org/docs/user-guide/configuring/rules) for ignoring lines, files. It seems quite complicated though.

I think a YAML setting to disable all rules or only some rules would work for most cases.
