### ISSUE TITLE
Feature Request: Sherlock tidy-footnotes plugin?

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#466]
I tried adding the command from the [tidy footnotes plugin](https://obsidian.md/plugins?id=obsidian-tidy-footnotes), as an extra custom command. However, it seems the plugin leaves extra blank lines at the end of a file if there are no footnotes in a note. even with the rule enforcing exactly one line break at the end of a file, somehow there are still the extra blank lines added at the end.

Theoretically, this could be an issue for the tidy footnotes plugin, but it does not look very active anymore. Moreover, the linter already has footnote linting rules, making the addition actually useful for users not looking for extra plugins. So the tidy footnote code could maybe be simply sherlocked for a simpler (and probably more bug free) user setup?

**Comment by pjkaufman** [comment]
This is also likely related to #359 which I am not sure I fully understand either.

**Comment by chrisgrieser** [comment]
yeah it's the issue discussed in #359, that the current linting rule does *not* preserve the relation between key and footnote definition. The issue mostly concerns duplicate keys. Given: 

```
bla[^1], bla[^1], bla[^2]
[^1]: bla
[^1]: bla
[^2]: bla
```

tidy footnotes will result in
```
bla[^1], bla[^1], bla[^2]
[^1]: bla
[^2]: bla
```

while the re-indexing rule will result in:
```
bla[^1], bla[^2], bla[^3]
[^1]: bla
[^2]: bla
[^3]: bla
```

The re-indexing rule only really makes sense in the context of multiple notes being merged into one (its original purpose, which is now a bit obsolete since we have longform compile options), while tidy footnotes is intended to sort sort footnotes when you are working in one note and have changed the order / deleted a footnote while writing.

**Comment by chrisgrieser** [comment]
Since reindex-footnotes is a bit obsolete by now, I think I would replace that rule with the mechanism from tidy footnotes

**Comment by pjkaufman** [comment]
Gotcha. So what is being asked as a rewriting of the re-index rule that would have the following functionality:
- Get a list of all distinct footnote keys
- Replace each distinct key with a re-indexed value based on order in the document

Does that sum up the issue at hand or am I missing something else?

**Comment by chrisgrieser** [comment]
> Get a list of all distinct footnote keys
Replace each distinct key with a re-indexed value based on order in the document

yes, I think so. The key issue solved by tidy footnotes is essentially to sort and re-enumerate the footnotes in case of you deleting a footnote while writing or you changing the order of occurence. Also, it sorts the definitions at the end. For the tidy-footnotes usecase, the most important thing would be that the pairing of key and definition is preserved, to not loose any information (something the current re-indexing rule does not do, since it's meant to deal with duplicate keys/definitions)

**Comment by pjkaufman** [comment]
Gotcha. Thanks for the update. I was not present for its initial writing so this info is helpful. Did we also want to ignore the non-numeric footnote keys for the reindexing or at least have that be an option?

**Comment by pjkaufman** [comment]
I guess that #359 wants to also add an option to index based on the order found at the end of the document instead of the order in the actual document itself.

**Comment by pjkaufman** [comment]
This should now be on master and will go out with the next release. Please let us know if this is not fixed or if there is some other issue with footnotes.

@chrisgrieser , please let me know if for some reason there is some kind of functionality from `tidy-footnotes` that I missed when I added updated `re-index footnotes`. I believe I covered them all based on what was said here. But since I used my own method of implementing what tidy notes is doing, it may behave differently.

**Comment by chrisgrieser** [comment]
sure, will definitely check it out once it's available in the next release :)

**Comment by pjkaufman** [comment]
Sounds good. I hope to do a release tonight, but one of the changes I am making is kicking my butt right now. I am not sure what exactly I am doing wrong in it. But I will figure out something eventually for it.

**Comment by chrisgrieser** [comment]
okay, I gave it a quick spin, and all the scenarios I tried seem to work fine. 

Only issues are when there are more keys than definitions or more definitions than keys, both of which are scenarios where there is no good solution. So I think simply showing a notification than like it does right now seems like the reasonable approach.

a few minor things regarding the plugin's communication:
- the notification time for when there is an issue with footnotes is too short, it disappears after a sec, not giving me enough time to read it
- when there are more keys than there are footnotes (i.e., orphan keys), there is no notification / communication at all. It could make sense to turn the key into `[ref missing]` like with wikipedia? when there are footnotes without corresponding key, maybe do the same? 🤔 
- in the settings for `Re-index footnotes`, it should emphasize that this rule now does something different than before, maybe even with a striking color or something. It's all too easy to miss this change if you are a long time user

**Comment by pjkaufman** [comment]
> okay, I gave it a quick spin, and all the scenarios I tried seem to work fine.
> 
> Only issues are when there are more keys than definitions or more definitions than keys, both of which are scenarios where there is no good solution. So I think simply showing a notification than like it does right now seems like the reasonable approach.
> 
> a few minor things regarding the plugin's communication:
> 
> * the notification time for when there is an issue with footnotes is too short, it disappears after a sec, not giving me enough time to read it
> * when there are more keys than there are footnotes (i.e., orphan keys), there is no notification / communication at all. It could make sense to turn the key into `[ref missing]` like with wikipedia? when there are footnotes without corresponding key, maybe do the same? thinking
> * in the settings for `Re-index footnotes`, it should emphasize that this rule now does something different than before, maybe even with a striking color or something. It's all too easy to miss this change if you are a long time user

Thanks for the feedback. 

I think that the notification time for errors can be increased to require the user to click it or have it be something like 5 seconds or more. I am not sure if there is a good timeframe for that.

For handling orphaned refs, that is something that is a little harder to do, but I can add a check for that. I guess it is not too bad to do since it is just going over the list of footnote references and checking if they existing in the footnote key set. So that can be added.

I am not sure on a good way to make the `re-index footnotes` change visible easily. The reason being while descriptions can have a color added to them it gets a bit tricky to properly display that value with how things are setup if it is for a regular rule. I can bold the description for the time being if that would help. I am not sure on changing the color as that may not be feasible.

**Comment by pjkaufman** [comment]
Added user click based timeout to all errors that the Linter encounters.
