### ISSUE TITLE
Bug: "Capitalize headings" incorrectly capitalizes

### ISSUE THREAD

**Issue by Calorion** [platers/obsidian-linter#484]
## Describe the Bug

"Capitalize headings—first letter" rule is perhaps a bit too literal. It will capitalize the first letter even if it preceded by several other characters. This is usually not desirable. 

### Input

`### 1.0.0-b.4`

### Expected output

`### 1.0.0-b.4`

### Actual output

`### 1.0.0-B.4`

## Device

- [ ] Desktop
- [x] Mobile

**Comment by pjkaufman** [comment]
I have a simple fix for this that I am pushing up. It was actually not that bad to fix and it helped simplify the regex a decent bit because it made me reevaluate how this was working to account for just the minimum regex needed for it to function properly.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release. Please let us know if that is not the case.
