### ISSUE TITLE
FR: list space style

### ISSUE THREAD

**Issue by rea1shane** [platers/obsidian-linter#485]
See [google markdown style guide](https://github.com/google/styleguide/blob/gh-pages/docguide/style.md#nested-list-spacing)

before:

```
1. item 1
  1. item 1-1
  2. item 1-2
3. item 2
4. item 3

- A
  - x
  - y
- B
- C
```
after:

```
1.  item 1
    1.  item 1-1
    2.  item 1-2
3.  item 2
4.  item 3

-   A
    -   x
    -   y
-   B
-   C
```

**Comment by pjkaufman** [comment]
By chance is this a duplicate of https://github.com/platers/obsidian-linter/issues/178?

**Comment by rea1shane** [comment]
> By chance is this a duplicate of #178?

yes, sorry for the duplicate.
