### ISSUE TITLE
FR: blockquote style

### ISSUE THREAD

**Issue by rea1shane** [platers/obsidian-linter#487]
before:

```
>A
>>B
>>>C
```

after:

```
> A
> > B
> > > C
```

**Comment by rea1shane** [comment]
another fr is blockquote increasement, like:

before:

```
> A
> > > > > B
> > > C
```

after:

```
> A
> > B
> C
```

if you think its necessary, I will create a separate issue.

**Comment by pjkaufman** [comment]
The following issue seems to duplicate this request: https://github.com/platers/obsidian-linter/issues/591

This FR seems to be asking for the following:
1. A rule that makes blockquotes have a space after the `>` in any blockquote entry (I am assuming that is supposed to be the case for empty blockquote lines as well.
2.  The ability to make sure blockquotes increment by 1 level at a time.

**Comment by pjkaufman** [comment]
I am going to create a second issue for you for the blockquote incrementing as that is something that will likely be tackled separately from this. It is much easier to break these apart and track them that way.

**Comment by pjkaufman** [comment]
The related issue is now #719 .

**Comment by pjkaufman** [comment]
The changes for adding blockquote style to the Linter should be on master and go out with the next release which will hopefully be tomorrow. Please let us know if there are any issues with the rule or any things that could be added to it to make it better.

**Comment by rea1shane** [comment]
Thanks for your hardworking.
