### ISSUE TITLE
Bug: css color definitions are confused as tags when transferring tags to front matter

### ISSUE THREAD

**Issue by HanumanTFM** [platers/obsidian-linter#489]
## Describe the Bug

I am using linter and setting it up to move tags to the frontmatter.

highlightr plugin uses the syntax 

`<mark style="background: #FFB8EBA6;">some text</mark>`
linter confuses the color definition as tags and extracts the color declaration along with all the trailing characters 
resulting in

`---
tags:
  - FFB8EBA6;">text</mark>
aliases:
---`

## How to Reproduce
Install linter+highlightr
set up linter to move tags to frontmatter
run linter

**Comment by pjkaufman** [comment]
Thanks for reporting this. I have a simple fix for it, but it will not account for the contents of `<style></style>` as there is not a really good way to ignore that without potentially ignoring valid tags.

**Comment by pjkaufman** [comment]
Please let us know if this is not fixed on master or in the next release.

**Comment by HanumanTFM** [comment]
Thank you!
I appreciate it 🙏

**Comment by HanumanTFM** [comment]
> Please let us know if this is not fixed on master or in the next release.

The issue has been resolved. Thank you for the swift fix!
