### ISSUE TITLE
FR: Rule to replace triple brackets by double brackets in content

### ISSUE THREAD

**Issue by jayambede** [platers/obsidian-linter#490]
## Is Your Feature Request Related to a Problem? Please Describe.

1. Every time you just have a typo of 3 (or more) brackets. Obsidian will see, there is a link, but it will point to an non existent file.

2. I do, for research purposes, sometimes download wikipedia-articles using the fantastic md-downloader plugin by death-au. Afterwords I do link it to the notes and concepts I am working on, or that already exist. I mostly use the unlinked mentions for this. The problem is, that some of the concepts in my vault (that I want to link to) are also external links in the new wp-note (this goes for all variations of the links in the new note). If I then then link such a concept to a note, using the buttons in the unlinked mentions pane, the concept is replaced by [[concept]]. This leads to this: [[[concept]]] in the note, which Obsidian interprets as a link in the form of '[concept', which obviously only leads to an empty (new) file. To obtain proper internal links, I have to do a search and replace ( [[[ to [[, and ]]] to ]] ) manually at least once for any of these notes.

## Describe the Solution You'd Like

I would like to have a rule in linter, that does the search and replace part automatically either on closing the note or on cue.

**Please include an example where applicable:**

``` markdown
[[[concept]]]
```

``` markdown
[[concept]]
```

## Describe Alternatives You've Considered

Doing it manually, which is a bit annoying.

## Additional Context

None

**Comment by jayambede** [comment]
Hey @pjkaufman, I tried it and got the following result:
Before: [[[John Locke]]]

Linting with \[\[\[ _ g _ \[\[ and \]\]\] _ g _ \]\] as regex rules

Result: \[\[Locke, John – Wikipedia|John Locke\]\]

So the replacement itself worked fine, but the desired result ( [[Locke, John – Wikipedia|John Locke]] ) is somehow still not right.

Am I doing something wrong?

**Comment by pjkaufman** [comment]
> Hey @pjkaufman, I tried it and got the following result: Before: [[[John Locke]]]
> 
> Linting with [[[ _ g _ [[ and ]]] _ g _ ]] as regex rules
> 
> Result: [[Locke, John – Wikipedia|John Locke]]
> 
> So the replacement itself worked fine, but the desired result ( [[Locke, John – Wikipedia|John Locke]] ) is somehow still not right.
> 
> Am I doing something wrong?

I think I am missing some context around what you are trying to do. Could you add a before and after as well as expected snippet, so I can better visualize what you mean? Right now I am seeing something like the following for what you are saying is your before, after, but wanted

before:
```markdown
[[[John Locke]]]
```

after (I am not sure how this change would have been made by the regex in question):
```markdown
[[Locke, John – Wikipedia|John Locke]]
```

desired:
```markdown
[[Locke, John – Wikipedia|John Locke]]
```

If my understanding is right the two regexes used should have inputs as follows
| Find | Flags | Replace |
| ----- | ------ | -------- |
| \\[\\[\\[ | g | \\[\\[ |
| \\]\\]\\] | g | \\]\\] |

All this does is replace a triple bracket with a double bracket which is, if I am not mistaken, the request made by this feature request.

Please let me know if my understanding of any of this is off.

**Comment by jayambede** [comment]
Sorry for the mistake, I forgot to add the code-brackets ... Now it should be clearer ... 

And: thanks a lot (in advance) for your help and this Plugin!!

**Comment by pjkaufman** [comment]
> Sorry for the mistake, I forgot to add the code-brackets ... Now it should be clearer ...
> 
> And: thanks a lot (in advance) for your help and this Plugin!!

I think I told you the wrong replace values. Could you try using `[[` and `]]` instead of `\[\[` and `\]\]`. The escaping of the brackets may be unnecessary in the replace value.

**Comment by jayambede** [comment]
Yes! That works. Thank you very much for your help!! This saves me alot of time and work.

**Comment by pjkaufman** [comment]
I am glad to hear that. If the use case for this feature request is satisfied, I will go ahead and close it.

**Comment by jayambede** [comment]
Yes, works for me perfectly! Thanks
