### ISSUE TITLE
FR: `Remove Space around Fullwidth Characters` should be more configurable

### ISSUE THREAD

**Issue by mnaoumov** [platers/obsidian-linter#493]
## Is Your Feature Request Related to a Problem? Please Describe.

Currently rule `Remove Space around Fullwidth Characters` just removes spaces around some set of characters. 

My concern are `en dash` (`–`, `U+2013`) and `em dash` (`—`, `U+2014`) characters.

The [rules](https://www.scribbr.com/language-rules/dashes/) about spaces around those characters differ. Some guides recommend to don't have spaces around those characters, other recommend to have spaces.

## Describe the Solution You'd Like

We need to be able configure the rule to exclude certain characters from removing spaces.

**Please include an example where applicable:**

``` markdown
— Hi, John!
— Hi, Mary.
```

in such dialogue cases it is very natural (for me) to keep the space after the `em dash`.

**Comment by pjkaufman** [comment]
Thanks for the input. I can put this in the backlog and it can be addressed as the current issues get worked through. But feel free to make this change as well if you would like it sooner.

**Comment by pjkaufman** [comment]
Do you mind explaining what is meant by making it more configurable? The values it hits are specified via regex. Are you suggesting that I go ahead and swap that out for a list of characters in a text area that users can add to or remove from?

Thanks for helping me better understand what the idea of configurability looks like in this case.

**Comment by pjkaufman** [comment]
This issue should now be fixed on master. Please let us know if it is not fixed on master or in the next release.
