### ISSUE TITLE
FR: header Increment start at level 2

### ISSUE THREAD

**Issue by thomashoggard** [platers/obsidian-linter#494]
## Is Your Feature Request Related to a Problem? Please Describe.

Within the core config you can now specify the title to be inlined within your note.  This removes the need of the "File Name Heading" option.  This has a side effect where Header Increment doesn't see a level 1 heading anymore and will convert level 2 headings to level 1.   I want to keep the Header Increment option enabled since it adds a lot of value, but also would like to use the default Obsidian setting for the title.

## Describe the Solution You'd Like

Is it possible to add an option to check if the obsidian title option is set, and if header increment is set to start heading levels at 2?

**Comment by pjkaufman** [comment]
I believe that this is a duplicate of #412 . Please let us know if this is different.

**Comment by thomashoggard** [comment]
Opps, I didn't see it when I searched, sorry about that.  I'll go ahead and close this ticket.
