### ISSUE TITLE
Bug: Pasting certain urls will cause it to freeze

### ISSUE THREAD

**Issue by 3dot141** [platers/obsidian-linter#497]
## Describe the Bug

rt
## How to Reproduce

paste **\[github.com/NewbeeFE\](https://link.juejin.cn?target=https%3A%2F%2Fgithub.com%2FNewbeeFE "https://github.com/NewbeeFE")**
and then obsidian will not response until closed it

## Expected Behavior

can paste url normally

## Device

- [ ] Desktop

**Comment by pjkaufman** [comment]
Thanks for reporting this. I could paste the URL just fine on mobile. I will check desktop shortly though I am not sure if you mean pasting the URL or pasting the markdown link.

**Comment by pjkaufman** [comment]
Well. Pasting the markdown link does fail. I will check what is going on there.

**Comment by pjkaufman** [comment]
Have you tried to paste it using the Obsidian Linter command to paste the text as normal?

**Comment by pyxelr** [comment]
@3dot141: I am observing the same issue since some time. For example, pasting such a hyperlink freezes both Windows and macOS Obsidian clients (I didn't try Linux yet):

```text
[https://](https://apples.branches.trees.com)
```

@pjkaufman: I have just tried the option `Linter: Paste as Plain Text & without modifications` and it didn't cause Obsidian to freeze upon pasting the troublesome hyperlink.

**Comment by pjkaufman** [comment]
> @3dot141: I am observing the same issue since some time. For example, pasting such a hyperlink freezes both Windows and macOS Obsidian clients (I didn't try Linux yet):
> 
> ```
> [https://](https://apples.branches.trees.com)
> ```
> 
> @pjkaufman: I have just tried the option `Linter: Paste as Plain Text & without modifications` and it didn't cause Obsidian to freeze upon pasting the troublesome hyperlink.

Gotcha. This is likely an infinite loop in one of the pasting rules. Do you have all of the paste rules on?

**Comment by pjkaufman** [comment]
Well. I am not seeing where this would actually happen in the linting rules themselves. I guess that means it would reside in the logic prior to running the rules. I will have to take a closer look.

**Comment by pyxelr** [comment]
@pjkaufman: I am keeping all the pasting rules disabled. Nevertheless, I have just tried will all the paste rules applied, and Obsidian still freezes.

**Comment by pjkaufman** [comment]
> @pjkaufman: I am keeping all the pasting rules disabled. Nevertheless, I have just tried will all the paste rules applied, and Obsidian still freezes.

Gotcha. So it must be something in the logic prior to running the paste rules that causes this. Thanks for taking a look. The paste logic that is run prior to running the paste rules is always active. I could always short circuit if I were 100% certain that no paste rules were on, but it is likely better to figure out the cause of the infinite loop or whatever seems to stall.

**Comment by pyxelr** [comment]
@pjkaufman: Thanks a lot! I cannot wait to give it a try in the next release.
