### ISSUE TITLE
Bug: `Space between Chinese and English or numbers` not working any more

### ISSUE THREAD

**Issue by dutry** [platers/obsidian-linter#498]
## Describe the Bug

The function `Space between Chinese and English or numbers` used to work, but not this time, even when I have restarted Obsidian.

## How to Reproduce

1. Turn on the `Space between Chinese and English or numbers` in the setting of Linter
2. Run `lint the current file`

Please make sure to include the rule(s) that cause the issue if applicable. If you are not sure which rule(s) may cause the issue, please attach the `data.json` file located at `<vault>/.obsidian/plugins/obsidian-linter/`.

```json
{
  "ruleConfigs": {
    "Escape YAML Special Characters": {
      "Escapes colons with a space after them (: ), single quotes ('), and double quotes (\") in YAML.": false,
      "Default Escape Character": "\"",
      "Try to Escape Single Line Arrays": false,
      "Force Yaml Escape on Keys": ""
    },
    "Format Tags in YAML": {
      "Remove Hashtags from tags in the YAML frontmatter, as they make the tags there invalid.": false
    },
    "Format Yaml Array": {
      "Allows for the formatting of regular yaml arrays as either multi-line or single-line and `tags` and `aliases` are allowed to have some Obsidian specific yaml formats. Note that single string to single-line goes from a single string entry to a single-line array if more than 1 entry is present. The same is true for single string to multi-line except it becomes a multi-line array.": false,
      "Yaml aliases section style": "single-line",
      "Format yaml aliases section": true,
      "Yaml tags section style": "single-line",
      "Format yaml tags section": true,
      "Default yaml array section style": "single-line",
      "Format yaml array sections": true,
      "Force key values to be single-line arrays": "",
      "Force key values to be multi-line arrays": ""
    },
    "Insert YAML attributes": {
      "Inserts the given YAML attributes into the YAML frontmatter. Put each attribute on a single line.": false,
      "Text to insert": "aliases: \ntags: "
    },
    "Move Tags to Yaml": {
      "Move all tags to Yaml frontmatter of the document.": false,
      "Yaml tags section style": "single-line",
      "Remove the hashtag from tags in content body": false,
      "Tags to ignore": ""
    },
    "Remove YAML Keys": {
      "Removes the YAML keys specified": false,
      "YAML Keys to Remove": ""
    },
    "YAML Key Sort": {
      "Sorts the YAML keys based on the order and priority specified. Note: may remove blank lines as well.": false,
      "YAML Key Priority Sort Order": "",
      "Priority Keys at Start of YAML": true,
      "YAML Sort Order for Other Keys": "None"
    },
    "YAML Timestamp": {
      "Keep track of the date the file was last edited in the YAML front matter. Gets dates from file metadata.": false,
      "Date Created": true,
      "Date Created Key": "date created",
      "Date Modified": true,
      "Date Modified Key": "date modified",
      "Format": "dddd, MMMM Do YYYY, h:mm:ss a"
    },
    "YAML Title": {
      "Inserts the title of the file into the YAML frontmatter. Gets the title from the first H1 or filename if there is no H1.": false,
      "Title Key": "title"
    },
    "YAML Title Alias": {
      "Inserts the title of the file into the YAML frontmatter's aliases section. Gets the title from the first H1 or filename.": false,
      "YAML aliases section style": "Multi-line array",
      "Preserve existing aliases section style": true,
      "Keep alias that matches the filename": false,
      "Use the YAML key `linter-yaml-title-alias` to help with filename and heading changes": true
    },
    "Capitalize Headings": {
      "Headings should be formatted with capitalization": false,
      "Style": "Title Case",
      "Ignore Cased Words": true,
      "Ignore Words": "macOS, iOS, iPhone, iPad, JavaScript, TypeScript, AppleScript",
      "Lowercase Words": "via, a, an, the, and, or, but, for, nor, so, yet, at, by, in, of, on, to, up, as, is, if, it, for, to, with, without, into, onto, per"
    },
    "File Name Heading": {
      "Inserts the file name as a H1 heading if no H1 heading exists.": false
    },
    "Header Increment": {
      "Heading levels should only increment by one level at a time": false
    },
    "Footnote after Punctuation": {
      "Ensures that footnote references are placed after punctuation, not before.": false
    },
    "Move Footnotes to the bottom": {
      "Move all footnotes to the bottom of the document.": false
    },
    "Re-Index Footnotes": {
      "Re-indexes footnote keys and footnote, based on the order of occurrence (NOTE: This rule deliberately does *not* preserve the relation between key and footnote, to be able to re-index duplicate keys.)": false
    },
    "Convert Bullet List Markers": {
      "Converts common bullet list marker symbols to markdown list markers.": false
    },
    "Emphasis Style": {
      "Makes sure the emphasis style is consistent.": false,
      "Style": "consistent"
    },
    "No Bare URLs": {
      "Encloses bare URLs with angle brackets except when enclosed in back ticks, square braces, or single or double quotes.": false
    },
    "Ordered List Style": {
      "Makes sure that ordered lists follow the style specified. Note that 2 spaces or 1 tab is considered to be an indentation level.": false,
      "Number Style": "ascending",
      "Ordered List Indicator End Style": "."
    },
    "Proper Ellipsis": {
      "Replaces three consecutive dots with an ellipsis.": false
    },
    "Remove Consecutive List Markers": {
      "Removes consecutive list markers. Useful when copy-pasting list items.": false
    },
    "Remove Empty List Markers": {
      "Removes empty list markers, i.e. list items without content.": false
    },
    "Remove Hyphenated Line Breaks": {
      "Removes hyphenated line breaks. Useful when pasting text from textbooks.": false
    },
    "Remove Multiple Spaces": {
      "Removes two or more consecutive spaces. Ignores spaces at the beginning and ending of the line. ": false
    },
    "Strong Style": {
      "Makes sure the strong style is consistent.": false,
      "Style": "consistent"
    },
    "Two Spaces Between Lines with Content": {
      "Makes sure that two spaces are added to the ends of lines with content continued on the next line for paragraphs, blockquotes, and list items": false
    },
    "Unordered List Style": {
      "Makes sure that unordered lists follow the style specified.": false,
      "List item style": "consistent"
    },
    "Compact YAML": {
      "Removes leading and trailing blank lines in the YAML front matter.": false,
      "Inner New Lines": false
    },
    "Consecutive blank lines": {
      "There should be at most one consecutive blank line.": false
    },
    "Convert Spaces to Tabs": {
      "Converts leading spaces to tabs.": false,
      "Tabsize": 4
    },
    "Empty Line Around Blockquotes": {
      "Ensures that there is an empty line around blockquotes unless they start or end a document. **Note that an empty line is either one less level of nesting for blockquotes or a newline character.**": false
    },
    "Empty Line Around Code Fences": {
      "Ensures that there is an empty line around code fences unless they start or end a document.": false
    },
    "Empty Line Around Tables": {
      "Ensures that there is an empty line around github flavored tables unless they start or end a document.": false
    },
    "Heading blank lines": {
      "All headings have a blank line both before and after (except where the heading is at the beginning or end of the document).": false,
      "Bottom": true,
      "Empty Line Between Yaml and Header": true
    },
    "Line Break at Document End": {
      "Ensures that there is exactly one line break at the end of a document.": false
    },
    "Paragraph blank lines": {
      "All paragraphs should have exactly one blank line both before and after.": false
    },
    "Remove Empty Lines Between List Markers and Checklists": {
      "There should not be any empty lines between list markers and checklists.": false
    },
    "Remove link spacing": {
      "Removes spacing around link text.": false
    },
    "Remove Space around Fullwidth Characters": {
      "Ensures that fullwidth characters are not followed by whitespace (either single spaces or a tab). Note that this may causes issues with markdown format in some cases.": false
    },
    "Space after list markers": {
      "There should be a single space after list markers and checkboxes.": false
    },
    "Space between Chinese and English or numbers": {
      "Ensures that Chinese and English or numbers are separated by a single space. Follows these [guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines)": true
    },
    "Trailing spaces": {
      "Removes extra spaces after every line.": false,
      "Two Space Linebreak": false
    }
  },
  "lintOnSave": false,
  "displayChanged": true,
  "foldersToIgnore": [],
  "linterLocale": "system-default",
  "logLevel": 4,
  "lintCommands": []
}
```

## Expected Behavior

Previously it used to work, but not this time, I have tried to restart Obsidian, but still not work.

## Screenshots

<img width="1090" alt="Screen Shot 2022-11-14 at 7 09 53 PM" src="https://user-images.githubusercontent.com/17509207/201645693-6e625f8b-bd1c-4532-a6d6-5097219888df.png">

## Device

- [x] Desktop
- [ ] Mobile

macOS mojave, Obsidian version 1.0.3, installer 1.0.0

**Comment by dutry** [comment]
I have tried to update the installer to v.1.0.3, but the bug is still there. I guess the reason might be that this function is not compatible with v.1.0.3, but works fine on v.1.0.0.

**Comment by pjkaufman** [comment]
Is there anything in the console log when you run `cmd+shift+I`?

**Comment by dutry** [comment]
@pjkaufman 
The console shows the message from other extensions (like Obsidian-Git), but not from Linter, although there is a Linter bandage saying "0 characters added", it is odd.

<img width="1187" alt="Screen Shot 2022-11-15 at 9 45 51 PM" src="https://user-images.githubusercontent.com/17509207/201935254-da3eb789-1190-41a3-95c1-3f4b22ce3456.png">

**Comment by pjkaufman** [comment]
The 0 character change means it found nothing that met the criteria for a change. I can take a look and create an example locally, but unless this is not working for all files and not just a specific file, you might just have a file that does not have content that meets the criteria to get updated as per the underlying regex. Could you provide a sample file that could be used to reproduce the issue?

**Comment by dutry** [comment]
@pjkaufman 
It is odd! I created a new Obsidian vault, and installed Linter, and this time it works!
So I think there should be something wrong with my original vault!

**Comment by pjkaufman** [comment]
> @pjkaufman It is odd! I created a new Obsidian vault, and installed Linter, and this time it works! So I think there should be something wrong with my original vault!

It is possible that that is the case. were you able to lint the same file you were having trouble with before?

**Comment by dutry** [comment]
I find that the bug is influenced by latex blocks. 

Here is a sample text (I have highlighted the texts that should be formatted):
```markdown
==测试test==
$$a=b
\tag{1}$$
==测试test==
```
The first `测试test` can be formatted well, while the second cannot.

Once I write a multiline latex block, and put the equation label `\tag{1}` while `$$` denoting the end of latex code in the same line, this bug can be reproduced in the texts following the rendered latex block. 

Now I think the bug is rather a minor one, because it is highly related to my private habit to write latex codes.

**Comment by pjkaufman** [comment]
So the issue can be seen by the following and I am not really able to do anything about it on my end directly unless I do some funky parsing. Here is an AST parser run against what you have above: https://astexplorer.net/#/gist/f84501a2b986e7656461e1c51e408abb/dd22329c7f2ac378807bb15fc7273e8eac8b91c5
It considers 
``` plaintext
$$
a=b
\tag{1}
$$
==测试test==
```
to be a part of a math block. This means it will not get parsed. Out of curiosity, what does `==测试test==` mean syntactically? Is that regular markdown or is that latex? If it is the latter then, the above makes some sense since the parser is looking for math blocks and not full blown latex.

**Comment by dutry** [comment]
`==测试test==` is just regular markdown, highlighted. 

I now know the bug happens when the katex rendering is embedded in regular markdown texts. You see from the website ( https://astexplorer.net/#/gist/f84501a2b986e7656461e1c51e408abb/dd22329c7f2ac378807bb15fc7273e8eac8b91c5 ).

We may find the type difference of the `test` in line 7, 13, 15, 17. All the lines after the second math block is recognized as "math".

**Comment by dutry** [comment]
An odd thing is that, I have write multiline math block like this for a long time in Obsidian, no other bug have ever happened, except for Linter.

**Comment by dutry** [comment]
If no more specific things the developers can deal with this, I think the administrator might close this thread.

**Comment by pjkaufman** [comment]
The Linter uses a different parser than Obsidian does which is why they act differently. But as for the issue here. Does enabling the blank lines around math blocks allow this to work as expected?

**Comment by pjkaufman** [comment]
It looks like it is the issue with `$$` not being on its own line so the math parsing gets a little confused. Why not put the ending of the math block on its own line? I know that is a rule that the Linter has.

**Comment by dutry** [comment]
@pjkaufman 

I have updated the URL in my previous comment, you may see that blank lines does not help. All texts after `$$` will be "math".

You are right, it is a workaround, as I have commented previously, I should change my habit to write math equations.

**Comment by pjkaufman** [comment]
I will open an issue upstream and see where it goes, but in the meantime, I would use the rule to keep the `$$` on its own line to prevent this.

**Comment by dutry** [comment]
Glad that I my bug reported can make a change, thank you for your patience!

**Comment by pjkaufman** [comment]
I am glad that you are able to see the rule now. Hopefully it will help reduce friction with this.

Here is the discussion trying to figure out if this is intended functionality: https://github.com/orgs/remarkjs/discussions/1069

**Comment by pjkaufman** [comment]
For anyone that may look at this issue in the future, the ending of a math block has to be on its own line for the math block parsing to work as intended, at least at for now.
