### ISSUE TITLE
FR: Lint All Files in Folder/ in Vault

### ISSUE THREAD

**Issue by brimwats** [platers/obsidian-linter#5]
To accompany the lint file command

**Comment by platers** [comment]
Will add when the project is a bit more stable. Don't want to mess up someones notes!

**Comment by platers** [comment]
Don't see the utility of lint in folder, wouldn't be hard to add.

**Comment by gavinmn** [comment]
I tested this in the same go when testing #35 and found that after running it about 50k words were added to my vault.

**Comment by gavinmn** [comment]
Tested this again. I believe the weird word jump was a combo of all the YAML being added to my files and counting changes in the source code for the plugin so I don't think this is an issue.
