### ISSUE TITLE
FR: Format the code gracefully

### ISSUE THREAD

**Issue by Chen-913** [platers/obsidian-linter#506]
## Is Your Feature Request Related to a Problem? Please Describe.
Whenever I copy my code from vscode to obsidian, the following puzzling phenomena will occur
vscode：
![image](https://user-images.githubusercontent.com/72293244/202855017-7858219f-587f-49c0-ad3e-6d4227c92501.png)
Copying to obsidian becomes code with many newlines
![image](https://user-images.githubusercontent.com/72293244/202855099-57b9b62a-4a00-464c-b008-8a64ba75c481.png)

To tell the truth, these new lines will make me feel very uncomfortable
## Describe the Solution You'd Like
I hope so, and it will be better to carry the function of automatically formatting code, just like `Prettier`
![image](https://user-images.githubusercontent.com/72293244/202855343-444e8261-bed8-4623-bf62-b6ddc62d8d41.png)

**Please include an example where applicable:**

``` markdown
```jsx
export default class App extends Component {

  constructor() {

    this.state = {

      age: 18,

    };

  }

  render() {

    return <ChildComp props={{ age: this.age }}></ChildComp>;

  }

}
```
```

``` markdown
```jsx
export default class App extends Component {
  constructor() {
    this.state = {
      age: 18,
    };
  }
  render() {
    return <ChildComp props={{ age: this.age }}></ChildComp>;
  }
}
```
```

## Describe Alternatives You've Considered

A clear and concise description of any alternative solutions or features you've considered.

## Additional Context

Add any other context or screenshots about the feature request here.

**Comment by pjkaufman** [comment]
I am pretty sure this is a setting in Obsidian.

**Comment by pjkaufman** [comment]
I have it turned off for me so this does not happen. I will check to see which setting that is when I have a chance to get to my computer.

**Comment by pjkaufman** [comment]
If all you want is your paste to not add extra blank lines, then you need to turn off the setting for auto convert html (see image).
![obsidian-setting](https://user-images.githubusercontent.com/29898683/202857809-fdffc6e7-85b8-4e2c-bf6c-fc7beee96147.png)

Is that all you were looking for with this request?

**Comment by Chen-913** [comment]
Great. This is exactly what I want. Because I need to use this function, I did not turn it off. I chose to use `Ctrl`+`Shift`+`V` to paste my code into the code block. It no longer generates new line breaks, but this produces unexpected vertical lines, as shown in the following figure.
![image](https://user-images.githubusercontent.com/72293244/202908933-61ace41b-6883-4676-997c-3c7836503ed8.png)

**Comment by Chen-913** [comment]
I also tried to save it, hoping that Linter could eliminate it, but nothing happened.
Then I found that this happens when I use the `Tab` in the code block.
![image](https://user-images.githubusercontent.com/72293244/202909406-e1a52595-0229-4d76-9a12-9a9be22dcc99.png)

Here is the code I used:
```markdown
```jsx
export default class App extends Component {
  constructor() {
    this.state = {
				      age: 18,
    };
  }
  render() {
    return <ChildComp props={{ age: this.state.age }}></ChildComp>;
  }
}
```
```

**Comment by Gewerd-Strauss** [comment]
This is a normal obsidian feature. You can toggle it off in the settings under 
`Editor → Display → Show indentation guides`:
Toggled On:
![grafik](https://user-images.githubusercontent.com/80548781/205314205-08c705c2-4411-43af-b7a7-692a449eaa15.png)



Toggled Off:
![grafik](https://user-images.githubusercontent.com/80548781/205314107-cb18b5c7-9efa-4422-adbf-fdb63a5d0f4a.png)

**Comment by pjkaufman** [comment]
Hey @Chen-913 , I wanted to see if the suggested setting change satisfies your request. The Linter cannot get rid of those visual indentation indicators as they are a display setting created Obsidian. If it does not fix your issue, if you could clarify exactly what kind of codeblock formatting you are looking for, this may become a small enough scope to make it actionable. Thanks!

**Comment by pjkaufman** [comment]
My understanding is this is something related to Obsidian and not at all related to the Linter itself. The description implies it is how Obsidian displays the different tab levels that is what the request would like to change. Since this is not something the Linter does or has control over, I am going to close this issue.

If I have misunderstood and this is something the Linter causes or controls, I am happy to reopen the issue.
