### ISSUE TITLE
FR: Sort and De-Duplicate Frontmatter Tags

### ISSUE THREAD

**Issue by grantx2016** [platers/obsidian-linter#508]
## Is Your Feature Request Related to a Problem? Please Describe.

After migrating a gazillion notes into Obsidian from another app, and in the course of ongoing tag manipulation using vs code and regex, I am finding an overwhelming number of tag duplicates appearing in the frontmatter.

## Describe the Solution You'd Like

Sort the multiline frontmatter tag list alphabetically and then de-duplicate it to leave a clean and more readable list of tags.

**Please include an example where applicable:**

``` markdown

---
tags:
  - 25-ict/org/test2
  - 17-marketing/test1
  - 25-ict/org/test1
  - 25-ict/org/test2
  - general
  - 24-human-resources/people
  - 17-marketing/test1
  - 25-ict/org/test3
  - 24-human-resources/people
---
```

``` markdown
---
tags:
  - 17-marketing/test1
  - 24-human-resources/people
  - 25-ict/org/test1
  - 25-ict/org/test2
  - 25-ict/org/test3
  - general
---
```

## Describe Alternatives You've Considered

I have toyed with writing a separate regex script using awk to do this but, apart from my limited skills in this area, considered it to be a good fit for this linter plugin, and if implemented, would be a more robust solution that would benefit others.

## Additional Context

This feature would also ensure that the tag count is correct as it would no longer be counting duplicates.

P.S. Keep up the great work on this plugin! One of my favorites. 👍

**Comment by pjkaufman** [comment]
A change has been merged that adds the logic to remove duplicate YAML array values. It should go out in the next release. Please let us know if that is not the case.

**Comment by pjkaufman** [comment]
I just went ahead and wrote something for sorting the YAML array values. It does not give you the granularity to decide different sort orders for different array types (tags, aliases, normal array). But if we want to, that can be added later.

**Comment by pjkaufman** [comment]
It has been merged into master and should go out with the next release. Please let us know if this is not the case.
