### ISSUE TITLE
Bug:  Repeated empty lines

### ISSUE THREAD

**Issue by jerviscui** [platers/obsidian-linter#517]
## Describe the Bug

There are two blank lines at the end of the table.

## How to Reproduce

Use linter 
1. When I use linter v1.8.0 formatting, I get two blank rows between the table and title

``` markdown
### 常量

|  `[[Link]]`         |  A link to the file named "Link"  |
|:--------------------|:----------------------------------|
|  `[[Link]]`         |  A link to the file named "Link"  |
|  `[1, 2, 3]`        |  A list of numbers 1, 2, and 3    |
|  `[[1, 2],[3, 4]]`  |  A list of lists                  |
|  `{ a: 1, b: 2 }`   |  An object                        |
|  `date()`           |                                   |
|  `dur()`            |                                   |

### 表达式

```

## Expected Behavior

There should be only one blank line between the table and the other blocks.

## Screenshots

After formatting, two spacing lines are added:
![image](https://user-images.githubusercontent.com/6396748/204182046-4b459cf4-752f-4096-b33c-eca0f1618ad5.png)

Linter settings:
![image](https://user-images.githubusercontent.com/6396748/204181828-99e8a7e8-79aa-4048-8758-9fceff1e23ad.png)
![image](https://user-images.githubusercontent.com/6396748/204181872-f48084e6-7424-4fdf-94bd-29575ad4a6f6.png)
![image](https://user-images.githubusercontent.com/6396748/204181898-e48532b1-5dd4-496a-a285-6a050daac9a9.png)
![image](https://user-images.githubusercontent.com/6396748/204181908-b2084902-cb67-4ed3-8093-9886061a47e8.png)

## Device

- [x] Desktop

**Comment by pjkaufman** [comment]
Thanks for reporting this. I see that you took a screenshot of your spacing rules. I will see about reproducing the issue. If I cannot, I will ask for the exact `data.json` file you are using to help out with reproducing the issue.

**Comment by pjkaufman** [comment]
The issue is that paragraph blank lines is adding a blank around the paragraph in question. I will see what I can do about that.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release. Please let us know if the issue still exists on master or in the next release.

**Comment by jerviscui** [comment]
🤝 
I've_ been so busy with work lately that I'm just now paying attention to it.

**Comment by jerviscui** [comment]
Great, that solves the problem.
