### ISSUE TITLE
Bug: Word "I" not Capitalized when First Letter Capitalization Used 

### ISSUE THREAD

**Issue by Calorion** [platers/obsidian-linter#518]
## Describe the Bug

"Headings should be formatted with capitalization" lowercases words that should always be capitalized when "First letter" is selected.

In practice, this may only mean the word "I".

## How to Reproduce

1. Write a heading such as `### What did I learn?`
2. Lint
3. The heading is changed to `### What did i learn?`

## Expected Behavior

No change, i.e. 

``` 
### What did I learn?
```

## Device

- [ ] Desktop
- [x] Mobile

## Additional Context

I realize I can add "I" to the list of ignored words, but I shouldn't have to.

**Comment by pjkaufman** [comment]
I don't think that is necessarily as that seems to be the intended affect of the rule, but it likely can be updated to use a word list for what to capitalize for it.

**Comment by pjkaufman** [comment]
The rule does not care for words that should be capitalized since it was asked to lowercase everything except the first letter. The only way I can see getting around this either adding a list of words that should either be ignored or a list or words that should be capitalized.

**Comment by Calorion** [comment]
There is already a list of Ignore Words. I suppose that you could just add I to the defaults that are already in there rather than hard-coding it.

**Comment by Calorion** [comment]
Apparently it is. But there's no reason it should be. There's nothing in the settings to say that it is. So I think this list should be used for both rules, and "I" added to it.

**Comment by pjkaufman** [comment]
The logic here would need updating to work on a word by word basis instead of a header by header basis for other capitalization cases besides the "Title Case": https://github.com/platers/obsidian-linter/blob/master/src/rules/capitalize-headings.ts#L76-L127

**Comment by pjkaufman** [comment]
Would it be a correct understanding to say that the ignored words would only affect "Title Case" and the capitalization of the first letter? That is to say it would not affect forcing all caps on the header. Or should ignore words affect all of the capitalization types for the heading rule?

Thanks for helping me flush this out before I take a stab at this.

**Comment by pjkaufman** [comment]
Dev note: I can improve performance [here](https://github.com/platers/obsidian-linter/blob/master/src/rules/capitalize-headings.ts#L70-L72) since we can match all headers and then iterate from there. We can use a custom regex replace argument and allow it to work that way.

It would look something like this:
``` TypeScript
return text.replace(headerRegex, (headerText: string) => {
 let firstWord = true;
 let capitalizeJustFirstLetter = false;
 switch (options.style) {
    case 'First letter':
      capitalizeJustFirstLetter = true;
  case 'Title Case':
    const headerWords = headerText.match(/\S+/g);
    // split by comma or whitespace
    const keepCasing = options.ignoreWords;
    const ignoreShortWords = options.lowercaseWords;
    let firstWord = true;
    for (let j = 1; j < headerWords.length; j++) {
      // based on https://stackoverflow.com/a/62032796 "/\p{L}/u" accounts for all unicode letters across languages
      const isWord = headerWords[j].match(/^[\p{L}'-]+[.?!,:;]?$/u);
      if (!isWord) {
        continue;
      }

      const ignoreCasedWord = options.ignoreCasedWords && headerWords[j] !== headerWords[j].toLowerCase();
      const keepWordCasing = ignoreCasedWord || keepCasing.includes(headerWords[j]);
      if (!keepWordCasing) {
        headerWords[j] = headerWords[j].toLowerCase();
        const ignoreWord = ignoreShortWords.includes(headerWords[j]);
        if ((!ignoreWord !capitalizeJustFirstLetter) &&  || firstWord === true) {
          // ignore words that are not capitalized in titles except if they are the first word
          headerWords[j] = headerWords[j][0].toUpperCase() + headerWords[j].slice(1);
        }
      }

     firstWord = false;
   }

   headerText = escapeDollarSigns(`${headerWords.join(' ')}`),
 case 'ALL CAPS':
   headerText = headerText.toUpperCase(); // convert full heading to uppercase
   break;
  }

  return headerText;
});
```

**Comment by pjkaufman** [comment]
> Would it be a correct understanding to say that the ignored words would only affect "Title Case" and the capitalization of the first letter? That is to say it would not affect forcing all caps on the header. Or should ignore words affect all of the capitalization types for the heading rule?
> 
> Thanks for helping me flush this out before I take a stab at this.

I think I have answered my own question in my head on this. Uppercasing the whole heading should happen irrespective of the words present as ignore words and short words should all be entirely capitalized.

I will see about making this change this evening.

**Comment by Calorion** [comment]
> Would it be a correct understanding to say that the ignored words would only affect "Title Case" and the capitalization of the first letter? That is to say it would not affect forcing all caps on the header. Or should ignore words affect all of the capitalization types for the heading rule?

So…I'm talking about "First letter," not "Title Case." "First Letter" should not lowercase words that are always capitalized, such as "I." It should also not lowercase any of the words in the "Ignore Words" list. The fix to my mind is to either make "Ignore Words" apply to "First letter" as well as "Title Case" (if that doesn't cause other conflicts), or to create an "Uppercase Words" list that never get lowercased.

**Comment by pjkaufman** [comment]
> > Would it be a correct understanding to say that the ignored words would only affect "Title Case" and the capitalization of the first letter? That is to say it would not affect forcing all caps on the header. Or should ignore words affect all of the capitalization types for the heading rule?
> 
> So…I'm talking about "First letter," not "Title Case." "First letter" should not lowercase words that are always capitalized, such as "I." It should also not lowercase any of the words in the "Ignore Words" list. The fix to my mind is to either make "Ignore Words" apply to "First letter" as well as "Title Case" (if that doesn't cause other conflicts), or to create an "Uppercase Words" list that never get lowercased.

The best way to incorporate this would be to just use the same logic under the hood for both of them. So using ignore words makes the most sense.

**Comment by pjkaufman** [comment]
This should be fixed on master now and it will go out with the next release. Please let us know if there is an issue with the change.
