### ISSUE TITLE
Bug: YAML Title does not pull from filename

### ISSUE THREAD

**Issue by Calorion** [platers/obsidian-linter#519]
## Describe the Bug

If there are any headers in the file, "YAML Title" will pull the first header for the title instead of using the filename (or even an h1 later in the file) for the YAML title field.

## How to Reproduce

1. Create a file with a header besides an h1
2. Lint
3. The YAML will contain `title: headername`

## Expected Behavior

The YAML should contain `title: filename`

## Device

- [ ] Desktop
- [x] Mobile

**Comment by pjkaufman** [comment]
This is actually a part of the documentation: https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#yaml-title

It will pull the filename only if no H1 is present.

**Comment by Calorion** [comment]
There is no h1 in the file, so it pulls from the first header of any level.

Actually it pulls from the first header of any level even if there *is* an h1 in the file, so if you have

```
Text
### not the title

# Title
```

The result will be 

```
---
title: not the title
---
```

**Comment by pjkaufman** [comment]
Interesting. I will see if I can reproduce this when I get a chance later this week.

For future reference, it would help if the initial creation of these bugs and feature requests included the example to help avoid misunderstandings on my or other dev's parts as the example makes it clear that you mean a non-H1 header while the words describing this scenario are a little more ambiguous.

**Comment by pjkaufman** [comment]
I see the issue with it grabbing the wrong header: https://github.com/platers/obsidian-linter/blob/master/src/utils/regex.ts#L5
It needs to be updated to use a regex that just checks that the header is just an H1. I will update that soon.

**Comment by Calorion** [comment]
Yeah, I see now that I edited it to make it less clear. Oops!

**Comment by pjkaufman** [comment]
No worries. This should be a simple fix.

**Comment by pjkaufman** [comment]
The fix for this should be pushed onto master shortly.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release. Please let us know if that is not the case.
