### ISSUE TITLE
Bug: Move Tags to Yaml not respecting the "Tags to ignore" list

### ISSUE THREAD

**Issue by ddmarl** [platers/obsidian-linter#521]
## Describe the Bug
The Move Tags to Yaml option does not respect the "Tags to ignore" list.

### Settings
Turn on Move all tags to Yaml front matter of the document. 

Turn "Body tag operation" to "Remove whole tag" option

### Testing
Open markdown file and test:

``` markdown

#tag1
#tag2
#ignored-tag test data
#ignored-tag/nested-tag more tested data

```

Result:
``` markdown
---
tags: tag1 tag2
---

test data
more tested data
```

## Expected Behavior
Expected output:

``` markdown
---
tags: tag1 tag2
---

#ignored-tag test data
#ignored-tag/nested-tag more tested data
```
## Device

- [x] Desktop - macOS Ventura 13.0.1
- [x] Mobile - iOS 16.1.1

Running Linter 1.8.0

## Additional Context

If the "Remove hashtag" option is used instead, it performs as expected. The ignored tags remain hashtagged, and the expected tags that should have the hashtag removed are so.

If you need any more information, please let me know! 

Thanks!

**Comment by pjkaufman** [comment]
Thanks for reporting this. This is likely just an oversight and it is likely just not checking the ignore list for the remove tags option.

**Comment by pjkaufman** [comment]
The logic [here](https://github.com/platers/obsidian-linter/blob/master/src/rules/move-tags-to-yaml.ts#L93-L106) needs to be condensed to do a check whether or not to remove the tag or hashtag in the regex replace function.

**Comment by pjkaufman** [comment]
I have a fix for this. Do note that it only affects the tags  and the prior whitespace character when it removes a tag. So the change for the rule in question would result in:
``` markdown
---
tags: tag1 tag2
---
#ignored-tag test data
#ignored-tag/nested-tag more tested data
```

**Comment by pjkaufman** [comment]
This issue should be fixed on master now and in the next release. Please let us know if that is not the case.
