### ISSUE TITLE
FR: "ignore cased word" Should Affect First Letter Capitalization

### ISSUE THREAD

**Issue by tristone13th** [platers/obsidian-linter#526]
## How to Reproduce

1. Go to "H1 heading" tab,
2. Check the "ignore cased word" option,
3. select the style to "First letter",
4. format

The word with upper case letters is still formatted as lower case letters.

## Expected Behavior

Only apply the "First letter" rule to the words with all lower case letters.

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Do you mind providing an example of this? The purpose of First Letter is to only capitalize the first letter of the first "word" in the whole heading. It has recently been updated to respect the the ignore words as well #518, but that has not been released yet. 

So `# this is a Header` becomes `# This is a header`. It should respect words to ignore, but my understanding of ignoring cased words is just for Title Case.

**Comment by pjkaufman** [comment]
At least as it stands, the rule should be clear enough that with the change to include ignore words, that those are the only things are exceptions for `First Letter`. Ignore cased words is just meant to be used for the style `Title Case`.

**Comment by tristone13th** [comment]
> Do you mind providing an example of this? The purpose of First Letter is to only capitalize the first letter of the first "word" in the whole heading. It has recently been updated to respect the the ignore words as well #518, but that has not been released yet.
> 
> I think the rule you are intending to use is `Title Case` which capitalizes each word in the header unless it is an ignore word, a cased word, or something along those lines. So `# this is a Heading` becomes `# This is a Heading`.
> 
> `First Letter` is meant to only capitalize the first letter in the first "word" in the header, minus ignore words. This means that the intent of that rule is to do the following: `# This Heading is Title Cased` becomes `# This heading is title cased`.
> 
> Are you intending to use `Title Case` instead of `First Letter`?

Thanks for your detailed reply. My intention is to just capitalize the first letter of the first word, and leave other letters alone, for example, the following heading:

```
GNU is not Unix
```

When formatted, it will become:

```
Gnu is not unix
```

it lowercases the letters that shouldn't be lowercase (NU in the GNU, and U in Unix), so I think we should keep it simple, just uppercase the first letter of the whole sentence would be ok. What do you think?

**Comment by pjkaufman** [comment]
If that is the case, GNU should be added to the list of ignored words. As for the rest of the logic. I am not sure how I feel about that. While it would satisfy the case you are referring to, I am not sure that it makes sense as a whole.

Out of curiosity, is Unix always capitalized my memory is failing me on this)? If so, it should live in the list of ignored words which will have the desired affect in the next release.

**Comment by tristone13th** [comment]
> If that is the case, GNU should be added to the list of ignored words. As for the rest of the logic. I am not sure how I feel about that. While it would satisfy the case you are referring to, I am not sure that it makes sense as a whole.
> 
> Out of curiosity, is Unix always capitalized my memory is failing me on this)? If so, it should live in the list of ignored words which will have the desired affect in the next release.

That's indeed a solution, but I think it is not so elegant because we couldn't add all the special words into the ignore list, I don't mean to modify the current feature but I think we could provide it as an additional feature, what do you think?

**Comment by pjkaufman** [comment]
If we were to make such a change, that would mean that if the first word has any capital in it, then the whole header would be skipped.

Thus `# javaScript is Great` would not change at all. Is that the intention you have in suggesting this?

**Comment by tristone13th** [comment]
> If we were to make such a change, that would mean that if the first word has any capital in it, then the whole header would be skipped.
> 
> Thus `# javaScript is Great` would not change at all. Is that the intention you have in suggesting this?

Yes, thats my intention. actually, I think the format feature should have minimal modification to the file, so just capitalize the first letter of the first word no matter what other letters are is OK.

**Comment by tristone13th** [comment]
If that's ok, let me submit a pull request for it.

**Comment by pjkaufman** [comment]
You can definitely create a pull request. You would need to modify the following line: https://github.com/platers/obsidian-linter/blob/master/src/rules/capitalize-headings.ts#L89

Then you would need to add a break statement for the for loop if it were to set to ignore cased words and First Letter is on.

It would also require modifying a UT: https://github.com/platers/obsidian-linter/blob/master/__tests__/capitalize-headings.test.ts#L140-L152

**Comment by pjkaufman** [comment]
This should go out with the release. Please let us know if there is a problem with the changes.
