### ISSUE TITLE
Bug: `Empty Line Around Tables` messes up LaTeX with pipe character

### ISSUE THREAD

**Issue by mnaoumov** [platers/obsidian-linter#527]
## Describe the Bug

`Empty Line Around Tables` messes up LaTeX formulas with pipe (`|`) character

## How to Reproduce

Consider the following note

``` markdown
$|a| + |b|$
```

And enable `Empty Line Around Tables` rule.

## Expected Behavior

Markup unchanged

## Actual Behavior

```markdown
$|a

$|a| + |b|$
$|a
```

**Comment by pjkaufman** [comment]
The following line needs math and inline math added to the ignore list to fix this: https://github.com/platers/obsidian-linter/blob/master/src/rules/empty-line-around-tables.ts#L25

**Comment by mnaoumov** [comment]
> The following line needs math and inline math added to the ignore list to fix this: https://github.com/platers/obsidian-linter/blob/master/src/rules/empty-line-around-tables.ts#L25

Yes, I am about to send a PR with exactly the fix you suggested

**Comment by pjkaufman** [comment]
Thanks!
