### ISSUE TITLE
Bug: [Consecutive Blank Lines]: Whitespace in consecutive empty lines results in them not being removed upon linting 

### ISSUE THREAD

**Issue by Gewerd-Strauss** [platers/obsidian-linter#529]
## Describe the Bug

The rule [Consecutive Blank lines](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#consecutive-blank-lines) is supposed to condense any number of blank lines into one. "Blank" is an arbitrary word in this case, because - at least to me - it suggests that lines containing solely whitespace (spaces, tabs, etc) should be treated as empty - after all, they don't contain printable characters.
## How to Reproduce

1. Create a note
2. Paste the contents of this codeblock
``` markdown
A

B
				 

the above "emtpy" lines **are not** merged into one line because the upper one contains spaces (but no printable characters)



the above empty lines _do_ get reduced to one line because they are truely empty, aka don't contain whitespace

```
3. run the linter with the above-mentioned setting activated.

## Expected Behavior

I'd expect that a line containing pure whitespace is treated as an empty line (and is considered for the purpose of the rule). This means that any number of lines (≥2) that contain either 

1. no characters at all, or 
2. any combination of whitespace characters, e.g. tabs, spaces, newlines, line feeds, carriage returns, ...

are to be considered empty, and therefore removed by the linter. 
Expected output if applicable:

``` markdown
A

B

the above "emtpy" lines are not merged into one line because the upper one contains spaces (but no printable characters)

the above empty lines **do get reduced** to one line because they are truely empty, aka don't contain whitespace

```
## Actual output:

``` markdown
A

B
				 

the above "emtpy" lines are not merged into one line because the upper one contains spaces (but no printable characters)

the above empty lines _do_ get reduced to one line because they are truely empty, aka don't contain whitespace
```

## Screenshots

/

## Device

- [x] Desktop
- [ ] ~~Mobile~~, not checked on mobile

## Additional Context

Version/Installer Version: 1.0.3  
Plugin Version: 1.8.0

**Comment by pjkaufman** [comment]
To handle this, we would need to change the consecutive line regex to include `([\t\v\f\r \u00a0\u2000-\u200b\u2028-\u2029\u3000]+)?` as suggested [here](https://stackoverflow.com/a/3873354/8353749).

**Comment by pjkaufman** [comment]
I believe that I have a fix for this that will be merged in shortly.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release. Please let us know if the issue still exists on master or in the next release.

**Comment by Gewerd-Strauss** [comment]
I'll check it once we have a release for me to check, as I always have issues attempting to install from sourcecode properly.

**Comment by pjkaufman** [comment]
Sounds good. I may be able to create a release tomorrow, but we will see. There have been enough bug fixes and features merged in to go ahead and do a release.
