### ISSUE TITLE
Bug: `Consecutive Blank Lines` Removes Removes Starting Whitespace from Next Line When Line is Not Entirely Whitespace

### ISSUE THREAD

**Issue by haint126** [platers/obsidian-linter#538]
## Describe the Bug

The "Consecutive blank lines" in Spacing auto remove any list levels if there any space between 2 items.

## How to Reproduce

Example:

Before

``` markdown
- Item 1

	- Subitem 1

	- Subitem 2

		- Sub sub item 1

		- Sub sub item 2
```

After:

``` markdown
- Item 1
- Subitem 1
- Subitem 2
- Sub sub item 1
- Sub sub item 2
```

## Expected Behavior
Before

``` markdown
- Item 1

	- Subitem 1

	- Subitem 2

		- Sub sub item 1

		- Sub sub item 2
```

After

``` markdown
- Item 1
	- Subitem 1
	- Subitem 2
		- Sub sub item 1
		- Sub sub item 2
```

## Device

- [X] Desktop: windows 10
- [ ] Mobile

## Additional Context

It used to work correctly.
The bug appear recently, for about 2-3 days.
I update all extensions weekly.

I try to find the exact option which make this problem by turning off one by one and turning off "Consecutive blank lines" give me the expected result

Here are my `data.json`:
[data.txt](https://github.com/platers/obsidian-linter/files/10172115/data.txt)

Sorry if it is not really a bug but my config's fault.
Thank you

**Comment by pjkaufman** [comment]
Thanks for reporting this. I will see if I can reproduce this soon. I am pretty sure it is not consecutive blank lines that is doing this, but it could be. It really should only be affecting whitespace unless the unicode in the regex is wrong.

**Comment by pjkaufman** [comment]
I am not seeing the regex match needed to create the issue mentioned above. It could be a combination of rules, since consecutive blank lines looks to be behaving just fine for me. I will try it by running the rule and using the `data.json` to see if I can reproduce the issue in question.

**Comment by pjkaufman** [comment]
I am not seeing the described behavior with the `data.json` provided. I am seeing the following happen

Before:
``` markdown
> - Item 1

> > - Subitem 1

> > - Subitem 2

> > > - Sub sub item 1

> > > - Sub sub item 2
```

after:
``` markdown
> - Item 1

>
>
> > - Subitem 1
>
> > - Subitem 2
>
> >
> >
> > > - Sub sub item 1
>
> >
>
> >
> >
> > > - Sub sub item 2
```

The odd thing is that the blank after item 1 is added instead of another blockquote indicator. However that is perfectly valid for the output of the blank lines around blockquotes because a blank line around a single level of a blockquote can be either a single blockquote `> ` level indicator or a blank line. In this case, it used the latter.

Could you try restarting Obsidian and if that fails to fix the issue, restarting your computer? If that fails, it may be worth removing and reinstalling the plugin to see if that fixes the issue. If you do go the route of the remove and reinstall, make sure to back up your `data.json` ahead of time as that is not kept when you remove a plugin.

**Comment by pjkaufman** [comment]
You could also turn off all other plugins and then run the Linter to see if it still happens instead of removing and reinstalling the plugin.

**Comment by haint126** [comment]
Ah, I just thought the ">" means the number of tabs at the start of the line, did know that it means blockquote

Let me correct the example (also fixed in the post):
Before:
```markdown
- Item 1

	- Subitem 1

	- Subitem 2

		- Sub sub item 1

		- Sub sub item 2
```
After:
```markdown
- Item 1
- Subitem 1
- Subitem 2
- Sub sub item 1
- Sub sub item 2
```

Expected:
```markdown
- Item 1
	- Subitem 1
	- Subitem 2
		- Sub sub item 1
		- Sub sub item 2
```

I am very sorry for the inconvenience
Thank you for your relies
Have a nice day!

**Comment by pjkaufman** [comment]
I should be able to reproduce and fix this soon. It should be a simple regex update. I will see about pushing out a patch after that.

**Comment by pjkaufman** [comment]
This should have a fix ready. I am just testing to make sure nothing really gets messed up when I run the logic against my personal vault which has that rule active. Assuming it makes no unexpected changes, we should be good to go.

**Comment by pjkaufman** [comment]
It looks good. There do not seem to be the issues from before anymore. I will go ahead and patch that and get it on out there.

**Comment by pjkaufman** [comment]
This should be fixed on master and a patch is coming up. Please let us know if either master or the patch does not fix this.
