### ISSUE TITLE
FR: Add command that respects `Lint on save` setting

### ISSUE THREAD

**Issue by JeppeKlitgaard** [platers/obsidian-linter#546]
I am currently triggering the "Lint the current file" command using another plugin, but I would like the linting step to respect ignored folders. This requires adding a new command ("Lint the current file unless exempt") which could be used. This is essentially the same as "Lint the current file" except it respects the ignored folders.

Would you @pjkaufman take a PR that implements this?

**Comment by pjkaufman** [comment]
I am not sure I fully follow the need for a new rule. Can we not just update the `Lint on Save` command?

I may be misunderstanding what is being asked. I was under the impression that `Lint on Save` did respect ignored folders. If it does not, that should be added.

**Comment by JeppeKlitgaard** [comment]
I should've formulated my request a bit better. `Lint on Save` is not currently a command (in the sense that it does not appear in the Command Palette). Instead, the `Lint the current file` command currently (and in my opinion, rightly) ignores whether the current file is present in the list of folders to ignore. 

I propose adding a new command `Lint the current file unless exempt`, which is like `Lint the current file`, but respects the files ignored by the filter in the settings.

I would be happy to implement this command myself in a PR – the addition should be quite simple and small.

**Comment by pjkaufman** [comment]
I think it should be fine to add, but I would call the command `Lint the current file unless ignored` to keep it more consistent with the wording in the plugin.

**Comment by pjkaufman** [comment]
So long as it follows how the current commands are written, I don't see myself having a problem with it.

**Comment by JeppeKlitgaard** [comment]
I've added the (tiny) PR that adds this functionality over in #548.
