### ISSUE TITLE
Feature Suggestion: Automatic Spell Correction

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#549]
I recently stumbled upon [codespell](https://github.com/codespell-project/codespell), which takes a different approach to spellchecking: instead of indicating spelling mistakes, it just has a big library of words that are clearly misspelled and autofixes them ([see here for the dictionary](https://github.com/codespell-project/codespell/blob/master/codespell_lib/data/dictionary.txt)). (despite the name it also fixes none-code)

I was wondering whether this could also be a direction for the Obsidian Linter to explore? rather than fixing every misspelling individually, one could have a bunch of common and clear misspellings automatically fixed.

**Comment by pjkaufman** [comment]
That is an interesting suggestion. The problem I see with doing this is that startup time may be negatively impacted and this rule would not be fast at all. The reason for this being that it would have to look for either each word in the misspelling list and check the document for it or vice versa. That doesn't mean it is not worth doing. I am just not sure how performant using such a large set of words would be.

**Comment by chrisgrieser** [comment]
Hmm, how does `codespell` do it though? The cli is almost instant for me, even on big files

**Comment by pjkaufman** [comment]
It looks like it iterates over each word in the file, but I have not had time to take amuch closer look. I will see about taking a look at this later on this week.

**Comment by pjkaufman** [comment]
Out of curiosity, would you expect an ignore word list as well? I plan to add it, but I am not sure I can do a very good job letting people know what the default list of auto-corrected words would be.

**Comment by chrisgrieser** [comment]
for non-code I think one can do without an ignore list. I tried codespell for a wekk now, and it seems to really only fixes clear misspellings like "teh" to "the" 🤔

**Comment by pjkaufman** [comment]
Gotcha. I think I would add one just in case there is a someone who really wants the auto-correct ability, but also wants one of the misspellings for some odd reason.

I am pretty sure that load time for the plugin may double with the change, but that may be fine.

**Comment by pjkaufman** [comment]
> for non-code I think one can do without an ignore list. I tried codespell for a week now, and it seems to really only fixes clear misspellings like "teh" to "the" 🤔

When you say "non-code" do you mind clarifying what you mean?

Also would this affect tags as well? I plan to have it affect the YAML.

**Comment by chrisgrieser** [comment]
with "non-code" I mean natural language. not sure how it would go with the yaml. Especially with tags, I think there is a real danger of accidentally messing up vault organization (you search for a tag, but cannot find the note, since the spelling of the tag has changed)

**Comment by pjkaufman** [comment]
Some of them are easy to simply replace, but these ones are a little tougher to handle. I can remove them or I can just let it handle the values as if they were one value and let the person decide which to select after linting is done.

**Comment by chrisgrieser** [comment]
> Any suggested way to tackle mappings that go from one value to 2 possible values?
> 
> For example `["referers", "referrer, referrers,"]` and `["referes", "refers, referees,]"`.

I think I'd leave them out. Codespell use this for displaying earnings in the editor, not for auto fixing

**Comment by pjkaufman** [comment]
Gotcha. I was not aware of that. I will go clean it up and then see if I can test it out. Whether it gets added will be dependent on how much it affects runtime performance.

**Comment by pjkaufman** [comment]
Performance looks pretty good from my test. It looks like it may only add about 30 seconds to linting my personal vault which has 3k+ files.

**Comment by pjkaufman** [comment]
This looks pretty good. I added an ignore list for people like myself who write in multiple languages at times and need to have the ability to specify that the word in question is actually valid in that language.

**Comment by pjkaufman** [comment]
This should be on master and will go out with the next release. Thanks for the great suggestion!
