### ISSUE TITLE
Bug: `YAML Title` rule incorrectly considers `#tag` after header as a part of the title

### ISSUE THREAD

**Issue by mnaoumov** [platers/obsidian-linter#551]
## Describe the Bug

`YAML Title` rule incorrectly considers `#tag` after header as a part of the title

## How to Reproduce

Markup

``` markdown
# title
#tag
```

`YAML Title` rule.

## Expected Behavior

``` markdown
---
title: title
---
# title
#tag
```

## Actual Behavior

``` markdown
---
title: title
#tag
---
# title
#tag
```

**Comment by pjkaufman** [comment]
Thanks for reporting this. It should be an easy fix layer on today unless you already have a fix.
