### ISSUE TITLE
FR: Rule "Remove multiple spaces" should optionally trim lineend spaces down to two at most

### ISSUE THREAD

**Issue by Gewerd-Strauss** [platers/obsidian-linter#556]
## Is Your Feature Request Related to a Problem? Please Describe.

Due to various plugins, self-written solutions, various other things and just normal work one can end up with lines ending in more than 2 spaces. Markdown requires 2 spaces to render a line-break, but any additional spaces are not relevant - and instead look kind of ugly when displayed constantly - cf. image below.

![grafik](https://user-images.githubusercontent.com/80548781/207860988-77fe9200-4184-4d7f-8924-59b8192db8dd.png)

Additionally, more than two spaces at line-end do not adhere to the markdown format. 

## Describe the Solution You'd Like

I'd suggest an option to reduce line-ending whitespace longer than 2 spaces down to 2 spaces. Singular spaces at the lineend should still be removed completely, and two spaces should not be affected.

**Please include an example where applicable:**

``` markdown
No Space
One Space 
Two Spaces  
More than two spaces        
```
results in 
``` markdown
No Space
One Space
Two Spaces  
More than two spaces  
```

This makes sense as it increases a notes conformity with the markdown-spec, where 1 space or more than 2 spaces have no meaning, and thus should also not be used - intentionally or accidentally. 

## Describe Alternatives You've Considered
The current alternative is manually removing such things whenever they spring up. However, that is prone to _not noticing them_, takes time and focus doing so and is overall comparatively way too much work.

## Additional Context

/

**Comment by pjkaufman** [comment]
@Gewerd-Strauss , sorry it has been a little while. I went ahead and took another look at this to see what was going on and I do see that this logic has already been implemented as part of [trailing spaces](https://platers.github.io/obsidian-linter/settings/spacing-rules/#trailing-spaces). So I think it is safe to close issue in favor of just using the trailing spaces rule.

If there is a reason to not use that rule for what is described above, then it can be looked at, but I believe that that rule satisfies the user case of this request.

**Comment by Gewerd-Strauss** [comment]
Yep. I believe that the `trailing spaces`-rule does solve the issue I outlined here. I haven't actively thought about this issue in a long time; but just now off the top of my head I don't think I see any issues with the current implementation. So I suppose it's fine for me.

**Comment by pjkaufman** [comment]
Gotcha. Sorry about the delay. I am trying to cleanup the issues and address as many old ones as possible to better understand what is still to be worked on.
