### ISSUE TITLE
Bug: Don't lint inside mathjax expressions...

### ISSUE THREAD

**Issue by olearydj** [platers/obsidian-linter#558]
## Describe the Bug
Mathjax  expressions are linted like normal text.

## How to Reproduce
The following expression was created in a monospace font with the structure aligned:
```
$$
x = \left \{ \begin{array}{ll}
                 y   & \mbox{if $y>0$}   \\
                 z+y & \mbox{otherwise}
             \end{array}
    \right.
$$
```

When linted the internal spacing is changed, breaking the alignment.

### Steps to reproduce the behavior:

Create a MD file with the example and lint it.
[data.json.zip](https://github.com/platers/obsidian-linter/files/10254510/data.json.zip)

## Expected Behavior
I would like it to ignore anything inside `$ ... $` or `$$ ... $$`.

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

Thanks for the team's continued efforts on the plugin. I understand that the complexity and potential of this tool increases significantly with each new addition (as evidenced by the number of Bugs / FRs), and appreciate your consideration.

**Comment by pjkaufman** [comment]
Hey @olearydj . Thanks for reporting this. What exactly did this content look like after linting? My guess is the rule about not having multiple spaces in a row is being violated and it is fixing that, but it is unclear from the example provided without the output of the lint.

**Comment by pjkaufman** [comment]
I am guessing that updating all locations that ignore codeblocks and inline code to also ignore mathblocks and inline math would take care of this. I just want to make sure the issue being describe is specifically a whitespace issue.

**Comment by olearydj** [comment]
Yes, sorry I wasn't more clear. It condensed some spaces.
I believe it would be appropriate to ignore mathblocks, as you suggest.

**Comment by pjkaufman** [comment]
Gotcha. That should be a simple fix. I just have to wait until I have time to make the change. These next couple weeks will be quite hectic for me, so it may happen for the release I plan to make later this week or it may have to wait until next year when things calm down.

**Comment by olearydj** [comment]
No problem. Happy holidays!

**Comment by pjkaufman** [comment]
I think I have a fix for this, but I don't plan to merge it until I am ready for release since it is attached to some documentation changes that will likely be confusing without the actual code changes going along with it.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the release I am working on getting out. Please let us know if for some reason the issue persists.

**Comment by olearydj** [comment]
I've gotten the update and confirmed the fix at least in the original case. Thanks for your continued support on this plugin. It greatly improves my quality of life in Obsidian. Happy Holidays!

**Comment by pjkaufman** [comment]
I am glad it helps! Have a merry Christmas and a happy New Year!
