### ISSUE TITLE
Bug: `empty-line-around-tables` Erroneously Recognizing Wiki Links on the Same Line as Tables

### ISSUE THREAD

**Issue by mzietlow** [platers/obsidian-linter#559]
# Describe the Bug

There seems to be an issue with text being generated, when the `empty-line-around-tables`-rule is activated.

# How to Reproduce

The issue occurs when

1. An internal link that contains a `.` is used
2. this internal link is given a custom name
3. a second internal link with a custom name is placed in the same line
4. the two links are followed by a new line.

## Examples

When linting:
```
[[filename with dot . |alt name]] [[filename|alt name]]

```

I receive the message: `20 characters added`, resulting in
```
[[filename with dot . |alt name]] [[filename|alt name]]
[[filename with dot

```

More complex examples lead to similar results, e.g.:
```
dolor sit amet [[filename with dot . |alt name]] lorem ipsum [[filename|alt name]] adipisci velit [[filename|alt name]]

```

=> 
```
dolor sit amet [[filename with dot . |alt name]] lorem ipsum [[filename|alt name]] adipisci velit [[filename|alt name]]
dolor sit amet [[filename with dot

```

In some complex examples, existing text is replaced with `{INLINE_MATH_PLACEHOLDER}`, even in seemingly distant regions of the file

# Device

I did not try it out on mobile.
- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
@mzietlow, this definitely sounds like a bug. Could you provide some examples and how you know this is related to `empty-line-around tables` as opposed to some other rule?

The examples that would be useful:
1. Shows the addition of extra content erroneously (this seems to have been provided)
2. Allows for reproducing the issue with `{INLINE_MATH_PLACEHOLDER}` showing up in the file (this is needed to figure out what is going on in this case)

Empty lines around tables could in theory cause this issue, but I am a bit skeptical given the addition of extra content which really would only be feasible if some kind of ignoring of logic went bad and somehow resulted in the duplication of an ignored content placeholder.

**Comment by pjkaufman** [comment]
Looks like the issue with two links on the same line is that they are recognized as a part of a table, so ignoring links for that rule should fix the issue for it. Though I am not sure how the links had added text as opposed to having the original link broken since it only creates a partial match which should result in something more akin to the following:
``` markdown
[[filename with dot
 . |alt name]] [[filename|alt name]]

```

**Comment by pjkaufman** [comment]
Dev note: add markdown and wiki links to the following ignore list: `https://github.com/platers/obsidian-linter/blob/master/src/rules/empty-line-around-tables.ts#L25`. That should fix the issue with them being considered tables.

**Comment by pjkaufman** [comment]
Ah. I think I see how that value is getting copied to the next line. The Linter is counting that as the start of the line which is resulting in the result you are seeing. It adds the beginning of the current line as the ending line since it thinks it is in some kind of blockquote or nesting.

**Comment by pjkaufman** [comment]
I believe I have a fix for the two examples provided, but I am not sure on the one about inline math as I will need an example to test against for that. I plan to merge these changes in later this week when I do the next release.

**Comment by mzietlow** [comment]
@pjkaufman Thank you so much for your hard work and dedication!!! 💯 

On your first question of how I know this is related to `empty-line-around-tables` as opposed to some other rule:
I created myself a minimal-working-example-vault with Linter being the only plugin and `empty-line-around-tables` as the only rule activated. I then reproduced the bug in this minimal vault.

The following examples show how `empty-line-around-tables` leads to the creation of {INLINE_MATH_PLACEHOLDER}'s

## Minimal working example

```
- $math1$ [[name1 .|alt name1]]  [[name2 |alt name2]]:

- $math2$

```

gets turned into

```
- $math1$ [[name1 .|alt name1]]  [[name2 |alt name2]]:
- $math2$ [[name1

- {INLINE_MATH_PLACEHOLDER}

```

## Complex example
The most complex example I have at hand is the following:
```
- Die Folge $(a_{n})$ konvergiert gegen $a$.
- Die konstante Folge $(\alpha)$ konvergiert gegen $\alpha$.
- Die konstante Folge $(\beta)$ konvergiert gegen $\beta$.

Es folgt:
- Da $\alpha\leq a_{n}$ für [[Definition - Fast alle Glieder einer Folge...|fast alle Glieder]] von $(a_n)$, gilt mit dem [[Proposition - Vergleichssatz|Vergleichssatz]]:
  $\alpha\leq a$
- Da $a_{n}\geq\beta$ für [[Definition - Fast alle Glieder einer Folge...|fast alle Glieder]] von $(a_n)$, gilt mit dem [[Proposition - Vergleichssatz|Vergleichssatz]]:
  $a\leq \beta$

Sei $(a_n)$ eine konvergente Folge.
Sei $a=\lim(a_n)$.
[[Definition - Ohne Beschränkung der Allgemeinheit|O.b.d.A.]] nehmen wir an, dass $\alpha\leq\beta$.
Es gelte für [[Definition - Fast alle Glieder einer Folge...|fast alle Glieder]] von $(a_n)$: $\alpha\leq a_{n}\leq\beta$.

Wir konstruieren uns zunächst zwei neue Folgen:
1. $(l_{n})=(a_{n}-a+\alpha)$
2. $(r_{n})=(a_{n}-a+\beta)$

Mit [[Proposition - Der Grenzwert von (a_n-a)=0|Aufgabe 13.1.4]] gilt
- $\lim(l_{n})=\alpha$
- $\lim(r_{n})=\beta$

Das heißt, für [[Definition - Fast alle Glieder einer Folge...|fast alle Glieder]] gilt $a_{n}-a+\alpha\leq a_{n}\leq a_{n}-a+\beta$.

Durch Umstellen folgt:
$$
\begin{aligned}
&a_{n}-a+\alpha\leq a_{n}\leq a_{n}-a+\beta \mid -a_{n}
\\

\iff &-a+\alpha\leq 0\leq 0-a+\beta \mid +a
&\text{mit A8}\\

\iff &\alpha\leq a\leq\beta
&\text{mit A8}
\end{aligned}
$$

was zu zeigen war.
```

Which is transformed into:

```
- Die Folge $(a_{n})$ konvergiert gegen $a$.
- Die konstante Folge $(\alpha)$ konvergiert gegen $\alpha$.
- Die konstante Folge $(\beta)$ konvergiert gegen $\beta$.

Es folgt:
- Da $\alpha\leq a_{n}$ für [[Definition - Fast alle Glieder einer Folge
- Da $(a_n)$ für [[Definition - Fast alle Glieder einer Folge...|fast alle Glieder]] von $\alpha\leq a$, gilt mit dem [[Proposition - Vergleichssatz|Vergleichssatz]]:
- Da $a_{n}\geq\beta$ für [[Definition - Fast alle Glieder einer Folge
  $(a_n)$
- Da $a\leq \beta$ für [[Definition - Fast alle Glieder einer Folge...|fast alle Glieder]] von $(a_n)$, gilt mit dem [[Proposition - Vergleichssatz|Vergleichssatz]]:
  $a=\lim(a_n)$

Sei $\alpha\leq\beta$ eine konvergente Folge.
Sei $(a_n)$.
[[Definition - Ohne Beschränkung der Allgemeinheit|O.b.d.A.]] nehmen wir an, dass $\alpha\leq a_{n}\leq\beta$.
Es gelte für [[Definition - Fast alle Glieder einer Folge...|fast alle Glieder]] von $(l_{n})=(a_{n}-a+\alpha)$: $(r_{n})=(a_{n}-a+\beta)$.

Wir konstruieren uns zunächst zwei neue Folgen:
1. $\lim(l_{n})=\alpha$
2. $\lim(r_{n})=\beta$

Mit [[Proposition - Der Grenzwert von (a_n-a)=0|Aufgabe 13.1.4]] gilt
- $a_{n}-a+\alpha\leq a_{n}\leq a_{n}-a+\beta$
- {INLINE_MATH_PLACEHOLDER}

Das heißt, für [[Definition - Fast alle Glieder einer Folge...|fast alle Glieder]] gilt {INLINE_MATH_PLACEHOLDER}.

Durch Umstellen folgt:
$$
\begin{aligned}
&a_{n}-a+\alpha\leq a_{n}\leq a_{n}-a+\beta \mid -a_{n}
\\

\iff &-a+\alpha\leq 0\leq 0-a+\beta \mid +a
&\text{mit A8}\\

\iff &\alpha\leq a\leq\beta
&\text{mit A8}
\end{aligned}
$$

was zu zeigen war.
```

**Comment by pjkaufman** [comment]
This change should be on master now and should be included in the next release. Please let us know if the issue persists.

**Comment by mzietlow** [comment]
@pjkaufman Thank you so much, looking forward to the release! :)
