### ISSUE TITLE
[BUG] format-tags-in-yaml does not support nested tags

### ISSUE THREAD

**Issue by HueLiu** [platers/obsidian-linter#56]
Hello, I got into an issue.

# Expected

From

```
---
tags: #aaa/bbb/ccc
---
```

to

```
---
tags: aaa/bbb/ccc
---
```

# Current Issues

Not working. It cannot be modified after being triggered.

# Extras
**nested tags**: https://help.obsidian.md/Plugins/Tag+pane#Nested+tags

**Comment by chrisgrieser** [comment]
PR #60 should fix this :)

**Comment by HueLiu** [comment]
Thanks for your fix 💪

When will you release the new version?

**Comment by chrisgrieser** [comment]
I am only a contributor, @platers as the repo owner does the releases. (He releases regularly though, so shouldn't be very long).
