### ISSUE TITLE
Bug: `move-math-block-indicators-to-their-own-line` Incorrectly does not recognize `>` in block quotes as own line

### ISSUE THREAD

**Issue by mzietlow** [platers/obsidian-linter#560]
## Describe the Bug

When `move-math-block-indicators-to-their-own-line` is enabled, Linter moves `$$math-blocks$$` outside of block quote environments.

## How to Reproduce

1. Enable `move-math-block-indicators-to-their-own-line`
2. Create a new Document
3. Write a block quote with math-block, e.g. 
``` markdown
> $$math$$

```
4. Lint the file multiple times. After three steps, the process converges to
``` markdown
> 
$$
math
$$

```

### First Linting Step
``` markdown
> $$
math
$$

```

### Second Linting Step
``` markdown
> 
$$

math

$$

```
### Final Linting Step
``` markdown
> 
$$
math
$$

```

The process has now converged, further linting does not change the file.

## Expected Behavior

The minimal example

``` markdown
> $$math$$

```

Should be converted into

``` markdown
> $$
> math
> $$

```

## Device

I only tested on Desktop

- [x] Desktop
- [ ] Mobile

## Additional Context

The issue does not occur with `empty-line-around-math-blocks`.

**Comment by pjkaufman** [comment]
Thanks for reporting this @mzietlow . I did not account for this when the rule was written. I am not sure I have time to account for it before I do the next release and then take a break until after the end of the year, so this may stick around for a couple of weeks, but hopefully it won't be too hard to fix when I get back.

If anyone wants to tackle this while I am away, I am more than happy to review a PR for a fix to this.

**Comment by mzietlow** [comment]
Don't worry, I am just happy if it gets fixed eventually :) 

Unfortunately I am ill currently, so I cannot set up the dev environment and tackle it myself either. Maybe I can give it a shot earlier next week

**Comment by pjkaufman** [comment]
Gotcha. Hopefully you feel better soon. I was going to take a stab at this yesterday and then I ran into the problem of how to handle the following scenario:

``` markdown
> blockquote text
> > Nested blockquote $$ math $$
> > More text
> Some more text
```

My first impression tells me it should become the following:

``` markdown
> blockquote text
> > Nested blockquote 
> > $$
> >  math 
> > $$
> > More text
> Some more text
```

The only problem would be capturing the beginning of the line. It could be something where it grabs the start of the line by iterating character by character only including whitespace and the blockquote indicator.

I might have time to take a stab at this today, but we will see.

**Comment by pjkaufman** [comment]
I was taking a look at this and it looks like I need to refactor some logic to make this work better. As of right now it uses regex to do the newline additions, but that is not really possible when dealing with blockquotes and the other logic is not designed to properly handle this. So it will need a whole new method and likely a refactoring of the existing logic around putting a blank line before and after specified text.

**Comment by pjkaufman** [comment]
I have been able to work on the refactor for this. I still need to do some work around this. I am having some trouble with blockquotes with regards to what is an empty line when it comes to lines around content found in the blockquote.

For example, say the content we are adding an empty line around is `Content to add empty lines around` in the markdown as follows
``` markdown
> > Blockquote
> > 
> Content to add empty lines around
> > 
> > More content
```
Would the lines  `> > ` be consdered empty lines despite the increase in blockquote nesting? Also, would the expected empty lines around  `Content to add empty lines around` be expected to be `>` or `> >`. That is my confusion right now. I am probably just over complicating this, but this is the scenario I am causing myself to be confused about for the refactor. From what I can tell, the refactored logic does work for the existing tests, but I want to make it a little more thorough before moving forward with it.

If you are wondering why I am adding this info here, it is because the refactored logic may be usable to help with this specific issue.

**Comment by mzietlow** [comment]
@pjkaufman Interesting question, even more so, because Obsidian renders 

``` Markdown
> > 
> a
```

as double indent
![double indent](https://user-images.githubusercontent.com/30702083/209987588-f5727ba4-611b-406b-936c-55ae0fd29d17.png)

If you would lint the example as follows
``` Markdown
> > 
> 
> a
>
```

the result rendered output would change to
![image](https://user-images.githubusercontent.com/30702083/209987961-e2438b84-69ba-461d-be6c-135693ec126e.png)

Regarding your original example, I would consider `> >` an empty line, because the rendered output between adding `> >` or removing it differs drasticly:

``` Markdown
> > Blockquote
> > 
> Content to add empty lines around
> > 
> > More content
```
is rendered as

![image](https://user-images.githubusercontent.com/30702083/209988567-5f787284-8898-4e2b-aac0-eaba0f31423b.png)

Whereas 
``` Markdown
> > Blockquote
> Content to add empty lines around
> > More content
```
is rendered as a single line:

![image](https://user-images.githubusercontent.com/30702083/209988627-1c3be93e-8046-4c28-b893-ebbf33a0340c.png)

**Comment by pjkaufman** [comment]
Ok. I am back and going to take another look at this. I got caught up in several things at the start of the year, but hopefully I can get this knocked out. I may need to start over again with this due to the time-lapse that has happened which includes some pretty major changes. But hopefully this won't be too bad to setup.

**Comment by pjkaufman** [comment]
Well. It looks like the rebase worked just fine. Now I just need to figure out where I was in the logic before I left off at the start of the year.

**Comment by pjkaufman** [comment]
It looks l should be able to use the logic in question to fix the bug here. I just need to figure out a good way to grab the start of the line as well.

**Comment by pjkaufman** [comment]
Looks like the fix here was a lot simpler than what I was thinking of doing. I just need to apply it to both cases and move forward from there assuming it does not break any test cases. As of right now, this will hopefully go out with the next release. I just need to make sure that it does not break anything that I have tests for.

**Comment by pjkaufman** [comment]
I have the fix ready for this, but the better handling of empty lines will be separated from it for now. I will likely join them back together at some point. But for now, this fix will be different from that one since it looks like this change is easier to decouple from the other set of changes.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release. As of right now, the next release date is unknown as I am letting the kinks get worked out for it. Please let us know if there is an issue with either the next release or master.

**Comment by pjkaufman** [comment]
Note that I have most of the test cases fixed for the revised version of the empty lines around block logic. I am just working on one last test case. It is just a matter of what is going on with it as it seems to be wonky.

**Comment by pjkaufman** [comment]
I found out the cause of that issue as well and remedied it. The change should be merged in soon,

**Comment by mzietlow** [comment]
@pjkaufman Again, thank you so much for all your efforts and hard work fixing all these issues! 💛🎉
