### ISSUE TITLE
Bug: multiple newlines don't work in regex replacement

### ISSUE THREAD

**Issue by nathan-oneill** [platers/obsidian-linter#575]
## Describe the Bug
Multiple uses of `\n` in custom regex replacement only interprets the first `\n` correctly. It appears that the fix for #524 was only for the first `\n`.

## How to Reproduce
Custom regex replacement:
![image](https://user-images.githubusercontent.com/87982911/210224415-462357f4-53d0-4456-93ba-a8bf43909805.png)

replaces
```
foo
bar
```

with

```

\n
bar
```

## Expected Behavior
Any `\n` should be interpreted as a newline, as opposed to being interpreted as `\\n`. Continuing with the example above, I would expect the replacement to be:

```


bar
```

## Screenshots
N.A.

## Device
- [x] Desktop
- [ ] Mobile

## Additional Context
N.A.

**Comment by pjkaufman** [comment]
Thanks for reporting this issue. I plan on taking a look and seeing if it truly is only escaping the first instance of `\n`. If that is the case, I will have to go ahead and figure something out for this.

**Comment by pjkaufman** [comment]
I forgot that I needed to do replace all for it to work on all instances of the characters. I will test out the fix and see if it works.

**Comment by pjkaufman** [comment]
The fix seems to be working, so I will push up the changes to fix this.

**Comment by pjkaufman** [comment]
This issue should be fixed on master and in the next release. I plan to make the release next week since I am just getting back into the swing of things after the holidays. Thanks for reporting the issue!

**Comment by nathan-oneill** [comment]
And many thanks for fixing it! 😄
