### ISSUE TITLE
Bug: Header Increment Doesn't Properly Decrement when Decremented Heading Is One Less than Next Heading

### ISSUE THREAD

**Issue by wistone777** [platers/obsidian-linter#576]
When I open  the button “Start Header Increment at Heading Level 2”

Original display：
```
## HHELLO
#### HHELLO
## HHELLO
## HHELLO
## HHELLO
```
Expected display content：
```
## HHELLO
### HHELLO
## HHELLO
## HHELLO
## HHELLO
```

Actual display content：
```
## HHELLO
### HHELLO
## HHELLO
### HHELLO
### HHELLO
```
I don't know if it's a problem with my setup, or a bug. There have been attempts to disable and reset other plugins, but this is still the case. The obsidian version used is 1.1.9. Looking forward to guidance, thanks!

**Comment by pjkaufman** [comment]
I may have a fix for this depending on how the changes I make work against the UTs that are in place. I have 2 UTs currently failing with the fix. Once I get them fixed, I think I will have a working solution, but only time will tell.

**Comment by pjkaufman** [comment]
I have tested the fix and it looks to be working. It took me longer than expected due to the way in which the rule was written originally. It should roughly work the same as before with a couple of bug fixes and a couple fixes for weird behavior.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release. If the issue exists on either master or in the next release, please let us know.
