### ISSUE TITLE
Bug: Erroneous Table Match Causes Content Duplication when Table Match Is Not Start of Line

### ISSUE THREAD

**Issue by cnyyk** [platers/obsidian-linter#577]
## Describe the Bug

WHEN SAVE AND LINT, DUPLICATES SOME LINE AUTOMATICLY.

## How to Reproduce

1. Create a new note
2. Paste `magneto - | maɡˈnedō |` to the editor
3. Save it
4. Will see the content becomes to:
   ```
   magneto

   magneto - | maɡˈnedō |

   magneto
   ```
5. If placed `magneto - | maɡˈnedō |` into code block, will not generate duplicated lines.

Please make sure to include logs and the rule(s) that cause the issue if applicable. You can include logs by going to the debug tab of the Linter and setting the log level to debug. Then enable the capturing of logs and either lint on save or lint the current file. Then go back to the debug tab and you can grab Linter logs from the last run.

If you are not sure which rule(s) may cause the issue, please attach the `data.json` file located at `<vault>/.obsidian/plugins/obsidian-linter/` or copy the config from the debug tab.

[data.json.zip](https://github.com/platers/obsidian-linter/files/10365663/data.json.zip)

## Expected Behavior

DO NOT DUPLICATE THE CONTENT.

## Screenshots

![obsidian-linter-bug](https://user-images.githubusercontent.com/275233/211135422-b9c83069-1836-4b2f-85a5-61406005477f.gif)

## Device

- [x] Desktop

## Additional Context

macOS 13.1
Obsidian: 1.1.9
Obsidian Linter: 1.10.1

**Comment by pjkaufman** [comment]
Looks like the problem here is that blank lines around tables is matching with ` - | maɡˈnedō |` from the file. This then causes the duplication of the value in question. I can try something to fix this and see if it does not break anything else.

**Comment by pjkaufman** [comment]
I believe I have a fix. I am pushing it up. It should fix this and similar scenarios. It was thinking it was a table.

**Comment by pjkaufman** [comment]
This should now be on master and in the next release. Please let us know if this issue exists on master or in the next release.
