### ISSUE TITLE
FR:  FileName as default [yaml title ] when lint the current file

### ISSUE THREAD

**Issue by heyzoeys** [platers/obsidian-linter#578]
his guys, first thanks for so awesome plugin. 

when i use lint the file ,  i want the current file name as the yaml title field. 

i saw the link plugin setting, there is a relevate setting in the picture: ![image](https://user-images.githubusercontent.com/93904235/211237996-3a0ba149-4c3d-48b9-87ab-6cad37aa8be9.png)

its possible to sepecified only  filename to be setted to be the yaml title? 
**because when i write something , then the yaml title auto be setted to H1 header, if i lint the file.**

**it would be very nice, if we can select file name or h1 header as our yaml title.!!!**

thanks all.

**Comment by pjkaufman** [comment]
This relates to #205 and should be added with the changes for that feature request.

**Comment by pjkaufman** [comment]
The change to `YAML Title` adding 3 modes (one for how it currently works, one for just the filename, and one for just the first H1) should go out with the next release. Please let us know if this does not work on master or in the next release.
