### ISSUE TITLE
Bug: Move Tags to Yaml incorrectly identifies titles with # in the hyperlink as labels

### ISSUE THREAD

**Issue by cpfy** [platers/obsidian-linter#579]
## Describe the Bug

`Move Tags to Yaml` incorrectly identifies titles with # in the hyperlink as labels

## How to Reproduce

Paste the following text into Obsidian

``` markdown
Hyperlink example: 
[Travis Linux builds failing: can't find FFTW · Issue #152 · SHTOOLS/SHTOOLS · GitHub](https://github.com/SHTOOLS/SHTOOLS/issues/152)
```

with rules setting like this:

![1673245016572](https://user-images.githubusercontent.com/30110832/211250218-8c11bbd3-6e12-499a-a22c-2f0ecc8e22eb.png)

After Linter, the tags field in the yaml section will have an additional tag named 152, due to the text `Issue #152` in the link title being recognized as a note tag

```yaml
---
tags: [152]
---
```

DEBUG logs as follows:
```
Running linter
Running Move Tags to Yaml
Running YAML Title
Running Headings Start Line
Running Remove Trailing Punctuation in Heading
Running Remove Consecutive List Markers
Running Remove Empty List Markers
Running Remove Hyphenated Line Breaks
Running Remove Multiple Spaces
Running Empty Line Around Blockquotes
Running Empty Line Around Code Fences
Running Empty Line Around Math Blocks
Running Empty Line Around Tables
Running Heading blank lines
Running Remove link spacing
Running Space between Chinese Japanese or Korean and English or numbers
Running Trailing spaces
Running Custom Regex
Running YAML Timestamp
Running Custom Lint Commands
```

## Expected Behavior

Ignore `#` content in the note text (images, web links, etc.) as these are not tagging the note

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Thanks for reporting this. It seems that markdown and wiki links need to be ignored for this so that they don't get treated as tags.

**Comment by pjkaufman** [comment]
I guess that I will go ahead an ignore markdown and wiki links for this rule to make it so that they do not accidentally trigger the rule. Hopefully that will be a simple change.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release. Please let us know if the issue persists in either of these places. Have a great day!

**Comment by cpfy** [comment]
Thank you very much! I'll try to test it in the next version! Hope Linter keeps getting better!
