### ISSUE TITLE
FR: Enable only update create time if create time doesn't exist

### ISSUE THREAD

**Issue by aiyolo** [platers/obsidian-linter#580]
## Is Your Feature Request Related to a Problem? Please Describe.
Last week, I accidently deleted all my notes, after I restored all my notes, the metadata of create time and update time of my notes are totally changed to the new time, if I lint my notes, the original create_time yaml tag and update_time yaml tag will simultaneously be linted, however, I want to preserve the create_time yaml tag and only lint update time tag since the create time tag is already correct, which is important for me to remember the first time I created the notes.

## Describe the Solution You'd Like
I wish there was an option that would let me choose whether I would like not to lint create time if create_time tag already exists, otherwise that would lint simultaneouly update create time and update_time tag.

**Comment by aiyolo** [comment]
After I reviewed the code of obsidian-lint, I found this feature was already implemented in the following line

https://github.com/platers/obsidian-linter/blob/dff37822ca6d23bb20e6c81a1369870020289440/src/rules/yaml-timestamp.ts#L82-L91

And what caused my problems was that I set the moment time format as "YYYY-MM-DD HH:mm:ss ", where there is an extra space in the moment time format. So, the first time I pressed "ctrl+s" to lint my note, there was an extra space in the `date created` tag, which caused `createdDateTime.isValid()` returned false, and then this tag was replaced with `created_date_line`.

To fix the bug, I suggest to trim `options.format` simultaneously, or turn the fourth parameter of class `moment()` to false so that it won't do strict check.

Would you mind I make a pull request to fix it?

**Comment by aiyolo** [comment]
If the create time was 2021-01-28(meta data), but the time listed was 2020-05-09(yaml tag), the original rule would not relate one with the other. Replacement only happens when the listed time is invalid. 

So if format has an extra space, for example "YYYY-MM-DD HH:mm:ss ", the first time we lint file, we get create time "2023-01-12 22:12:00 " , which also has a space, in the following line, the first parameter is `"2023-01-12 22:12:00 ".trim()`, however, if we didn't remove the space in options.format, under the strict check, `createDateTime.isValid()` will return false;
```js
// orignal code
const createdDateTime = moment(text.match(created_match)[0].replace(options.dateCreatedKey + ':', '').trim(), 
          options.format, options.locale, true); 
// second parameter has an extra space which will not match the first parameter under strict check.
const createdDateTime = moment("2023-01-12 22:12:00 ".trim(), "YYYY-MM-DD HH:mm:ss ", "zh-cn, true); 
```

**Comment by pjkaufman** [comment]
I will have to look at this code area again and make sure I understand what is going on, but the problem I am seeing with this is that if the format says it ends in whitespace (I am not sure why a person would do this, but I think it is still considered valid) then the changes would make it so that they could not have that whitespace present.

**Comment by pjkaufman** [comment]
I am going to close this since I believe that whitespace being added to the end of the timestamp is a valid timestamp format that people can specify if they so choose. However if this does have more people who want this change, we may end up revisiting this in the future.
