### ISSUE TITLE
格式化后链接失效

### ISSUE THREAD

**Issue by Bulbbbb** [platers/obsidian-linter#583]
我在obsidian中使用`_[[abs接口]]_`链接到其他文件，但是在格式化后，它变成了`_[[abs 接口]]_`，文件`abs 接口`是不存在的，我的实际文件时`abs接口`，所以该链接失效了。
请问我应该如何设置才能避免`_[[]]_`中的文本被格式化？

**Comment by pjkaufman** [comment]
Here is the translation I am seeing for this issue based on Google Translate:
```
I use _[[abs interface]]_ in obsidian to link to other files, but after formatting, it becomes _[[abs interface]]_, the file abs interface does not exist, when my actual file abs interface, so the link is invalid.
How should I set it to avoid the text in _[[]]_ being formatted?
```
My response is as follows:
```
I am not sure what the issue is. The before and after you have provided are the exact same. Can you explain how they are different?
As for the format you have mentioned not being touched, that currently is not something you can ignore. I am working on custom ignore, but first I am working on getting a lot of bugs closed out.
Sorry if this is hard to understand as I am using Google Translate to get this in the right language.
```

我不确定是什么问题。 您提供的之前和之后完全相同。 你能解释一下它们有何不同吗？
至于你提到的不被触及的格式，目前不是你可以忽略的。 我正在处理自定义忽略，但首先我正在努力解决很多错误。
对不起，如果这很难理解，因为我正在使用谷歌翻译以正确的语言获得它。

**Comment by Bulbbbb** [comment]
I mean, after using other symbols to surround hyperlinks, such as italic symbols, the plug-in cannot recognize hyperlinks well. If the hyperlink contains both Chinese and English, formatting will insert spaces between Chinese and English.So You're linking to a file that doesn't exist.

**Comment by pjkaufman** [comment]
> I mean, after using other symbols to surround hyperlinks, such as italic symbols, the plug-in cannot recognize hyperlinks well. If the hyperlink contains both Chinese and English, formatting will insert spaces between Chinese and English.So You're linking to a file that doesn't exist.

I would need to see the example in question to know whether that is the case. I thought link text was an exception to having whitespace added between Chinese and English characters.

**Comment by Bulbbbb** [comment]
Formatting does not change the title of the file to which it is linked without being surrounded by other symbols。
![image](https://user-images.githubusercontent.com/36302435/215241592-e80d0f13-9938-4bcf-9d45-78e2fc23dc43.png)
When enclosed in italics, formatting adds spaces between Chinese and English.
![image](https://user-images.githubusercontent.com/36302435/215241730-7e938fc0-5b0e-4b41-8719-8bcc89286d8c.png)
Obviously, this file does not exist. When you move the mouse over, obsidian will let me create this file.
![image](https://user-images.githubusercontent.com/36302435/215241794-d05a3a18-3ebd-4e98-a3b3-234322c3fdac.png)
Therefore, when I create a title, I should always remember to insert spaces between Chinese and English, otherwise unexpected problems will occur.

**Comment by northword** [comment]
he means:

`*[[abs接口]]*` will be format to `*[[abs 接口]]*` (a space between "abs" and "接口") , however, no filname `abs 接口`. 

Original is `*[[abs接口]]*`
Expected is  `*[[abs接口]]*`
Actual is  `*[[abs 接口]]*`

**Comment by pjkaufman** [comment]
I will take a look and see about fixing that. It may be that I just didn't transfer over the right ignores when I moved that logic out from the normal logic.

**Comment by pjkaufman** [comment]
I think I have a fix for this. The italics and bold values were assumed to not have links in them, so they were not being ignored. I should have a simple fix for this.

**Comment by Bulbbbb** [comment]
This is excited.Looking forward to receiving the fix update.

**Comment by pjkaufman** [comment]
I have pushed up the changes. I am planning on merging them and then closing this issue. I may do a bug fix or 2 more before I go ahead and make a release for the bug fixes. Hopefully it will not take too long to do so.

**Comment by pjkaufman** [comment]
The fix has been merged into master and will be released with the next release. Please let us know if the next release or master does not fix this.

**Comment by Bulbbbb** [comment]
Thanks,i have received the update,no problems have been found.
