### ISSUE TITLE
FR: Change order of custom regex replacement

### ISSUE THREAD

**Issue by dagomar** [platers/obsidian-linter#584]
## Is Your Feature Request Related to a Problem? Please Describe.

The custom regex replacement is a great addition (thank you so much!). Often times you'd want to have multiple of these replacements run and the order in which they're run can affect the outcome. It would be great if the order could be changed from the interface. There is of course a workaround: re-add rules to get the order that you want.  

## Describe the Solution You'd Like

I would like to be able to rearrange the order in which regexes are run.

## Describe Alternatives You've Considered

Re-adding a rule to get the order I want is a good workaround, but makes it a bit difficult to manage as the rule set grows.

## Additional Context

Here's an example of what I'm doing with this. I've set up the day planner plugin and use it for the pomodoro time-boxing method. My template has divided my whole day in half hour chunk tasks like so:

### Prep the day
- [ ] 9:00 
- [ ] 9:25 BREAK
- [ ] 9:30 Meeting example
...
### Finalize the day
- [ ] 16:30 
- [ ] END

During the day I fill out what I've been doing, but not for all of these tasks. Day planner automatically checks all of these tasks when the time has passes, so at the end of the day I end up with this:

### Prep the day
- [x] 9:00 
- [x] 9:25 BREAK
- [x] 9:30 Meeting example
...
### Finalize the day
- [x] 16:30 
- [ ] END

Note that the last one is never checked (not sure if this is a bug in day planner, but doesn't matter). I use the regex replacement to remove all the tasks that are checked + (empty after the time or 'BREAK'). However, the last line (- [] END) I wanted to remove as well, which I can only do if the previous line is checked. Now, when that previous line is empty, it is removed and the regex doesn't remove the last line. The order in which the regexes run makes the difference. If I remove the last line first, and then the others, it works. Sorry for the wall of text, but it's a real life example :)

**Comment by dagomar** [comment]
Oh lol, I didn't realize my example would show up as actual tasks in this ticket, sorry about that!

**Comment by pjkaufman** [comment]
Sorry about the delay. I just went and checked how bad the logic change would be to do this and realized it would be relatively easy. I just had to make some CSS changes to make it work.

This change should go out with the next release and it is on master now. Please let us know if this does not work.
