### ISSUE TITLE
FR: Move all YAML to callout at the bottom of file

### ISSUE THREAD

**Issue by ArneNostitz** [platers/obsidian-linter#587]
Hi! i was wondering if it would be possible with this plugin to move the current YAML of a file to the bottom of that file and inside a callout. 
i have a lot of links in my yaml and it would be great if that would be active. so a callout with inline fields (:: instead of : between the key and value) would be a workaround that is also Dataview compatible. 

thanks!!

**Comment by pjkaufman** [comment]
I am not sure this is something that the Linter is suited to. This seems more like a custom script that could be implemented if you know JS. Or even something that can be done with regex if you feel confident enough in your regex skills.
