### ISSUE TITLE
Bug: dont see re-index-footnote on ctrl-P...

### ISSUE THREAD

**Issue by ccchan234** [platers/obsidian-linter#590]
## Describe the Bug

dont see re-index-footnote on ctrl-P...

windows 10, 22h2, 64bit.

simple enough, i'll skip the other things below thanks

## How to Reproduce

Or

Example to reproduce issue with

``` markdown
example here
```

Please make sure to include logs and the rule(s) that cause the issue if applicable. You can include logs by going to the debug tab of the Linter and setting the log level to debug. Then enable the capturing of logs and either lint on save or lint the current file. Then go back to the debug tab and you can grab Linter logs from the last run.

If you are not sure which rule(s) may cause the issue, please attach the `data.json` file located at `<vault>/.obsidian/plugins/obsidian-linter/` or copy the config from the debug tab.

## Expected Behavior

Expected output if applicable:

``` markdown
expected output here
```

## Screenshots

![image](https://user-images.githubusercontent.com/37549409/212827479-566b917d-7334-4be3-9da6-af4b56f354a8.png)

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Hey @ccchan234 , I am pretty sure this is not a bug. It looks like you are looking for re-index footnotes as a command when it is just a linting rule run under the lint file rules. So you will have to run that to get the enabled rules to run.

**Comment by ccchan234** [comment]
> Hey @ccchan234 , I am pretty sure this is not a bug. It looks like you are looking for re-index footnotes as a command when it is just a linting rule run under the lint file rules. So you will have to run that to get the enabled rules to run.

ok, my fault,
other plugins usually work as command thru ctrl+P,
i now just found for linter, in the settings there are some rules, 
toggle them and then we can ctrl+P to lint one or all files.

ok, thank you.
