### ISSUE TITLE
Bug: Header increment breaks when tags are used in the header

### ISSUE THREAD

**Issue by kndshein** [platers/obsidian-linter#598]
## Describe the Bug
In a document with properly-incremented headers, when a tag (i.e. `#`) is added onto one of the headers, the sub-headers gets bumped up to the same level as the header with the tag.

## How to Reproduce

Example to reproduce issue with

``` markdown
# Page Title
## Foo #tag
### Bar
### Baz
```

Linter Config for incrementing header:
```
 "Header Increment": {
      "Heading levels should only increment by one level at a time": true,
      "Start Header Increment at Heading Level 2": false
    },
```

## Expected Behavior

Expected output:

``` markdown
# Page Title
## Foo #tag
### Bar
### Baz
```

The actual output:

``` markdown
# Page Title
## Foo #tag
## Bar
## Baz
```

## Device

- [x] Desktop
- [ ] Mobile

Reproducible in both v1.10.1 and v1.10.2

**Comment by pjkaufman** [comment]
Thanks for reporting this. It looks like it is an easy fix. I am pushing up the changes for it.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release. Please let us know if that is not the case.
