### ISSUE TITLE
FR: Support exclude glob patterns for files

### ISSUE THREAD

**Issue by maxime1992** [platers/obsidian-linter#609]
## Is Your Feature Request Related to a Problem? Please Describe.

I would like to have the ability to exclude a given set of files.

As a practical example, in my case I use Excalidraw plugin so I do have some files ending with `.excalidraw.md` and I want to exclude all of these files from the linting.

## Describe the Solution You'd Like

Have an array of file path globs to exclude. 

**Please include an example where applicable:**

In this case it'd be `["*.exclidraw.md"]` to exclude all these files.

## Describe Alternatives You've Considered

There's the folder feature (which is for folders ofc, not files), and the one to exclude a file put writing it down in the frontmatter on each files to exclude, but I may not remember this all the time, when creating new excalidraw files etc... So it's far from ideal.

## Additional Context

None. Thanks for the great tool!

**Comment by pjkaufman** [comment]
This library may be worth considering for using for excluding files that match a specific pattern: https://github.com/axtgr/wildcard-match/tree/master

**Comment by pjkaufman** [comment]
The only problem I can think of with doing this right now is the potential issue with having to check each file name against the regex that would be generated based on the globs. That could add up in terms of time it takes to lint a whole vault or folder.

**Comment by maxime1992** [comment]
Assuming that this could really be a bottleneck for some people with plenty of notes, maybe you could come up with a caching strategy that saves the regex or a hash of the regex and for each file by default look up into a table if we already have the result otherwise the first time for a file, run the regex and save the result so that next time it comes from the cache.

Might be a bit premature to jump on such optimizations but I know some people have thousands of files in their vault so maybe it's a good idea.

**Comment by pjkaufman** [comment]
There is a ticket for caching right now, but I have not taken the time to tackle it yet. It would likely mitigate the issue.

**Comment by Nepherim** [comment]
Any update on this? Excalidraw breaks when files get linted, so having a means to exclude a patterned list of files would be great.

**Comment by pjkaufman** [comment]
There currently has been no work put toward this at this time. But it may be worth considering. Is excalidraw a markdown file or is it only masquerading as a markdown file?

**Comment by pjkaufman** [comment]
Well, I just double checked something and this may have already been addressed though not exactly as described here. There is an option to ignore files using regex. I forget how long ago that was added. But I believe that addresses this issue here @Nepherim , @maxime1992 , is that correct?

**Comment by Nepherim** [comment]
I had been stuck on 1.19 and the "Files to ignore" option was not there. It looks like that was added in [1.25.0](https://github.com/platers/obsidian-linter/releases/tag/1.25.0). Updated to 1.26.0, and that option works. It excludes Excalidraw files from Linting, and thus prevents the errors initially reported.

For reference, use this regex: `.*\.excalidraw\.md$`

Note, Linter will still Lint the file if you explicitly say "Lint this file", and then you get the issues reported. However, if you set the Lint on Save/Change options, the regex will ignore Excalidraw files. Basically, set it and forget it, don't manually Lint Excalidraw files.

Thanks for the follow-up.

**Comment by pjkaufman** [comment]
No problem. I think that the docs need to be added for that file ignore. I am working on getting that in place. But beyond that, I think there is a command for linting unless ignored. I am guessing that I should swap to the following for linting:
- Lint file command respects ignore
- Special lint file command for linting irrespective of file ignore

That would be a breaking change. But I think that it is warranted given that linting a file that is ignored should have a warning and thus have an added burden for running.

**Comment by Nepherim** [comment]
I think that makes sense. It's a little unexpected for Lint file to ignore the file exclusion pattern. But as you note it may be useful to have an option to force Lint.

**Comment by Nepherim** [comment]
In case you still need it, here's a simple drawing -- a single box shape:
```
---

excalidraw-plugin: parsed
tags: [excalidraw]

---
==⚠  Switch to EXCALIDRAW VIEW in the MORE OPTIONS menu of this document. ⚠== You can decompress Drawing data with the command palette: 'Decompress current Excalidraw file'. For more info check in plugin settings under 'Saving'


# Excalidraw Data
## Text Elements
%%
## Drawing
```compressed-json
N4KAkARALgngDgUwgLgAQQQDwMYEMA2AlgCYBOuA7hADTgQBuCpAzoQPYB2KqATLZMzYBXUtiRoIACyhQ4zZAHoFAc0JRJQgEYA6bGwC2CgF7N6hbEcK4OCtptbErHALRY8RMpWdx8Q1TdIEfARcZgRmBShcZQUebQBWbQAGGjoghH0EDihmbgBtcDBQMBKIEm4IAGl6ADUARgBZIR4AZQBNAA5JZQAWGDaAUQAzAA1SAAkAOVSSyFhECsDsKI5l

YJnSzG5neLqk/lKYbZ6AThPtHp74gGY6nniDyAoSdW4OnsepBEJlaW4Admun2sa3EqH2hQEUFIbAA1ggAMJsfBsUgVADEdQQWKxG0gmlw2FhyhhQg4xCRKLREmh1mYcFwgWyeIgQ0I+HwLVg6wkgg8LOY0LhCAA6i9JNw+JCIIKYfCuTAeeg+eVPqTfhxwrk0HVPmwGdg1EcdUkIbMICThHAAJLEbWoPIAXU+Q3ImVt3A4Qg5n0I5KwFVwKTVwnJ

muY9uK5vmYOukIAvp8wghiNw7nV/nUejweKbPowWOwuGgc/mmKxOJNOGJuNdcydrh06gA2Dq+5gAEXSUBT3CGBDCn00oeIA2CmWy9q9PulQjgxFwPdTOv+PFXHSS8XuLbNpSIHFhnu9+E+KKJvbQ/fwYUK8fAzrouDgcC5i7BUegkgyYIgRF+UA2BhCAQCgACFCWJUlyUpVEMSGeCEMA7ARCZKBrR7fQuTlRFkVgiRMWxQikJQrI0Iw8CiUtMkKV

w6l0FpDh6UZUjiNIVD0IyAAxdlOW5H8VVTA4IGQtjSI4zChXhMViFeEshJE9iMKw4UFSVGVkVVQphJI7JxIAJWEDUtTTeSdLIjIAHkDSNNM8y0hSxIwzjOCgTjcH0dljVQB57LM8TnOyFpCCMMFc1M0TdIwgAVLAoAAQT/Yt0GCIYAPCxSMlfUh4rYtgKC/XBl1QacT18iLzP0AZyTi3L8pCIqIEZGEqHSxyMhq5qovgH8oMErTmGwGEORGWz7gS

ISBqG/A2m4Ztmx6BJ4h6Vt/h80ojDYAxuCjSB6AIIQwTqW9WsijIDOo8N7QgXrAJJEggpCyVdwtUh7p7OBuDWyA7uIBo2GIBAqtwTRgiKq9By0n6YLonaIFA5EGtIZQCQACh4DNqF4DGsf+TGkgSABKFk9IQZRvUZRZkdwNHrn2XhacxngGfBQmIGOsrUOU+ErKgIsp2PITXXchASf9V7Vm26UsmB0HuGhA7PmwIgPrQeWEE+Dhhbl0gFelYQoH3

ME1fZ0o7AAKwQZZmBaTW4D+gGgZBi9UHB9WtMJXnGCizb8El6NuoqMJgmWIsWWQwUDC6hY0BK082HPMGBzd818FCeKQ69n2jw5W9wETOg2WCSM73jIA=
```
%%
```

**Comment by pjkaufman** [comment]
Thanks for all the input and feedback. I am going to go ahead and close this as it was already added. Feel free to give feedback around possible improvements.
