### ISSUE TITLE
Bug: `Proper Ellipsis` rule breaks transcluded links

### ISSUE THREAD

**Issue by mnaoumov** [platers/obsidian-linter#611]
## Describe the Bug

`Proper Ellipsis` rule breaks transcluded links

## How to Reproduce

``` markdown
![title](a...b.md)

![](c...d.png)
```

Apply `Proper Ellipsis` rule

## Expected Behavior

The note is unchanged

## Actual behavior Behavior

The three consecutive dots `...` were replaced with a single Unicode character `…`, breaking the links

``` markdown
![title](a…b.md)

![](c…d.png)
```

**Comment by pjkaufman** [comment]
Sounds like I need to add an exception for links though it seems like bad practice to include multiple dots in a row in a file name. @mnaoumov , did you have a fix for this or do you want me to create one real quickly before I mage the next release?

**Comment by pjkaufman** [comment]
This only looks to affect images or things in the image markdown format.

**Comment by mnaoumov** [comment]
@pjkaufman yes, I almost finished my fix

**Comment by pjkaufman** [comment]
Gotcha. I will wait on it then. It should just be adding the ignore type of image to the list of ignore types.
