### ISSUE TITLE
FR: Support Space between Chinese Japanese or Korean and English or numbers ignore code block

### ISSUE THREAD

**Issue by lbydev** [platers/obsidian-linter#618]
## Is Your Feature Request Related to a Problem? Please Describe.

Code blocks I want to keep original content

## Describe the Solution You'd Like

I would like the "space between Chinese Japanese or Korean and English or numbers" rule support ignore code block

**Please include an example where applicable:**

- 14:45 test中文

 ```
INSERT INTO beautiful (name, age)
    VALUES
    ('Yumie中文', 29)
ON DUPLICATE KEY UPDATE
    age = VALUES(age),
     …
```
- 15:04 中文test

**expected**

- 14:45 test 中文

 ```
INSERT INTO beautiful (name, age)
    VALUES
    ('Yumie中文', 29)
ON DUPLICATE KEY UPDATE
    age = VALUES(age),
     …
```
- 15:04 中文test

**Actual**

- 14:45 test 中文

```
INSERT INTO beautiful (name, age)
    VALUES
    ('Yumie 中文 ', 29)
ON DUPLICATE KEY UPDATE
    age = VALUES(age),
     …
```
- 15:04 中文test

## Describe Alternatives You've Considered

eg. add options: `ignore code block`

## Additional Context

None. Thanks for the great tool!

**Comment by pjkaufman** [comment]
Hey @lbydev , this rule already ignores code blocks. At least, it is supposed to do so based on the ignore types. I will test out the scenario in question and let you know if I am able to reproduce this.

**Comment by pjkaufman** [comment]
I cannot reproduce with the example provided. Could you provide your `data.json` so I can see if there is a bug with some other rule causing it to think that the code block is not actually one?

**Comment by lbydev** [comment]
> I cannot reproduce with the example provided. Could you provide your `data.json` so I can see if there is a bug with some other rule causing it to think that the code block is not actually one?
Thank you for your work!

I resolve the problem.
because code block Text indented with a tab or space, obsidian will also look like a code block in preview.

![with-space-tab](https://user-images.githubusercontent.com/3990616/216967145-545efd0e-183c-46d8-9e5b-c34421fd7588.jpg)
