### ISSUE TITLE
Issue: The link to the QuickAdd repo in the Readme is dead. Are there other examples to look at for custom lint commands?

### ISSUE THREAD

**Issue by YousufSSyed** [platers/obsidian-linter#624]
Here's the excerpt in the readme:
> Once the macro is added, go ahead and configure the macro making sure to add your user user script (this should be a JavaScript file in your Obsidian vault). [Here](https://github.com/chhoumann/quickadd/blob/master/docs/Examples/Macro_LogBookToDailyJournal.md) is an example from the QuickAdd repo with an explanation of what the code does.

**Comment by pjkaufman** [comment]
Looks like it moved to a new location: https://github.com/chhoumann/quickadd/blob/master/docs/docs/Examples/Macro_LogBookToDailyJournal.md

I will update the docs.

**Comment by pjkaufman** [comment]
The fix should now be present. Please let us know if the link is still broken.
