### ISSUE TITLE
Format Tags in YAML doesn't work as expected

### ISSUE THREAD

**Issue by bmdesmet** [platers/obsidian-linter#63]
The rule "Format Tags in YAML" doesn't handle tags in the front matter formatted like
---
Tags:
  - #foo
  - #Bar
---
Applying the linter does nothing. The expected results were
---
Tags:
  - foo
  - Bar
---

My use case for this is that I find this style of lists in YAML to be more legible and easier to edit or remove a tag. I suspect the reason I start with the # is similar to others, we want auto-complete help when assigning tags.

**Comment by TheodorrodeohT** [comment]
> ## The rule "Format Tags in YAML" doesn't handle tags in the front matter formatted like
> Tags:
> 
> * #foo
> * #Bar
> 
> ## Applying the linter does nothing. The expected results were
> Tags:
> 
> * foo
> * Bar
> 
> My use case for this is that I find this style of lists in YAML to be more legible and easier to edit or remove a tag. I suspect the reason I start with the # is similar to others, we want auto-complete help when assigning tags.

To be more precise, the following case does not work as expected:

```
---
tags:
- #tag1
- #tag2
---
```

The rule `format-tags-in-yaml` ignores the hashes as the [original regex](https://github.com/platers/obsidian-linter/blob/222136f76db02a29598eb9128f0a0e4bf00876d5/src/rules.ts#L389) parses only a single string.

**Comment by neldeles** [comment]
A possible implementation for this is to have options on the desired output format after parsing out the `#`. Workflow would be: 

1. Users type out their tags as suggested: `tags: #tag1 #tag2`
2. On save it's formatted based on the format output setting chosen by user i.e. bullet points, array

I myself prefer keeping my tags in an array e.g. `tags: [ tag1, tag2 ]` so a feature like this would be great.

**Comment by JeppeKlitgaard** [comment]
I also use this type of YAML list to do tags, and I think fixing this would be fantastic!

Ideally it would maintain the style used by the user, essentially just replacing the hashtags with nothing
