### ISSUE TITLE
Bug: `YAML Title Alias` does not escape commas

### ISSUE THREAD

**Issue by wrenger** [platers/obsidian-linter#630]
## Describe the Bug

If an h1 contains commas, the generated aliases array entry is not correctly escaped. 
Obsidian expects an array for the aliases field; thus, any entry without quotes that contains commas is interpreted as multiple entries. Unfortunately, headers with commas are not enquoted, resulting in multiple aliases instead of one.

## How to Reproduce

The following example shows the problem:

``` markdown
---
aliases: [Consistent, Durable, and Safe Memory Management for Byte-addressable Non Volatile Main Memory]
---

# Consistent, Durable, and Safe Memory Management for Byte-addressable Non Volatile Main Memory

Lorem Ipsum...
```

Obsidian parses this as multiple aliases:
- Consistent 
- Durable
- and Safe Memory Management for Byte-addressable Non Volatile Main Memory

This can be seen for example in the open document dialog.

<img width="732" alt="file-open-dialog" src="https://user-images.githubusercontent.com/20145354/218313805-a8154d7f-d602-4708-bcf9-348f36b24236.png">

## Expected Behavior

If a title contains commas, it should be enquoted, exactly like if it contains `:` and their like.

``` markdown
---
aliases: ["Consistent, Durable, and Safe Memory Management for Byte-addressable Non Volatile Main Memory"]
---

# Consistent, Durable, and Safe Memory Management for Byte-addressable Non Volatile Main Memory

Lorem Ipsum...
```

The alias is now correct:

<img width="724" alt="file-open-dialog-exp" src="https://user-images.githubusercontent.com/20145354/218314014-f99bfb21-33cd-45f8-8db8-8070fca5fafb.png">

## Device

- [x] Desktop
- [x] Mobile

**Comment by wrenger** [comment]
I just found out that it works correctly with multi-line arrays. Just single-line and single string break.

**Comment by pjkaufman** [comment]
Thanks for reporting this. I will see about fixing this. It seems that I just need to go ahead and escape that value if it is for either of those two types.

**Comment by wrenger** [comment]
Ok thanks!
The multi line workaround is sufficient at the moment, but a single line would be more condense. So I appreciate your work :)

**Comment by pjkaufman** [comment]
I believe I have a fix for this issue. It was much simpler than I thought it would be. However it may not fix existing bad data, so that may need to be dealt with manually.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release. Please let us know if that is not the case.
