### ISSUE TITLE
Bug: incorrect/spurious transformation être → êtree.

### ISSUE THREAD

**Issue by lebigot** [platers/obsidian-linter#633]
## Describe the Bug

When a text contains "être", this word is **transformed into "êtree"**, which is **incorrect** (in French).

## How to Reproduce

0. Make sure that "**Auto-correct common misspellings**" is On in the Linter settings.
1. Type "être" in a note.
2. Launch the linter.

## Expected Behavior

The word "être" should instead not be touched.

## Device

- [X] Desktop
- Mobile not tested

**Comment by pjkaufman** [comment]
Hey @lebigot , is there a reason not to add that value to the ignore list? English is the only language that the auto fix is really designed for. So for French words that may be the case, but when used in English it may not be the same (assuming that is even a thing). However if that is a French word and the English usage is spelled as you suggest, that should probably be bubbled up to the [codespell](https://github.com/codespell-project/codespell) maintainers to get it fixed there as well.

**Comment by pjkaufman** [comment]
I have not heard anything about this. in about 2 weeks. If I do not hear anything else by Sunday, I will close this issue since I am not able to validate the claim here on my own with the information provided.

**Comment by lebigot** [comment]
There is a reason to not add "être" to the ignore list: there is no valid reason for it to be transformed into "êtree" anyway, be it in French or English, where "êtree" doesn't exist, and fixing at the source is more useful for everybody.

Now, codespell 2.2.4 (the latest version) doesn't run into this problem.

Maybe the bug comes from a previous version of codespell? Maybe it is somewhere in linter? Maybe it's a while guess, but maybe linter somehow doesn't recognize the "ê" and codespell applies its rule "tre" → "tree", resulting in "être" being transformed into "êtree", which is not correct?

**Comment by pjkaufman** [comment]
This may be a bug in the Linter where that rule you suggested may be getting applied. Let me see if it gets modified in a UT and move forward from there. The possibility you suggested could be the case. I wonder if python has a different default set for regex which could cause the issue in question.

**Comment by pjkaufman** [comment]
Looks like I have a fix for this. Thanks for taking a look at codespell and verifying it was not in the list @lebigot !

**Comment by pjkaufman** [comment]
The change should go out with the next release.

**Comment by lebigot** [comment]
Great, thanks!
