### ISSUE TITLE
FR: 【Line Break at Document End】Add two line breaks

### ISSUE THREAD

**Issue by calmwaves111** [platers/obsidian-linter#634]
## Is Your Feature Request Related to a Problem? Please Describe.
In obsidian, The content of the two newline breaks  is a block. When I continue to write at the end of the document, it means that I am adding a new block.

**Comment by pjkaufman** [comment]
Hey @irrealizable , could you explain a little more what you mean by your statement? Are you saying that you want an exception to `Line Break at Document End` where it will not affect 2 lines in a row at the end of the document?

**Comment by pjkaufman** [comment]
It has been several days and I have not heard back. I will give this a about a week more before closing it if I do not hear back on this.

**Comment by irrealizable** [comment]
> It has been several days and I have not heard back. I will give this a about a week more before closing it if I do not hear back on this.

no, I mean 【Line Break at Document End】 guarantees a blank line at the end of the document, but I want two blank lines at the end of the document

**Comment by pjkaufman** [comment]
Interesting. I am not sure if this is something that will be added to the Linter, but I am not going to just reject this outright. If there is a desire for the ability to set the amount of blank lines to have at the end of a file, it should not be too hard to add.

**Comment by pjkaufman** [comment]
Hey @calmwaves111 , have you tried enforcing this using Custom Replace? Using regex should handle exactly what you are referring to here.

**Comment by calmwaves111** [comment]
> Hey @calmwaves111 , have you tried enforcing this using Custom Replace? Using regex should handle exactly what you are referring to here.嘿，您是否尝试过使用自定义替换来强制执行此操作？使用正则表达式应该可以准确处理您在这里所指的内容。

You're right, I didn't expect that
Here are my configurations, hoping to help like-minded people
![image](https://github.com/platers/obsidian-linter/assets/56907077/f52a0462-efc1-4dbe-80c4-5ef198c45e0f)
