### ISSUE TITLE
FR: Double spaces at the end of sentences

### ISSUE THREAD

**Issue by RhvdG** [platers/obsidian-linter#638]
## Is Your Feature Request Related to a Problem? Please Describe.

Adding two spaces, instead of just one, at the end of each sentence is an old-fashioned, but legibility enhancing habit.  But I often forget.

## Describe the Solution You'd Like

Lint might check to see if there are instances of just one space between two sentences, and when found, add a space there.

**Please include an example where applicable:**

``` markdown
Hello there. Today is Wednesday.
```

``` markdown
Hello there.  Today is Wednesday.
```

## Describe Alternatives You've Considered

Strengthening the double spaces habit.

**Comment by pjkaufman** [comment]
Thanks for the request @RhvdG . Could you define what would indicate a sentence in this case? I have my own idea of what this looks like, but I am not sure that my idea of what a sentence is and how to determine it programatically lines up with what others think.

**Comment by RhvdG** [comment]
Instead of trying to define 'sentence' I would say a space that needs to be doubled is one following one of these: `.` `?` `!` `.'` `?'` `!'` `."` `?"` `!"` `.’` `?’` `!’` `.”` `?”` `!”` `.»` `?»` `!»` followed by a capitalised word.  There are of course even more types of quotation marks...

**Comment by pjkaufman** [comment]
Hey @RhvdG . I think this is better served by using [custom replace](https://platers.github.io/obsidian-linter/settings/custom-rules/#custom-regex-replacements). Have you tried using this feature?

**Comment by pjkaufman** [comment]
I have not heard back in over a year, so I am going to close this issue. If users do indeed want this feature, it can be reconsidered at a later date.
