### ISSUE TITLE
The number of Footnotes added

### ISSUE THREAD

**Issue by Liong1976** [platers/obsidian-linter#64]
After I used the move-footnotes-to-the-bottom and re-index-footnotes, the number of the footnotes was added.

See the discussion on discord: https://discord.com/channels/686053708261228577/722584061087842365/889892608522997780

**Comment by chrisgrieser** [comment]
Found the issue, have committed a fix in PR #65.

Should be fixed in the next release, until then you can simply deactivate `move-footnotes-to-the-bottom` since that rule causes the issue.

**Comment by Liong1976** [comment]
Great, thanks, Chris!
