### ISSUE TITLE
Bug: Should not handle inline code and block code.

### ISSUE THREAD

**Issue by jerviscui** [platers/obsidian-linter#641]
## Describe the Bug

The inline code `h[^ae]llo` will be formatted as `h[^1]llo`.

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
@jerviscui , do you have the footnote rules on? If so, it is possible that I need to ignore code blocks for the footnote rules.

**Comment by jerviscui** [comment]
Yes, I will turn on the footnote rules.

![image](https://user-images.githubusercontent.com/6396748/224360161-00ebb761-c981-4272-bb50-1617562a94b9.png)

**Comment by pjkaufman** [comment]
I am not sure if you meant to say that you have them turned off or whether you truly mean to say you are turning those rules on. But I am going to assume the prior for now.

**Comment by pjkaufman** [comment]
I have a fix for this from what I can tell. It should take care of the scenario in question so long as there is not another scenario that you are referring to that I am not recognizing.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release. Please let us know if that is not the case.

**Comment by jerviscui** [comment]
I am using v1.12.0 and it works fine, thanks for your work.
