### ISSUE TITLE
FR: Remove Blank Lines in File

### ISSUE THREAD

**Issue by zuojinxin** [platers/obsidian-linter#642]
## Describe the Bug

line-break-at-document-end似乎没有正常工作，勾选Line Break at Document End，运行插件，正文间的间隔没有任何变化

![image](https://user-images.githubusercontent.com/118601868/223988446-8facd425-6ce2-486f-a420-a08f9418320c.png)

**Comment by pjkaufman** [comment]
@zuojinxin , it looks like you are using the wrong rule for what you are trying to do. Line break at the end of the file only affects the end of the file. It looks like you want to use [consecutive-blank-lines](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#consecutive-blank-lines).

Chinese translation via Google Translate:
@zuojinxin ，看起来你对你想做的事情使用了错误的规则。 文件末尾的换行符只影响文件末尾。 看起来您想使用 [consecutive-blank-lines](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#consecutive-blank-lines)。

**Comment by zuojinxin** [comment]
no，“consecutive-blank-lines” ，I've used it，I hope there are no spaces in the text,This habit more accord with my notes
![image](https://user-images.githubusercontent.com/118601868/224023681-80e9254a-27e1-49ad-9203-bd52e774b9c9.png)

**Comment by pjkaufman** [comment]
Ah. That sounds more like you want to use [remove-empty-lines-between-list-markers-and-checklists)](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#remove-empty-lines-between-list-markers-and-checklists), but it also looks like you want spaces removed between paragraph contents. The latter is currently not a feature the Linter provides, but for list items it can remove the lines. Though I see an odd character after the numbers in your list items. What character comes after the number 10 in your list item and is that valid markdown?

**Comment by zuojinxin** [comment]
Thank you for taking the time to answer my questions！

The list is just a random excerpt of text to show the final result, so the number 10 is not important. I would prefer not to have any blank lines in the paragraph content.
Initially, I thought that "line-break-at-document-end" meant adding a line break at the end of each line in the paragraph, which would achieve the effect I needed. However, I misunderstood it.

I can use other methods to remove blank lines, but it would be nice if linter could provide this feature.

**Comment by pjkaufman** [comment]
Would it be a correct understanding that you are requesting that blank lines be removed from files so long as they are not in 
- code blocks
- math blocks

**Comment by csss1234** [comment]
This simple regex removes all blank lines:
![SCR-20230719-mzpj](https://github.com/platers/obsidian-linter/assets/45954264/bf4bd4d4-28e7-4fd4-8177-fc67600ce3c8)

**Comment by pjkaufman** [comment]
There has not been much conversation around this in a while. It looks like this already has a solution via custom regex replacement, so I am going to close this issue. We can reopen the issue if there is a desire to do so.
