### ISSUE TITLE
Bug: H1 first letter capitalisation fails

### ISSUE THREAD

**Issue by RhvdG** [platers/obsidian-linter#647]
## Describe the Bug

H1 Headers are created from the file name, but the first letter (normal a-z letter) is never capitalised.

## How to Reproduce

Run Linter on a file without a H1 header.

Logs don't appear.

## Expected Behavior

Capitalised first letter in generated H1 header.

**Comment by pjkaufman** [comment]
@RhvdG , do you mind giving an example file name? I am guessing it is lowercase, but I am not sure. Does this happen when you run the Linter multiple times? If not, then I am not sure this is a bug since adding the H1 and the capitalization of the first letter of the H1 name does not know about the capitalize header rule.

**Comment by RhvdG** [comment]
@pjkaufman Yes, all lowercase, like ``ervaring.md``. I ran the Linter twice to try, and the second time the first letter *is* capitalised. Perhaps this should somehow happen the when the H1 header is first created from the file name?

**Comment by pjkaufman** [comment]
The rule knows nothing about it, so that would be hard to do. It would only be feasible if the H1 generating rules were set to run before all other regular rules, but after YAML fix rules were applied.

**Comment by pjkaufman** [comment]
Instead of running the H1 rules first, I will move the H1 capitalization rule to run at the end of all other rules and see if it fixes the issue you are describing. I believe it will do the trick, but I will need to do some testing to be sure.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release. I plan to make the release later on today or tomorrow after I add some documentation around adding translation info. Please let us know if this is not fixed on either master or in the next release.
