### ISSUE TITLE
Bug: Paste Seems to Mess with YAML Frontmatter

### ISSUE THREAD

**Issue by SirSpidey** [platers/obsidian-linter#653]
## Describe the Bug

I use a textexpander plain text snippet to create the yaml metadata. When the linter extension is enabled, the yaml is reformatted to invalid yaml even when linting is not run. I haven't been able to identify which linter setting is causing the issue, if that's the problem. 

- When I disable the Linter extension the behavior goes away (snippet works fine)
- I can type the metadata manually with no issue.
- I can use the snippet in another text editor with no issue
- I can use another program to create the snippet and have the same issue (for example, I can reproduce by adding the snippet to Raycast.

## How to Reproduce

1. Create a note in obsidian
2. Run a snippet or macro that outputs the yaml.
3. See error

Although the textexpander snippet has date variables, that isn't the cause of the problem. The snippet in Raycast is just this text, and the reformatting still happens:

```text
---
created: 
aliases: []
source: 
tags: []
updated: 
---
```

## Expected Behavior

Expected output if applicable:

``` markdown
---
created: "2023-03-17"
aliases: []
source: 
tags: []
updated: "2023-03-17T11:51:50-0400"
---
```

## Actual behavior

The 3rd hyphen on the first line and new line are removed

```markdown
--created: "2023-03-17"
aliases: []
source: 
tags: []
updated: "2023-03-17T11:52:15-0400"
---
```

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

[data.json.zip](https://github.com/platers/obsidian-linter/files/11003381/data.json.zip)

**Comment by pjkaufman** [comment]
@SirSpidey , thanks for reporting this. Could you provide the macro in question or one that creates the issue and an explanation on setting that up so I can recreate the scenario? I as it stands I am not sure how to reproduce what you are stating since I do not have a setup like that personally.

**Comment by SirSpidey** [comment]
@pjkaufman Yeah, this is a tough one to reproduce if you don't have either app. I tried reproducing with MacOS text replacements and with a free open source package called [espanso](https://espanso.org/), but neither one cause the issue. I'm not sure what TextExpander and Raycast snippets do differently when they insert the snippets.

[Raycast](https://www.raycast.com/) is free and an awesome new tool. So if you're so inclined 😸 , you could install it and create a [snippet](https://manual.raycast.com/snippets) like the one here. 

<img width="491" alt="image" src="https://user-images.githubusercontent.com/8194208/226056460-92ebe0aa-43b9-4734-9976-34ffe5416066.png">


But if not, you can just close this issue as not reproducible.

**Comment by SirSpidey** [comment]
I couldn't reproduce the issue by using the old obsidian plug-in `Text snippets`, So TextExpander and Raycast, which use keylogger permissions (`Privacy & Security -> Accessibility`), must be doing something that's interpreted differently in Obsidian when your extension is enabled. 

However, I did find a workaround or TextExpander that works with `Linter` and in other text editors: I added a carriage return to the end of first line

![image](https://user-images.githubusercontent.com/8194208/226112966-c938ecff-9356-4472-ab1b-b25a3fab303b.png)

Closing as not reproducible

**Comment by pjkaufman** [comment]
I will note that I see this problem every once and a while when I paste a value. I need to check and see if this is something the Linter accidentally does.

**Comment by pjkaufman** [comment]
Looks like I can reproduce this on my personal setup. It is unclear as to why. I am going to reopen this and see about fixing it.

**Comment by pjkaufman** [comment]
I am guessing this is due to the logic for removing hyphens on paste.

**Comment by pjkaufman** [comment]
I believe that I have a fix for the problem as I am no longer seeing it. I will push up my change to fix this and it should go out with the next release.
