### ISSUE TITLE
Bug: Move tags from body also moves "tags" from other YAML attributes

### ISSUE THREAD

**Issue by SheepYY039** [platers/obsidian-linter#661]
## Describe the Bug

When enabling move tag to YAML, other attributes in YAML which uses the format `#.*` also gets moved to tags

## How to Reproduce

1. Enable `Breadcrumbs` plugin
2. Enable `dataview` plugin
3. Then create a file with the code below

``` markdown
---
BC-dataview-note: "#tag1 and #tag2"
BC-dataview-note-field: parent
---

# Title 

#tag-body
```

`after linting`:
``` markdown
---
tags:
- tag2"
- tag-body
BC-dataview-note: "#tag1 and
BC-dataview-note-field: parent
---

# Title 

```

`config` extract
```json
    "Move Tags to Yaml": {
      "Move all tags to Yaml frontmatter of the document.": true,
      "Body tag operation": "Remove whole tag",
      "Tags to ignore": ""
    }
```

## Expected Behavior

Expected output if applicable:
``` markdown
---
tags:
- tag-body
BC-dataview-note: "#tag1 and #tag2"
BC-dataview-note-field: parent
---

# Title 

```

## Screenshots

`Before linting`
<img width="739" alt="image" src="https://user-images.githubusercontent.com/56354081/227102430-c33959bd-f4c4-4480-a87f-c9e11b231f90.png">

`After Linting`
<img width="787" alt="image" src="https://user-images.githubusercontent.com/56354081/227102479-6ab56e65-c4ba-4dda-a4f0-917b86f7fe15.png">

`Lint again outputs error`
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/56354081/227102526-fde59b35-095d-4ca5-b0b5-be319c7a849b.png">

## Device

- [X] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Thanks for reporting this. It should just require ignoring the YAML frontmatter for parsing the doc for tags, but keep it present for pulling the right value from the frontmatter. Hopefully this will not be too hard to work on.

**Comment by pjkaufman** [comment]
I made an update to the logic. Hopefully it will address this issue. Please let us know if this issue is not fixed on master or in the next release.
