### ISSUE TITLE
Bug: Add space need to ignore filenames

### ISSUE THREAD

**Issue by Erimus-Koo** [platers/obsidian-linter#662]
Turn on the option "Space between Chinese Japanese or Korean and English or numbers"

```html
before
<img src="中文small.png" />

after
<img src="中文 small.png" />
```
Then the image file won't be found.

**Comment by pjkaufman** [comment]
Thanks for pointing this out. It looks like I need to ignore html for "Space between Chinese Japanese or Korean and English or numbers".

**Comment by pjkaufman** [comment]
I can reproduce this issue and I have a potential fix for this.

**Comment by pjkaufman** [comment]
This change should be on Test and master now. I plan to release it later this week.

Please let us know if this issue exists in the next release or on master.

**Comment by Erimus-Koo** [comment]
I've tried the current master version, and it looks great. Thank you for fixing it so quickly.

**Comment by pjkaufman** [comment]
No problem. Easy fixes like this are something I tend to pick up and fix more quickly since I can do it in one sitting.

**Comment by Erimus-Koo** [comment]
And there's one more thing I've just found,

```
Before
<u>「知識」ではなく</u>

After (a Space on the left of the </u> will be created, and the underline will appear on the Space.)
<u>「知識」ではなく </u>
```

I don't want to open a new issue so append it here.

**Comment by pjkaufman** [comment]
> And there's one more thing I've just found,
> 
> ```
> Before
> <u>「知識」ではなく</u>
> 
> After (a Space on the left of the </u> will be created, and the underline will appear on the Space.)
> <u>「知識」ではなく </u>
> ```
> 
> I don't want to open a new issue so append it here.

This one is actually quite different as it deals with html and will be a decwnt bit harder to deal with.

**Comment by Erimus-Koo** [comment]
Yes, agree.
I add a new issue here #667
