### ISSUE TITLE
Bug: Consecutive Blockquotes Merging

### ISSUE THREAD

**Issue by usernotnull** [platers/obsidian-linter#668]
## Describe the Bug

After updating to 1.11.0, consecutive blockquotes are merged, the empty lines in between not serving as separation anymore but replaced by ">".

Suspect due to https://github.com/platers/obsidian-linter/pull/658

## How to Reproduce

Example to reproduce issue with

``` markdown
> [!quote] Title 1
> The quote 1

> [!quote] Title 2
> The quote 2
```

## Expected Behavior

Keep empty lines between consecutive blockquotes.

Expected output: No change

What I got:
``` markdown
> [!quote] Title 1
> The quote 1
>
> [!quote] Title 2
> The quote 2
```

**Comment by pjkaufman** [comment]
I should be able to just do a check if the type is a blockquote and if so a blank line then should not be allowed to go into any non-whitespace line after that.

**Comment by pjkaufman** [comment]
I believe that I have a fix for this issue. It does not seem too bad to fix, but there may be some other lingering scenarios out there. I am going to double check that I don't see any other issues in my personal vault before continuing with this fix.

**Comment by pjkaufman** [comment]
Everything looks good, so I will go ahead and get this on master. It should go out with the next release.

**Comment by pjkaufman** [comment]
The changes should be on master and in the next release. Please let us know if that is not the case.
