### ISSUE TITLE
Rule line-break-at-document-end not recognized

### ISSUE THREAD

**Issue by Columpio** [platers/obsidian-linter#67]
I get a popup message "`Rule line-break-at-document-end not recognized`".
My rules:
```
trailing-spaces
space-after-list-markers
header-increment
re-index-footnotes
move-footnotes-to-the-bottom
line-break-at-document-end
```
Obisidian v0.12.15
Linter v1.1.5

**Comment by chrisgrieser** [comment]
Thats because the readme is ahead of the actual releases. Line break at document end is a new rule that will be available in the upcoming release

**Comment by platers** [comment]
updated the readme to make this more clear. The new UI should help too
