### ISSUE TITLE
FR: Translate into Chinese

### ISSUE THREAD

**Issue by windily-cloud** [platers/obsidian-linter#685]
## Is Your Feature Request Related to a Problem? Please Describe.

I don't know if anyone is involved in this contribution, if not I can help translate it into Chinese.

I can translate the language of the ui interface into Chinese, which can help Chinese people to use the plugin better, I don't know what your requirements are. I don't intend to translate the documentation, because the workload for this may be rather large.

## Describe the Solution You'd Like

You specify where I need to translate (in addition to the documentation) and I will PR after translation

**Comment by pjkaufman** [comment]
So if you wanted to translate all keys for `zh-cn` you would clone the repo, and either manually copy the structure of `en.ts` to `zh-cn.ts` and fill out the strings from there or do so via the script that helps setup the actual structure of the language without any need to directly update an existing file.

To use the script:
- Clone this repo
- Then run `npm ci`
- Once that finishes, run `npm run translate`
- You will see the following and want to specify `T` as that allows translation of all keys in a specific language.

``` bash
  =========================================================================
  Select a translation mode to use:
  [A]dd a translation value for a specific language.
  [L]ist untranslated keys in the specified language.
  [R]eplace translated value with a new value for the specified key.
  [T]ranslate all untranslated keys in a language one at a time.
  =========================================================================
```

It should then prompt you for the language to translate which would be `zh-cn`.

From there it should allow you to translate as many keys as you choose.

-

**Comment by pjkaufman** [comment]
I believe this was taken care of by #688 . As such I will close this FR as it should go out this release. I still need to look into potential issues with the translation helper and show that code some love. But that is a separate issue (#689 ).
