### ISSUE TITLE
Bug: Header Increment increments the wrong headers.

### ISSUE THREAD

**Issue by MoonBrew** [platers/obsidian-linter#686]
## Describe the Bug

The header increment does not behave as expected. It changes level 2 headers (##) to level 3 (###) where it shouldn't after lint on save.

## How to Reproduce
Use the setting that `Heading levels should increment by one level at a time` and `Start Header increment at Heading level 2`.
Example to reproduce issue with

``` markdown
## Primitive Literal

### Character

- use `''`.

### String

- use `""`.
- Is a [[#List]].

## Condition

- `else` compulsory as is [[expression]].  

## Function

- `'` is allowed. Denotes a stricter version (non-lazy) / slight modification of a function.
- can't start with capital.
```

Every time I save on lint the last heading becomes a level 3 heading even though I don't want it to.

## Logs
```
Running linter
Running Format Tags in YAML
Running Escape YAML Special Characters
Running Format Yaml Array
Running Insert YAML attributes
Running Capitalize Headings
Running Header Increment
Running Headings Start Line
Running Remove Trailing Punctuation in Heading
Running Footnote after Punctuation
Running Move Footnotes to the bottom
Running Re-Index Footnotes
Running Auto-correct Common Misspellings
Running Convert Bullet List Markers
Running Emphasis Style
Running No Bare URLs
Running Ordered List Style
Running Proper Ellipsis
Running Remove Consecutive List Markers
Running Remove Empty List Markers
Running Remove Hyphenated Line Breaks
Running Remove Multiple Spaces
Running Strong Style
Running Two Spaces Between Lines with Content
Running Unordered List Style
Running Compact YAML
Running Consecutive blank lines
Running Convert Spaces to Tabs
Running Empty Line Around Blockquotes
Running Empty Line Around Code Fences
Running Empty Line Around Math Blocks
Running Empty Line Around Tables
Running Heading blank lines
Running Line Break at Document End
Running Move Math Block Indicators to Their Own Line
Running Paragraph blank lines
Running Remove Empty Lines Between List Markers and Checklists
Running Remove link spacing
Running Space after list markers
Running Trailing spaces
Running Custom Regex
Running YAML Timestamp
Running YAML Key Sort
Running Custom Lint Commands
```

## Expected Behavior

The last heading (## Function) should remain as a level 2 heading after lint on save.

## Device

- [x] Desktop
- [ ] Mobile

**Comment by MoonBrew** [comment]
I can have a look at the header increment logic if I have the time.

**Comment by pjkaufman** [comment]
@MoonBrew , could you provide your `data.json`? I am not seeing the change you mention when just using the rule you are referring to. I am guessing it is caused by multiple rules running in such a way that they conflict with each other.

**Comment by MoonBrew** [comment]
Here you go.
[data.json.txt](https://github.com/platers/obsidian-linter/files/11243104/data.json.txt)

**Comment by pjkaufman** [comment]
I am not seeing the issue with the `data.json` provided. Are you using the latest version of the Linter? Based on your `data.json` I have a feeling you are several versions behind the latest as the config keys were changed a couple of releases ago.

**Comment by MoonBrew** [comment]
I will check. If not updated, will update and check.

**Comment by MoonBrew** [comment]
So this isn't happening in the updated version. Thanks for the support.
