### ISSUE TITLE
Use markdownlint

### ISSUE THREAD

**Issue by NomarCub** [platers/obsidian-linter#7]
[markdownlint](https://github.com/markdownlint/markdownlint) is an existing semi-popular tool for markdown linting.
Using it provides you with more rules than this plugin. Rules that you can enforce outside of Obsidian, which makes people less dependent on the plugin and the rules more portable. It has a command line tool and a VSCode plugin among other things.

Without using markdownlint or consulting with existing plugin devs ([Markdown prettifier](https://github.com/cristianvasquez/obsidian-prettify), [prettier](https://github.com/hipstersmoothie/obsidian-plugin-prettier)) this is just another formatter with its own proprietary set of rules.

**Comment by platers** [comment]
I'm aware of those projects, and was heavily inspired by them! Markdown prettifier and prettier are both very opinionated and rely on external libraries, making them difficult to configure for users and devs. The goal of Linter is to match the configurability of markdownlint without having to leave obsidian. I hope all the rules from markdownlint will be implemented at some point.
I'm open to suggestions :)

**Comment by simonwiles** [comment]
> The goal of Linter is to match the configurability of markdownlint without having to leave obsidian.

Should just use `markdownlint` under the hood.  Would make a more complete and robust offering that would be interoperable with other tools.

**Comment by platers** [comment]
I agree, would like some integration with established linters.
