### ISSUE TITLE
Bug: "Lint folder" notification missing folder name

### ISSUE THREAD

**Issue by ekamil** [platers/obsidian-linter#700]
## Describe the Bug

The alert that pops up when linting a folder contains a placeholder instead of folder's name

## How to Reproduce

1. Go to file browser/"navigation" (built-in)
2. Right click on a folder
3. Select "Lint folder"
4. See the unfilled alert/notification

## Expected Behavior

FOLDER_NAME should actually contain folder's name :) 

## Screenshots

<img width="288" alt="Screenshot 2023-04-28 at 09 28 28" src="https://user-images.githubusercontent.com/1164694/235083417-86f5cafb-d3e0-41d4-8639-9fa3e714bacb.png">

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
This has already been addresswd by a PR that has been merged into master and will go out next release: #695 .

**Comment by pjkaufman** [comment]
I am going to close this since it has already been addressed.
