### ISSUE TITLE
FR: Hide Right-Click Menu Item "Lint Folder"

### ISSUE THREAD

**Issue by coswvw** [platers/obsidian-linter#703]
I hope to have a setting option that could hide the right-click menu item "Lint Folder". This menu item is often not necessary since we only lint a single file in most cases, or please, give it a more nice icon. The current icon is really ugly and does not match the original icon style of Obsidian.

**Comment by pjkaufman** [comment]
Thanks for the feedback @coswvw.

I don't think I will be removing the lint folder icon, but if you have a recommended icon that looks better, then I am open to suggestions on this.

**Comment by coswvw** [comment]
Thanks. I have downloaded two example icons from some websites for your reference.

Lint Folder:

![ec6c](https://user-images.githubusercontent.com/15816345/236095608-80d10a92-86ef-4350-ad63-fc306ee25f85.png)

![f156](https://user-images.githubusercontent.com/15816345/236095630-96997854-7da7-4e83-b899-2cef2074a52e.png)

Compared to what icons you currently used, I think Obsidian's icons are more regular in shape and more rounded and simple in line. Perhaps another issue is more critical, I think your icons are a little big, which makes them mismatched with Obsidian's icons.

The related actions may not necessarily have to use icons that truly represent their meaning, we can use other relatively abstract icons. For example:

![123](https://user-images.githubusercontent.com/15816345/236100074-e17082d9-6fc5-402c-b1d6-e8a47fd0c0e7.png)

This is now a formatting command I added in right-click menu of edit area (based on Plugin: Commander), I use an aperture icon.

Maybe you can find a good alternative from these websites:

* https://fluenticons.co/
* https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font
* https://mui.com/material-ui/material-icons/

Of course, I still prefer if you could add a setting option to freely choose whether to display or hide menu items.

**Comment by coswvw** [comment]
Thank you again! 

Perhaps this comment is my personal opinion. Regarding this, I found a better solution. I tried modifying the code of the plugin (i.e., main.js) and disabled the menu items. 

No more troubles. Have a nice time!
