### ISSUE TITLE
Rule Suggestion: Dumb Quotes

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#707]
## Is Your Feature Request Related to a Problem? Please Describe.

For consistency and/or pandoc exports, it's often preferable to use "dumb quotes" instead of smart quotes. 

## Describe the Solution You'd Like

though there are probably forms of "smart" quotes I haven't considered.
```regex
/[„“”]/"/g
/[‚’]/'/g
```

**Please include an example where applicable:**

``` markdown
„foo“
```

``` markdown
"foo"
```

## Describe Alternatives You've Considered

Adding a custom linter rule works fine for this. Just found it useful enough to suggest in general.

**Comment by pjkaufman** [comment]
@chrisgrieser , is this something that would just affect non-code , math, and yaml blocks? If so, it should not be too hard to add. This is the second time I have gotten this request, and I would like like to make sure I understand the scope of the functionality. Likely it would be a dropdown that let you choose the quote to use and it would replace all of the related quotes with the selected quote.

The only problem I am thinking of would be when dumb quotes are used whether or not the same quote is used for opening and closing quotes. Hopefully it would distinguish the 2, but you never know.

Here is the related FR: #399

**Comment by chrisgrieser** [comment]
> is this something that would just affect non-code , math, and yaml blocks? 

Yep!

> The only problem I am thinking of would be when dumb quotes are used whether or not the same quote is used for opening and closing quotes. Hopefully it would distinguish the 2, but you never know.

Well, they are called dumb quotes for a reason ;)

But yes, strictly speaking, there is information loss, though in practice it does not really matter.

**Comment by pjkaufman** [comment]
I believe I found a methodology to follow when converting straight quotes to smart quotes. It is not the most robust and has some scenarios that it does not address, but that can be ironed out down the road. I plan to implement this change allowing a person to specify the single and double quote styles for body content. That should address this and the other ticket.

**Comment by pjkaufman** [comment]
This rule should be added in the next release. If it has any issues please let us know.
