### ISSUE TITLE
FR: I would like to add a group to the rexexp transformation

### ISSUE THREAD

**Issue by mineclover** [platers/obsidian-linter#709]
I'd like to have an interface that allows me to modify the lint for a group that can be found with a regular expression.

## Describe the Solution You'd Like

Lint now changes everything queried
I wanted to delete only groups, not matches

**Please include an example where applicable:**

``` markdown
---
name : hello
type : post
tags : name , dev
---

```

``` markdown
---
name : hello
type : blog
tags : name, dev
---
If you want to load the type in a track that starts with hello in the name, but only the front matter needs to apply the regular expression, place a complex regular expression.
Choosing to do without caring about groups in these situations it is very difficult

```

## Describe Alternatives You've Considered

to get closer to the group
Just being able to separate the matches and groups and select only group 1 to display the content would be enough.

## Additional Context

![image](https://user-images.githubusercontent.com/61359316/236698868-7057e893-3ca9-48b1-8437-e1f2028cf388.png)
`(?<=]()(?:[^)]+)()(?=)|#)`
Originally, I tried to find `[](test)` but failed.
Putting in a regex that works well but has loopholes

**Comment by mineclover** [comment]
I think I can fix it by using the $1 flag, thanks

**Comment by pjkaufman** [comment]
Gotcha. I hope that works for you. Assuming the group works in the regex on matching the right text, then the `$GROUP_NUMBER` should work.
