### ISSUE TITLE
A Footnote Text is Added

### ISSUE THREAD

**Issue by Liong1976** [platers/obsidian-linter#71]
This time, a footnote text was added after I had executed the Linter plugin.

Here is the initial note:
![image](https://user-images.githubusercontent.com/88898230/134656018-ba3894a8-a287-4ae7-b8fe-e75d4abcd957.png)

Here is the modified one:
![image](https://user-images.githubusercontent.com/88898230/134656149-b5640f16-37a6-421e-bef5-97a6fbbfbe1c.png)

See the uploaded files in https://discord.com/channels/686053708261228577/722584061087842365/890900413547696139

**Comment by chrisgrieser** [comment]
Sorry, I overlooked the case of not having a line break at the end of the document before linting, when committing the last fix.

The next #72 should fix this now properly.
