### ISSUE TITLE
Minor Visual Bug: "Yaml" cased inconsistently

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#711]
![CleanShot 2023-05-08 at 19 04 26@2x](https://user-images.githubusercontent.com/73286100/236885896-53b82709-b88e-4afc-b7f8-da53ca960fcd.png)

**Comment by pjkaufman** [comment]
I should be able to go ahead and fix this now. I will go ahead and do so. Hopefully no one is running a really old version of the plugin still. If so, then it will not do so well for them to upgrade to the latest after this.

**Comment by pjkaufman** [comment]
This change should be on master and go out in the next release. Thanks for reminding of this issue!
