### ISSUE TITLE
FR: Insert YAML attribute dynamic

### ISSUE THREAD

**Issue by xiongwei0714** [platers/obsidian-linter#712]
Can the plugin get the file title use below code?
filename : {{title}}
I tried, it did not get the file title, it is what it looks like.
If I used the wrong grammar, please correct me. If it doesnot support now, I think it is better to support it.

**Comment by pjkaufman** [comment]
We currently do not support dynamic values. That is more of where Templater or other plugins come into play. The title can be set via the [yaml title rule](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#yaml-title). The rule lets you specify the key to put the title in.

**Comment by xiongwei0714** [comment]
> We currently do not support dynamic values. That is more of where Templater or other plugins come into play. The title can be set via the [yaml title rule](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#yaml-title). The rule lets you specify the key to put the title in.

Thanks. 
Firstly, "title" is only an example. If  linter  can also trigger templater command e.g. <% tp.time.yesterday %> or obsidian build-in code e.g. {{title}}, it will be better.
Secondly, if dynamic value cannot be supported, can the YAML title rule add a option-always use file name as title no matter H1 exsists or not ?

**Comment by pjkaufman** [comment]
Adding support for dynamic syntax is not something that makes sense to do in the Linter, so it would have to be something that would be done by the respective plugins.

As for the second option, I am not entirely sure why the separation is needed. This is the second request I have gotten around it, so I would like to better understand what the intent is behind the request to break the two rules apart. I would only add an option to the existing rule to pull from H1 as it stands so you could choose not to pull from the H1 if you only wanted to use the file name. However I am not sure if that is what is desired here.

**Comment by pjkaufman** [comment]
Also, does the request [here](https://github.com/platers/obsidian-linter/issues/205) satisfy what you are looking for? If so, I may just go ahead and bite the bullet breaking the 2 rules apart since that would make this around 4 people requesting the change thus far.

**Comment by xiongwei0714** [comment]
>  I would only add an option to the existing rule to pull from H1 as it stands so you could choose not to pull from the H1 if you only wanted to use the file name. However I am not sure if that is what is desired here.
This is what I want.

**Comment by xiongwei0714** [comment]
> Also, does the request [here](https://github.com/platers/obsidian-linter/issues/205) satisfy what you are looking for? If so, I may just go ahead and bite the bullet breaking the 2 rules apart since that would make this around 4 people requesting the change thus far.



> Also, does the request [here](https://github.com/platers/obsidian-linter/issues/205) satisfy what you are looking for? If so, I may just go ahead and bite the bullet breaking the 2 rules apart since that would make this around 4 people requesting the change thus far.

This is also good and more flexible than only add an option in your last reply.

**Comment by pjkaufman** [comment]
The only issue that arises is you cannot have both in that case. I may just convert the all 3 rules into 1 and use a dropdown to determine what value is pulled for the title in the YAML. It maay be the most flexible and allow for better handling of the data.

**Comment by pjkaufman** [comment]
The change to `YAML Title` adding 3 modes (one for how it currently works, one for just the filename, and one for just the first H1) should go out with the next release. Please let us know if this does not work on master or in the next release.
