### ISSUE TITLE
Footnote number(s) (still) added

### ISSUE THREAD

**Issue by Liong1976** [platers/obsidian-linter#73]
See the uploaded files here: https://discord.com/channels/686053708261228577/722584061087842365/890925403861024819

I think the pattern is that for every seven footnotes there is one additional footnote number.

**Comment by chrisgrieser** [comment]
ah yes, I think I found the issue... will fix later

**Comment by chrisgrieser** [comment]
next commit at #72 should fix this.

**Comment by chrisgrieser** [comment]
fixed with latest release.
@platers, you can can close this one :)
