### ISSUE TITLE
Bug: Too many warning inside develop tool

### ISSUE THREAD

**Issue by CaptainVincent** [platers/obsidian-linter#734]
## Describe the Bug

Error: Component for proper lifecycle management is missing. This is needed to avoid memory leaks when embedded contents register global event handlers. Please let the plugin's author mentioned in the stack trace know.
 
## How to Reproduce

Open develop tool check `console`

I'm seeing hundreds of these warnings, and I didn't encounter these issues in the previous weeks.

I'm not sure if this is related to conflicts with other plugins or obsidian version, 

but simply (a b testing) disabling this plugin could resolves the issue.

## Expected Behavior

Remove unnecessary warnings.

## Screenshots
<img width="616" alt="warning" src="https://github.com/platers/obsidian-linter/assets/12159865/99cff126-b2a9-48e1-a411-89262edbdac5">

## Device

- [x] Desktop - Mac M2
- [ ] Mobile

## Additional Context

About Obsidian Version 1.3.3 (Installer 1.2.7)
Linter 1.15.0

**Comment by pjkaufman** [comment]
@CaptainVincent , have you verified that disabling the Linter causes the warnings to go away?

I am asking because I did not see these warnings yesterday, but I might not be on the latest version of Obsidian.

**Comment by pjkaufman** [comment]
This probably has to do with the latest update and memory leaks they said they figured out were happening due to plugins. I am not sure that the Linter is causing any memory leaks, but I will gladly apply the fix to the plugin if the Linter does get the warnings.

**Comment by pjkaufman** [comment]
I believe I have a fix for this. It should go out with the next release which will hopefully be a patch today or tomorrow, but we will see how that turns out.

**Comment by pjkaufman** [comment]
Also note that I am not seeing the same behavior as you are. I am just seeing the warning logged once for the Linter which likely means that other plugins are also having this issue.

**Comment by pjkaufman** [comment]
Looks like the fix I wanted to use is not something I am supposed to use. I am waiting on feedback on how to do what has been requested with the new update, but so far it seems like I don't have a good way of fixing this at this time.

**Comment by pjkaufman** [comment]
This issue should be fixed with the next release. Thanks for reporting it.

If the issue persists after the next release, please turn off a plugins except the Linter and verify that this is an issue specific to the Linter as there seem to be a decent amount of plugins that have this warning.

**Comment by CaptainVincent** [comment]
Sorry for the late response. I apologize for not seeing your reply earlier. This issue could be resolved on my local end by disabling the extension (clearing all warnings). However, I understand that you mentioned experiencing this phenomenon only once, so it cannot be ruled out that it was triggered by another extension recursively. Thank you very much for your quick fix, and I look forward to the next release. THANK U 💯

**Comment by pjkaufman** [comment]
You should be able to update to version 1.15.1, @CaptainVincent  and the issue should be resolved for the Linter.

**Comment by CaptainVincent** [comment]
@pjkaufman Great! It's fixed now. Thanks again!
