### ISSUE TITLE
Disable all doesnt disable custom rules

### ISSUE THREAD

**Issue by tim-hilde** [platers/obsidian-linter#739]
## Describe the Bug

Using the yaml key to disable all rules does not disable custom rules 

```
---
disabled rules: [ all ]
---
```

## How to Reproduce
1. Use custom rules
2. Disable all rules via yaml frontmatter
3. lint file

**Comment by pjkaufman** [comment]
Thanks for reporting this @tim-hilde , I believe that is by design, but I will have to take another look. There was no disable option added for custom regex and custom commands if I recall.

**Comment by pjkaufman** [comment]
So I am thinking that the best solution for this is to short circuit before running running rules if the option for all rules are disabled. The change would need to happen [here](https://github.com/platers/obsidian-linter/blob/8faa95c12f30582196d111ea10849ff724ac9137/src/rules.ts#L168-L200). It would need to add a boolean value where it would return true if the file should be ignored. That value would either need to bubble up, or it will need to go ahead and be done higher up in the stack.

**Comment by wickles** [comment]
I am also running into this with custom regex replacements still running in content after a `<!-- linter-disable -->`.

**Comment by pjkaufman** [comment]
I will see about tackling both problems in one go. They are a little bit related (they are in the same area of the code). So I will go ahead and make a change to that area and see how things go. I am revamping the tests for the rules runner so it should help take care of the regex replace issue pretty easily.

As for the fact that custom commands are not affected, that might need a little more work to make it play nice since it requires some more information to be present that was not previously being used.

**Comment by pjkaufman** [comment]
@tim-hilde , what specifically are you calling custom rules? Does that include both custom commands and custom replacement?

**Comment by tim-hilde** [comment]
> @tim-hilde , what specifically are you calling custom rules? Does that include both custom commands and custom replacement?

I am only using custom replacements

**Comment by pjkaufman** [comment]
> > @tim-hilde , what specifically are you calling custom rules? Does that include both custom commands and custom replacement?
> 
> I am only using custom replacements

Gotcha. I am adding the change for both of them. So it should not run either custom commands or custom replacements if disable all is present.

**Comment by pjkaufman** [comment]
These 2 issues should be resolved on master and be in the next release. Please let us know if there are any issues with master or the next release.
