### ISSUE TITLE
Notifications don't disappear

### ISSUE THREAD

**Issue by tim-hilde** [platers/obsidian-linter#740]
## Describe the Bug
Notifications don't disappear

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
This was an intentional change except for the initial message for linting and characters changed notification.

This should get fixed in the next release.

**Comment by pjkaufman** [comment]
The following lines would need to be changed:  https://github.com/platers/obsidian-linter/blob/master/src/main.ts#L424

I can technically fix this by removing the `userClickTimeout` on that line. I just cannot compile new files for a patch as I do not have my computer.

**Comment by pjkaufman** [comment]
The fix has been created for this. I may be able to monkey wrench a patch in, but I am not able to ensure this as I cannot currently build the plugin for release (i.e. I would need to manually update a `main.js` and push that out from there.

**Comment by pjkaufman** [comment]
This should be fixed in the latest patch: v1.15.2
