### ISSUE TITLE
Bug: Numerical aliases need to be quoted to work

### ISSUE THREAD

**Issue by finn-matti** [platers/obsidian-linter#747]
## Describe the Bug

Purely numerical aliases (e.g. `20230603151900`) need to be quoted to make them work in obsidian. The linter doesn't pick this up, yet.

## How to Reproduce

Steps to reproduce the behavior: See [this forum post](https://forum.obsidian.md/t/cannot-use-uid-as-alias/20306/3). The described behavior is still found in today's Obsidian.

## Expected Behavior

Purely numerical aliases are quoted to make them valid (e.g. `"20230603151900"`).

## Device

- [x] Desktop
- [x] Mobile

**Comment by pjkaufman** [comment]
@finn-matti , I think I understand what you are saying. Thanks for bringing this to my attention. Which rules would this be expected to affect?
Would it just be [YAML Title Alias](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#yaml-title-alias)?

**Comment by pjkaufman** [comment]
I may have a fix for this, but it will depend on what YAML alias formats have the issue with needing to escape numeric values.

**Comment by pjkaufman** [comment]
Looks like this applies to all of the alias formats. I will go ahead and merge the fix.

**Comment by pjkaufman** [comment]
Updated the logic around this for `YAML Title Alias`. This should go out with the next release. It is on master for the repo. Please let us know if there are any issues with this after the next release or on master.

**Comment by finn-matti** [comment]
Whoa! Would have been nice to give me a chance to react!

What about the rewriting of aliases? Shouldn't they also been quoted? E.g.:

Before:

```
aliases: 20230614100140
```

After (with single line, for example):

```
aliases: ["20230614100140"]
```

**Comment by pjkaufman** [comment]
> Whoa! Would have been nice to give me a chance to react!
> 
> What about the rewriting of aliases? Shouldn't they also been quoted? E.g.:
> 
> Before:
> 
> ```
> aliases: 20230614100140
> ```
> 
> After (with single line, for example):
> 
> ```
> aliases: ["20230614100140"]
> ```

Sorry. I tend to go a mile a minute with code changes. Existing aliases are not touvhed as I do not believe there is a rule for this in particular. So existing aliases are left as is. Is there a particular rule you were referring to with that?

**Comment by finn-matti** [comment]
>Existing aliases are not touched as I do not believe there is a rule for this in particular.

I think I get what you're saying, but imho, if you change the style of aliases and there is an invalid alias in there, this should lead to a fix, right?

**Comment by pjkaufman** [comment]
> > Existing aliases are not touched as I do not believe there is a rule for this in particular.
> 
> I think I get what you're saying, but imho, if you change the style of aliases and there is an invalid alias in there, this should lead to a fix, right?

So, to clarify, you are saying that `format-yaml-arrays` should also deal with this? I ask because it is formatting a valid YAML array. The only thing invalid is how that array is handled in Obsidian, technically.

**Comment by finn-matti** [comment]
>So, to clarify, you are saying that format-yaml-arrays should also deal with this? I ask because it is formatting a valid YAML array. The only thing invalid is how that array is handled in Obsidian, technically.

I'd expect the frontmatter to be linted for the Obsidian use case, yes.

Also, check out this comment from the aforementioned thread in the Obsidian forums by WhiteNoise of the Obsidian team:

>The notation without quotation marks makes certain inputs easier but is not-standard and it creates oddities like the one that you just discovered.

I don't know exactly how to parse "non-standard", but it seems to be standing at odds with what you're saying.

P. S.: I actually appreciate your trying to get your hand around the requirements.

**Comment by pjkaufman** [comment]
YAML is non-standard which creates problems. I can try to build it into formatting aliases that they need to be escaped. However, that may cause unexpected results and I may need to pass even more keys down the chain. I will see what I can do though.

**Comment by pjkaufman** [comment]
Looks like for simplicity, I would add an optional param called `escapeNumericValues`  and just escape numeric strings that are not already escaped.

This is a dev note for later when I get a chance to take another look.

**Comment by pjkaufman** [comment]
The change for this has been merged into master and should go out with the next release. Please let us know if there are any issues with it on master or in the next release.
