### ISSUE TITLE
FR: No bare URIs

### ISSUE THREAD

**Issue by nhan000** [platers/obsidian-linter#767]
## Is Your Feature Request Related to a Problem? Please Describe.
URI such as `obsidian://show-plugin?id=cycle-in-sidebar` and `zotero://select/library/items/6R98DML4` need to be wrapped in `<>` in order to be clickable in Reading Mode.

## Describe the Solution You'd Like

Linter detects these URIs and autowraps them in `<>`, similar to the [No Bare URLs](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#no-bare-urls) feature.

Example:

Before
``` markdown
obsidian://show-plugin?id=cycle-in-sidebar
```
After
``` markdown
<obsidian://show-plugin?id=cycle-in-sidebar>
```

## Describe Alternatives You've Considered

Just manually add `<` and `>`. However, Obsidian doesn't autopair `<` (understandable because `<` is used a lot for other things), so it's quite cumbersome to do.

**Comment by pjkaufman** [comment]
Thanks for the input @nhan000 .

I am having trouble finding a good way of identifying URIs which would make implementing this change a bit difficult. Do note that URLs are a subset of URIs which means that we should probably just combine the 2 rules into 1 since escaping URIs would escape URLs.

**Comment by nhan000** [comment]
Thanks. Preface this with me not knowing anything about programming:

I'm wondering if the complicated thing here is the various variable of the app `obsidian` or `zotero`, etc. and it's hard to make a regex to recognize these URIs (instead of just `https://` in URLs)? If so users can have an input box to put the name of the app that they regularly use for their URIs, such as "obsidian" and "zotero" and that would help with recognition of the URIs. If that works, you don't have to come up with a solution that encompass every URI-supported app imaginable. Users likely will use a few app that support URIs anyway so it should not be a big deal to have to input those?

**Comment by pjkaufman** [comment]
Allowing for a manual list of app names may work, but I am looking to see if there is a better option.

As for [Paste URL into selection](https://github.com/denolehov/obsidian-url-into-selection), it just has to determine if the text you are pasting or the text selected is a URL. It does not identify URLs or URIs throughout a file. A URI is much easier to detect as the only text selected or being pasted rather than parsing it out of a string which is why they can do it there, while I am having a bit of a harder time.

**Comment by pjkaufman** [comment]
I may have a potential solution, but I am not sure. It is related to #776 .

**Comment by pjkaufman** [comment]
I will be expecting the URIs to follow the following format:
`URI_SCHEME://REMAINING_VALUE`
- `URI_SCHEME` can be any combination of letters, numbers, or dashes
- `REMAINING_VALUE` can be just about any valid URL character, but it will not include whitespace and cannot end in whitespace, a double quote, a single quote, a closing paren, a period, a question mark, or an exclamation mark

Here is a list of URIs I have tested the regex against:
``` plaintext
applenews://
applenewss://
itms-apps://itunes.apple.com
music://
musics://
audio-player-event://
applenews://
applenewss://
itms-apps://itunes.apple.com
itms-apps://search.itunes.apple.com/WebObjects/MZSearch.woa/wa/search?media=software&term=
itms-apps://itunes.apple.com/WebObjects/MZStore.woa/wa/viewTop?genreId=36&popId=30
itms-apps://itunes.apple.com/updates
videos://
calshow://
x-apple-calevent://
webcal://suscribelinkforcalendar
clips://
contacts://
diagnostics://
diags://
facetime-audio://phoneoremail
facetime-audio-prompt://phoneoremail
facetime://phoneoremail
facetime-prompt://phoneoremail
applefeedback://
findmyfriends://
fmf1://
grenada://
fmip1://
shareddocuments://
gamecenter://
itms-gc://
itms-gcs://
garageband://
 headspace://
ibooks://
itms-books://
itms-bookss://
appleiclouddrive://
imovie://
remote://
itms://
itmss://
itms-itunesu://
map://
maps://
mapitem://
message://
mailto://emailaddress
sms://phonenumber
mobilenotes://
tel://phonenumber
telprompt://phonenumber
photos-redirect://
feed://
podcast://
pcast://
itms-pcast://
itms-pcasts://
podcasts://
itms-podcast://
itms-podcasts://
x-apple-reminder://
x-web-search://
ftp://locationtofileonftpserver
http://websiteurl
https://websiteurl
App-prefs://
App-prefs:
prefs://
prefs:
prefs:root
shortcuts://
voicememos://
shoebox://
itms-watch://
itms-watchs://
workflow://
workflow://create-workflow
workflow://open-workflow?name=name
workflow://run-workflow?name=name&input=input
workflow://gallery
workflow://gallery/search?query=query
onepassword://search/{query}
ophttp://{url}
achievement://
fb1431194636974533://
amc://
fb1414385748867269suffix://
fb1761190244145574amplifi://
ancestry://
anchorfm://
anchorfmspotify://
com.popcap.ios.BejBlitz://
com.popcap.ios.BejBlitz.From.Bej3://
com.popcap.ios.BejBlitz.From.Bej2://
ea850758://
ea47862://
teamblind://
bloomberg://
brushstroke://
cakeslice://
havecake://
cameraplus://
squarecash://
cashme://
castro2://
castro2://podcast/19d759ce-5a6b-43ef-b7b2-39469df85f47
citymapper://directions?startcoord=<lat>,<lon>&startname=<name>&startaddress=<address>&endcoord=<lat>,<lon>&endname=<name>&endaddress=<address>
clashofclans://
wxfa242abf8cdd841a://
tencent1105771533://
tencentlaunch1105771533://
doordash://
fb225826214141508paid://
dbapi-1://
ddgLaunch://
ddgQuickLink://
duolingo://
com.duolingo.DuolingoMobile
evernote://x-callback-url/[action]?[action parameters]&[x-callback parameters]
fb://
facetune://
fandango://
fantastical://
fantastical2://
fitbit://
flickr://
forest://
gboard://
yuanshengame://
github://
googlegmail://
goodreads://
google://
googleassistant://
googlecalendar://
googledocs://
googledocs-v2://
com.google.sso.263492796725://
googlechrome://
googledrive://
googleearth://
comgoogleearth://
comgooglekeep://
googlemaps://
googlephotos://
googlesheets://
googletranslate://
googlevoice://
halide://
hbogo://
hbonow://
hulu://
hyperlapse://
ifttt://
imdb://
instagram://
instagram-stories://share
instapaper://
lastpass://
launch://
litely://
wear://
fb-messenger://
moviepass://
myliftmaster://
nflx://
overcast://
paypal://
photoscan://
pinterest://
plex://
pyto-run://
sgnl://
skype://
snapchat://
speedtest://
spotify://
steller://
sleeptown://
tumblr://
twitch://
twitter://
tweetbot://
vimeo://
vlc://
vsco://
waze://
whatsapp://
youtube://
```

**Comment by pjkaufman** [comment]
I believe I ironed out the kinks I was seeing. The changes should be on master and go out in the next release. Please let us know if there is an issue with master or in the next release.

**Comment by pjkaufman** [comment]
Note: the new setting was only translated into Spanish and English. If desired, other translations can be added for the new setting.
