### ISSUE TITLE
FR: Heading Blank Lines Rule should not insert empty lines between headings

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#773]
## Is Your Feature Request Related to a Problem? Please Describe.

Right now, the rule [Heading Blank Lines](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#heading-blank-lines) creates blank lines above/below headings, except when it's a heading at the start or at the end of the document.

However, if you have two consecutive headings, e.g. a h2 without paragraph, only followed by h3s with paragraphs, it results in the linter inserting a line break between the two headings. In my view, it looks a bit weird, especially if you have the "bottom" sub-option disabled. In that case, it will literally insert a blank below a heading, even though the respective option has been disabled.

## Describe the Solution You'd Like

At least when the bottom sub-option has been disabled, the rule should not insert a blank below a heading. 

**Please include an example where applicable:**

right now, it gets turned into this
``` markdown
...paragraph...

# foobar 1

## foobar 2
...paragraph...
```

but it should better look like this
``` markdown
...paragraph...

# foobar 1
## foobar 2
...paragraph...
```

## Describe Alternatives You've Considered
well, creating a custom rule, I guess?

**Comment by pjkaufman** [comment]
This likely came about by removing the logic that removed existing blank lines between headings. I will have to see what can be done when I get a chance to take a closer look.

**Comment by pjkaufman** [comment]
I believe I have a change that will satisfy this feature request. Sorry it took so long. The change was simple, but I got carried away with other things.

**Comment by pjkaufman** [comment]
Do note that it will not remove any spacing that already exists between headers. It just will not add a blank line between 2 headers when the setting for bottom is false.

**Comment by pjkaufman** [comment]
This change should be on master and go out with the next release. Please let us know if there are any issues with the change on master or in the next release.
