### ISSUE TITLE
FR: Custom Rules should get a label

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#774]
## Is Your Feature Request Related to a Problem? Please Describe.

When you have quite a few custom rules with long regexes, it can get quite confusing quickly what exactly those rules do
![CleanShot 2023-06-26 at 22 14 25@2x](https://github.com/platers/obsidian-linter/assets/73286100/27dba6ea-b849-4960-a23e-aee4a552639e)

## Describe the Solution You'd Like
a field to add a label or note what the rule does

## Describe Alternatives You've Considered
Keeping an extra note in my vault explaining what my rules do 🙈

**Comment by pjkaufman** [comment]
Thanks for the suggestion @chrisgrieser . The only problem I see with adding a label is that it will make the somewhat cramped space even more cramped for custom rules. I guess the flags could be shrunk down to be a smaller size, but that only partially addresses the size issue.

**Comment by pjkaufman** [comment]
Yeah that could work. What do you think of the following @chrisgrieser ?
![image](https://github.com/platers/obsidian-linter/assets/29898683/7426bb74-8924-4d60-beb1-c5ea6b6bed83)

I can include the label, but a lot of other styling is a challenge based on using the underlying settings logic.

**Comment by chrisgrieser** [comment]
yes! 

two minor things I'd improve:
- add a little bit of spacing between the two rules, so it is clearer that the label belongs to the regex below it (and not the regex above)
- the label field could be wider; there is more than enough space there, and some users might wanna even add a small explanation instead of just a label

**Comment by pjkaufman** [comment]
> yes!
> 
> two minor things I'd improve:
> 
> * add a little bit of spacing between the two rules, so it is clearer that the label belongs to the regex below it (and not the regex above)
> * the label field could be wider; there is more than enough space there, and some users might wanna even add a small explanation instead of just a label

I can see about adding the spacing. The label field is refusing to get any wider and I am not sure what CSS is causing that. If I am going to make that wider it will likely take a decent bit of tinkering since flex seems to be causing the issue.

**Comment by pjkaufman** [comment]
I will take a closer look at adding a border/spacing between regex replacements and making the label wider this evening. Thanks for the feedback!

**Comment by pjkaufman** [comment]
I think I figured something out. How do the spacing and width look, @chrisgrieser ? 
![image](https://github.com/platers/obsidian-linter/assets/29898683/531ec41f-d8c5-4ae9-93b9-20de994f1d92)

**Comment by chrisgrieser** [comment]
LGTM! <3

**Comment by pjkaufman** [comment]
This should go out with the next release. It is on master now. Please let us know any feedback around this.
