### ISSUE TITLE
Bug: No Bare URLs Affects HTML

### ISSUE THREAD

**Issue by zhl111** [platers/obsidian-linter#777]
❶ no use linter 
❷ use linter optimization
![image](https://github.com/platers/obsidian-linter/assets/29135984/72cf7cb3-87c6-4eef-9e42-2e21f47d984a)

**Comment by pjkaufman** [comment]
Looks like I need to ignore html in the ignore list for that rule and it should fix the issue.

**Comment by pjkaufman** [comment]
Ignoring html fixes the issue, but note that you have some extra space in your `src` of the iframe which I am not sure is valid @zhl111 . But making the change to the ignore types should handle this scenario.

**Comment by pjkaufman** [comment]
The fix for this should be on master and go out with the next release.
