### ISSUE TITLE
[bug] Settings are gone

### ISSUE THREAD

**Issue by Parlazo** [platers/obsidian-linter#78]
Since last plugin update i cant find the linter settings tab.

may because linter does lint every thing now?
except if i add YAML exclussion rules, i think this is a semi bad idea, people should be able to define the rules they want in settings, apply extra rules in YAML od deactivate rules in YAML, but people should not need to place YAML exclussions to all files because the want to exclude only one rule in general.

how ever ... thanks for your effort

**Comment by chrisgrieser** [comment]
I had the same issue, its from the transition to the new settings menu. Simply uninstall and reinstall the plugin, then the menu should properly re-appear

**Comment by platers** [comment]
thats unfortunate, can anyone can post the console logs when this happens?

**Comment by Parlazo** [comment]
dont know how to get logs from a console

reinstall did help but still a problem ... now i have nice butons in the settings and there is a text that always tells me that the setting is enabled ... i can turn it on and off but it always tells me to be enabled.

**Comment by mcndt** [comment]
> thats unfortunate, can anyone can post the console logs when this happens?

![image](https://user-images.githubusercontent.com/23149353/134870852-85295742-3a5e-49d8-bee0-06dd73b22747.png)

This is all that is visible in the console. Not sure if this contains something useful for you

**Comment by mcndt** [comment]
Other than this bug, great work on the new settings tab for the plugin! Greatly improved usability.

**Comment by platers** [comment]
Should be fixed in the latest release, thanks for the logs!
