### ISSUE TITLE
FR: Bill / bullets on same line as text

### ISSUE THREAD

**Issue by billher** [platers/obsidian-linter#781]
## Is Your Feature Request Related to a Problem? Please Describe.

I have exported my repository from Evernote into MD files for Obsidian.  In many cases the bullet of a list item is on a separate line than the list text itself.  That is, rather than a space/tab between the bullet and text there are a couple of newlines and spaces.  I would like to replace the newlines with a single space.  

## Describe the Solution You'd Like

I would like the bullet and text to be on the same line

**Please include an example where applicable:**

``` markdown
 - 

    The text 
```

``` markdown
- The text
```

## Describe Alternatives You've Considered

I can't find a solution within Lint so I have used find/replace in a text editor to edit the file directly

## Additional Context

I would consider writing a command but I'm not familiar with Javascript etc.

**Comment by pjkaufman** [comment]
@billher , does [custom replace](https://github.com/platers/obsidian-linter#custom-regex-replacements) handle your use case? It requires you to know regex, but you can test it out on the referenced playground.

**Comment by billher** [comment]
ok thanks

Regards,
Bill

Thornhill, Ontario, Canada
www.hertha.ca | ***@***.***

**Comment by pjkaufman** [comment]
The following regex replacement should do it for you:

| Regex | Flags | Replacement |
| --------- | -------- | ------------------ |
| `(^( \|\t)*-) \s*(.+)` | `gm` | `$1 $3` |

It may need some tweaking, but it should handle what you are dealing with.

**Comment by billher** [comment]
Thanks so much.  I tried it but as you said, it requires a bit of tweaking.  

Regards,
Bill

Thornhill, Ontario, Canada
www.hertha.ca | ***@***.***

**Comment by pjkaufman** [comment]
Hey @billher . Were you able to get this resolved? I have not seen any updates around what would need tweaking or what scenarios were not accounted for. I plan to close this issue if I do not hear back by Sunday the 24th.

**Comment by billher** [comment]
Thanks for following up.

You provided me with some instructions (see below) which I applied.  As you suggested, they did require some tweaking, which is beyond my skill set so I left it. So I have left it.



Regards,
Bill

Thornhill, Ontario, Canada
www.hertha.ca | ***@***.***


> The following regex replacement should do it for you:
> 
> Regex	Flags	Replacement
> (^( |\t)*-) \s*(.+)	gm	$1 $3
> It may need some tweaking, but it should handle what you are dealing with.
>

**Comment by pjkaufman** [comment]
Could you provide examples that the regex did not work for @billher ?

**Comment by billher** [comment]
Thank you for following up.

First, as per your original instructions I entered the sequence (^( |\t)*-) \s*(.+) gm $1 $3

I am providing 3 files:

1. 2023-02-15 Sontag on Photography and Plato's Cave
2. 2023-02-15 Sontag on Photography and Plato's Cave-1
3. 2023-02-15 Sontag on Photography and Plato's Cave-2

The first is the original file, as converted from its original source into an md file.  Please note the problem I am trying to solve is to try and get the text realigned with the bullet points.  I have attached two screen shots, the first @4.24.37 is the “original” file showing the misaligned bullet points; the second ***@***.***) shows how I would like it to look.  I reformatted the text manually.

￼

￼

The second file is one run through Linter without the custom code.

The third file is one run with the custom code.


Regards,
Bill

Thornhill, Ontario, Canada
www.hertha.ca | ***@***.***

￼

￼

￼

**Comment by pjkaufman** [comment]
Hey @billher , it looks like the 3 files were not uploaded.

**Comment by billher** [comment]
Let’s try this …

Regards,
Bill

Thornhill, Ontario, Canada
www.hertha.ca | ***@***.***



￼￼￼

**Comment by pjkaufman** [comment]
Looks like attaching via email does not work unless I am mistaken about how you are adding them @billher .

**Comment by billher** [comment]
as far as I can tell they are there when I send them.  They are .md files.  

I have copied them to a google folder:
https://drive.google.com/drive/folders/1OwdKJrmBSWkt3P3m3Hjt22gK_duUJbA3?usp=drive_link￼

Hope this works ...

Regards,
Bill

Thornhill, Ontario, Canada
www.hertha.ca | ***@***.***

**Comment by pjkaufman** [comment]
Without knowing what rules you have enabled, I can only speculate, but it sounds like you have the rule to get rid of empty list items present. That rule needs to be disabled when you format a file you want the regex to apply to.

**Comment by billher** [comment]
You’re right.  It worked.  Thanks!

Regards,
Bill

Thornhill, Ontario, Canada
www.hertha.ca | ***@***.***

**Comment by pjkaufman** [comment]
No problem. I will close this since it seems to be resolved by the regex provided.

**Comment by billher** [comment]
ok, thanks again.
Regards,
Bill

Thornhill, Ontario, Canada
www.hertha.ca | ***@***.***
