### ISSUE TITLE
Bug: Paragraph blank lines incorrectly adding blank lines between footnotes 

### ISSUE THREAD

**Issue by pjlewisuk** [platers/obsidian-linter#787]
- [ ] I have verified that I am on the latest version of the Linter

## Describe the Bug

When adding footnotes to the bottom of a note, they are normally added without blank lines in between them, e.g.:

![image](https://github.com/platers/obsidian-linter/assets/6115202/da5839af-2f7d-4406-9cfd-31d96e06d2f6)

When saving the file, Linter will then add a bunch of blank lines between the footnotes:

![image](https://github.com/platers/obsidian-linter/assets/6115202/a0b15a2e-6335-4856-a8ad-958ddcc8ea44)

This is not required, and looks less appealing than footnotes without the line spaces. Footnotes should be excluded from this linter action.

## How to Reproduce

1. Add 2 or more footnotes to a note, without blank lines between them
2. Save the note, or trigger linter
3. Observe the blank lines added in between each footnote

Or

Example to reproduce issue with

``` markdown
example here
```

Please make sure to include logs and the rule(s) that cause the issue if applicable. You can include logs by going to the debug tab of the Linter and setting the log level to debug. Then enable the capturing of logs and either lint on save or lint the current file. Then go back to the debug tab and you can grab Linter logs from the last run.

If you are not sure which rule(s) may cause the issue, please attach the `data.json` file located at `<vault>/.obsidian/plugins/obsidian-linter/` or copy the config from the debug tab.

## Expected Behavior

Footnotes should be excluded from this type of linting, or an option should be adding so the user can choose their preference.

Expected output if applicable:

``` markdown
expected output here
```

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
@pjlewisuk, could you provide a reproducible example? I see part of the content in the image, but an actual set of text is much easier to work with.

**Comment by pjlewisuk** [comment]
Sure:

```markdown

- reference to footnote 1 [^1]
- reference to footnote 2 [^2]
- reference to footnote 3 [^3]
- reference to footnote 4 [^4]
- reference to footnote 5 [^5]

[^1]: [Release 2023-06-11 (github.com)](https://github.com/Azure/AKS/releases/tag/2023-06-11.2)
[^2]: [Release 2023-06-18 (github.com)](https://github.com/Azure/AKS/releases/tag/2023-06-18)
[^3]: [Release 2023-06-25 (github.com)](https://github.com/Azure/AKS/releases/tag/2023-06-25)
[^4]: [Release 2023-07-02 (github.com)](https://github.com/Azure/AKS/releases/tag/2023-07-02)
[^5]: [Release 2023-07-09 (github.com)](https://github.com/Azure/AKS/releases/tag/2023-07-09)
```

Let me know if you need more than this.

**Comment by pjkaufman** [comment]
Looks like to fix this I will need to ignore footnotes when it comes to this rule [here](https://github.com/platers/obsidian-linter/blob/e2b85955a3087da9bfdb67005a60d6c9ad00c193/src/rules/paragraph-blank-lines.ts#L16).

**Comment by pjkaufman** [comment]
I have updated the underlying logic around this. Paragraph blank lines should not be affecting footnote definitions that start a line anymore. The change is on master and should go out with the next release. Please let us know if there are any issues with the change.

**Comment by pjlewisuk** [comment]
Thanks for the speedy fix, I'll look out for the next release :)

**Comment by pjkaufman** [comment]
No problem. It was not too bad to add the change and I had some downtime.
