### ISSUE TITLE
Doc: Specify the name the linter is registered under in the Community Plugin directory

### ISSUE THREAD

**Issue by bradykelly** [platers/obsidian-linter#792]
## What I Would Like Documented

The official name used to register the plugin in the Community Plugin directory.

### Why I would like to see this documented

In various places, the plugin is referred to as _Obsidian Linter_, _obsidian-linter_, or by the rather nondescript and overly generic term _Linter_. I almost gave up on the automated installation method after not finding it in the directory a few times. I assumed the instructions for installing it in your README were incorrect for the current Obsidian version, that the plugin was no longer available in the directory, and that manual installation was required.

> As of version [0.9.7 of Obsidian](https://forum.obsidian.md/t/obsidian-release-v0-9-7-insider-build/7628), this plugin is available to be installed directly from within the app. The plugin can be found in the Community Plugins directory which can be accessed from the Settings pane under Third Party Plugins.

I eventually found the name `Linter` in a locale file after perusing the plugin code, but many Obsidian users are lay people who would never hope to understand a NodeJS app, especially one catering to multiple languages. This is why I feel the documentation could be more helpful.

### How I would like to see the installation instructions improved

> ... The plugin can be found in the Community Plugins directory which can be accessed from the Settings pane under Third Party Plugins. **It is registered under the name _Linter_**.

### Why have I not just corrected this and submitted a PR?

It is just after 03h00 and I have yet to sleep. Your build and i18n processes, as well as whether or not the plugin directory localises its plugin names, make some investigation necessary before simply changing some locale files. I will revisit this issue fairly soon when I have some time and probably then submit a PR.

**Comment by pjkaufman** [comment]
Gotcha. This should not be too bad to update. Personally I think that if you are looking for a foatter you would search for a linter or a specific linter by name, but it can't hurt to list the name of the plugin in the installation instructions.

**Comment by pjkaufman** [comment]
I believe I have a fix for this. I will go ahead and push it up.

**Comment by pjkaufman** [comment]
This should now be on master and pulled by Obsidian soon. Please let us know if there is anything else we can improve around the documentation.
