### ISSUE TITLE
FR: Allow Priority Key Sort to Sort Keys that End in Colons

### ISSUE THREAD

**Issue by zhl111** [platers/obsidian-linter#796]
I'd like to sort it like this.
![image](https://github.com/platers/obsidian-linter/assets/29135984/98522754-df1f-4ba7-a4e6-ed73afa5bb57)

It's sorted, but not the way I want it.   
![image](https://github.com/platers/obsidian-linter/assets/29135984/0a1d15dd-df86-4aff-83cd-2182aa263720)

**Comment by pjkaufman** [comment]
This could just be a bug. Could you provide a reproducible example?

**Comment by pjkaufman** [comment]
It could also be that there are colons at the end of your keys.

**Comment by pjkaufman** [comment]
I will see about making that rule ignore the colons when present in the list. I just need to define the splitting regex as an optional colon then a new line character.

**Comment by pjkaufman** [comment]
I am making a code change around this. It should take care of the scenario where users add a colon at the end of the keys.

**Comment by pjkaufman** [comment]
The change to allow this kind of value setup should be on master now and go out with the next release. Please let us know if it does not work or there is some kind of problem with the functionality or logic.
