### ISSUE TITLE
Bug: Changelog link is broken in release notes

### ISSUE THREAD

**Issue by oenu** [platers/obsidian-linter#797]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

link found -> https://github.com/platers/obsidian-linter/releases/tag/1.17.0#:~:text=Full%20Changelog%3A-,1.16.0...v1.17.0,-Contributors

which points to -> https://github.com/platers/obsidian-linter/compare/1.16.0...v1.17.0)
is broken

## How to Reproduce

1. Go to release page
2. Click on Full changelog
3. See error

Link should probably be https://github.com/platers/obsidian-linter/compare/1.16.0...1.17.0

(good template for issues, might yoink)

**Comment by oenu** [comment]
Almost forgot to say, thank you so much for your hard work on this project, it pushes Obsidian head and shoulders above the rest!

 (its a damn shame that obsidian itself isnt open source)

**Comment by pjkaufman** [comment]
Thanks for reporting the issue!

I am glad that you find the Linter to be useful. I have fixed the issue and it should be working now on.
