### ISSUE TITLE
FR: caltialize headers rule

### ISSUE THREAD

**Issue by brandonxoliver** [platers/obsidian-linter#8]
Nice plug-in!

How difficult is it to add new rules? One that will reformat headers to Capitalized would be great!

**Comment by gavinmn** [comment]
Are you asking about `# Title Case Headers` or `# Just the first word of a header` ?

**Comment by platers** [comment]
All of those options seem good to have! A smart option that skips words like 'the' and 'of' would also be great.

**Comment by gavinmn** [comment]
I can try and work on this when I have some time later but anyone should feel free to beat me to it!

**Comment by brandonxoliver** [comment]
Thanks for adding this! What's the correct way for me to add the rule? `capitalize-headings titleCase=true` shows an error saying it's not recognized .

**Comment by platers** [comment]
Have you installed the plugin from the repo manually? I haven't pushed a new release with the new rule yet, will do that sometime this week.

**Comment by brandonxoliver** [comment]
ah! no, I have it installed though the appstore. thanks again for adding it. look fwd to giving it a run
