### ISSUE TITLE
Question: How is date modified supposed to work?

### ISSUE THREAD

**Issue by kalico1** [platers/obsidian-linter#806]
What you would like to know more about...

When I use YAML Timestamp >> Date Modified the first time YAML is inserted, it grabs the last modified date/time from the file metadata. However, if this feature is turned on when linting the file in the future, the "date modified" is the same date/time as the lint that just occurred. That is: linting counts as the last modification to the file. 

I get it...but that's more literal than I think it should be. I want it to grab the last time I modified the file myself, not the moment the file was linted.

Is this a bug, a feature, or user error?

**Comment by pjkaufman** [comment]
That is a feature. There are new docs available to explain it here: https://platers.github.io/obsidian-linter/settings/yaml-rules/#date-modified-value-origin

Please let me know if that makes sense or if something needs clarification still.

**Comment by kalico1** [comment]
Thank you! I am only unclear on one part of the description:

> As such, the date modified is the time the Linter needs to update the file via any rule except Custom Commands.

- What does "needs to update" mean, exactly?
- Is there some exception here with Custom Commands that would be useful to understand?

Just want to say how AWESOME this plugin is. It is an absolute godsend as I'm trying to refactor my vault. Thank you.

**Comment by pjkaufman** [comment]
I am glad that it is useful!

"needs to update" means that the Linter rule for updating date modified is active and a change has been made in the file, the date modified is not in the specified format, the date modified is missing, or the date modified is more than 5 seconds from the time the file's metadata says.

Aa for custom commands, there is nothing the Linter can do around updating the date modified of a file when custom commands run. They are responsible for doing any updates needed there with no later input from the Linter. So if custom commands modify a file, the date modified is not updated in the file until the next time the Linter is run.

**Comment by pjkaufman** [comment]
Just as a heads up @kalico1 , I plan to close this question come Wednesday if there are no followup questions.
