### ISSUE TITLE
Bug: `Empty Lines Around Blockquotes` Can Cause Problems with Nested Callouts with a Single Blank Line Between Them

### ISSUE THREAD

**Issue by alitekdemir** [platers/obsidian-linter#812]
- [x]  Linter v1.17.0

## Describe the Bug
I showed it in the video. Actually I was thinking it wouldn't add extra characters. Since I did not see such an explanation in the document, I wanted to report it as an error.

## Expected Behavior
shouldn't add extra characters.

i use this sample markdown
``` markdown
> [!multi-column]
>
>> [!note]+ Use Case
>> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
>> ##### User Case Background
>> Vitae nunc sed velit dignissim sodales. In cursus turpis massa tincidunt dui ut ornare lectus.
>
>> [!warning]+ Resources
>> #### Requirement
>> - Lorem ipsum dolor sit amet
>> - Vitae nunc sed velit dignissim sodales.
>> - In cursus turpis massa tincidunt dui ut ornare lectus.
>
>> [!todo]+
>> - [x] Define Use Case
>> - [ ] Craft User Story
>> - [ ] Develop draft sketches
```

## Screenshots
https://github.com/platers/obsidian-linter/assets/1507344/b98e915a-199a-4168-ab63-fc74e2c2fe65

**Comment by pjkaufman** [comment]
I believe I have a fix for this. I will push it up and barring any formatting issues caused when I test before the next release, it will go out with the next release.

**Comment by pjkaufman** [comment]
Hopefully this fix will not cause other issues to pop up.

**Comment by alitekdemir** [comment]
Thank you very much for your prompt attention. And my heartfelt congratulations to you.
