### ISSUE TITLE
Bug: `Sort YAML Keys` Error

### ISSUE THREAD

**Issue by guix54** [platers/obsidian-linter#822]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

when I lint the file, sorting yaml fields as defined gives an error

## example
before lint
``` markdown
---
locate: Somewhere
tags:
  - catégorie/note
sujet: Something
AREAS:
  - "[[Link1]]"
  - "[[Link2]]"
ressources:
  - "[[Link3]]"
---
```
after lint
``` markdown
---
tagso:
  s:- cLinatégorie/note
AREAS:
  - "[[L1in1k1]]"
  - "[[Link2]]"
AREAS:
  - "[[Ldiamo inki|k1]]"ed: 20230729 17:07:36
date: 2Li0nk3729 17:02:23
locate: Somewhere
tags:
  - catégorie/note
ressources:
  - "[[Link3]]"
sujet: Something
---
```

the sorting request is
aliases
date modified
date
locate
PROJET
AREAS
RESSOURCES
relation
sujet
URL
tags

**Comment by pjkaufman** [comment]
Could you provide your `data.json`? It looks like you may have invalid YAML, but I am not certain on that.

**Comment by guix54** [comment]
{
  "ruleConfigs": {
    "escape-yaml-special-characters": {
      "enabled": false,
      "try-to-escape-single-line-arrays": false
    },
    "force-yaml-escape": {
      "enabled": false,
      "force-yaml-escape-keys": ""
    },
    "format-tags-in-yaml": {
      "enabled": false
    },
    "format-yaml-array": {
      "enabled": false,
      "alias-key": false,
      "tag-key": false,
      "default-array-style": "single-line",
      "default-array-keys": false,
      "force-single-line-array-style": "",
      "force-multi-line-array-style": ""
    },
    "insert-yaml-attributes": {
      "enabled": false,
      "text-to-insert": ""
    },
    "move-tags-to-yaml": {
      "enabled": false,
      "how-to-handle-existing-tags": "Nothing",
      "tags-to-ignore": ""
    },
    "remove-yaml-keys": {
      "enabled": false,
      "yaml-keys-to-remove": ""
    },
    "yaml-key-sort": {
      "enabled": true,
      "yaml-key-priority-sort-order": "aliases\ndate modified\ndate\nlocate\nPROJET\nAREAS\nRESSOURCES\nrelation\nsujet\nURL\ntags",
      "priority-keys-at-start-of-yaml": true,
      "yaml-sort-order-for-other-keys": "None"
    },
    "yaml-timestamp": {
      "enabled": true,
      "date-created": true,
      "date-created-key": "date",
      "force-retention-of-create-value": true,
      "date-modified": true,
      "date-modified-key": "date modified",
      "format": "YYYYMMDD HH:mm:ss"
    },
    "yaml-title": {
      "enabled": false,
      "title-key": "title",
      "mode": "first-h1-or-filename-if-h1-missing"
    },
    "yaml-title-alias": {
      "enabled": false,
      "preserve-existing-alias-section-style": false,
      "keep-alias-that-matches-the-filename": false,
      "use-yaml-key-to-keep-track-of-old-filename-or-heading": false
    },
    "capitalize-headings": {
      "enabled": false,
      "style": "Title Case",
      "ignore-case-words": true,
      "ignore-words": "macOS, iOS, iPhone, iPad, JavaScript, TypeScript, AppleScript, I",
      "lowercase-words": "a, an, the, aboard, about, abt., above, abreast, absent, across, after, against, along, aloft, alongside, amid, amidst, mid, midst, among, amongst, anti, apropos, around, round, as, aslant, astride, at, atop, ontop, bar, barring, before, B4, behind, below, beneath, neath, beside, besides, between, 'tween, beyond, but, by, chez, circa, c., ca., come, concerning, contra, counting, cum, despite, spite, down, during, effective, ere, except, excepting, excluding, failing, following, for, from, in, including, inside, into, less, like, minus, modulo, mod, near, nearer, nearest, next, notwithstanding, of, o', off, offshore, on, onto, opposite, out, outside, over, o'er, pace, past, pending, per, plus, post, pre, pro, qua, re, regarding, respecting, sans, save, saving, short, since, sub, than, through, thru, throughout, thruout, till, times, to, t', touching, toward, towards, under, underneath, unlike, until, unto, up, upon, versus, vs., v., via, vice, vis-à-vis, wanting, with, w/, w., c̄, within, w/i, without, 'thout, w/o, abroad, adrift, aft, afterward, afterwards, ahead, apart, ashore, aside, away, back, backward, backwards, beforehand, downhill, downstage, downstairs, downstream, downward, downwards, downwind, east, eastward, eastwards, forth, forward, forwards, heavenward, heavenwards, hence, henceforth, here, hereby, herein, hereof, hereto, herewith, home, homeward, homewards, indoors, inward, inwards, leftward, leftwards, north, northeast, northward, northwards, northwest, now, onward, onwards, outdoors, outward, outwards, overboard, overhead, overland, overseas, rightward, rightwards, seaward, seawards, skywards, skyward, south, southeast, southwards, southward, southwest, then, thence, thenceforth, there, thereby, therein, thereof, thereto, therewith, together, underfoot, underground, uphill, upstage, upstairs, upstream, upward, upwards, upwind, west, westward, westwards, when, whence, where, whereby, wherein, whereto, wherewith, although, because, considering, given, granted, if, lest, once, provided, providing, seeing, so, supposing, though, unless, whenever, whereas, wherever, while, whilst, ago, according to, as regards, counter to, instead of, owing to, pertaining to, at the behest of, at the expense of, at the hands of, at risk of, at the risk of, at variance with, by dint of, by means of, by virtue of, by way of, for the sake of, for sake of, for lack of, for want of, from want of, in accordance with, in addition to, in case of, in charge of, in compliance with, in conformity with, in contact with, in exchange for, in favor of, in front of, in lieu of, in light of, in the light of, in line with, in place of, in point of, in quest of, in relation to, in regard to, with regard to, in respect to, with respect to, in return for, in search of, in step with, in touch with, in terms of, in the name of, in view of, on account of, on behalf of, on grounds of, on the grounds of, on the part of, on top of, with a view to, with the exception of, à la, a la, as soon as, as well as, close to, due to, far from, in case, other than, prior to, pursuant to, regardless of, subsequent to, as long as, as much as, as far as, by the time, in as much as, inasmuch, in order to, in order that, even, provide that, if only, whether, whose, whoever, why, how, or not, whatever, what, both, and, or, not only, but also, either, neither, nor, just, rather, no sooner, such, that, yet, is, it"
    },
    "file-name-heading": {
      "enabled": false
    },
    "header-increment": {
      "enabled": false,
      "start-at-h2": false
    },
    "headings-start-line": {
      "enabled": false
    },
    "remove-trailing-punctuation-in-heading": {
      "enabled": false,
      "punctuation-to-remove": ".,;:!。，；：！"
    },
    "footnote-after-punctuation": {
      "enabled": false
    },
    "move-footnotes-to-the-bottom": {
      "enabled": false
    },
    "re-index-footnotes": {
      "enabled": false
    },
    "auto-correct-common-misspellings": {
      "enabled": false,
      "ignore-words": ""
    },
    "blockquote-style": {
      "enabled": false,
      "style": "space"
    },
    "convert-bullet-list-markers": {
      "enabled": false
    },
    "emphasis-style": {
      "enabled": false,
      "style": "consistent"
    },
    "no-bare-urls": {
      "enabled": false
    },
    "ordered-list-style": {
      "enabled": false,
      "number-style": "ascending",
      "list-end-style": "."
    },
    "proper-ellipsis": {
      "enabled": false
    },
    "quote-style": {
      "enabled": false,
      "single-quote-enabled": true,
      "single-quote-style": "''",
      "double-quote-enabled": true,
      "double-quote-style": "\"\""
    },
    "remove-consecutive-list-markers": {
      "enabled": false
    },
    "remove-empty-list-markers": {
      "enabled": false
    },
    "remove-hyphenated-line-breaks": {
      "enabled": false
    },
    "remove-multiple-spaces": {
      "enabled": false
    },
    "strong-style": {
      "enabled": false,
      "style": "consistent"
    },
    "two-spaces-between-lines-with-content": {
      "enabled": false
    },
    "unordered-list-style": {
      "enabled": false,
      "list-style": "consistent"
    },
    "compact-yaml": {
      "enabled": false,
      "inner-new-lines": false
    },
    "consecutive-blank-lines": {
      "enabled": false
    },
    "convert-spaces-to-tabs": {
      "enabled": false,
      "tabsize": 4
    },
    "empty-line-around-blockquotes": {
      "enabled": false
    },
    "empty-line-around-code-fences": {
      "enabled": false
    },
    "empty-line-around-math-blocks": {
      "enabled": false
    },
    "empty-line-around-tables": {
      "enabled": false
    },
    "heading-blank-lines": {
      "enabled": false,
      "bottom": true,
      "empty-line-after-yaml": true
    },
    "line-break-at-document-end": {
      "enabled": false
    },
    "move-math-block-indicators-to-their-own-line": {
      "enabled": false
    },
    "paragraph-blank-lines": {
      "enabled": false
    },
    "remove-empty-lines-between-list-markers-and-checklists": {
      "enabled": false
    },
    "remove-link-spacing": {
      "enabled": false
    },
    "remove-space-around-characters": {
      "enabled": false,
      "include-fullwidth-forms": true,
      "include-cjk-symbols-and-punctuation": true,
      "include-dashes": true,
      "other-symbols": ""
    },
    "remove-space-before-or-after-characters": {
      "enabled": false,
      "characters-to-remove-space-before": ",!?;:).’”]",
      "characters-to-remove-space-after": "¿¡‘“(["
    },
    "space-after-list-markers": {
      "enabled": false
    },
    "space-between-chinese-japanese-or-korean-and-english-or-numbers": {
      "enabled": false
    },
    "trailing-spaces": {
      "enabled": false,
      "twp-space-line-break": false
    },
    "add-blockquote-indentation-on-paste": {
      "enabled": false
    },
    "prevent-double-checklist-indicator-on-paste": {
      "enabled": false
    },
    "prevent-double-list-item-indicator-on-paste": {
      "enabled": false
    },
    "proper-ellipsis-on-paste": {
      "enabled": false
    },
    "remove-hyphens-on-paste": {
      "enabled": false
    },
    "remove-leading-or-trailing-whitespace-on-paste": {
      "enabled": false
    },
    "remove-leftover-footnotes-from-quote-on-paste": {
      "enabled": false
    },
    "remove-multiple-blank-lines-on-paste": {
      "enabled": false
    }
  },
  "lintOnSave": true,
  "recordLintOnSaveLogs": false,
  "displayChanged": true,
  "lintOnFileChange": false,
  "displayLintOnFileChangeNotice": false,
  "settingsConvertedToConfigKeyValues": true,
  "foldersToIgnore": [
    "50 MODELE",
    ""
  ],
  "linterLocale": "system-default",
  "logLevel": 4,
  "lintCommands": [],
  "customRegexes": [],
  "commonStyles": {
    "aliasArrayStyle": "single-line",
    "tagArrayStyle": "single-line",
    "minimumNumberOfDollarSignsToBeAMathBlock": 2,
    "escapeCharacter": "\"",
    "removeUnnecessaryEscapeCharsForMultiLineArrays": false
  }
}

**Comment by pjkaufman** [comment]
I am having trouble reproducing the scenario in question. Could you upload a file that is having the issue?

**Comment by guix54** [comment]
Hello here a file when the issue occurs. But with the different evolution (linter and obsidian) lint a file seems to give best results compare in the past...to follow.

[Conseils pour mettre en place la semaine de 4 jours.md](https://github.com/platers/obsidian-linter/files/12224859/Conseils.pour.mettre.en.place.la.semaine.de.4.jours.md)
[linterconfig.txt](https://github.com/platers/obsidian-linter/files/12224860/linterconfig.txt)

**Comment by guix54** [comment]
Here another example, my tought: it is the result of the lenght of the field...
in this case, the object "RESSOURCES" is dubble and one terme is cutted
[linter_error.txt](https://github.com/platers/obsidian-linter/files/12228946/linter_error.txt)

**Comment by pjkaufman** [comment]
I am not sure why, but I am not able to reproduce. Is the Linter the only plugin you have active or is there a particular way you are linting the file?

I am linting by hitting `ctrl+s`

**Comment by guix54** [comment]
Hello Peter,
I am linting as you with the ctrl+s
another example before/after the root cause seems to be my link [[9....]]
in frontmatter the line is cutted and after linting this no more a link with some ' added
[after The Checklist Manifesto.md](https://github.com/platers/obsidian-linter/files/12237712/after.The.Checklist.Manifesto.md)
[before The Checklist Manifesto.md](https://github.com/platers/obsidian-linter/files/12237713/before.The.Checklist.Manifesto.md)

**Comment by guix54** [comment]
After another test, it seems to be the links length the root cause.
I have test with just linter activate and I have the error.
With the filed <sujet:> and 73 caracters > error. I reduce the filed to 56 and it's ok 
no problem with long url...

**Comment by pjkaufman** [comment]
> Hello Peter, I am linting as you with the ctrl+s another example before/after the root cause seems to be my link [[9....]] in frontmatter the line is cutted and after linting this no more a link with some ' added [after The Checklist Manifesto.md](https://github.com/platers/obsidian-linter/files/12237712/after.The.Checklist.Manifesto.md) [before The Checklist Manifesto.md](https://github.com/platers/obsidian-linter/files/12237713/before.The.Checklist.Manifesto.md)
Unfortunately I am not hitting this error. What OS are you using?

**Comment by pjkaufman** [comment]
Also have you tried with all other plugins disabled?

**Comment by pjkaufman** [comment]
If you continue to have problems after that on `1.19.0`. I can upload a custom `main.js` and have you run it with the logs to help me better understand what is going on.

**Comment by guix54** [comment]
> > Hello Peter, I am linting as you with the ctrl+s another example before/after the root cause seems to be my link [[9....]] in frontmatter the line is cutted and after linting this no more a link with some ' added [after The Checklist Manifesto.md](https://github.com/platers/obsidian-linter/files/12237712/after.The.Checklist.Manifesto.md) [before The Checklist Manifesto.md](https://github.com/platers/obsidian-linter/files/12237713/before.The.Checklist.Manifesto.md)
> 
> Unfortunately I am not hitting this error. What OS are you using? I am on Linux so this could be due to a different OS being used.

I'm using Win11

**Comment by guix54** [comment]
> Also have you tried with all other plugins disabled?

yes as requested.

**Comment by pjkaufman** [comment]
> > Also have you tried with all other plugins disabled?
> 
> yes as requested.

Gotcha. I will see about creating a custom `main.js` to help get better logs on this then. I will include logs in `sort-yaml-keys` and also for the output of each rule that runs.

**Comment by pjkaufman** [comment]
Which them are you using? I may be able to replicate the issue if the theme is at fault.

Also, is the theme modifying source mode?

**Comment by guix54** [comment]
LYT Mode but
In fact, after desabling all plugin end with the default theme, I have always the problem with some long data links...
But after correction in source mode, all is OK.
I think the cause is obsidian...I will ask some help in discord channel

**Comment by pjkaufman** [comment]
Gotcha.

**Comment by pjkaufman** [comment]
Looks like Obsidian does cause the problem when line lengths are longer than 79: https://forum.obsidian.md/t/processfrontmatter-creates-undesired-line-break-for-long-strings/63380/2

**Comment by guix54** [comment]
😃 good to know,,,I will modify link for thé future,,,,

**Comment by guix54** [comment]
information from yesterday.
YAML properties will be modified in the next release, I have just to wait after 1.4.3
