### ISSUE TITLE
Feature Request: `Display Lint on File message` option to only notify when changes were made

### ISSUE THREAD

**Issue by chrisgrieser** [platers/obsidian-linter#824]
Right now, the new `Display Lint on File message` setting *always* shows a notification when we change files. 

However, I'd find it much more useful if it only notified me when actual changes have been made.

**Comment by pjkaufman** [comment]
This is a good suggestion. I will see about implementing that functionality.

**Comment by pjkaufman** [comment]
I believe I have this ready to be added. I have tested the change and it seems to be working to me.

**Comment by pjkaufman** [comment]
The changes for this have been merged and should go out with the next release. Please let us know if there are any issues with it on master or in the next release.
