### ISSUE TITLE
Bug: Lint on file change should respect ignored folders

### ISSUE THREAD

**Issue by TheKysek** [platers/obsidian-linter#825]
## Is Your Feature Request Related to a Problem? Please Describe.

Files in ignored folders are getting modified when "Lint on File Change" is active.

I would like a way to prevent that.

**Comment by pjkaufman** [comment]
Gotcha. I thought it did respect that, but I will have to double check.

**Comment by pjkaufman** [comment]
Looks like it is not doing the ignore check. I will have to add that.

**Comment by ironhak** [comment]
Hello, I'm trying to exlude my template folder from auto-updating front matter modification date, I've inserted the path to that folder to the "Folders to ignore" section but it does not work and my templates are getting modified.

**Comment by pjkaufman** [comment]
> Hello, I'm trying to exlude my template folder from auto-updating front matter modification date, I've inserted the path to that folder to the "Folders to ignore" section but it does not work and my templates are getting modified.

That is currently a bug. I plan to issue a patch later this week. For now, I would disable the feature to lint on active file change.

**Comment by ironhak** [comment]
Thank you :)

**Comment by pjkaufman** [comment]
No problem.

**Comment by pjkaufman** [comment]
I have a fix for this ready. It should take care of the issue. I plan to patch soon, but I am not sure if that will be tonight or later on.

**Comment by pjkaufman** [comment]
The changes for this have been merged and should go out with the next release.
