### ISSUE TITLE
FR: Exclude quote rules from inline code (single backticks)

### ISSUE THREAD

**Issue by nihaals** [platers/obsidian-linter#826]
## Is Your Feature Request Related to a Problem? Please Describe.

I ran the linter across my vault and notices that it changes something like `` `'Test'` `` to `` `‘Test’` `` when smart quotes are enabled, but in this case it was referring to a string in code.

## Describe the Solution You'd Like

It would be great if there was an option to disable the option for inline code. There are a few other rules which also seem to be deactivated in code blocks but not in inline code (like removing spaces after punctuation) so it could make sense to make an option that is broader and affects more than one rule.

**Please include an example where applicable:**

```markdown
- `'string'`
```

```markdown
- `'string'`
```

## Describe Alternatives You've Considered

You could use a code block but for small snippets especially in the middle of a sentence inline code makes more sense so I ended up disabling the rules that negatively affected my inline code snippets.

**Comment by pjkaufman** [comment]
I can add this pretty easily. It should go out with the next release.

**Comment by pjkaufman** [comment]
This has been merged into master and should be available in the next release. Please let us know if there are any issues on master or in the next release.

**Comment by nihaals** [comment]
Thanks for the quick fix! What do you think about removing spaces before and after characters also being excluded?

**Comment by pjkaufman** [comment]
> Thanks for the quick fix! What do you think about removing spaces before and after characters also being excluded?

I don't believe I understand what is meant by "What do you think about removing spaces before and after characters also being excluded?"

**Comment by pjkaufman** [comment]
I think I just realized what you mean. The change can be made, but it will go out with `1.20.0` whenever that gets released since I already made `1.19.0`.

**Comment by pjkaufman** [comment]
The ignore inline code logic for space around characters should be merged into master and will go out in `1.20.0`.

**Comment by pjkaufman** [comment]
As an update, this will go out with `1.19.1`.
