### ISSUE TITLE
Bug: New properties and Linter (with 12-hour datetime format) not working together well.

### ISSUE THREAD

**Issue by everonegraham** [platers/obsidian-linter#828]
- [X] I have verified that I am on the latest version of the Linter

## Describe the Bug

New properties feature doesn't seem to work well with auto “created” and “modified” datetime in 12-hour format. Sometimes works with 24 format. Always works for regular dates. 

## How to Reproduce

1. Go to 'Linter Settings'
2. Got to 'YAML'
3. Scroll down to 'YAML Timestamp' > 'Format'
4. Use 'MM/DD/YYYY hh:mm A' for 12-hour format
5. Properties will stay empty

## Expected Behavior

For proper datetime format to be returned in 12-hour format in new properties.

## Device

- [X] Desktop
- [X] Mobile

**Comment by pjkaufman** [comment]
This is an interesting potential issue. I will habe to take a look at this at some point. I know that we had an issue similar to this in the past, but it was due to the system time and desired display formats being different

Hopefully I will be able to take a stab at this shortly.

**Comment by everonegraham** [comment]
No prob at all. Please let me know if you need me to test anything on my end.

**Comment by pjkaufman** [comment]
@everonegraham , I see you mentioned a new properties feature. Do you mind explaining what that means? You probably should not use YAML Timestamp keys with Insert YAML Keys

**Comment by everonegraham** [comment]
Hi @pjkaufman, referring to this new feature: 

- https://twitter.com/obsdmd/status/1684275039703814145 
- https://obsidian.md/changelog/2023-07-26-desktop-v1.4.0

It does seem to work with date format though. Just not sure what the issue with datetime.

**Comment by pjkaufman** [comment]
That may be something specific to the insider options. I am not sure I can do anything around that. However I can see if there is an issue with the logic around YAML Timestamp for the date format specified. If the issue is specific to an insider build, I will have to wait to address this until it is available as part of the non-insider release.

**Comment by pjkaufman** [comment]
I am not sure how properties are stored, so I can only speculate as to what may be going on.

**Comment by pjkaufman** [comment]
Based on what I am seeing [here](https://www.youtube.com/watch?v=kJbe1jk98SE), this new feature is something that deals with the YAML Frontmatter, so the issue may not be related to the new properties option except in that it causes values not to populate visually. So this may be fixable/reproducible.

**Comment by pjkaufman** [comment]
I am not seeing a problem with the YAML. If you could provide your `data.json` that would help me confirm whether the problem is with my attempts to reproduce whether it is a problem with a newer version of Obsidian.

**Comment by everonegraham** [comment]
Hi @pjkaufman, data.json is in that zip file. Sorry, I forgot to mention that it is currently an insider feature. :(

[data.zip](https://github.com/platers/obsidian-linter/files/12223299/data.zip)

**Comment by everonegraham** [comment]
Sorry, wrong button.

**Comment by everonegraham** [comment]
I found a format that works for me: `YYYY-MM-DDThh:mm A`

If I try anything else, it returns as a string.

**Comment by pjkaufman** [comment]
I am glad that you have found at least a partial workaround. I need to double check with the `data.json` you provided above to see if I can reproduce this scenario. I am not sure if I can. I thought I had tested it and still could not see the problem, but lacking a comment from me, I assume I must have not actually done the check.

**Comment by pjkaufman** [comment]
> It's defaulting to AM for some reason. Probably an issue on my end.

I know that when this happened before it was because the system clock and the time format desired did not match the mode. Are you sure your system is also set to 12 hour mode?

For example, if the system is set to 24 hour mode and the date format that is specified to be 12 hour mode, it might not parse the file metadata correctly and just assume it is always the AM. It has happened before, but I thought it was fixed.

**Comment by everonegraham** [comment]
It should be in 12 hour mode. See attached image below. Very unclear what the issue is to me. But it could be a bug with the properties feature? 

![image](https://github.com/platers/obsidian-linter/assets/28059522/d83a0740-c50b-470c-8246-af4a90e52245)

**Comment by pjkaufman** [comment]
@everonegraham , could you provide a screenshot of both the properties view of the YAML frontmatter and the actual value in frontmatter (i.e. the source view of the YAML frontmatter)? I can only assume it is mutating the value instead of leaving it as is.

**Comment by everonegraham** [comment]
Hi @pjkaufman,

- ![Linter YAML](https://github.com/platers/obsidian-linter/assets/28059522/89aa5e1b-64d8-4ed8-abb7-e73f6e81fb55)
- ![md file source YAML](https://github.com/platers/obsidian-linter/assets/28059522/df309bbc-e7b5-4903-bf6b-fe1103a5b7d8)

It seems to be going through correctly.

**Comment by pjkaufman** [comment]
@everonegraham , is it not showing properly in the properties UI?

**Comment by everonegraham** [comment]
That's the strange part. It does, but it defaults to AM even if it gets edited during PM* . I have a feeling that I have to get the formatting just right for it to take it. 

Or maybe it's that properties is still being a bit wonky.

**Comment by everonegraham** [comment]
@pjkaufman, I figured it out. `YYYY-MM-DDTHH:mm` works. Properties auto-interprets AM/PM. So leaving it in 24-hour format in Linter YAML settings is the way to go. 

Will close this out.

Thanks for all the help on this. :D

**Comment by pjkaufman** [comment]
Gotcha. I am glad that you found a solution.
