### ISSUE TITLE
Bug: Empty Line Around Code Fences breaks blockquotes/callouts

### ISSUE THREAD

**Issue by usernotnull** [platers/obsidian-linter#833]
- [X] I have verified that I am on the latest version of the Linter

## Describe the Bug

The option "Empty Line Around Code Fences" inside a callout/blockquote adds the blank line without a ">" which breaks the callout, separating the block.

What are your thoughts on this? Can logic be added to check if the paragraph is in a callout/blockquote and add a blank line with a ">"?

FYI, I had this issue after a certain release, around v1.0 or so.

## How to Reproduce

`````` markdown
> [!abstract]- Mentions
> ```dataview
> XXX
> ```
``````
Becomes:

`````` markdown
> [!abstract]- Mentions

> ```dataview
> XXX
> ```
``````

## Device

- [X] Desktop
- [X] Mobile

## Trace

Running linter
Running Format Tags in YAML
format-tags-in-yaml: 0.19999998807907104 ms
Running Escape YAML Special Characters
escape-yaml-special-characters: 0.09999996423721313 ms
rules before regular rules: 0.2999999523162842 ms
Running Format YAML Array
format-yaml-array: 0.40000003576278687 ms
Running Move Tags to YAML
move-tags-to-yaml: 1.199999988079071 ms
Running File Name Heading
file-name-heading: 1.300000011920929 ms
Running Header Increment
header-increment: 0.699999988079071 ms
Running Headings Start Line
headings-start-line: 0.3999999761581421 ms
Running Remove Trailing Punctuation in Heading
remove-trailing-punctuation-in-heading: 0.699999988079071 ms
Running Footnote after Punctuation
footnote-after-punctuation: 1 ms
Running Move Footnotes to the bottom
move-footnotes-to-the-bottom: 0.699999988079071 ms
Running Convert Bullet List Markers
convert-bullet-list-markers: 0.9000000357627869 ms
Running Emphasis Style
emphasis-style: 0.8999999761581421 ms
Running Proper Ellipsis
proper-ellipsis: 0.800000011920929 ms
Running Remove Consecutive List Markers
remove-consecutive-list-markers: 0.6000000238418579 ms
Running Remove Empty List Markers
remove-empty-list-markers: 0.5999999642372131 ms
Running Remove Hyphenated Line Breaks
remove-hyphenated-line-breaks: 0.699999988079071 ms
Running Remove Multiple Spaces
remove-multiple-spaces: 0.9000000357627869 ms
Running Strong Style
strong-style: 0.8999999761581421 ms
Running Two Spaces Between Lines with Content
two-spaces-between-lines-with-content: 0.19999998807907104 ms
Running Compact YAML
compact-yaml: 0.10000002384185791 ms
Running Consecutive blank lines
consecutive-blank-lines: 0.5 ms
Running Empty Line Around Blockquotes
empty-line-around-blockquotes: 0.3999999761581421 ms
Running Empty Line Around Code Fences
empty-line-around-code-fences: 0.19999998807907104 ms
Running Empty Line Around Math Blocks
empty-line-around-math-blocks: 0.6000000238418579 ms
Running Empty Line Around Tables
empty-line-around-tables: 0.5999999642372131 ms
Running Heading blank lines
heading-blank-lines: 0.800000011920929 ms
Running Line Break at Document End
line-break-at-document-end: 0 ms
Running Paragraph blank lines
paragraph-blank-lines: 0.5999999642372131 ms
Running Remove Empty Lines Between List Markers and Checklists
remove-empty-lines-between-list-markers-and-checklists: 0.8999999761581421 ms
Running Remove link spacing
remove-link-spacing: 0.10000002384185791 ms
Running Space after list markers
space-after-list-markers: 0.5 ms
Running Trailing spaces
trailing-spaces: 0.6000000238418579 ms
Running Custom Regex
custom regex rules: 0.19999998807907104 ms
Running Capitalize Headings
capitalize-headings: 0.5 ms
Running YAML Key Sort
yaml-key-sort: 0.699999988079071 ms
rules after regular rules: 1.5 ms
rules running: 21.19999998807907 ms
Running Custom Lint Commands

**Comment by usernotnull** [comment]
The issue seems that the option "Empty Line Around Code Fences" inside a code block is adding the blank line with a ">" which is breaking the callout.

What are your thoughts on this? Can a logic be added to check if the paragraph is in a callout of quote and add a blank line with a ">"?

**Comment by pjkaufman** [comment]
This could be related to a recent change I made, so I will have to check on that and just make sure nothing weird is going on with it.

**Comment by pjkaufman** [comment]
The likely culprit is #817 . I believe I need to do an initial check as to whether or not I am dealing with an empty line around a blockquote or callout initially. If I can handle that as I currently am, but if it is meant for things like code blocks and tables, use the previous logic which I believe works with this scenario.

**Comment by pjkaufman** [comment]
Looks like it is unrelated to #817 . I will see what I can find out about this.

**Comment by usernotnull** [comment]
Thanks!
I'll wait for the release and re-open in case not resolved.
