### ISSUE TITLE
Bug: `Lint on File Change` Throws Error when Current File Deleted

### ISSUE THREAD

**Issue by hogru** [platers/obsidian-linter#834]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

When changing and deleting the changed file, Linter throws an error.

## How to Reproduce

1. Turn on `Lint on File Change`
2. Change the content of `abc.md` (file name does not matter)
3. (Change my mind) and delete the file

Console output:

```
plugin:obsidian-linter:43 [Obsidian Linter] Lint File Error in File 'abc.md':
Error ENOENT: no such file or directory, open '/Users/stephan/Datenbanken/Obsidian/Notizen/abc.md'
Error: ENOENT: no such file or directory, open '/Users/stephan/Datenbanken/Obsidian/Notizen/abc.md'
```

## Expected Behavior

Don't try to lint a deleted file.

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Gotcha. Thanks for reporting this. I should be able to handle this scenario for the next release.

**Comment by hogru** [comment]
Just want to add... that's really a minor bug and does not reflect how much I love your plugin :-)

**Comment by pjkaufman** [comment]
No problem. I am glad you find it useful!

**Comment by pjkaufman** [comment]
This change should be on master now and go out with the next release. Please let us know if there is a problem with master or the next release.
