### ISSUE TITLE
Bug: (serious) Linter lints pdf attachments

### ISSUE THREAD

**Issue by nhan000** [platers/obsidian-linter#837]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

With "Lint on File Change" on, after viewing a PDF in Obsidian 1.4.2, Linter lints the PDF and corrupts it.

To replicate. Choose a PDF that's an export of a Word document (True PDF, not a scanned PDF).

## Expected Behavior

I expect Linter to only lint .md files.

## Device

Windows 11 updated

## Additional Context

I don't know if it also happens when viewing an embeded PDF (likely not) but if you're fixing this please test that case too. Sorry I was too scared of what happened (This bug triggered others plugins to behave erratically, generating weird files, and crashed Obsidian).

I was really surprised that Linter works on PDF. Is there a way to limit Linter to work only on .md files?

**Comment by pjkaufman** [comment]
It might take a day or 2 for me to get to this. So I would recommend turning off that rule. The Linter can run against a PDF as it does not normally check the extension of the file it runs against, but typically it runs it against a list of markdown files. I just take it for granted that you would be viewing a markdown file in Obsidian, so I will see about fixing that scenario.

**Comment by pjkaufman** [comment]
As a dev note: updating the following line to include `|| this.lastActiveFile.extension === 'md'` should roughly handle the issue:
https://github.com/platers/obsidian-linter/blob/0a9b86621d541c33f2d35a4770c85885b4ae55fd/src/main.ts#L259

**Comment by pjkaufman** [comment]
@nhan000 , the embed you are referring to is essentially the following, right? `![[fileName.pdf]]`.

If so, we should be good to go on this.

**Comment by nhan000** [comment]
Yes that's the embed I was referring to. Thank you!

**Comment by pjkaufman** [comment]
This should be taken care of on master and go out with the next release. Please let us know if there is an issue with either.
