### ISSUE TITLE
[bug] linter settings button work but text is aways "enabled"

### ISSUE THREAD

**Issue by Parlazo** [platers/obsidian-linter#84]
i had to uninstall and reinstall linter to get the settings tab back in obsidian
now i have cool buttons to enable and disable settings
what ever i click ... the test "enabled" does not change... it is confusing

**Comment by chrisgrieser** [comment]
Could you provide some screenshots and/or a screencast what exactly you mean?

**Comment by Parlazo** [comment]
![linter](https://user-images.githubusercontent.com/66982240/135704244-dce48882-1f80-40a5-aa64-d93d822aa394.png)

**Comment by Parlazo** [comment]
i think its some how contradicting ... is it enabled as the text tells me or is it disabled as the button tells me?

**Comment by platers** [comment]
you toggle the button to enable or disable the rule. So right now its disabled. The 'Enabled' text is just telling you that the toggle enables or disables the rule. 
Do you have any suggestions for a less confusing label?
