### ISSUE TITLE
FR: Option to enclose title  in Yaml frontamtter with quotes (when using H1 to create)

### ISSUE THREAD

**Issue by danieltomasz** [platers/obsidian-linter#840]
Currently there is no such options, if the title contains yaml special characters it will broke the properties

Request:
Add option to enclose title in quotes (either single or double)  when creating it from H1 in Linter settings

**Comment by danieltomasz** [comment]
There might be option to put enclose title with quotes even when it exist as well

**Comment by pjkaufman** [comment]
@danieltomasz , I am guessing that you are saying that force YAML escape is either not running at the right time or just not adequate for this scenario. Is that correct?

**Comment by danieltomasz** [comment]
My scenario:

1. I have my frontmatter H1 in my file
```
# Untitled 1:f
```
2. I set  within settings
```
YAML Title
Inserts the title of the file into the YAML frontmatter. Gets the title based on the selected mode.
Mode ; First H1 or Filename if H1 is Missing
```

3. When I lint I am getting in my yaml
```
title: Untitled 1:f
```

Which is clearly invalid for Yaml

4. My preferred behaviour - running linter should insert
```
title: "Untitled 1:f"
```

**Comment by pjkaufman** [comment]
Yeah. That is just a scenario that was not accounted for. I can add logic to escape the colon as well. I am just not sure on the concept of adding a force escape to the title.

**Comment by danieltomasz** [comment]
My personal preference would be to not escape any specific characters but just enclose whole title in quotes (optionally  rule per user settings)
This would be useful  with Obsidian 1.4 as there will be stronger yaml rules enforcing

**Comment by pjkaufman** [comment]
I will see what can be done. I am not sure where this will fall all things considered though.

**Comment by pjkaufman** [comment]
@danieltomasz , `title: Untitled 1:f` is valid YAML. It is only not valid when you have it like the following `title: Untitled 1: f`

So it only becomes invalid when there is an unescaped colon and then a space (`: `).

**Comment by danieltomasz** [comment]
Thanks for answers! I can close it right now :)

**Comment by pjkaufman** [comment]
No problem.
