### ISSUE TITLE
Bug: Pasting document link with period in title, period content not included

### ISSUE THREAD

**Issue by dylan-dot-tech** [platers/obsidian-linter#846]
## Describe the Bug

If I have a `.md` document with a decimal value in the title, for example `Half is .5`, the decimal content is **not** included when pasting a link to the document. That is, pasting `[[Half is .5]]` from your clipboard pastes as `[[Half is ]]`. This is due to the [Remove Leftover Footnotes from Quote on Paste](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#remove-leftover-footnotes-from-quote-on-paste) setting as disabling this setting will paste the link as expected: `[[Half is .5]]`. I do not believe this is the expected behavior for that specific setting as it is not a footnote, it is an internal link.

## How to Reproduce

1. Linter: Enable the [Remove Leftover Footnotes from Quote on Paste](https://github.com/platers/obsidian-linter/blob/master/docs/rules.md#remove-leftover-footnotes-from-quote-on-paste) plugin setting
2. Create a new note with a decimal value in the title, ex: `The value is .333 repeating of course`
3. Link the newly created note in itself so that the document content would then equal `[[The value is .333 repeating of course]]`
4. Copy the link `[[The value is .333 repeating of course]]` to your clipboard
5. Paste your clipboard into the same (or any) document
6. The resulting paste does **not** include the decimal value, thereby linking to a document that does not exist, ex: `[[The value is  repeating of course]]`

## Expected Behavior

The expected result should paste the document link without removing the decimal value in the title to maintain the integrity of said link.

Expected output: `[[The value is .333 repeating of course]]`

## Device

- Desktop
  - Linux Mint 21.2 Cinnamon
  - Obsidian v1.3.7.AppImage
  - Linter v1.19.1

**Comment by pjkaufman** [comment]
Thanks for reporting this @dylan-dot-tech . I will need to see about ignoring links for this paste method.

**Comment by pjkaufman** [comment]
I believe I have a fix. I am just not sure if it has any wider implications. Hopefully it will be relatively small and just affect this.

**Comment by pjkaufman** [comment]
I just pushed up the fix for this. It should be on master now and go out in the next release. Please let us know if this does not work or has any issues on master or in the next release.
