### ISSUE TITLE
FR: Improve German Localization

### ISSUE THREAD

**Issue by afischer211** [platers/obsidian-linter#847]
- [x] I have verified that I am on the latest version of the Linter (1.19.1)

## Describe the Bug

The german localization is very poor and partly not understandable.
One example is the word "Flusen".

## How to Reproduce

1. Use Obsidian and the Linter plugin with german language

## Expected Behavior

A understandable german ui.
 
## Screenshots

![CleanShot 2023-08-14 at 17 38 23](https://github.com/platers/obsidian-linter/assets/4056990/a5483b86-0556-4628-9423-90399e519ce4)

## Device

- [x] Desktop
- [ ] Mobile

## Comment

I could help you with german translation (is my natural language).

**Comment by pjkaufman** [comment]
Help with that translation would be greatly appreciated. I do not speak German, so what is there is just a google translate of the values.

There is some information on how to do the translation listed here on the new wiki which I am still linking into the plugin here: https://platers.github.io/obsidian-linter/contributing/translation/#addingupdating-values-for-an-existing-language

**Comment by pjkaufman** [comment]
Hey @afischer211 , I wanted to reach back out and see if you had any suggestions around updating the German translation for the Linter. I know that you said you would be willing to help, so I thought I would reach out and ask. Feel free to let me know if anything needs better documentation or what wordings are and what they should be.

**Comment by afischer211** [comment]
Hello,
I'm starting with the work and hopefully I can create a PR until end of the week.

**Comment by pjkaufman** [comment]
Thanks @afischer211 . Feel free to reach out if you run into any issues.
