### ISSUE TITLE
Bug: takes two passes to remove period and trailing space in a header

### ISSUE THREAD

**Issue by PatrickF1** [platers/obsidian-linter#851]
- [X] I have verified that I am on the latest version of the Linter

## Describe the Bug

The linter needs to be run twice / manually make two passes in order to remove both a trailing period and space in a heading.

## How to Reproduce

1. Turn on "Remove trailing punctuation in heading" and "Removes extra spaces after each line"
2. Create a note and create this heading `## Heading with trailing period and space. `
3. Lint the file, notice the trailing space was removed but not the period
4. Lint again without making any changes, and notice the period was removed

## Expected Behavior

Both the trailing period and space should be removed in one pass.

``` markdown
## Heading with trailing period and space
```

## Device

- [X] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Thanks for reporting this @PatrickF1 . I am not sure this a bug, but I can see about ignoring whitespace when removing trailing punctuation. My guess is that there is whitespace after the punctuation causing it to assume that the punctuation is not truly trailing. 

I will have to take a closer look to see if my understanding of the problem is correct.

**Comment by pjkaufman** [comment]
I have a change that should take care of this. I will push it up shortly.

**Comment by pjkaufman** [comment]
This should be on master and go out with the next release. Please let us know if there are any issues around it.

**Comment by PatrickF1** [comment]
Wow that was super fast. Thank you Peter!

**Comment by pjkaufman** [comment]
No problem. I was working on some other things, but since this was a pretty easy change, I decided to give it a shot.
