### ISSUE TITLE
FR: Delete all the blank lines

### ISSUE THREAD

**Issue by yoghurtdewdew** [platers/obsidian-linter#853]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Hello, I really like your plugin, but I found that no matter what the settings are, blank lines cannot be completed removed. I hope to support switches to remove all blank lines, unless there are other corresponding switches below to keep at least one blank line.

## Expected Behavior

Delete all the blank lines unless I set to keep one.

## Device

- [x] Desktop

**Comment by pjkaufman** [comment]
Hey @yoghurtdewdew . I am not sure I follow this bug report. Which rules imply that you can remove blank lines and are not doing so?

If there is not a rule that currently does this, this may be a feature request that has already been made, but I would need to double check on that.

**Comment by yoghurtdewdew** [comment]
For example, I need blank lines get disappeared to make valid markdown table.

<img width="580" alt="image" src="https://github.com/platers/obsidian-linter/assets/63794438/438e87b9-9ead-4250-8f18-5a3adc389129">

**Comment by yoghurtdewdew** [comment]
There is no rules to delete all blank lines, there is always at least one blank line between different lines. I need all blank lines just get deleted, "leave at least one blank line" or "just delete duplicate blank lines" doesn't work for this.

**Comment by pjkaufman** [comment]
Why not use the following custom replacement values?
Find: `\n{2,}`
Flags: `gm`
Replace: `\n`

It will take 1 or more blank lines and replace them with no blank lines.

**Comment by yoghurtdewdew** [comment]
Thank you for your reply, I do not know Regex substitution, so I would like to use linter to help me. I hope it would be able to support the removal of all blank lines. That not only useful for the table format, I usually like no blank lines everywhere, no blank lines between headings and paragraphs or between paragraphs and paragraphs.

**Comment by pjkaufman** [comment]
The regex above should do that for you.

**Comment by pjkaufman** [comment]
All you should need to do is add the values I mentioned above into custom replacement and it should do what you are asking for.

**Comment by yoghurtdewdew** [comment]
Thanks for your instructions! But the custom regox conflict with other rules: one blank line for title/table in the front&back.

<img width="683" alt="image" src="https://github.com/platers/obsidian-linter/assets/63794438/5822e36d-1ad8-407f-a618-28b385d157b3">
<img width="649" alt="image" src="https://github.com/platers/obsidian-linter/assets/63794438/7716ffd7-d879-4cda-bc5f-d39e8781f5fc">

**Comment by pjkaufman** [comment]
That makes sense to me. I am not sure that there is, or will be, a rule for removing blank lines with the specifications that have been provided since it is unclear which blank lines need to be kept and which ones need to be removed. Initially I thought it was all blank lines that would be removed. However it seems there are exceptions. Due to that there will likely need to be a rule added or a custom command added via QuickAdd to handle the particulars.

I am open to adding this kind of rule if there are clearly defined places that blank lines would be removed, and there is a desire from the community to implement that formatting style. In the meantime, I am open to PRs to add this feature, but I don't know that I will be able to get to this myself barring a desire to have this from the community.

**Comment by yoghurtdewdew** [comment]
I thought **step-1-clean**-blank-lines https://github.com/platers/obsidian-linter/issues/853#issuecomment-1685232147 will work, and **step-2-keep**-blank-lines https://github.com/platers/obsidian-linter/issues/853#issuecomment-1685595457 will work after that former replacement.

**Comment by pjkaufman** [comment]
I am not sure how the Linter would be able to satisfy what you are asking since I am not sure of all of the cases where you want to retain a blank line. Without knowing that it is hard to know if the Linter can do anything to help in this case.

**Comment by pjkaufman** [comment]
I am going to close this since it looks like the discussion ahs long died out on this. If I can get clarification on exactly what is expected here, I may be able to better help with this. But given how long this has been stale and the info I see here, I am going to close this.
