### ISSUE TITLE
FR/BUG? Keep alias that matches the filename

### ISSUE THREAD

**Issue by zanodor** [platers/obsidian-linter#855]
I have always had this turned off. It is superfluous.  

Now, I cannot decide if it is a bug as in not working well or we need a feature request here but when I lint a file that has an alias value matching the title/filename, they don't get removed. 
I am guessing the functionality only caters to key creation not maintenance? Could we have the scope of this setting expanded to remove alias values that equal the title/filename. That would be great.  

Cheers

Z.

**Comment by pjkaufman** [comment]
Hey @zanodor . Could you provide a sample scenario and what settings you have turned on? I am not sure how to look into the scenario in question if I don't know which settings are active for the rule and what values are already present.

**Comment by pjkaufman** [comment]
Hey @zanodor . I think I got distracted when looking at this before. Could you provide your `data.json` that would make things much clearer on my end. I am not able to test how other plugins interact with the Linter when dealing with Commander and a lot of other places, but if there is something not working right with the Linter, I can see about fixing that.

**Comment by pjkaufman** [comment]
Sounds good. I will close this then since that should be taken care of by some recently merged logic.
