### ISSUE TITLE
FR: Delete Duplicate Array Values from YAML

### ISSUE THREAD

**Issue by zanodor** [platers/obsidian-linter#857]
Further to our discussion at #855, please add a toggle or perhaps preferably a rule (without a setting) that removes any duplicate keys, e.g. from alias property (actually any number over one instance should be removed).  

Of course, diactric characters like `ä`, etc. are not to be taken as equals of `a`, etc. And "Lion" does not equal "lion".  But these are of course self-explanatory.

Thank you,

Best

**Comment by pjkaufman** [comment]
Just as a heads up, this is similar to https://github.com/platers/obsidian-linter/issues/508. It just deals with removing duplicates for tags.

**Comment by pjkaufman** [comment]
Likely this would get added as its own rule to remove duplicate YAML array values.

**Comment by pjkaufman** [comment]
No worries. I was just noting the overlapp as that will help me close both issues when one has a code change that completes it.
