### ISSUE TITLE
Bug: Invalid Date Format Makes Linter Always Update Date Modified Timestamp

### ISSUE THREAD

**Issue by FChris** [platers/obsidian-linter#861]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Linter always updates "date modified" in the front matter, even if no modifications were made by the linter or the user.

## How to Reproduce

1. Go to 'Linter Settings'
2. Got to 'YAML'
3. Scroll down to 'YAML Timestamp' > 'Format'
4. Enable "Keep track of the date file was last edited in the YAML Frontmatter..."
5. Enable "Date Modified"
6. Add "yyyy-MM-DDTHH:mm" Format
7. Create a new note with random name and random content
8. Execute Linter for the first time and front matter will be filled with the date modified
9. Repeatedly execute the linter after some time has passed (at least 1 min) without changing any content of the file.

[Linter-Debug.log](https://github.com/platers/obsidian-linter/files/12432676/Linter-Debug.log)

## Expected Behavior

I would expect that the 'date modified' is only updated if at least one change was made.

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

One place where this issue originates is the `handleDateCreatedValue` function in the yaml-timestamp.ts
This method will always return textModified true as far as I can see, thus resulting in an update of the dateModified, even if the `date created` is not changed.
However, apparently this is not the only place that needs to be changed to fix the behaviour. 

I haven't figured out if it is actually possible to know whether any changes were made in the `handleDateModifiedValue` function.
I'd be glad to create a pull request if there can be a fix for this.

**Comment by pjkaufman** [comment]
If you can include the `data.json`, I may be able to take a look and see about reproducing this.

**Comment by pjkaufman** [comment]
As a dev note, there are scenarios where `handleDateCreatedValue` will return false if it does not make a change.

**Comment by FChris** [comment]
Sure, here you go. I had to rename the file to data.txt because Github does not let me upload a json file. 
You can simply rename it again after downloading. 

[data.txt](https://github.com/platers/obsidian-linter/files/12432790/data.txt)


Amazingly fast response time  btw. :-)

**Comment by pjkaufman** [comment]
Thanks! I will have to take a look at this tomorrow or later tonight based on my availability.

**Comment by FChris** [comment]
Thank you, let me know if I can help somehow :-)

**Comment by pjkaufman** [comment]
@FChris, am I missing something or did you add a space to the end of your moment format?
``` JSON
    "yaml-timestamp": {
      "enabled": true,
      "date-created": true,
      "date-created-key": "date created",
      "force-retention-of-create-value": false,
      "date-modified": true,
      "date-modified-key": "date modified",
      "format": "yyyy-MM-DDTHH:mm "
    },
```

You need to remove the space at the end of the format to make the problem go away.

**Comment by pjkaufman** [comment]
I plan to add some logic to trim the format in the rules themselves. But the issue is caused by a bad moment format.

**Comment by pjkaufman** [comment]
I pushed up a change that should fix this moving forward. However it does not fix the bad format present in the settings. This should still fix the issue on master and in the next release. Please let us know if that is not the case.

**Comment by FChris** [comment]
I did not notice the blank space in there and I guess I would have thought it does not matter as the behavior was as expected in all other cases. With the space removed it now works just as expected.

 Thank you for the  help and update :-)

**Comment by pjkaufman** [comment]
No problem.
