### ISSUE TITLE
FR: Alter the functionality of "Folders to Ignore" / add files

### ISSUE THREAD

**Issue by TheOverpassArsonist** [platers/obsidian-linter#864]
## Is Your Feature Request Related to a Problem? Please Describe.
I configured Linter to do cleanup (as is intended) but noticed that it killed my excalidraw files. (which is a reported bug) I then added ./Attachments to the "Folders to Ignore" list which seemed to fix the problem at first, but then I noticed it would still attempt to lint an excalidraw file that was manually saved (or saved and exited in my case) so while it wasn't breaking my previous excalidraw files it _**was**_ breaking any new ones as I made them and saved them 

## Describe the Solution You'd Like

I would suggest either adding a "Files to Ignore" or "Extensions to Ignore" field or making it so that any item inside of an ignored folder will never be linted, even if it's activated by saving the file.

**Please include an example where applicable:**
N/A

## Describe Alternatives You've Considered

Alternatives mentioned above, adding a blacklist for extensions or regex name matching to file names would be another solution, although I imagine they would take more tooling to implement.

**Comment by pjkaufman** [comment]
@TheOverpassArsonist , thanks for making the request. The Linter is supposed to only work on Markdown (`.md`) files. If there is a place that is not happening, I would be happy to fix that.

Could you give a sample non-md file and a set of steps you took to lint that file (for example `ctrl+s` or a specific obsidian command that was used)?

**Comment by pjkaufman** [comment]
I think I found a couple of places that were not checking that the file is a Markdown file (`.md`). I have updated several of them to not work on non-markdown files. But if you could give me a scenario that I could test against or if you would be willing to test out a custom version of the plugin, I can make sure it covers the issue described in this ticket.

**Comment by TheOverpassArsonist** [comment]
The issue I noticed specifically was that when I pressed my hotkey to create and embed an Excalidraw canvas I could create the canvas, draw on it, etc. like expected, however when I then pressed my hotkey to close the tab and go back to my original tab the drawing would fail to load and be corrupted. Specifically, the files are saved like 
`./Attachments/Testing Excalidraw YYYY-MM-DD HH.mm.ss.excalidraw`
and I have 
`./Attachments`
set as my "Folder(s) to Ignore"

In hindsight I probably should have added this in the original issue but given I thought that the way to fix it would be to more strictly apply the "Folders to Ignore" rule I guess I didn't think the naming would have been relevant. For testing purposes I would be willing to use a custom version of the plugin if there is anything else you want to know.

**Comment by pjkaufman** [comment]
`./Attachments` will not work for folders to ignore from my understanding. It should be `Attachments/`.

**Comment by TheOverpassArsonist** [comment]
> `./Attachments` will not work for folders to ignore from my understanding. It should be `Attachments/`.

after adding it (and backing up my vault) I ran a manual linting on the folder again and it worked. I do expect that it is linux-exclusive behaviour though since ./ is, itself, linux specific. (insert obligatory "well actually uni-" yes, we know) Since linux literally presents things like . and .. as directories on the filesystem level it correctly ignores them fine. 

If it wasn't working at all then I'd 100% agree that it's a different issue (or arguably not an issue at all since this is more of a linux-specific usecase) but the fact that it does work to prevent manual folder linting but doesn't work to prevent individual file linting indicates that it's a more specific issue with folder exemptions not applying depending on what calls the linting. Inconsistent behaviour implies that it's an issue that would span OS-es since if it was strictly an incompatibility with linux or linux behaviour/features then it shouldn't work at all. I'm not sure if this is intended functionality or not so I made it as an FR to include a check for excluded folders in manual saves instead of a bug report saying that it didn't do that.

**Comment by TheOverpassArsonist** [comment]
Does the linting always start from the root of the vault, or does it run within each subfolder individually? It might have been that the excalidraw embeds I tested on were in my root Attachments folder as opposed to the Attachments folder within the subfolder where they're embeded. I don't have any real way of testing that but it would explain why it worked before and isn't now. If it's run from the root of the vault then the ./ directory functionality wouldn't work on the subfolders but would point to /Attachments, so if it's always run from the root of the vault with full-length-paths (well, full length relative to the vault) then that might explain it. I thought I had tested on folders where I had the embeds local but maybe I didn't and I'm just misremembering.

**Comment by pjkaufman** [comment]
It does a starts with check on the file path. So in your case you are saying ignore a folder called Attachments at the root of my vault when you have a value of `Attachments`.

**Comment by pjkaufman** [comment]
I see a lot of discussion here, but it looks like the core issue should be resolved here since only `md` files should be lintable. If another filetype can currently be linted, we can revisit this. In the meantime, I will go ahead and close this.
