### ISSUE TITLE
Question: Use property "aliases" instead of "alias"

### ISSUE THREAD

**Issue by vanbang9710** [platers/obsidian-linter#867]
When enabling "Inserts the title of the file into the YAML frontmatter's aliases section. Gets the title from the first HI or filename.", it inserts an "alias" property ![|50pct](https://i.imgur.com/L1PA6Uo.png)
But ["alias" is deprecated](https://help.obsidian.md/Editing+and+formatting/Properties#Deprecated%20properties) in favor of "aliases"

**Comment by pjkaufman** [comment]
Thanks for pointing that out @vanbang9710 . Currently v1.4 is still juat for insiders. So for now the Linter uses whichever value you have right now or it picks one to use.
