### ISSUE TITLE
Bug: Quote style is not applied 

### ISSUE THREAD

**Issue by RhvdG** [platers/obsidian-linter#885]
- [X] I have verified that I am on the latest version of the Linter

## Describe the Bug

When the file has an even number of straight single quotes, Linter complains that it doesn't, and won't make the straight quotes curly.

## How to Reproduce

Write a file with one or more words in single quotes, and save it, triggering Linter. 

## Expected Behavior

Curly quotes and no complaints :-)

By the way, the "even number" test seems unwise, given that in many languages, like Dutch and English, single instances of single quotes are used, as in ``zo'n`` and ``doesn't``.

## Screenshots
<img width="265" alt="image" src="https://github.com/platers/obsidian-linter/assets/34862159/fb00d2d5-a67b-4e23-bb39-5942627e4f92">

<img width="336" alt="image" src="https://github.com/platers/obsidian-linter/assets/34862159/77660be8-3d77-4d9d-9ad4-2c1e9acb9212">

## Device

- [X] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Hey @RhvdG , I will need to look at the scenario in question. The Linter does look into whether or not an English contraction is being used (I cannot acvount for other languages as I don't know contractions in other languages).

Would you recommend checking the character before and after a single or double quote to see whether it should be an opening or closing smart quote? If so, how are fullwidth characters handled? If we are not dealing with fullwidth characters, how do we handle a quote character between 2 non-quote characters?

I look forward to seeing how this logic can be improved.

**Comment by RhvdG** [comment]
Hi. In Dutch, English, French, Italian (and probably in other languages as well) when a ``'`` occurs inside a word, with [a-z,A-Z] on both sides, it's always a closing quote mark ``’``.  

``Zo’n``
``Don’t``
``l’autre``
``all’inizio``

I am not sure what you mean by "fullwidth characters".

**Comment by pjkaufman** [comment]
Full width characters are Chinese, Japanese, and Korean characters, but they are also used as English characters sometimes. Fullwidth characters have no need to have spacing added around them as they already come with it added in.

**Comment by pjkaufman** [comment]
I am thinking that the following could work as an option for a replacement algorithm that is more robust:

Go through and determine opening and closing values based on what preceeds and follows the quote. When the quote is followed by a letter, it is an opening quote. If it is followed by and/or preceeded by a letter it will be a closing quote.

If the surrounding characters are not letters then it will be determined based on what the last quote was. If the last quote was an opening quote it will be a closing quote. Otherwise it will be an opening quote?

**Comment by RhvdG** [comment]
Sounds about right!

**Comment by pjkaufman** [comment]
I believe I have a fix for this. It should not be too bad to implement. There are some edge cases that may need to be ironed out. But I plan to push it up and have it in the next release.

**Comment by pjkaufman** [comment]
This has been merged into master now. It should take care of the problem in question and add better support. It may need modification, but it is better than it was before from my understanding.

Please let us know if there is an issue on master or in the next release.
