### ISSUE TITLE
FR: Ignore updating timestamps when linting all files in folder/vault

### ISSUE THREAD

**Issue by usernotnull** [platers/obsidian-linter#886]
## Is Your Feature Request Related to a Problem? Please Describe.

I am making a mass styling change that affects all files in the vault. 
In the frontmatter, I am tracking the date-modified, and linter updates the value whenever I save the file (Ctrl + S) as set in the options.
The issue I'm facing is that the modified date, when linting all files in the vault, is also updating all the files' date-modified.
Everyone may have different uses for the 'date-modified' field, so I'm suggesting the below solution to cope with the users who do not want to update this field for **mass linting** changes in the vault but still want to update it when working on the currently open file.

## Describe the Solution You'd Like

Add a checkbox in the 'YAML Timestamp' settings to `Ignore updating timestamps when linting all files in folder/vault`.

## Describe Alternatives You've Considered

I am disabling and re-enabling the checkbox `Keep track of the date the file was last edited in the YAML front matter. Gets dates from file metadata.` every time I am mass linting, which is far from ideal.

**Comment by pjkaufman** [comment]
Hey @usernotnull . Could you explain why mass changes are any different than single file changes? Or at least why linting rules shoukd act differently between the 2 scenarios?

The date modified should only be updated if the file contents are, so I am not sure I understand why it should be optionally turned off for mass lint operations.

Thanks for helping me better understand your request!

**Comment by usernotnull** [comment]
@pjkaufman Your linter plugin helps me update the date-modified even when no linting is required, which is great! I'm expecting the currently open file to be updated because I'm editing it.

The downside is that sometimes I add a custom regex that affects the whole vault. These changes, as opposed to the currently open file, do not add any new meaning to the file except linting, so if I use dataview to query which files were updated, I will see that all my vault got updated. 

So in my reasoning, the date-modified does not mean that the content has changed per-se (I could get that date from the system properties). But the value of date-modified metadata is that, regardless of the filesystem changes of the file, or the lint changes that do not affect the contents/ideas (e.g. what I am writing), I can still lint the whole vault and STILL know that X file was last modified, as an idea, on that date. 

An example I can think of would be a MOC with diary values. The diary note could go through multiple lints, but as long as I personally have not added/removed any idea, then linting the metadata to change from single-line to multi-line should not be reflected on the date-modified.

Furthermore, each style lint with NO effects on the files is still updating the date-modified, so as a github user, with every lint of the vault, 800+ changes are being recorded!

**Comment by pjkaufman** [comment]
@usernotnull , could you give me an example file where the file contents do not change on lint, but the date modified is still updated? As per

> Furthermore, each style lint with NO effects on the files is still updating the date-modified, so as a github user, with every lint of the vault, 800+ changes are being recorded!

This is something I have worked to avoid since it was reported a couple of versions ago and has since had measures put in place to only update the file itself when something has changed.

**Comment by usernotnull** [comment]
@pjkaufman 

Here is to reproduce.

As the lint command is ran, the date-modified changes to your current date.
If you revert manually the time to let's say T00:00:00 and run lint again, no changes are done but the date-modified changes again to the current time even though nothing was changed in the end result by linting.

```
---
up: 
related: 
tags: []
aliases: []
type: 
date-created: 2023-09-03T00:00:00
date-modified: 2023-09-12T17:00:00
---
```

Here's the linter config:

```
{
  "ruleConfigs": {
    "Remove Space around Fullwidth Characters": {
      "Ensures that fullwidth characters are not followed by whitespace (either single spaces or a tab). Note that this may causes issues with markdown format in some cases.": true
    },
    "escape-yaml-special-characters": {
      "enabled": false,
      "try-to-escape-single-line-arrays": false
    },
    "force-yaml-escape": {
      "enabled": false,
      "force-yaml-escape-keys": ""
    },
    "format-tags-in-yaml": {
      "enabled": true
    },
    "format-yaml-array": {
      "enabled": true,
      "alias-key": true,
      "tag-key": true,
      "default-array-style": "multi-line",
      "default-array-keys": false,
      "force-single-line-array-style": "",
      "force-multi-line-array-style": ""
    },
    "insert-yaml-attributes": {
      "enabled": true,
      "text-to-insert": "aliases: \ntags: \ntype: \nup: \nrelated: "
    },
    "move-tags-to-yaml": {
      "enabled": true,
      "how-to-handle-existing-tags": "Nothing",
      "tags-to-ignore": "todo\npin"
    },
    "remove-yaml-keys": {
      "enabled": false,
      "yaml-keys-to-remove": ""
    },
    "yaml-key-sort": {
      "enabled": true,
      "yaml-key-priority-sort-order": "up\nrelated\ntags\naliases\ncover\nsource\ntype\ncssclasses\ndate-created\ndate-modified",
      "priority-keys-at-start-of-yaml": false,
      "yaml-sort-order-for-other-keys": "Ascending Alphabetical"
    },
    "yaml-timestamp": {
      "enabled": true,
      "date-created": true,
      "date-created-key": "date-created",
      "force-retention-of-create-value": true,
      "date-modified": true,
      "date-modified-key": "date-modified",
      "format": "YYYY-MM-DDTHH:mm:ss"
    },
    "yaml-title": {
      "enabled": false,
      "title-key": "title"
    },
    "yaml-title-alias": {
      "enabled": false,
      "preserve-existing-alias-section-style": false,
      "keep-alias-that-matches-the-filename": false,
      "use-yaml-key-to-keep-track-of-old-filename-or-heading": true
    },
    "capitalize-headings": {
      "enabled": true,
      "style": "Title Case",
      "ignore-case-words": true,
      "ignore-words": "macOS, iOS, iPhone, iPad, JavaScript, TypeScript, AppleScript",
      "lowercase-words": "via, a, an, the, and, or, but, for, nor, so, yet, at, by, in, of, on, to, up, as, is, if, it, for, to, with, without, into, onto, per"
    },
    "file-name-heading": {
      "enabled": false
    },
    "header-increment": {
      "enabled": true,
      "start-at-h2": true
    },
    "headings-start-line": {
      "enabled": true
    },
    "remove-trailing-punctuation-in-heading": {
      "enabled": true,
      "punctuation-to-remove": ".,;:!。，；：！"
    },
    "footnote-after-punctuation": {
      "enabled": true
    },
    "move-footnotes-to-the-bottom": {
      "enabled": true
    },
    "re-index-footnotes": {
      "enabled": false
    },
    "auto-correct-common-misspellings": {
      "enabled": false,
      "ignore-words": ""
    },
    "convert-bullet-list-markers": {
      "enabled": true
    },
    "emphasis-style": {
      "enabled": true,
      "style": "asterisk"
    },
    "no-bare-urls": {
      "enabled": false
    },
    "ordered-list-style": {
      "enabled": false,
      "number-style": "ascending",
      "list-end-style": "."
    },
    "proper-ellipsis": {
      "enabled": true
    },
    "remove-consecutive-list-markers": {
      "enabled": true
    },
    "remove-empty-list-markers": {
      "enabled": true
    },
    "remove-hyphenated-line-breaks": {
      "enabled": true
    },
    "remove-multiple-spaces": {
      "enabled": true
    },
    "strong-style": {
      "enabled": true,
      "style": "asterisk"
    },
    "two-spaces-between-lines-with-content": {
      "enabled": true
    },
    "unordered-list-style": {
      "enabled": true,
      "list-style": "-"
    },
    "compact-yaml": {
      "enabled": true,
      "inner-new-lines": true
    },
    "consecutive-blank-lines": {
      "enabled": true
    },
    "convert-spaces-to-tabs": {
      "enabled": false,
      "tabsize": "4"
    },
    "empty-line-around-blockquotes": {
      "enabled": true
    },
    "empty-line-around-code-fences": {
      "enabled": true
    },
    "empty-line-around-math-blocks": {
      "enabled": true
    },
    "empty-line-around-tables": {
      "enabled": true
    },
    "heading-blank-lines": {
      "enabled": true,
      "bottom": true,
      "empty-line-after-yaml": true
    },
    "line-break-at-document-end": {
      "enabled": true
    },
    "move-math-block-indicators-to-their-own-line": {
      "enabled": false
    },
    "paragraph-blank-lines": {
      "enabled": true
    },
    "remove-empty-lines-between-list-markers-and-checklists": {
      "enabled": true
    },
    "remove-link-spacing": {
      "enabled": true
    },
    "remove-space-around-characters": {
      "enabled": false,
      "include-fullwidth-forms": true,
      "include-cjk-symbols-and-punctuation": true,
      "include-dashes": true,
      "other-symbols": ""
    },
    "space-after-list-markers": {
      "enabled": true
    },
    "space-between-chinese-japanese-or-korean-and-english-or-numbers": {
      "enabled": false
    },
    "trailing-spaces": {
      "enabled": true,
      "twp-space-line-break": false
    },
    "add-blockquote-indentation-on-paste": {
      "enabled": false
    },
    "prevent-double-checklist-indicator-on-paste": {
      "enabled": true
    },
    "prevent-double-list-item-indicator-on-paste": {
      "enabled": true
    },
    "proper-ellipsis-on-paste": {
      "enabled": true
    },
    "remove-hyphens-on-paste": {
      "enabled": true
    },
    "remove-leading-or-trailing-whitespace-on-paste": {
      "enabled": true
    },
    "remove-leftover-footnotes-from-quote-on-paste": {
      "enabled": true
    },
    "remove-multiple-blank-lines-on-paste": {
      "enabled": true
    },
    "blockquote-style": {
      "enabled": false,
      "style": "space"
    },
    "quote-style": {
      "enabled": false,
      "single-quote-enabled": true,
      "single-quote-style": "''",
      "double-quote-enabled": true,
      "double-quote-style": "\"\""
    },
    "remove-space-before-or-after-characters": {
      "enabled": false,
      "characters-to-remove-space-before": ",!?;:).’”]",
      "characters-to-remove-space-after": "¿¡‘“(["
    }
  },
  "lintOnSave": true,
  "recordLintOnSaveLogs": false,
  "displayChanged": true,
  "lintOnFileChange": false,
  "displayLintOnFileChangeNotice": false,
  "settingsConvertedToConfigKeyValues": true,
  "foldersToIgnore": [
    ""
  ],
  "linterLocale": "system-default",
  "logLevel": "ERROR",
  "lintCommands": [],
  "customRegexes": [],
  "commonStyles": {
    "aliasArrayStyle": "single-line",
    "tagArrayStyle": "single-line",
    "minimumNumberOfDollarSignsToBeAMathBlock": 2,
    "escapeCharacter": "\"",
    "removeUnnecessaryEscapeCharsForMultiLineArrays": true
  }
}
```

**Comment by usernotnull** [comment]
<img width="730" alt="image" src="https://github.com/platers/obsidian-linter/assets/15612814/fd9cbe50-2ddf-4edc-8d23-59efe8ab0bd3">

Starting with a repository with no changes, I call the command to lint all the files in the vault. 
The above is a screenshot of one of the many files that have changed, and you can see that the date-modified was the only change done automatically by linter, even though no other change in that file was done.

What I was expecting was to keep the date-modified because nothing else in that file was changed as per screenshot. 

In this request, I'm taking it a step further and requesting, if you see fit, an option to disable updating this date-modified when mass linting, the reason being that on the working file that I'm actually editing, linter will help me keep the date-modified updated on saves, but I don't need this option when mass linting because otherwise all files will have the same date-modified, which is not the purpose of that field, IMHO. That field should reflect idea changes not an update because there was a trailing space somewhere.

**Comment by pjkaufman** [comment]
So it seems this is just a different use case for date modified than it was originally intended. The use case of date modified in the Linter was supposed to reflect the date modified of the file metadata (within about 5 seconds of the actual value). It was never designed to be used on different devices (hence the problem with date modified getting updated when you clone/sync the files to a new device).

I do believe it is possible to add an option to only update the date modified when the Linter makes a change, but that means that if you manually edit the file, the Linter will not know that it needs to update the file. The alternative that you have suggested is to just add an option to disable date modified updates. I would really like to avoid doing that as rules should work the same whether run against one or multiple files. However if there is a lot of desire for this functionality, it may get added.

**Comment by usernotnull** [comment]
The way I worked around this is by making a JS that modifies the date-modifed by regex, then calls the lint command. 
I bound it to CTRL+S, and disabled the linter plugin setting to update the date modified value.
That way, I can still lint the currently open file and have its modified date correct, and not affect mass linting.

It can also be done by adding the JS as a command in the linter settings to be run after linting (since those don't run when mass linting).

I'll close this. If anyone is interested I can share the script.
