### ISSUE TITLE
FR: ignore `date modified` when `date modified` is per-se the only reason to update a file

### ISSUE THREAD

**Issue by ivan-kopylove** [platers/obsidian-linter#895]
Hey,

thanks for the great plugin. I use it extensively.

The suggestion is about `ruleConfigs.yaml-timestamp.date-modified` behavior:

![image](https://github.com/platers/obsidian-linter/assets/12880107/479346c4-97e7-4227-ac1a-e79791a06c87)

My suggestion is to add a toggle to ignore `date modified` when running in a bulk mode when `date modified` is per-se the only reason to update a file

Sometimes I run linter for the whole vault (4000 files) to catch up fall-behinds.

Every before running bulk I uncheck the `date modified` to prevent all 4000 files to be modified.

Please consider adding semantics variability (e.g. via toggle) - I think it would be beneficial to update `date modified` field for those notes where there are another candidates for update rather the only `date modified` itself.

Thanks in advance.

before a bulk update:

```
---
id: 0b8bc259-8406-47b0-84a2-75c8b7190206
created: 2023-08-02T17:29:52+0300
modified: 2023-09-03T10:42:22+0300
tags:
  - my-tag
---

a note text
```

after a bulk update:

```
---
id: 0b8bc259-8406-47b0-84a2-75c8b7190206
created: 2023-08-02T17:29:52+0300
modified: 2023-09-16T16:14:09+0300
tags:
  - my-tag
---

a note text
```

**Comment by pjkaufman** [comment]
Hey @ivan-kopylove . Thanks for your input. This is a duplivate of #886 . As I mentioned there, I do not plan to have different functionality for rules that run against multiple files versus running against a single file.

However #890  may be possible once I work out the kinks with autosave (#392 )

**Comment by ivan-kopylove** [comment]
Yes, mine one is a duplicate of #886.

#890 is something looks like the solution.

Thanks for the answer
