### ISSUE TITLE
FR: Update single letter 'word' i to I

### ISSUE THREAD

**Issue by BoydyBoydy** [platers/obsidian-linter#896]
## Is Your Feature Request Related to a Problem? Please Describe.

I would like to be able to 'correct' the lowercase 'i' to the capital 'I' as I have a tendency to write out the letters first without holding the shift button.
I then have to go back and correct them (or I get a red underline stating that I can autocorrect this).

I wasn't able to find another issue like this, or maybe as it is a smaller issue it was harder to find.

## Describe the Solution You'd Like

I believe there is already a list of misspelled words that can be used.
If it is possible to add (space)i(space) or something that might actually work to find the single lowercase letters (and then update them to the capital)

Hopefully the sentence above will be suitable as an example:

**Example:**

``` markdown
i would like to be able to 'correct' the lowercase 'i' to the capital 'I' as i have a tendency to write out the letters...
```

``` markdown
I would like to be able to 'correct' the lowercase 'i' to the capital 'I' as I have a tendency to write out the letters...
```

Going through my short example, it seems that there are two things to test here, that need to be converted to 'I':
1. Capital at the start of the sentence
2. Single letter word i within a sentence.

My intention is for the option 2.
I have seen that there is another issue for updating the capital letters at the start of a sentence, so that might overlap with option 1.

## Describe Alternatives You've Considered

- I'm not sure of any real alternatives, I'm not sure if the common spellchecker will be able to automatically update words
- Manually checking that the letters are updated
- Muscle Memory to hold down the shift button, which might work but doesn't form a proper validation if I am not able to review everything properly. Having the training wheels of the linter would be much nicer.

## Additional Context

N/A

**Comment by pjkaufman** [comment]
Hey @BoydyBoydy , it sounds like you can use custom replacement to tackle this: https://platers.github.io/obsidian-linter/settings/custom-rules/

Depending upon how nuanced you need it to be, I would just write ` i ` as the search text, `gm` as the flags, and ` I ` as the replacement value. It should then handle a lowercase i proceeded and followed by at least 1 space.

**Comment by BoydyBoydy** [comment]
Hi @pjkaufman, thanks for your quick response.

I was able to use the custom regex expressions quite easily.
(I was ready to do some proper regex, but I didn't realise that the custom regex was so easy to use)

I have done as you have suggested and it seems to work really well. Thanks again.
I was hoping that this small issue wouldn't impact the wider use of the tool and the regex helped more than expected.

:) - I will close this issue.
