### ISSUE TITLE
Can't enable plugin

### ISSUE THREAD

**Issue by ituri** [platers/obsidian-linter#90]
When trying to load the linter plugin on Obsidian 0.12.16 on Mac OS, I get the following error:
```
Plugin failure: obsidian-linter TypeError: fencedRegexTemplate.replaceAll is not a function
    at anonymous (eval at <anonymous> (app.js:1), <anonymous>:9596:56)
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
l @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.enablePlugin @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
t.enablePluginAndSave @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
o @ app.js:1
(anonymous) @ app.js:1
t.setValue @ app.js:1
t.onClick @ app.js:1
```

Is there anything I can do on my side to fix this problem?

**Comment by platers** [comment]
hmm Its working fine for me on obsidian v0.12.15. 
The replaceAll function is a new function in javascript, somehow obsidian must be using an older version https://www.designcise.com/web/tutorial/how-to-fix-replaceall-is-not-a-function-javascript-error. No idea why its different for you :/
A simple fix would be to replace all calls to replaceAll

**Comment by ituri** [comment]
>  A simple fix would be to replace all calls to replaceAll
That worked out for now. 
I hope that this is issue only came up because I'm running the Insider Build and that it won't be a problem for other users once the next version of Obsidian appears on the official channel.
