### ISSUE TITLE
Bug: no bare URL will contain some illegal characters

### ISSUE THREAD

**Issue by calmwaves111** [platers/obsidian-linter#900]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

I am a Chinese language speaker and I want to directly follow Chinese characters after URLs, but I will include these Chinese characters

## How to Reproduce

original sentence
```
我是一个网址https://github.com/platers/obsidian-linter一些中文字符。被包含进去了
```
After pressing ctrl+s to format
```
我是一个网址<https://github.com/platers/obsidian-linter一些中文字符。被包含进去了>
```
If I continue to add
```
我是一个网址<https://github.com/platers/obsidian-linter一些中文字符。被包含进去了>如果我继续写
```
Press ctrl+s again
```
我是一个网址<<https://github.com/platers/obsidian-linter一些中文字符。被包含进去了>如果我继续写>
```

## Device

- [x] Desktop
- [ ] Mobile

## Additional Context

V1.19.1 does not meet this issue, V1.20.0 meet this issue

**Comment by pjkaufman** [comment]
Hey @calmwaves111 . I see that there is an issue where `>` is being included in the URL, but what seems to be the other illegal characters that have been allowed in the URL?

**Comment by calmwaves111** [comment]
yes, My expectations is
```
我是一个网址<https://github.com/platers/obsidian-linter>一些中文字符。被包含进去了
```
Chinese characters should not be included

**Comment by pjkaufman** [comment]
Two things to account for here based on what has been stated here:
- Make sure that `>` is not included in the link at all (this was accidentally removed)
- Make sure Chinese characters are not allowed in the URL
If I am misunderstanding, please feel free to correct me.

**Comment by pjkaufman** [comment]
I believe I have a fix for this. It should go out with the next release.

**Comment by pjkaufman** [comment]
This change has been merged into master and should go out in the next release. Please let us know if either of them has any issues. Thanks!
