### ISSUE TITLE
Bug: Linting on Save and File Change not working

### ISSUE THREAD

**Issue by joshrouwhorst** [platers/obsidian-linter#904]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

I can't get linting to work on save or on file change. The only way I can get it to run is by calling the "Lint the current file" command.

## How to Reproduce

1. In Linter settings, turn on "Lint on save", "Display message on lint", "Lint on File Change", and "Display Lint on File Change Message".
2. Open a note and write some text.
3. Press cmd+s to save.

No logs showing in Linter Logs.

## Expected Behavior

Expected output if applicable:

I would expect the linting message to appear and for it to run rules on the content of the note when I press cmd+s or change the file content.

## Device

- [x] Desktop
- [ ] Mobile

Obsidian 1.4.14
MacOS 13.5.2

**Comment by pjkaufman** [comment]
Hey @joshrouwhorst . Are you using a file that ends in the `.md` extension?

**Comment by joshrouwhorst** [comment]
> Hey @joshrouwhorst . Are you using a file that ends in the `.md` extension?

They are, but I just realized this was my bad. I had the ignore folder set one level too high and so some files were linting and some weren't.

**Comment by pjkaufman** [comment]
> > Hey @joshrouwhorst . Are you using a file that ends in the `.md` extension?
> 
> They are, but I just realized this was my bad. I had the ignore folder set one level too high and so some files were linting and some weren't.

Gotcha. I am glad that got sorted out.
