### ISSUE TITLE
FR: If it's a list, remove spaces before the list indicators

### ISSUE THREAD

**Issue by nhan000** [platers/obsidian-linter#905]
## Is Your Feature Request Related to a Problem? Please Describe.

Sometimes copy and paste text results in

```markdown

- 1st item
	 - Have 1 tab character + 1 space
	  - Have 1 tab character + 2 spaces
```

I'd like to lint it to be
```markdown
- 1st item
	- Have 1 tab character 
	- Have 1 tab character 
```

## Describe the Solution You'd Like

Linter removes all spaces between the tab and the list indicator (I use `-`)

## Describe Alternatives You've Considered

I tried to use [Remove Space Before or After Characters](https://platers.github.io/obsidian-linter/settings/spacing-rules/#remove-space-before-or-after-characters) and set Remove Space After Characters: `	` (a tab character) but it conflicts with list such as

```markdown
- A list item
	- A list item
		- A list item
		  A line break
		  Another line break
```
![image](https://github.com/platers/obsidian-linter/assets/85216095/f00a4a22-a5a7-4b7b-a7eb-cba5a75ba7a5)
becomes
![image](https://github.com/platers/obsidian-linter/assets/85216095/483fcd9a-762a-4a41-bca7-12cf311e79fe)

## Additional context

I know the tab in Markdown spec indicates a code block. So not sure how feasible it is to implement this rule.

Btw, thank you so much for your work!

**Comment by pjkaufman** [comment]
Hey @nhan000 , here is my understanding of what can be done to handle this scenario if we still want a rule for this:

Add a new rule for handling list spacing on paste where it lets you choose whether spaces or tabs is the correct indentation character for the list items. It would on paste remove any characters that are not the selected indentation character from before the list items in the pasted value.

How does this sound?

**Comment by pjkaufman** [comment]
I am going to close this due to a year of inactivity and no response. If we need to, we can revisit this.
