### ISSUE TITLE
Bug: File Name Heading inserted numerous times

### ISSUE THREAD

**Issue by redactedscribe** [platers/obsidian-linter#911]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

With the below three options enabled, the file name is inserted as a header recursively:

- File Name Heading: Inserts the file name as a H1 heading if no H1 heading exists.
- Header Increment: Heading levels should only increment by one level at a time
- Header Increment: Start Header Increment at Heading Level 2

## How to Reproduce

1. ![Obsidian_2023-10-10_18-59-53](https://github.com/platers/obsidian-linter/assets/25013746/6f81204d-eba8-41fb-95b4-c072d12007de)
2. Lint a file multiple times.

## Expected Behavior

A single file name heading to be inserted / not allow the user to end up with this set of simultaneous options. I only use the latter two options, but I just happened to notice the bug when testing.

## Screenshots

![Obsidian_2023-10-10_19-05-05](https://github.com/platers/obsidian-linter/assets/25013746/6b455628-05fe-43df-b1cd-4e4fdb92591e)

## Device

- [x] Desktop
- [ ] Mobile

Thanks!

**Comment by pjkaufman** [comment]
Hey @redactedscribe . This is not really a bug. A H2 is not a file heading. H1 is a file heading. There is an issue somewhere that requests that a warning be shown for this scenario here.

**Comment by pjkaufman** [comment]
Here is the issue mentioning the recursion issue: https://github.com/platers/obsidian-linter/issues/856.

There are several rules that are not compatible together. However the rules themselves do not know what other rules are enabled in general. Thus the Linter would need a way to know that you have incompatible options selected.

**Comment by pjkaufman** [comment]
Given what has been stated, what is the proposed remedy here?
If we do conaider this a bug, does showing a warning when both are enabled constitute a valid fix or should it disable the rule since they are not compatible?

**Comment by redactedscribe** [comment]
It only appears to occur when _both_ of Header Increment's options are enabled. It could get complex to manage checking of different combinations of rules, so perhaps something simpler: A warning symbol present on options which are known to have incompatible rules. Any rules listed could potentially be clicked and the plugin scroll to the position of said rule. This way the user will at least have a heads-up on what not to do, or how to solve some strange behaviour. If on the other hand you want to implement something more comprehensive, then disabling of rules when conflicts are found, with some confirmation beforehand similar to conflicting hotkeys, isn't a bad choice.

**Comment by redactedscribe** [comment]
> Hey @redactedscribe . This is not really a bug. A H2 is not a file heading. H1 is a file heading. There is an issue somewhere that requests that a warning be shown for this scenario here.

It could be argued however that someone may want the title to be duplicated as the first H2 heading. When a user configures Linter with the options as shown in the screenshot, instead of showing a warning, the title could just be inserted at the top as `## <title>` without incrementing the rest of the headings.

**Comment by timoz** [comment]
I have experienced this problem too. Must've got carried away with the options. I managed to accidentally create a bunch headers for one file starting with H2 before I realised it was Linter-related
![Screenshot 2023-12-06 at 08 02 10](https://github.com/platers/obsidian-linter/assets/732498/d8f8ce96-d21f-4f70-b5a6-c224b9bf95ed)

**Comment by pjkaufman** [comment]
This is definitely a pain point I do not have time to work on right now. However I am open to PRs to fix this while I am working on other features/bugs.

**Comment by pjkaufman** [comment]
This should be fixed on master and in the next release. You will no longer be able to have the ability to insert the file name and have header increment start at H2. It will be an either or. So this issue should go away. Please let us know if either has an issue.
