### ISSUE TITLE
Bug: header refactor alsto Capilizer words inside double (`)(`)

### ISSUE THREAD

**Issue by perymimon** [platers/obsidian-linter#921]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Linter/Capitalize Headings style code inside `$= dataview etc` or `class: ` so it make the code break.

## How to Reproduce
1. turn on `Hedings should be formatted with capitalization` 
2. make it `ALL CAPS`
3. create a note with the next header
4. 

```markdown
## `= durationformat(date(this.day) - date(2023-10-06),"dd")` th days passed since the Black Shabbat
```
5. apply linter 
6. you will see 

``` markdown
## `= DURATIONFORMAT(DATE(THIS.DAY) - DATE(2023-10-06),"DD")` TH DAYS PASSED SINCE THE BLACK SHABBAT
```

## Expected Behavior

``` markdown
## `= durationformat(date(this.day) - date(2023-10-06),"dd")` TH DAYS PASSED SINCe THE BLACK SHABBAT
```

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Thanks for pointing this out @perymimon . Looks like inline math and code need to be ignored for this rule.

**Comment by pjkaufman** [comment]
The fix for this scenario with inline code should be on master and go out in the next release. Please let us know if there is an issue.
