### ISSUE TITLE
Bug encountered when creating a new file and saving to generate properties.

### ISSUE THREAD

**Issue by 2019YKL** [platers/obsidian-linter#924]
When I open 'linter to save' and 'inject yaml', and then create a new file, pressing the shortcut to save and generate Yaml properties, typing afterwards corrupts my Yaml section.

![image](https://github.com/platers/obsidian-linter/assets/51532948/cdb1ad91-c55a-472f-9a39-875a77b1add9)

Please refer to the additional feedback within this post for more information.

https://forum-zh.obsidian.md/t/topic/24935/4

![image](https://github.com/platers/obsidian-linter/assets/51532948/9cddf528-d2c0-4860-a540-59356ca15a70)

![image](https://github.com/platers/obsidian-linter/assets/51532948/d500a2b5-e040-4162-85d3-82c57c38cf30)

The bug has been reproduced when testing the linter in sandbox mode.

Thank you very much for reading 😘

**Comment by 2019YKL** [comment]
It doesn't seem to be either of the two situations you mentioned.

I tried the source mode and identified the issue. 

The cursor consistently appears before the YAML section.

![image](https://github.com/platers/obsidian-linter/assets/51532948/2ba72c8e-0c22-4a42-878c-1116725b631c)

However, in the live preview mode, the cursor is not visible.

To help you understand the issue, I've recorded a GIF.

![Obsidian Linter Bug compress 5](https://github.com/platers/obsidian-linter/assets/51532948/6d17e6d4-3003-4c5e-8cc4-c90556dd45e3)

Thank you for your attention and feedback.

**Comment by pjkaufman** [comment]
I may have a fix for this issue, but I am not certain it fixes all scenarios like this. There was an issue with Live Preview not working like Source Mode, so I had to change the save logic to update things all in one go. This may fix the issue and I can put the `main.js` on this issue if you want to test it out and see if it fixes your situation as well. I plan to get feedback from as many people experiencing the live preview issue as possible. Assuming all goes well, it will fix the issues seen there and go out in the next release.

**Comment by pjkaufman** [comment]
I believe I have a fix for this that has just been merged in. The changes should be in the next release and on master. Please let us know if either master or the next release has issues.

**Comment by 2019YKL** [comment]
Thank you very much for fixing the bug, but now I have a new issue. 

It seems that since the last version, when I use the shortcut `Ctrl+S` to manually save within the document, the property list no longer appears.

 I'm not sure if it's related to this fix. To be precise, this problem has been occurring since the last version.

I'm not quite sure if this issue is related or not. Could it be due to my own settings?

![image](https://github.com/platers/obsidian-linter/assets/51532948/3c15d3f5-d9a4-412e-8dda-de454758dc6d)
![image](https://github.com/platers/obsidian-linter/assets/51532948/2b8f908d-0335-47ab-ad5c-b8b288ade2ed)

**Comment by pjkaufman** [comment]
> Thank you very much for fixing the bug, but now I have a new issue.
> 
> It seems that since the last version, when I use the shortcut `Ctrl+S` to manually save within the document, the property list no longer appears.
> 
> I'm not sure if it's related to this fix. To be precise, this problem has been occurring since the last version.
> 
> I'm not quite sure if this issue is related or not. Could it be due to my own settings?
> 
> ![image](https://private-user-images.githubusercontent.com/51532948/290708173-3c15d3f5-d9a4-412e-8dda-de454758dc6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDg1NjYsIm5iZiI6MTcwMjYwODI2NiwicGF0aCI6Ii81MTUzMjk0OC8yOTA3MDgxNzMtM2MxNWQzZjUtZDlhNC00MTJlLThkZGEtZGU0NTQ3NThkYzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAyNDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MDlkM2M2ZGQwNTg2NmJjZGY4NjU1ZTcwOWE1MzI5N2E1YmJiODdhOGVhNDBhYzU0YzgzYjI3YmQyNTlhMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ykcajOxfK6beu89GvMh5MeT7lfLcHohh81buVGll_Jo) ![image](https://private-user-images.githubusercontent.com/51532948/290708178-2b8f908d-0335-47ab-ad5c-b8b288ade2ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDg1NjYsIm5iZiI6MTcwMjYwODI2NiwicGF0aCI6Ii81MTUzMjk0OC8yOTA3MDgxNzgtMmI4ZjkwOGQtMDMzNS00N2FiLWFkNWMtYjhiMjg4YWRlMmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAyNDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NjI2NTRhNWJmODM5YjYzZDczYTY4MTNlNTNjMTlmZTgzZDYzMjIzZjkwZGQ0ODZkYzgwNWMxNTBlNGI0MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UbRkg3ujqYGU1W7CItCILjUd7zAQpiy8xIjrs4yZ70M)

I can't say based on the information provided. Could you provide an example file that has this issue as well as your `data.json`?

**Comment by 2019YKL** [comment]
> > Thank you very much for fixing the bug, but now I have a new issue.
> > It seems that since the last version, when I use the shortcut `Ctrl+S` to manually save within the document, the property list no longer appears.
> > I'm not sure if it's related to this fix. To be precise, this problem has been occurring since the last version.
> > I'm not quite sure if this issue is related or not. Could it be due to my own settings?
> > ![image](https://private-user-images.githubusercontent.com/51532948/290708173-3c15d3f5-d9a4-412e-8dda-de454758dc6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDg1NjYsIm5iZiI6MTcwMjYwODI2NiwicGF0aCI6Ii81MTUzMjk0OC8yOTA3MDgxNzMtM2MxNWQzZjUtZDlhNC00MTJlLThkZGEtZGU0NTQ3NThkYzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAyNDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MDlkM2M2ZGQwNTg2NmJjZGY4NjU1ZTcwOWE1MzI5N2E1YmJiODdhOGVhNDBhYzU0YzgzYjI3YmQyNTlhMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ykcajOxfK6beu89GvMh5MeT7lfLcHohh81buVGll_Jo) ![image](https://private-user-images.githubusercontent.com/51532948/290708178-2b8f908d-0335-47ab-ad5c-b8b288ade2ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MDg1NjYsIm5iZiI6MTcwMjYwODI2NiwicGF0aCI6Ii81MTUzMjk0OC8yOTA3MDgxNzgtMmI4ZjkwOGQtMDMzNS00N2FiLWFkNWMtYjhiMjg4YWRlMmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDAyNDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NjI2NTRhNWJmODM5YjYzZDczYTY4MTNlNTNjMTlmZTgzZDYzMjIzZjkwZGQ0ODZkYzgwNWMxNTBlNGI0MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UbRkg3ujqYGU1W7CItCILjUd7zAQpiy8xIjrs4yZ70M)
> 
> I can't say based on the information provided. Could you provide an example file that has this issue as well as your `data.json`?

I apologize, it seems to have been an issue on my end. 

I tried upgrading the plugin and restarted my Obsidian, and the bug has been successfully fixed. 

Thank you for your patience and consistent help.

😘 May your work go smoothly and your life be joyful!

**Comment by pjkaufman** [comment]
I am glad it is fixed.

Thanks!
