### ISSUE TITLE
Bug: Quotes are formatted in markdown links

### ISSUE THREAD

**Issue by xplosionmind** [platers/obsidian-linter#929]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

Links in the format `[link](test.it 'Test title')` become `[link](test.it ‘Test title’)` if `Enable Single Quote Style` is on and Single `Quote Style` set to `‘’`.

## How to Reproduce

Example to reproduce issue with

``` markdown
[link](https://test.it 'Test title')
```

## Expected Behavior

Single or double quotes used in Markdown links to set the link title should be kept `''` and `""`.

Expected output if applicable:

``` markdown
[link](https://test.it 'Test title')
```

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Hey @xplosionmind , is that a valid url you are using as the link? If not, it may not be properly recognized by the Linter. If it is a valid link, I can look into what is going on.

**Comment by xplosionmind** [comment]
Thanks for your follow-up, @pjkaufman!

> is that a valid url you are using as the link?

Sorry, I was a bit distracted and I forgot to prepend `https://` to the link… I tested this with many different links (all valid), and the result is always the same.

**Comment by pjkaufman** [comment]
Could you explain why there is an unconnected part to the link itself in the YAML? It looks to me like `[link](https://test.it 'Test title')` has an extra part called `'Test title'` as if it is being run as URI or something like that instead of URL?

I can still work on this without knowing that, but I am just a little bit confused as to what is going on with that markdown link.

**Comment by pjkaufman** [comment]
I believe that I have a fix for this. Could this same issue apply to wikilinks or is this just a markdown link issue?

**Comment by pjkaufman** [comment]
I plan to fix the scenario for both markdown and wiki links.

**Comment by pjkaufman** [comment]
This should be fixed on master and the next release. Please let us know if that is not the case.
