### ISSUE TITLE
FR:+ Add empty line at the beginning of the page

### ISSUE THREAD

**Issue by metalmarco** [platers/obsidian-linter#932]
It would be great to have an option to always have an empty line at the beginning of every file. 

If you use notes for task managements, in order to quick create a task on top of the note having an empty space as fist line allows you to click there and start typing, instead of having to first bring everything down one line. 

Very useful also on mobile, if you use the Quick Create/Edit Task command. You can open the file, start that command and it will create the task in that first empty line. Without the empty line instead, starting that command will edit the task in the fist line. 

**Please include an example where applicable:**

``` markdown
This is the first line of a file
```

``` markdown

This is the fist line of a file
```

**Comment by pjkaufman** [comment]
Hey @metalmarco , could you not use [custom regex](https://platers.github.io/obsidian-linter/settings/custom-rules/#custom-regex-replacements) for this? Something like the following probably would do:
Regex find: `^([^\n])`
Regex replace: `\n\n$1`
Regex Flags: `m`

This should look at the start of a file and add a blank line if one is not present (test this yourself to verify I did not mess up my regex). But I think this should satisfy what you are looking for.

**Comment by pjkaufman** [comment]
I am going to close this since I have not heard back on this issue. We can reopen the issue if there is further discussion to be had around this.
