### ISSUE TITLE
FR: <br> as option for Two Spaces Between Lines with Content

### ISSUE THREAD

**Issue by HemanthJabalpuri** [platers/obsidian-linter#933]
## Is Your Feature Request Related to a Problem? Please Describe.

It is not a problem, but `<br>` can be used for better readability.

## Describe the Solution You'd Like

A option to select two spaces or `<br>`

``` markdown
line1  
line2  
```

``` markdown
line1<br>
line2<br>
```

**Comment by pjkaufman** [comment]
Hey @HemanthJabalpuri . This is something that would be feasible by adding an option for what to use as the line break. It would require a code change to add the option and a change to the following logic here.

Were you thinking that this would have the following options for the two spaces between lines with conent?
- `  `
- `<br>` -- correct, but not where xml is concerned
- `<br/>` -- the more correct option

**Comment by pjkaufman** [comment]
I went ahead and merged the PR for these changes. I plan to make a release later this week, but we will see if that pans out.

Please let us know if there is an issue with this on master or in the next release.

**Comment by pjkaufman** [comment]
I went ahead and merged the PR for these changes. I plan to make a release later this week, but we will see if that pans out.

Please let us know if there is an issue with this on master or in the next release.
