### ISSUE TITLE
Bug: Links with `#` in titles get treated differently

### ISSUE THREAD

**Issue by TrueMilli** [platers/obsidian-linter#941]
- [x] I have verified that I am on the latest version of the Linter

## Describe the Bug

A `#` in a hyperlink-title generates the `note` element in the YAML block, structurally different from without a `#` or with `\#`.

## How to Reproduce

1. Create a new file
2. Put a hyperlink in the title which has `#` in the text
3. Lint the file

### Examples

``` markdown
# [test #1](github.com/platers/obsidian-linter)
```
``` markdown
# test #2
```
``` markdown
# [test 3](github.com/platers/obsidian-linter)
```
``` markdown
# [test \#4](github.com/platers/obsidian-linter)
```

### Log

[log linter bug diamond.md](https://github.com/platers/obsidian-linter/files/13310164/log.linter.bug.diamond.md)

## Expected Behavior

The `note` YAML should look like usual for links (without syntax or the url)

``` markdown
---
note: "test #"
---
```

## Screenshots

![image](https://github.com/platers/obsidian-linter/assets/61841994/d1fe81ec-8ccd-4849-85d0-df512541e859)

## Device

- [x] Desktop
- [ ] Mobile

**Comment by pjkaufman** [comment]
Oh. Wait a second. Is this referring to not escaping the value properly for YAML? If so, that is something that can be added.

**Comment by pjkaufman** [comment]
Looks like there is a problem here that may cause some issues. That problem is that `#1` matches the appearance of a tag. This means it gets treated as such in the logic in the Linter. This seems to be creating some other problems that you are seeing here.

**Comment by pjkaufman** [comment]
Welp. I think I found the problem and have addressed it. I am hopeful that this will fix the issue however it may still have some problems.

**Comment by pjkaufman** [comment]
Ok. Based on my changes the following are the outputs for the scenarios provided:
| Input Header | Note YAML Key |
| -------------- | ----------------- |
| `# [test #1](github.com/platers/obsidian-linter)`  | `note: "test #1"` |
| `# test #2`  | `note: "test #2"` |
| `# [test 3](github.com/platers/obsidian-linter)`  | `note: test 3` |
| `# [test \#4](github.com/platers/obsidian-linter)`  | `note: "test \#4"` |

Please let me know if this is not the expected result. I plan to move forward with merging this fix later today or tomorrow.

**Comment by TrueMilli** [comment]
Yes, that looks good!
I'm impressed by your speed.

**Comment by pjkaufman** [comment]
I had some downtime, so I took a look. It can take some time to look into some issues, but this one was pretty simple (a 2 character change).

**Comment by pjkaufman** [comment]
This change is on master and should go out with the next release. Please let us know if there is an issue with either. Thanks!
