### ISSUE TITLE
FR: Set Default Code Fences Language

### ISSUE THREAD

**Issue by magicwenli** [platers/obsidian-linter#943]
## Is Your Feature Request Related to a Problem? Please Describe.

Nope

## Describe the Solution You'd Like

I would like the ability to set a default code fences language in the Obsidian linter rule. This would allow me to specify a default language for code blocks, so that every time I insert a code block, it automatically uses the specified language unless I override it.

**Please include an example where applicable:**

``` markdown
    ```
    echo "hello world"
    ```
```

```
echo "hello world"
```

Which will be transformed:

``` markdown
    ```bash
    echo "hello world"
    ```
```

```bash
echo "hello world"
```

## Describe Alternatives You've Considered

Nope

## Additional Context

There is a custom regex rule I used currently, but it depended on [empty-line-around-code-fences](https://platers.github.io/obsidian-linter/settings/spacing-rules/#empty-line-around-code-fences)

Regex:
```
^\n```$
```
Replaced with:
```
\n```bash
```

Thank you!

**Comment by magicwenli** [comment]
Hello,

How to push forward this PR?

@platers

**Comment by pjkaufman** [comment]
Hey @magicwenli , I will take a look at this week and test it out. From there it will either get merged oe have code change requests.

**Comment by magicwenli** [comment]
Hey, thanks bro.
