### ISSUE TITLE
FR: Ability to disable some commands in command palette

### ISSUE THREAD

**Issue by tyler-dot-earth** [platers/obsidian-linter#957]
## Is Your Feature Request Related to a Problem? Please Describe.

I only use the linter on-demand because i have many files that i don't want to lint and it would be too time-consuming/complex to update all files so i could use linting project-wide.

I want to keep the extension enabled but I'm paranoid that I'm going to lint *all* files.

## Describe the Solution You'd Like

I want to disable some/all commands from the command palette (commands pictured below)

<img width="705" alt="Screenshot 2023-12-03 at 6 12 51 PM" src="https://github.com/platers/obsidian-linter/assets/595711/4b692a8d-7faf-4f71-95b1-34330ac33959">

## Describe Alternatives You've Considered

- Being really careful.
- Going through thousands of my notes and updating them so they dont get accidentally linted.

## Additional Context

n/a

**Comment by tsnieman** [comment]
> why other options like ignoring folders is not viable here.

I have a lot of folders, and each folder's contents vary of files I'd like linted and files I would not like linted. I am also likely to add folders over time and forget to update my ignored list.

> Could you explain why using `Ctrl+S` is not viable for your use case?

Because I still might accidentally choose "lint all files" in the command palette.

> Thanks for helping me better understand what is going on here.

I appreciate the response - thanks for wanting to better understand the problem.

**Comment by pjkaufman** [comment]
Gotcha. Is there a reason to have the commands be able to be disabled when they require you to select ok to at least 1 modal dialog? Just checking to make sure that is not enough of a deterant for you.

**Comment by tsnieman** [comment]
> Gotcha. Is there a reason to have the commands be able to be disabled when they require you to select ok to at least 1 modal dialog? Just checking to make sure that is not enough of a deterant for you.

Oh. I ... didn't actually know that there was a confirmation dialog — I hadn't used the command because I didn't wanna mess up my vault 😅 That makes a lot of sense and does alleviate my want for this FR. I'll go ahead and close. Thank you 👍
