### ISSUE TITLE
FR: Ensure single space after blockquote `>` angle brackets

### ISSUE THREAD

**Issue by redactedscribe** [platers/obsidian-linter#961]
## Is Your Feature Request Related to a Problem? Please Describe.

I have one small issue I've just noticed related to blockquotes and our conversations in (#910). Not sure if it's intentional or not, and apologies if it has already been mentioned:

```markdown
>  Text
```

Doesn't lint as:

```markdown
> Text
```

Is there a reason why the >=2 spaces don't get reformatted as a single space? Maybe it's a compromise of some sort? Perhaps it's because not all people use spaces after blockquote angle brackets, e.g. `>> Text` or even `>>Text`.

The problem exists with plain lines beginning with a space too which lead me to find your options to "Remove space around/before/after characters". These could probably mitigate it (but as noted, whilst also risking Markdown formatting in some cases).

I mentioned a similar issue with tables, unsure if any relation: #951

## Describe the Solution You'd Like

I guess my only issue then is that maybe removing >1 spaces could be a distinct rule for blockquotes since we already have the "Space after list markers" option.

Consider adding "Space after _blockquote_ markers" to ensure a single space. Or more flexibly, make it a choice between ensuring no spaces (e.g. `>Text`), no spaces but one after final `>` (e.g. `>> Text`), and ensure space after each `>` (e.g. `> > Text`). If a blockquote `>` is followed by only whitespace, "Removes extra spaces after every line." should trim it.

You've recently done a lot to fix blockquote issues, so I don't expect you to be too enthusiastic at this time, but this issue is here for if/when that time comes.

Thanks!

**Comment by pjkaufman** [comment]
I think this was just an oversight. I don't think it would be too hard to implement this. I am just heads down on something else right now. I would definitely be open to a PR for this. I can take a look at this once I wrap up a couple of other things I am looking at.

**Comment by pjkaufman** [comment]
The changes here have been merged into master and should go out in the next release. Please let us know if there are any issues with either of those.

**Comment by redactedscribe** [comment]
@pjkaufman Something I overlooked:

```markdown
> 1. Hello
>     - Foo
> 2. Bar
```

(Not sure if 4 or 5 spaces is the correct amount to use pre a `-`, but only using 5 here causes the source view to show the vertical indent bar, and at minimum 4 to show same bar in reading view.)

Lints as:

```markdown
> 1. Hello
> - Foo
> 2. Bar
```

The point here is that an exception needs to be made for bulletpoints and any other syntax that can use indentation within blockquotes. I guess: Only ensure a single space if only <5 spaces are present after a `>`.

**Comment by pjkaufman** [comment]
I have overlooked this as well. I am going to reopen this issue and move it to in progress. This should be ironed out before I make another release. I can only think of checklists and lists that currently have that spacing issue.

The problem I am seeing with these scenarios is I cannot actually work with these situations well. I likely need  to check the first non-whitespace character on the line. If it is `-`, `+`, `*`, `\d+.`, or `\d+)` then leave the spacing as is after the last `>` unless there is no whitespace after it.

I will have to check what types Mardkown elements may normally use spacing (technically code blocks do, but I really dislike how this works, so I am not sure I would support using spaces for codeblocks here as that would be a nightmare).

**Comment by pjkaufman** [comment]
I believe I have the list item and checklist item scenarios accounted for. I am going to go ahead and get that merged.

**Comment by pjkaufman** [comment]
This change should now be on master and go out with the next release. Please let us know if either has an issue.
