### ISSUE TITLE
FR: Save without linting command

### ISSUE THREAD

**Issue by redactedscribe** [platers/obsidian-linter#968]
## Is Your Feature Request Related to a Problem? Please Describe.

With Linter set to lint on save, the only way I'm know to save a file without linting it (or it being in an excluded-from-linting folder) is by temporarily disabling the lint-on-save feature via the plugin's options.

In my particular case I'd like to format a part of a file in a particular way but Linter keeps adding a new line between two types of Markdown syntax that I want placed against each other (which is great 99% of the time).

## Describe the Solution You'd Like

A command which simply triggers Obsidian's save but skips linting, e.g. "Linter: Save without linting".

Thanks.

**Comment by pjkaufman** [comment]
Hey @redactedscribe . This sounds like a perfect use case for the linter ignore options: https://platers.github.io/obsidian-linter/usage/disabling-rules/#range-ignore

The syntax is as follows:
``` markdown
Here is some text
<!-- linter-disable -->
                          This area will not be formatted
<!-- linter-enable -->
More content goes here...
```

**Comment by pjkaufman** [comment]
Does that work for you? Or is there a reason ignoring the area for the Linter does not make sense?

**Comment by redactedscribe** [comment]
That definitely should work, and better than having to remember to not lint a particular file. Thanks for pointing it out! So let me try...

I'm not sure if my goal actually makes any sense since I was hoping to format an ordered list with a blockquote within it without the numbering resetting in edit mode. The numbering continues in reading mode though just fine so it might not actually be much of a problem if the rendered result is structurally fine.

Due to my Linter settings ("Empty Line Around Blockquotes"), new lines are added above and below the blockquote.

```
1. Foo.
2. Bar.

  > [!note]
  >
  > Text.

1. Hello.
```


Adding the comments ~~doesn't~~ _does_ help the case (~~still `1.` at bottom~~):

```
1. Foo.
2. Bar.
<!-- linter-disable -->
  > [!note]
  >
  > Text.
<!-- linter-enable -->
3. Hello.
```

Didn't seem to work at first, but it in fact does. I may have positioned the comments incorrectly.

Ideally both edit and reading mode would render the lists the same by default, but I think it's an issue with Obsidian itself.

**Comment by pjkaufman** [comment]
I am going to close this issue based on what has  been stated here.
