### ISSUE TITLE
Bug: Linter an URL adds the sign ">" after ...index.php (and not at the end, as expected)

### ISSUE THREAD

**Issue by merlinuwe** [platers/obsidian-linter#980]
- [x ] I have verified that I am on the latest version of the Linter

## Describe the Bug

I add this link

`https://m3.bbz-dormagen-moodle.de/tag/index.php?tc=1&tag=Nachschreibtermin&from=4817` 

 in a note and Linter with `<Strg-Alt-l>`.

I get this (look at the > after index.php)

`<https://m3.bbz-dormagen-moodle.de/tag/index.php>?tc=1&tag=Nachschreibtermin&from=4817`

but I wanted to get this

`<https://m3.bbz-dormagen-moodle.de/tag/index.php?tc=1&tag=Nachschreibtermin&from=4817>`

It makes no difference, if I switch the second switch on/off.

![image](https://github.com/platers/obsidian-linter/assets/4138869/adbded6c-8beb-4d13-98b7-d0b9fa9209a9)

If I start the url with < and let it end with >, 

`<https://m3.bbz-dormagen-moodle.de/tag/index.php?tc=1&tag=Nachschreibtermin&from=4817>` 

lintering destroys the url to

'<<https://m3.bbz-dormagen-moodle.de/tag/index.php>?tc=1&tag=Nachschreibtermin&from=4817>'

with 2 << at the beginning.

**Comment by pjkaufman** [comment]
This looks like a bug, I will need to look into why it does not like the URL. I am not sure if the regex is not matching because of the `.php`  or if it does not like the multiple params (I assume the latter, but need to confirm). Hopefully this will not be too hard to fix.

**Comment by pjkaufman** [comment]
I have merged the change for this. The fix should be on master and in the next release. Please let us know if neither is the case.

Thanks for reporting this issue!
