### ISSUE TITLE
Question: run as git commit hook

### ISSUE THREAD

**Issue by PatrickF1** [platers/obsidian-linter#988]
Hi, thanks for this amazing plugin! It's been so helpful.
I am aware of the settings to run the linter on file save or file close. However, I want to lint only when I'm about to git commit (I back up my files using git). Is there a binary somewhere that I can call in a git pre-commit hook? Thanks!

**Comment by pjkaufman** [comment]
Hey @PatrickF1 . There is no binary at this time. There has been a request to create a cli version of the plugin (#987), but that is likely a long ways off.

**Comment by pjkaufman** [comment]
As an update before I close this issue, there is currently no binary that can be run, and as things are going, there will likely not be one unless things change to make the Linter more viable to cross compile from another language into JS and a binary.
