### ISSUE TITLE
Question: How to stop headings from unfolding/uncollapsing on save?

### ISSUE THREAD

**Issue by BindingOx** [platers/obsidian-linter#989]
Can anyone point to the setting?

**Comment by pjkaufman** [comment]
Hey @BindingOx . That used to be possible when `editor.replaceRange` was used. However it was buggy in Live Preview and Reading Mode so it was replaced with something that worked in those 2 modes. So as of right now, this is currently not supported, but I am open to PRs that would add that which work in Live Preview and Reading Mode.
