### ISSUE TITLE
Question: Why does the console show an error message when using the format dddd, DD. MMMM YYYY, HH:mm:ss U\hr

### ISSUE THREAD

**Issue by merlinuwe** [platers/obsidian-linter#990]
In a note which lives in the root folder of Obsidian I have this YAML:

`````
---
aliases: [Themeneingrenzung]
tags: [KA, FW22A, Aufgaben, BBZ]
filename: Themen der KA05 FW22A
erstellt: Sonntag, 09. Januar 0000, 23:00:24 Uhr
geändert: Donnerstag, 04. Januar 2024, 12:02:30 Uhr
---

`````

In Linter, I defined the format in YAML-Timestamp as so:

```dddd, DD. MMMM YYYY, HH:mm:ss U\hr```

In the developer console, I see this:

![image](https://github.com/platers/obsidian-linter/assets/4138869/4a3c530c-8148-4aa2-88c1-48b96ea2cbd0)

(I use the latest releases of Obsidian and Linter.)

Why does the error occure in the developer console?

Is the format of the time string wrong (and if yes, how do I have to format it correct [in german with the word "Uhr" at the end])?

If I move this note to an other folder, restart Obsidian, I get the same error message. 

All my notes have the fields "erstellt:" and "geändert:" in YAML, but I see only one error message.

**Comment by pjkaufman** [comment]
That looks like it is just a deprecation warning. Is the date format not working for you or is there just the warning showing in the console?

**Comment by merlinuwe** [comment]
Thanks for your fast response. 

Yes I wonder if I did something wrong that causes the error message. (No problems with linter, only the depreciation warning.)

**Comment by pjkaufman** [comment]
Yeah. The deprecation warning happens every once in a while. I generally do not worry about it since I do not believe moment is maintained anymore and it is unlikely that the deprecated logic will be removed.

**Comment by pjkaufman** [comment]
I am planning to close this issue unless there is something else that needs addressing. I plan to close this on the 10th.

**Comment by merlinuwe** [comment]
Yes, no problem for me (and not a problem caused by your great plugin).

**Comment by pjkaufman** [comment]
Alrighty.  I will go ahead and close this then. I am glad the plugin is useful for you!
