### ISSUE TITLE
Bug: Lint on Change breaks mobile toolbar

### ISSUE THREAD

**Issue by csss1234** [platers/obsidian-linter#991]
## Describe the Bug

When switching between notes and tapping to add text (on iPadOS), the mobile toolbar doesnt pop up automatically. Have to hide and re-show the keyboard to get toolbar to appear. 

Disabling "Lint on change" fixes the problem

**Comment by pjkaufman** [comment]
Hey @csss1234 . Could you provide your `data.json`? It will help with debugging.

**Comment by csss1234** [comment]
[data.json](https://github.com/platers/obsidian-linter/files/13878727/data.json)

**Comment by csss1234** [comment]
In the meantime, any way I could disable the feature on mobile but keep on Mac? (I want Sync to work for other plugins so turning it off for plugins is not an option)

**Comment by pjkaufman** [comment]
@csss1234 , it looks like you have a blank custom command present:
``` YAML
"lintCommands": [
    {
      "id": "",
      "name": ""
    }
  ],
```
Could you remove the empty custom command and see if the same behavior still happens? It could be that there is a bug that when you have no valid lint commands in place it does not properly return you to the currently active file on mobile/desktop after custom commands run after changing the active file.

**Comment by csss1234** [comment]
Yes! Resolved! Thank you : )
