### ISSUE TITLE
FR: Auto Set Headings Number

### ISSUE THREAD

**Issue by zzReno** [platers/obsidian-linter#998]
## Number Headings Problem
Number headings is necessary for eveyrone, and everyone need a tools to automatically number.

I tried the plugin "Number Headings", only can number headings like 1/1.1/1.1.1. I can't customize it.
After use Linter, I think this is a feature that Linter can do better than other plugins. 

## Describe the Solution You'd Like

Linter has Heading control features
I want a feature like this on Linter, every heading numbers can be customized by users, and auto format the markdown files:

``` markdown
Linter Setting:
H1:  A、B、C、D、E、……
H2: 1、2、3、4、5、……
H3: 1.1、1.2、1.3、……
H4: 1) 、2)、3)、……
……
```

``` markdown
# One
## One-One

# Two
## Two-Two
### Two
```

After Linter's process:
```markdown
# A、One
## 1、One-One

# B、Two
## 2、Two-Two
### 2.1 Two
```

**Comment by pjkaufman** [comment]
Hey @zzReno , I don't think I will have time to work on this given the current list of feature requests and bugs. So I am open to PRs around this, but I don't think I will be able to work on this.

**Comment by pjkaufman** [comment]
I am going to close this as something that is not going to be implemented at this time. If there is desire for this feature in the future, this can be revisited.

**Comment by lvbibir** [comment]
@zzReno Hello, I would like to ask which solution you ultimately adopted, as I am also troubled by this issue
